LilycoveCity_House4_MapScripts::
	.byte 0

LilycoveCity_House4_EventScript_Man1::
	msgbox LilycoveCity_House4_Text_MysteriesAtBottomOfSea, MSGBOX_NPC
	end

LilycoveCity_House4_EventScript_Man2::
	msgbox LilycoveCity_House4_Text_UnderwaterTrenchMossdeepSootopolis, MSGBOX_NPC
	end

LilycoveCity_House4_Text_MysteriesAtBottomOfSea:
	.string "I più grandi misteri di questo mondo\n"
	.string "si nascondono in fondo al mare.\p"
	.string "Così dicono… E c'è perfino chi giura\n"
	.string "che laggiù si apra un Varco.$"

LilycoveCity_House4_Text_UnderwaterTrenchMossdeepSootopolis:
	.string "C'è una profonda fossa sottomarina\n"
	.string "tra Verdeazzupoli e Ceneride.\p"
	.string "Almeno, così mi hanno raccontato.$"

