BattleFrontier_Lounge8_MapScripts::
	.byte 0

BattleFrontier_Lounge8_EventScript_Man::
	msgbox BattleFrontier_Lounge8_Text_WhatATrainerNeeds, MSGBOX_NPC
	end

BattleFrontier_Lounge8_EventScript_Woman::
	msgbox BattleFrontier_Lounge8_Text_KnowAboutFrontierBrains, MSGBOX_NPC
	end

BattleFrontier_Lounge8_EventScript_NinjaBoy::
	msgbox BattleFrontier_Lounge8_Text_ToldMeIHaveTalentForBattling, MSGBOX_NPC
	end

BattleFrontier_Lounge8_Text_WhatATrainerNeeds:
	.string "Cosa serve a un Allenatore…\p"
	.string "Conoscenza…\n"
	.string "Strategia…\l"
	.string "Fortuna…\l"
	.string "Grinta…\l"
	.string "Spirito…\l"
	.string "Coraggio…\l"
	.string "E talento…\p"
	.string "Beh, io ho tutto quanto!\n"
	.string "Sarò inarrestabile in ogni edificio!\p"
	.string "Eh? I Pokémon?\n"
	.string "E che roba sarebbe?$"

BattleFrontier_Lounge8_Text_KnowAboutFrontierBrains:
	.string "Hai mai sentito parlare degli\n"
	.string "Assi del Parco?\p"
	.string "Scott chiama così i sette Allenatori\n"
	.string "speciali che guidano i sette edifici\l"
	.string "del Parco Lotta.\p"
	.string "Dicono che li abbia scelti uno per uno,\n"
	.string "per mettere alla prova chiunque arrivi\l"
	.string "un giorno dal Grande Varco!$"

BattleFrontier_Lounge8_Text_ToldMeIHaveTalentForBattling:
	.string "Alla Torre Lotta, una ragazza più\n"
	.string "grande mi ha detto che ho un sacco\l"
	.string "di talento per le lotte!\p"
	.string "Ma io preferisco le Gare Pokémon!\p"
	.string "Solo che alle Gare sono una schiappa!\p"
	.string "Avere talento e avere passione,\n"
	.string "a quanto pare, non sono la stessa cosa.$"

