#include "global.h"
#include "strings.h"
#include "battle_pyramid_bag.h"
#include "item_menu.h"

ALIGNED(4)
const u8 gText_ExpandedPlaceholder_Empty[] = _("");
const u8 gText_ExpandedPlaceholder_Kun[] = _("");
const u8 gText_ExpandedPlaceholder_Chan[] = _("");
const u8 gText_ExpandedPlaceholder_Sapphire[] = _("Zaffiro");
const u8 gText_ExpandedPlaceholder_Ruby[] = _("Rubino");
const u8 gText_ExpandedPlaceholder_Emerald[] = _("Smeraldo");
const u8 gText_ExpandedPlaceholder_Aqua[] = _("Omega");
const u8 gText_ExpandedPlaceholder_Magma[] = _("Alpha");
const u8 gText_ExpandedPlaceholder_Archie[] = _("Ulisse");
const u8 gText_ExpandedPlaceholder_Maxie[] = _("Ettore");
const u8 gText_ExpandedPlaceholder_Kyogre[] = _("Kyogre");
const u8 gText_ExpandedPlaceholder_Groudon[] = _("Groudon");
const u8 gText_ExpandedPlaceholder_Brendan[] = _("Arianna");
const u8 gText_ExpandedPlaceholder_May[] = _("Arianna");
const u8 gText_ExpandedPlaceholder_Red[] = _("Rosso");
const u8 gText_ExpandedPlaceholder_Green[] = _("Blu");
const u8 gText_EggNickname[POKEMON_NAME_LENGTH + 1] = _("Uovo");
const u8 gText_Pokemon[POKEMON_NAME_LENGTH + 1] = _("Pokémon");
const u8 gText_Player[] = _("Giocatore"); // Unused
const u8 gText_Pokedex[] = _("Pokédex"); // Unused
const u8 gText_Time[] = _("Tempo");
const u8 gText_Badges[] = _("Medaglie"); // Unused
const u8 gText_AButton[] = _("Tasto A"); // Unused
const u8 gText_BButton[] = _("Tasto B"); // Unused
const u8 gText_RButton[] = _("Tasto R"); // Unused
const u8 gText_LButton[] = _("Tasto L"); // Unused
const u8 gText_Start[] = _("START"); // Unused
const u8 gText_Select[] = _("SELECT"); // Unused
const u8 gText_ControlPad[] = _("Pulsantiera"); // Unused
const u8 gText_LButtonRButton[] = _("Tasto L  Tasto R"); // Unused
const u8 gText_Controls[] = _("Comandi"); // Unused
ALIGNED(4) const u8 gText_PickOk[] = _("{DPAD_UPDOWN}Scegli {A_BUTTON}OK"); // Unused
ALIGNED(4) const u8 gText_Next[] = _("{A_BUTTON}Avanti");
ALIGNED(4) const u8 gText_NextBack[] = _("{A_BUTTON}Avanti {B_BUTTON}Indietro");
ALIGNED(4) const u8 gText_PickNextCancel[] = _("{DPAD_UPDOWN}Scegli {A_BUTTON}Avanti {B_BUTTON}Esci");
ALIGNED(4) const u8 gText_PickCancel[] = _("{DPAD_UPDOWN}Scegli {A_BUTTON}{B_BUTTON}Esci");
ALIGNED(4) const u8 gText_AButtonExit[] = _("{A_BUTTON}Esci");
const u8 gText_Boy[] = _("Maschio");
const u8 gText_Girl[] = _("Femmina");
const u8 gText_ThisIsAPokemon[] = _("Questo è ciò che chiamiamo “Pokémon”.{PAUSE 96}\p");
const u8 gText_5MarksPokemon[] = _("Pokémon ?????");
const u8 gText_CryOf[] = _("Verso di");
const u8 gText_SizeComparedTo[] = _("Dimensioni rispetto a ");
const u8 gText_SelectorArrow[] = _("▶");
const u8 gText_EmptySpace[] = _(" "); // Unused
const u8 gText_WelcomeToHOF[] = _("Benvenuto nella Sala d'Onore!");
const u8 gText_HOFDexRating[] = _("Pokémon visti: {STR_VAR_1}!\nPokémon presi: {STR_VAR_2}!\pVoto Pokédex del Prof. Birch!\pProf. Birch: Vediamo…\p");
const u8 gText_HOFDexSaving[] = _("Salvataggio in corso…\nNon spegnere la console.");
const u8 gText_HOFCorrupted[] = _("I dati della Sala d'Onore sono corrotti.");
const u8 gText_HOFNumber[] = _("Sala d'Onore N. {STR_VAR_1}");
const u8 gText_LeagueChamp[] = _("Campione della Lega!\nCongratulazioni!");
const u8 gText_Number[] = _("N. ");
const u8 gText_Level[] = _("Lv. ");
const u8 gText_IdNumberSlash[] = _("N. ID /"); // Unused
const u8 gText_Name[] = _("Nome");
const u8 gText_IDNumber[] = _("N. ID");
const u8 gText_BirchInTrouble[] = _("Il Prof. Birch è nei guai!\nScegli un Pokémon e salvalo!");
const u8 gText_ConfirmStarterChoice[] = _("Vuoi scegliere questo Pokémon?");
const u8 gText_Pokemon4[] = _("Pokémon"); // Unused
const u8 gText_FlyToWhere[] = _("Dove vuoi volare?");
const u8 gMenuText_Use[] = _("Usa");
const u8 gMenuText_Toss[] = _("Getta");
const u8 gMenuText_Register[] = _("Registra");
const u8 gMenuText_Give[] = _("Dai");
const u8 gMenuText_Confirm[] = _("Conferma");
const u8 gText_Cancel[] = _("Annulla");
const u8 gText_Cancel2[] = _("Annulla");
const u8 gText_EmptyString2[] = _("");
const u8 gText_None[] = _("Nessuno");
const u8 gText_FiveMarks[] = _("?????");
const u8 gText_Slash[] = _("/");
const u8 gText_OneDash[] = _("-");
const u8 gText_TwoDashes[] = _("--");
const u8 gText_ThreeDashes[] = _("---");
const u8 gText_MaleSymbol[] = _("♂");
const u8 gText_FemaleSymbol[] = _("♀");
const u8 gText_LevelSymbol[] = _("{LV}");
const u8 gText_NumberClear01[] = _("{NO}{CLEAR 1}");
const u8 gText_RightArrow[] = _("{RIGHT_ARROW}"); // Unused
const u8 gText_IDNumber2[] = _("{ID}{NO}");
const u8 gText_Space[] = _(" ");
const u8 gText_SelectorArrow2[] = _("▶");
const u8 gText_GoBackPrevMenu[] = _("Torna al menu\nprecedente.");
const u8 gText_WhatWouldYouLike[] = _("Cosa vuoi fare?");
const u8 gMenuText_Give2[] = _("Dai");
const u8 gText_xVar1[] = _("×{STR_VAR_1}");
const u8 gText_Berry2[] = _(" Bacca"); // Unused
const u8 gText_Coins[] = _("{STR_VAR_1} Gett.");
const u8 gText_CloseBag[] = _("Chiudi Borsa");
const u8 gText_Var1IsSelected[] = _("Hai selezionato:\n{STR_VAR_1}.");
const u8 gText_CantWriteMail[] = _("Qui non puoi\nscrivere Messaggi.");
const u8 gText_NoPokemon[] = _("Non hai\nPokémon.");
const u8 gText_MoveVar1Where[] = _("Scegli dove\nspostare:\n{STR_VAR_1}");
const u8 gText_Var1CantBeHeld[] = _("Non si può tenere {STR_VAR_1}.");
const u8 gText_TossHowManyVar1s[] = _("{STR_VAR_1}:\nnumero da gettare?");
const u8 gText_ThrewAwayVar2Var1s[] = _("Hai gettato {STR_VAR_2}\n{STR_VAR_1}.");
const u8 gText_ConfirmTossItems[] = _("Vuoi davvero\ngettare {STR_VAR_2}\n{STR_VAR_1}?");
const u8 gText_DadsAdvice[] = _("Consiglio di Papà…\n{PLAYER}, c'è un tempo e un luogo\lper ogni cosa!{PAUSE_UNTIL_PRESS}");
const u8 gText_PlayerUsedVar2[] = _("{PLAYER} ha usato\n{STR_VAR_2}.{PAUSE_UNTIL_PRESS}");
const u8 gText_RepelEffectsLingered[] = _("Ma l'effetto del Repellente\nusato prima è ancora attivo.{PAUSE_UNTIL_PRESS}");
const u8 gText_LureEffectsLingered[] = _("Ma l'effetto del profumo\nusato prima è ancora attivo.{PAUSE_UNTIL_PRESS}");
const u8 gText_BoxFull[] = _("Il Box è pieno.{PAUSE_UNTIL_PRESS}");
const u8 gText_TheField[] = _("al gioco");
const u8 gText_TheBattle[] = _("alla lotta");
const u8 gText_ThePokemonList[] = _("alla squadra");
const u8 gText_TheShop[] = _("al negozio");
const u8 gText_ThePC[] = _("al PC");

const u8 *const gBagMenu_ReturnToStrings[] =
{
    [ITEMMENULOCATION_FIELD]               = gText_TheField,
    [ITEMMENULOCATION_BATTLE]              = gText_TheBattle,
    [ITEMMENULOCATION_PARTY]               = gText_ThePokemonList,
    [ITEMMENULOCATION_SHOP]                = gText_TheShop,
    [ITEMMENULOCATION_BERRY_TREE]          = gText_TheField,
    [ITEMMENULOCATION_BERRY_BLENDER_CRUSH] = gText_TheField,
    [ITEMMENULOCATION_ITEMPC]              = gText_ThePC,
    [ITEMMENULOCATION_FAVOR_LADY]          = gText_TheField,
    [ITEMMENULOCATION_QUIZ_LADY]           = gText_TheField,
    [ITEMMENULOCATION_APPRENTICE]          = gText_TheField,
    [ITEMMENULOCATION_WALLY]               = gText_TheBattle,
    [ITEMMENULOCATION_PCBOX]               = gText_ThePC,
    [ITEMMENULOCATION_BERRY_TREE_MULCH]    = gText_TheField,
};

const u8 *const gPyramidBagMenu_ReturnToStrings[] =
{
    [PYRAMIDBAG_LOC_FIELD]       = gText_TheField,
    [PYRAMIDBAG_LOC_BATTLE]      = gText_TheBattle,
    [PYRAMIDBAG_LOC_PARTY]       = gText_ThePokemonList,
    [PYRAMIDBAG_LOC_CHOOSE_TOSS] = gText_TheField
};

const u8 gText_ReturnToVar1[] = _("Torna\n{STR_VAR_1}.");

const u8 *const gPocketNamesStringsTable[] =
{
    [POCKET_ITEMS]      = COMPOUND_STRING("Strumenti"),
    [POCKET_POKE_BALLS] = COMPOUND_STRING("Poké Ball"),
    [POCKET_TM_HM]      = COMPOUND_STRING("MT e MN"),
    [POCKET_BERRIES]    = COMPOUND_STRING("Bacche"),
    [POCKET_KEY_ITEMS]  = COMPOUND_STRING("Strum. base")
};

const u8 gText_NumberItem_TMBerry[] = _("{NO}{STR_VAR_1}{CLEAR 3}{STR_VAR_2}");
const u8 gText_NumberItem_HM[] = _("{CLEAR_TO 17}{STR_VAR_1}{CLEAR 5}{STR_VAR_2}");

const u8 gText_ShopBuy[] = _("Compra");
const u8 gText_ShopSell[] = _("Vendi");
const u8 gText_ShopQuit[] = _("Esci");
const u8 gText_ThatItemIsSoldOut[] = _("Mi dispiace, ma è esaurito.{PAUSE_UNTIL_PRESS}");
const u8 gText_SoldOut[] = _("Esaurito");
const u8 gText_InBagVar1[] = _("Borsa: {STR_VAR_1}");
const u8 gText_QuitShopping[] = _("Esci dal negozio.");
const u8 gText_Var1CertainlyHowMany[] = _("{STR_VAR_1}? Certo!\nQuante unità ne vuoi?");
const u8 gText_Var1CertainlyHowMany2[] = _("{STR_VAR_1}? Certo!\nQuante unità ne vuoi?");
const u8 gText_Var1AndYouWantedVar2[] = _("{STR_VAR_1}? E ne vuoi {STR_VAR_2}?\nIn tutto fanno ¥{STR_VAR_3}.");
const u8 gText_Var1IsItThatllBeVar2[] = _("{STR_VAR_1}, giusto?\nCosta ¥{STR_VAR_2}. Va bene?");
const u8 gText_YouWantedVar1ThatllBeVar2[] = _("Vuoi {STR_VAR_1}?\nCosta ¥{STR_VAR_2}. Va bene?");
const u8 gText_HereYouGoThankYou[] = _("Ecco a te!\nGrazie mille.");
const u8 gText_ThankYouIllSendItHome[] = _("Grazie!\nLo invierò al PC di casa tua.");
const u8 gText_ThanksIllSendItHome[] = _("Grazie!\nTe lo mando al PC di casa.");
const u8 gText_YouDontHaveMoney[] = _("Non hai abbastanza soldi.{PAUSE_UNTIL_PRESS}");
const u8 gText_NoMoreRoomForThis[] = _("Non hai più spazio per questo\nstrumento.{PAUSE_UNTIL_PRESS}");
const u8 gText_SpaceForVar1Full[] = _("Lo spazio per {STR_VAR_1} è pieno.{PAUSE_UNTIL_PRESS}");
const u8 gText_AnythingElseICanHelp[] = _("Posso fare qualcos'altro\nper te?");
const u8 gText_CanIHelpWithAnythingElse[] = _("Ti serve qualcos'altro?");
const u8 gText_ThrowInPremierBall[] = _("Ti regalo anche una Premier Ball!{PAUSE_UNTIL_PRESS}");
const u8 gText_ThrowInPremierBalls[] = _("Ti regalo anche {STR_VAR_1} Premier Ball!{PAUSE_UNTIL_PRESS}");
const u8 gText_CantBuyKeyItem[] = _("{STR_VAR_2}? Oh, no.\nNon posso comprarlo.{PAUSE_UNTIL_PRESS}");
const u8 gText_HowManyToSell[] = _("{STR_VAR_2}?\nQuante unità vuoi vendere?");
const u8 gText_ICanPayVar1[] = _("Posso darti ¥{STR_VAR_1}.\nVa bene?");
const u8 gText_TurnedOverVar1ForVar2[] = _("Hai venduto {STR_VAR_2}\ne ricevuto ¥{STR_VAR_1}.");
const u8 gText_PokedollarVar1[] = _("¥{STR_VAR_1}");
const u8 gText_HP3[] = _("PS");
const u8 gText_SpAtk3[] = _("Att. Sp.");
const u8 gText_SpDef3[] = _("Dif. Sp.");
const u8 gText_WontHaveEffect[] = _("Non avrà alcun effetto.{PAUSE_UNTIL_PRESS}");
const u8 gText_NextFusionMon[] = _("Scegli il Pokémon da fondere.");
const u8 gText_CantBeUsedOnPkmn[] = _("Non si può usare su\nquel Pokémon.{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnCantSwitchOut[] = _("{STR_VAR_1} non può\nessere richiamato!{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnAlreadyInBattle[] = _("{STR_VAR_1} è già\nin lotta!{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnAlreadySelected[] = _("{STR_VAR_1} è già stato\nscelto.{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnHasNoEnergy[] = _("{STR_VAR_1} non ha più\nenergie per lottare!{PAUSE_UNTIL_PRESS}");
const u8 gText_CantSwitchWithAlly[] = _("Non puoi scambiare i Pokémon di\n{STR_VAR_1} con i tuoi!{PAUSE_UNTIL_PRESS}");
const u8 gText_EggCantBattle[] = _("Un Uovo non può lottare!{PAUSE_UNTIL_PRESS}");
const u8 gText_CantUseUntilNewBadge[] = _("Non puoi usarla finché non\notterrai una nuova Medaglia.{PAUSE_UNTIL_PRESS}");
const u8 gText_NoMoreThanVar1Pkmn[] = _("Non possono partecipare più\ndi {STR_VAR_1} Pokémon.{PAUSE_UNTIL_PRESS}");
const u8 gText_SendMailToPC[] = _("Vuoi inviare il Messaggio\nal tuo PC?");
const u8 gText_MailSentToPC[] = _("Il Messaggio è stato inviato al PC.{PAUSE_UNTIL_PRESS}");
const u8 gText_PCMailboxFull[] = _("La casella postale del PC è piena.{PAUSE_UNTIL_PRESS}");
const u8 gText_MailMessageWillBeLost[] = _("Se togli il Messaggio, il testo\nandrà perso. Va bene?");
const u8 gText_RemoveMailBeforeItem[] = _("Prima di dare uno strumento,\ndevi togliere il Messaggio.{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnWasGivenItem[] = _("{STR_VAR_1} ora tiene\n{STR_VAR_2}.{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnAlreadyHoldingItemSwitch[] = _("{STR_VAR_1} tiene già\n{STR_VAR_2}.\pVuoi scambiare i due\nstrumenti?");
const u8 gText_PkmnNotHolding[] = _("{STR_VAR_1} non tiene\nnessuno strumento.{PAUSE_UNTIL_PRESS}");
const u8 gText_ReceivedItemFromPkmn[] = _("Hai preso {STR_VAR_2}\nda {STR_VAR_1}.{PAUSE_UNTIL_PRESS}");
const u8 gText_MailTakenFromPkmn[] = _("Hai tolto il Messaggio\nal Pokémon.{PAUSE_UNTIL_PRESS}");
const u8 gText_SwitchedPkmnItem[] = _("Hai preso {STR_VAR_2} e al suo\nposto hai dato {STR_VAR_1}.{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnHoldingItemCantHoldMail[] = _("Questo Pokémon tiene già uno\nstrumento: non può tenere Messaggi.{PAUSE_UNTIL_PRESS}");
const u8 gText_MailTransferredFromMailbox[] = _("Hai preso il Messaggio dalla\ncasella postale.{PAUSE_UNTIL_PRESS}");
const u8 gText_BagFullCouldNotRemoveItem[] = _("La Borsa è piena. Impossibile\ntogliere lo strumento.{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnLearnedMove3[] = _("{STR_VAR_1} ha imparato\n{STR_VAR_2}!");
const u8 gText_PkmnLearnedMove4[] = _("{STR_VAR_1} ha imparato\n{STR_VAR_2}!{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnCantLearnMove[] = _("{STR_VAR_1} e {STR_VAR_2}\nnon sono compatibili.\pNon può imparare\n{STR_VAR_2}.{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnNeedsToReplaceMove[] = _("{STR_VAR_1} vuole imparare\n{STR_VAR_2}.\pMa {STR_VAR_1} conosce\ngià quattro mosse.\pVuoi sostituire una mossa\ncon {STR_VAR_2}?");
const u8 gText_StopLearningMove2[] = _("Rinunci a insegnare\n{STR_VAR_2}?");
const u8 gText_MoveNotLearned[] = _("{STR_VAR_1} non ha imparato\n{STR_VAR_2}.{PAUSE_UNTIL_PRESS}");
const u8 gText_WhichMoveToForget[] = _("Quale mossa deve dimenticare?{PAUSE_UNTIL_PRESS}");
const u8 gText_12PoofForgotMove[] = _("1, {PAUSE 15}2 e{PAUSE 15}… {PAUSE 15}… {PAUSE 15}… {PAUSE 15}{PLAY_SE SE_BALL_BOUNCE_1}Puff!\p{STR_VAR_1} ha dimenticato\n{STR_VAR_2}.\pE…{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnAlreadyKnows[] = _("{STR_VAR_1} conosce già\n{STR_VAR_2}.{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnHPRestoredByVar2[] = _("{STR_VAR_1} recupera\n{STR_VAR_2} PS.{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnCuredOfPoison[] = _("{STR_VAR_1} non è più\navvelenato.{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnCuredOfParalysis[] = _("{STR_VAR_1} non è più\nparalizzato.{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnWokeUp2[] = _("{STR_VAR_1} si è svegliato.{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnBurnHealed[] = _("{STR_VAR_1} non è più scottato.{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnFrostbiteHealed[] = _("{STR_VAR_1} non è più congelato.{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnThawedOut[] = _("{STR_VAR_1} si è scongelato.{PAUSE_UNTIL_PRESS}");
const u8 gText_PPWasRestored[] = _("PP ripristinati.{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnRegainhedHealth[] = _("{STR_VAR_1} si riprende.{PAUSE_UNTIL_PRESS}"); // Unused
const u8 gText_PkmnBecameHealthy[] = _("{STR_VAR_1} è guarito.{PAUSE_UNTIL_PRESS}");
const u8 gText_MovesPPIncreased[] = _("I PP di {STR_VAR_1} aumentano.{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnElevatedToLvVar2[] = _("{STR_VAR_1} è salito al\nLv. {STR_VAR_2}.");
const u8 gText_PkmnGainedExp[] = _("{STR_VAR_1} ottiene {STR_VAR_2} Punti Esp.!{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnGainedExpAndElevatedToLvVar3[] = _("{STR_VAR_1} ottiene {STR_VAR_2} Punti Esp.\ne sale al Lv. {STR_VAR_3}!");
const u8 gText_PkmnBaseVar2StatIncreased[] = _("{STR_VAR_1} migliora la statistica\nbase {STR_VAR_2}.{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnFriendlyBaseVar2Fell[] = _("{STR_VAR_1} è più affettuoso.\nCala la stat. base {STR_VAR_2}!{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnAdoresBaseVar2Fell[] = _("{STR_VAR_1} ti adora!\nCala la stat. base {STR_VAR_2}!{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnFriendlyBaseVar2CantFall[] = _("{STR_VAR_1} è più affettuoso.\nLa stat. base {STR_VAR_2} non cala!{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnSnappedOutOfConfusion[] = _("{STR_VAR_1} non è più\nconfuso.{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnGotOverInfatuation[] = _("{STR_VAR_1} non è più\ninnamorato.{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnTransformed[] = _("{STR_VAR_1} si è trasformato!{PAUSE_UNTIL_PRESS}");
const u8 gText_ThrowAwayItem[] = _("Vuoi gettare\n{STR_VAR_1}?");
const u8 gText_ItemThrownAway[] = _("Hai gettato\n{STR_VAR_1}.{PAUSE_UNTIL_PRESS}");
const u8 gText_TeachWhichPokemon2[] = _("A quale Pokémon insegnarla?"); // Unused
const u8 gText_ChoosePokemon[] = _("Scegli un Pokémon.");
const u8 gText_MoveToWhere[] = _("Dove vuoi spostarlo?");
const u8 gText_TeachWhichPokemon[] = _("A quale Pokémon insegnarla?");
const u8 gText_UseOnWhichPokemon[] = _("Su quale Pokémon usarlo?");
const u8 gText_GiveToWhichPokemon[] = _("A quale Pokémon darlo?");
const u8 gText_DoWhatWithPokemon[] = _("Che fare con il Pokémon?");
const u8 gText_NothingToCut[] = _("Non c'è niente da tagliare.");
const u8 gText_CantSurfHere[] = _("Qui non puoi usare Surf.");
const u8 gText_AlreadySurfing[] = _("Stai già usando Surf.");
const u8 gText_CantUseHere[] = _("Qui non puoi usarlo.");
const u8 gText_RestoreWhichMove[] = _("Quale mossa ricaricare?");
const u8 gText_BoostPP[] = _("Quale mossa potenziare?");
const u8 gText_DoWhatWithItem[] = _("Cosa fare con lo strumento?");
const u8 gText_NoPokemonForBattle[] = _("Nessun Pokémon per lottare!");
const u8 gText_ChoosePokemon2[] = _("Scegli un Pokémon.");
const u8 gText_NotEnoughHp[] = _("PS insufficienti…");
const u8 gText_PokemonAreNeeded[] = _("Servono {STR_VAR_1} Pokémon.");
const u8 gText_PokemonCantBeSame[] = _("Servono Pokémon diversi.");
const u8 gText_NoIdenticalHoldItems[] = _("Niente strumenti uguali.");
const u8 gText_CurrentIsTooFast[] = _("La corrente è troppo forte!");
const u8 gText_DoWhatWithMail[] = _("Cosa fare col Messaggio?");
const u8 gText_ChoosePokemonCancel[] = _("Scegli un Pokémon o annulla.");
const u8 gText_ChoosePokemonConfirm[] = _("Scegli i Pokémon e conferma.");
const u8 gText_SendWhichMonToPC[] = _("Quale Pokémon mandare al PC?");
const u8 gText_MoveItemWhere[] = _("Dove spostare lo strumento?");
const u8 gText_XsYAnd[] = _("{STR_VAR_2} di {STR_VAR_1} e\n");
const u8 gText_XsYWereSwapped[] = _("{STR_VAR_2} di {STR_VAR_1}: scambiati!{PAUSE_UNTIL_PRESS}");
const u8 gText_EnjoyCycling[] = _("Divertiti in bici!");
const u8 gText_InUseAlready_PM[] = _("È già in uso.");
const u8 gText_AlreadyHoldingOne[] = _("{STR_VAR_1} tiene già\n{STR_VAR_2}.");
const u8 gText_WhichAppliance[] = _("Scegli un\nelettrodomestico.");
const u8 gText_NoUse[] = _("Inutile");
const u8 gText_Able[] = _("Idoneo");
const u8 gText_First_PM[] = _("Primo");
const u8 gText_Second_PM[] = _("Secondo");
const u8 gText_Third_PM[] = _("Terzo");
const u8 gText_Able2[] = _("Idoneo");
const u8 gText_NotAble[] = _("Non idoneo");
const u8 gText_Able3[] = _("Impara!");
const u8 gText_NotAble2[] = _("Non impara");
const u8 gText_Learned[] = _("Imparata");
const u8 gText_Have[] = _("Tiene");
const u8 gText_DontHave[] = _("Non tiene");
const u8 gText_Fourth[] = _("Quarto");
const u8 gText_PkmnCantParticipate[] = _("Quel Pokémon non può partecipare.{PAUSE_UNTIL_PRESS}");
const u8 gText_CancelParticipation[] = _("Vuoi ritirare l'iscrizione?");
const u8 gText_CancelBattle[] = _("Vuoi annullare la lotta?");
const u8 gText_ReturnToWaitingRoom[] = _("Vuoi tornare in sala d'attesa?");
const u8 gText_CancelChallenge[] = _("Vuoi annullare la sfida?");
const u8 gText_EscapeFromHere[] = _("Vuoi fuggire da qui e tornare\nin questo luogo: {STR_VAR_1}?");
const u8 gText_ReturnToHealingSpot[] = _("Vuoi tornare all'ultimo luogo\ndi cura: {STR_VAR_1}?");
const u8 gText_PauseUntilPress[] = _("{PAUSE_UNTIL_PRESS}");
const u8 gJPText_AreYouSureYouWantToSpinTradeMon[] = _("Vuoi davvero offrire\n{STR_VAR_1} per lo scambio?");
ALIGNED(4) const u8 gText_OnlyPkmnForBattle[] = _("È il tuo unico Pokémon\nin grado di lottare.");
ALIGNED(4) const u8 gText_PkmnCantBeTradedNow[] = _("Ora quel Pokémon non può\nessere scambiato.");
ALIGNED(4) const u8 gText_PkmnCantBeTraded[] = _("Quel Pokémon non è scambiabile.");
ALIGNED(4) const u8 gText_EggCantBeTradedNow[] = _("Ora non puoi scambiare un Uovo.");
ALIGNED(4) const u8 gText_OtherTrainersPkmnCantBeTraded[] = _("Ora il Pokémon dell'altro\nAllenatore non è scambiabile.");
ALIGNED(4) const u8 gText_OtherTrainerCantAcceptPkmn[] = _("Ora l'altro Allenatore non può\naccettare quel Pokémon.");
ALIGNED(4) const u8 gText_CantTradeWithTrainer[] = _("Ora non puoi fare scambi con\nquell'Allenatore.");
ALIGNED(4) const u8 gText_NotPkmnOtherTrainerWants[] = _("Non è il tipo di Pokémon che\nl'altro Allenatore vuole.");
ALIGNED(4) const u8 gText_ThatIsntAnEgg[] = _("Quello non è un Uovo.");
const u8 gText_Register[] = _("Registra");
const u8 gText_Attack3[] = _("Attacco");
const u8 gText_Defense3[] = _("Difesa");
const u8 gText_SpAtk4[] = _("Att.Sp.");
const u8 gText_SpDef4[] = _("Dif.Sp.");
const u8 gText_Speed2[] = _("Vel.");
const u8 gText_HP4[] = _("PS");
const u8 gText_EmptyString8[] = _(""); // Unused
const u8 gText_OTSlash[] = _("AO/");
const u8 gText_RentalPkmn[] = _("Pokémon a noleggio");
const u8 gText_TypeSlash[] = _("Tipo/");
const u8 gText_Power[] = _("Potenza");
const u8 gText_Accuracy2[] = _("Precis.");
const u8 gText_Appeal[] = _("Esibiz.");
const u8 gText_Jam[] = _("Dist.");
const u8 gText_Status[] = _("Stato");
const u8 gText_ExpPoints[] = _("Punti Esp.");
const u8 gText_NextLv[] = _("Al Lv. succ.");
const u8 gText_RibbonsVar1[] = _("Fiocchi: {STR_VAR_1}");
const u8 gText_EmptyString5[] = _("");
const u8 gText_Events[] = _("Eventi"); // Unused
const u8 gText_Switch[] = _("Scambia");
const u8 gText_PkmnInfo[] = _("Info Pokémon");
const u8 gText_PkmnSkills[] = _("Statistiche");
const u8 gText_BattleMoves[] = _("Mosse lotta");
const u8 gText_ContestMoves[] = _("Mosse gara");
const u8 gText_Info[] = _("Info");
const u8 gText_EggWillTakeALongTime[] = _("Sembra che quest'Uovo ci\nmetterà molto a schiudersi.");
const u8 gText_EggWillTakeSomeTime[] = _("Cosa nascerà da qui?\nCi vorrà ancora un po'.");
const u8 gText_EggWillHatchSoon[] = _("Ogni tanto si muove.\nSi schiuderà presto.");
const u8 gText_EggAboutToHatch[] = _("Si sentono dei rumori.\nSta per schiudersi!");
const u8 gText_HMMovesCantBeForgotten2[] = _("Ora non si possono far\ndimenticare le mosse MN.");
const u8 gText_XNatureMetAtYZ[] = _("Natura {DYNAMIC 0}{DYNAMIC 2}{DYNAMIC 1}{DYNAMIC 5},\nincontrato al {LV_2}{DYNAMIC 0}{DYNAMIC 3}{DYNAMIC 1},\n{DYNAMIC 0}{DYNAMIC 4}{DYNAMIC 1}.");
const u8 gText_XNatureHatchedAtYZ[] = _("Natura {DYNAMIC 0}{DYNAMIC 2}{DYNAMIC 1}{DYNAMIC 5},\nschiuso al {LV_2}{DYNAMIC 0}{DYNAMIC 3}{DYNAMIC 1},\n{DYNAMIC 0}{DYNAMIC 4}{DYNAMIC 1}.");
const u8 gText_XNatureObtainedInTrade[] = _("Natura {DYNAMIC 0}{DYNAMIC 2}{DYNAMIC 1}{DYNAMIC 5},\nottenuto con uno scambio.");
const u8 gText_XNatureFatefulEncounter[] = _("Natura {DYNAMIC 0}{DYNAMIC 2}{DYNAMIC 1}{DYNAMIC 5},\nottenuto in un incontro\nfatidico al {LV_2}{DYNAMIC 0}{DYNAMIC 3}{DYNAMIC 1}.");
const u8 gText_XNatureProbablyMetAt[] = _("Natura {DYNAMIC 0}{DYNAMIC 2}{DYNAMIC 1}{DYNAMIC 5},\nforse incontrato al {LV_2}{DYNAMIC 0}{DYNAMIC 3}{DYNAMIC 1},\n{DYNAMIC 0}{DYNAMIC 4}{DYNAMIC 1}.");
const u8 gText_XNature[] = _("Natura {DYNAMIC 0}{DYNAMIC 2}{DYNAMIC 1}{DYNAMIC 5}");
const u8 gText_XNatureMetSomewhereAt[] = _("Natura {DYNAMIC 0}{DYNAMIC 2}{DYNAMIC 1}{DYNAMIC 5},\nincontrato altrove, {LV_2}{DYNAMIC 0}{DYNAMIC 3}{DYNAMIC 1}.");
const u8 gText_XNatureHatchedSomewhereAt[] = _("Natura {DYNAMIC 0}{DYNAMIC 2}{DYNAMIC 1}{DYNAMIC 5},\nschiuso altrove al {LV_2}{DYNAMIC 0}{DYNAMIC 3}{DYNAMIC 1}.");
const u8 gText_OddEggFoundByCouple[] = _("Uno strano Uovo trovato\ndai nonni della Pensione.");
const u8 gText_PeculiarEggNicePlace[] = _("Un curioso Uovo ottenuto\nin un posto speciale.");
const u8 gText_PeculiarEggTrade[] = _("Un curioso Uovo ottenuto\ncon uno scambio.");
const u8 gText_EggFromHotSprings[] = _("Un Uovo ottenuto\nalle terme.");
const u8 gText_EggFromTraveler[] = _("Uno strano Uovo ottenuto\nda un viaggiatore.");
const u8 gText_ApostropheSBase[] = _(" (Base)");
const u8 gText_OkayToDeleteFromRegistry[] = _("Vuoi cancellare {STR_VAR_1}\ndal Registro?");
const u8 gText_RegisteredDataDeleted[] = _("Dati registrati cancellati.{PAUSE_UNTIL_PRESS}");
const u8 gText_NoRegistry[] = _("Il Registro è vuoto.{PAUSE_UNTIL_PRESS}");
const u8 gText_DelRegist[] = _("Cancella");
const u8 gText_Var3Var1SlashVar2[] = _("{STR_VAR_3}{STR_VAR_1}/{STR_VAR_2}"); // Unused
const u8 gText_Decorate[] = _("Arreda");
const u8 gText_PutAway[] = _("Riponi");
const u8 gText_Toss2[] = _("Getta");
const u8 gText_Color161Shadow161[] = _("{COLOR 161}{SHADOW 161}");
const u8 gText_PutOutSelectedDecorItem[] = _("Sistema la decorazione scelta.");
const u8 gText_StoreChosenDecorInPC[] = _("Riponi la decorazione nel PC.");
const u8 gText_ThrowAwayUnwantedDecors[] = _("Getta le decorazioni inutili.");
const u8 gText_NoDecorations[] = _("Non ci sono decorazioni.{PAUSE_UNTIL_PRESS}");
const u8 gText_Desk[] = _("Scrivania");
const u8 gText_Chair[] = _("Sedia");
const u8 gText_Plant[] = _("Pianta");
const u8 gText_Ornament[] = _("Ornamento");
const u8 gText_Mat[] = _("Tappeto");
const u8 gText_Poster[] = _("Poster");
const u8 gText_Doll[] = _("Bambola");
const u8 gText_Cushion[] = _("Cuscino");
const u8 gText_Gold[] = _("oro");
const u8 gText_Silver[] = _("argento");
const u8 gText_PlaceItHere[] = _("Vuoi metterlo qui?");
const u8 gText_CantBePlacedHere[] = _("Non si può mettere qui.");
const u8 gText_CancelDecorating[] = _("Vuoi smettere di decorare?");
const u8 gText_InUseAlready[] = _("È già in uso.");
const u8 gText_NoMoreDecorations[] = _("Non puoi mettere altre decorazioni.\nNe puoi mettere al massimo {STR_VAR_1}.");
const u8 gText_NoMoreDecorations2[] = _("Non puoi mettere altre decorazioni.\nNe puoi mettere al massimo {STR_VAR_1}.");
const u8 gText_MustBePlacedOnDesk[] = _("Non si può mettere qui.\nVa messo su una scrivania o simili."); // Unused
const u8 gText_CantPlaceInRoom[] = _("Questa decorazione non può essere\nmessa nella tua stanza.");
const u8 gText_CantThrowAwayInUse[] = _("Questa decorazione è in uso.\nNon puoi buttarla via.");
const u8 gText_DecorationWillBeDiscarded[] = _("Stai per buttare via {STR_VAR_1}.\nVa bene?");
const u8 gText_DecorationThrownAway[] = _("La decorazione è stata buttata via.");
const u8 gText_StopPuttingAwayDecorations[] = _("Smettere di riporre le decorazioni?");
const u8 gText_NoDecorationHere[] = _("Qui non c'è nessuna decorazione.");
const u8 gText_ReturnDecorationToPC[] = _("Rimettere la decorazione nel PC?");
const u8 gText_DecorationReturnedToPC[] = _("La decorazione è tornata nel PC.");
const u8 gText_NoDecorationsInUse[] = _("Non ci sono decorazioni in uso.{PAUSE_UNTIL_PRESS}");
const u8 gText_NoItems[] = _("Non ci sono strumenti.{PAUSE_UNTIL_PRESS}");
const u8 gText_NoMailHere[] = _("Qui non ci sono Messaggi.{PAUSE_UNTIL_PRESS}");
const u8 gText_WhatToDoWithVar1sMail[] = _("Cosa vuoi fare con il Messaggio\ndi {STR_VAR_1}?");
const u8 gText_MessageWillBeLost[] = _("Il testo del Messaggio andrà perso.\nVa bene?");
const u8 gText_BagIsFull[] = _("La Borsa è piena.{PAUSE_UNTIL_PRESS}");
const u8 gText_MailToBagMessageErased[] = _("Il Messaggio è tornato nella Borsa\ne il suo testo è stato cancellato.{PAUSE_UNTIL_PRESS}");
const u8 gText_Dad[] = _("Papà");
const u8 gText_Mom[] = _("Mamma");
const u8 gText_CoolnessContest[] = _("Gara Classe");
const u8 gText_BeautyContest[] = _("Gara Bellezza");
const u8 gText_CutenessContest[] = _("Gara Grazia");
const u8 gText_SmartnessContest[] = _("Gara Acume");
const u8 gText_ToughnessContest[] = _("Gara Grinta");
const u8 gText_Information[] = _("Informazioni");
const u8 gText_Yes[] = _("Sì");
const u8 gText_No[] = _("No");
const u8 gText_Lv50[] = _("Liv. 50");
const u8 gText_OpenLevel[] = _("Liv. libero");
const u8 gText_BattleFrontier[] = _("Parco Lotta");
const u8 gText_Cool[] = _("Classe");
const u8 gText_Beauty[] = _("Bellezza");
const u8 gText_Cute[] = _("Grazia");
const u8 gText_Smart[] = _("Acume");
const u8 gText_Tough[] = _("Grinta");
const u8 gText_Normal[] = _("Normale");
const u8 gText_Super[] = _("Super");
const u8 gText_Hyper[] = _("Iper");
const u8 gText_Master[] = _("Master");
const u8 gText_SomeonesPC[] = _("PC di qualcuno");
const u8 gText_LanettesPC[] = _("PC di Lanette");
const u8 gText_BillsPc[] = _("PC di Bill");
const u8 gText_PlayersPC[] = _("PC di {PLAYER}");
const u8 gText_HallOfFame[] = _("Sala d'Onore");
const u8 gText_LogOff[] = _("Spegni");
const u8 gText_Single2[] = _("Singola");
const u8 gText_Double2[] = _("Doppia");
const u8 gText_Multi[] = _("Multipla");
const u8 gText_MultiLink[] = _("Multi Link");
const u8 gText_MenuOptionPokedex[] = _("Pokédex");
const u8 gText_MenuOptionPokemon[] = _("Pokémon");
const u8 gText_MenuOptionBag[] = _("Borsa");
const u8 gText_MenuOptionPokenav[] = _("PokéNav");
const u8 gText_MenuOptionSave[] = _("Salva");
const u8 gText_MenuOptionOption[] = _("Opzioni");
const u8 gText_MenuOptionExit[] = _("Esci");
const u8 gText_SouthernIsland[] = _("Isola Remota");
const u8 gText_BirthIsland[] = _("Isola Materna");
const u8 gText_FarawayIsland[] = _("Isola Suprema");
const u8 gText_NavelRock[] = _("Monte Cordone");
const u8 gText_NormalTagMatch[] = _("Lotta Normale");
const u8 gText_VarietyTagMatch[] = _("Lotta Varia");
const u8 gText_UniqueTagMatch[] = _("Lotta Unica");
const u8 gText_ExpertTagMatch[] = _("Lotta Esperti");
const u8 gText_BattleBasics[] = _("Regole base");
const u8 gText_PokemonNature[] = _("Natura Pokémon");
const u8 gText_PokemonMoves[] = _("Mosse Pokémon");
const u8 gText_Underpowered[] = _("Poca efficacia");
const u8 gText_WhenInDanger[] = _("In pericolo");
const u8 gText_BattlePokemon[] = _("Pokémon in lotta");
const u8 gText_BattleTrainers[] = _("Allenatori");
const u8 gText_1F[] = _("P1");
const u8 gText_2F[] = _("P2");
const u8 gText_3F[] = _("P3");
const u8 gText_4F[] = _("P4");
const u8 gText_5F[] = _("P5");
const u8 gText_6F[] = _("P6");
const u8 gText_7F[] = _("P7");
const u8 gText_8F[] = _("P8");
const u8 gText_9F[] = _("P9");
const u8 gText_10F[] = _("P10");
const u8 gText_11F[] = _("P11");
const u8 gText_B1F[] = _("S1");
const u8 gText_B2F[] = _("S2");
const u8 gText_B3F[] = _("S3");
const u8 gText_B4F[] = _("S4");
const u8 gText_Rooftop[] = _("Tetto");
const u8 gText_ElevatorNowOn[] = _("Sei al:");
const u8 gText_BP[] = _("PL");
const u8 gText_RankingHall[] = _("Sala Record");
const u8 gText_ExchangeService[] = _("Angolo Scambi");
const u8 gText_SlateportCity[] = _("Porto Selcepoli");
const u8 gText_Exit[] = _("Esci");
const u8 gText_YourPartysFull[] = _("La squadra è al completo!{PAUSE_UNTIL_PRESS}");
const u8 gText_InParty[] = _("Squadra");
const u8 gText_PokemonMaleLv[] = _("{DYNAMIC 0}{BACKGROUND WHITE}{TEXT_COLORS LIGHT_RED GREEN WHITE}♂{BACKGROUND WHITE}{TEXT_COLORS DARK_GRAY LIGHT_GRAY WHITE}/{LV}{DYNAMIC 1}"); // Unused
const u8 gText_PokemonFemaleLv[] = _("{DYNAMIC 0}{BACKGROUND WHITE}{TEXT_COLORS LIGHT_GREEN BLUE WHITE}♀{BACKGROUND WHITE}{TEXT_COLORS DARK_GRAY LIGHT_GRAY WHITE}/{LV}{DYNAMIC 1}"); // Unused
const u8 gText_PokemonNoGenderLv[] = _("{DYNAMIC 0}/{LV}{DYNAMIC 1}"); // Unused
const u8 gText_PokemonMaleLv2[] = _("{DYNAMIC 0}{BACKGROUND WHITE}{TEXT_COLORS LIGHT_RED GREEN WHITE}♂{BACKGROUND WHITE}{TEXT_COLORS DARK_GRAY LIGHT_GRAY WHITE}/{LV}{DYNAMIC 1}{DYNAMIC 2}"); // Unused
const u8 gText_PokemonFemaleLv2[] = _("{DYNAMIC 0}{BACKGROUND WHITE}{TEXT_COLORS LIGHT_GREEN BLUE WHITE}♀{BACKGROUND WHITE}{TEXT_COLORS DARK_GRAY LIGHT_GRAY WHITE}/{LV}{DYNAMIC 1}{DYNAMIC 2}"); // Unused
const u8 gText_PokemonNoGenderLv2[] = _("{DYNAMIC 0}/{LV}{DYNAMIC 1}{DYNAMIC 2}"); // Unused
const u8 gText_CombineFourWordsOrPhrases[] = _("Combina quattro parole o frasi");
const u8 gText_AndMakeYourProfile[] = _("e crea il tuo profilo.");
const u8 gText_CombineSixWordsOrPhrases[] = _("Combina sei parole o frasi");
const u8 gText_AndMakeAMessage[] = _("e crea un messaggio.");
const u8 gText_FindWordsThatDescribeYour[] = _("Trova le parole che descrivono");
const u8 gText_FeelingsRightNow[] = _("come ti senti in questo momento.");
const u8 gText_WithFourPhrases[] = _("Con quattro frasi,"); // Unused
const u8 gText_CombineNineWordsOrPhrases[] = _("Combina nove parole o frasi");
const u8 gText_AndMakeAMessage2[] = _("e crea un messaggio.");
const u8 gText_ChangeJustOneWordOrPhrase[] = _("Cambia una sola parola o frase");
const u8 gText_AndImproveTheBardsSong[] = _("e migliora la canzone del Bardo.");
const u8 gText_YourProfile[] = _("Il tuo profilo");
const u8 gText_YourFeelingAtTheBattlesStart[] = _("Cosa provi all'inizio della lotta");
const u8 gText_WhatYouSayIfYouWin[] = _("Cosa dici se vinci una lotta");
const u8 gText_WhatYouSayIfYouLose[] = _("Cosa dici se perdi una lotta");
const u8 gText_TheAnswer[] = _("La risposta");
const u8 gText_TheMailMessage[] = _("Il testo del Messaggio");
const u8 gText_TheMailSalutation[] = _("Il saluto del Messaggio"); // Unused
const u8 gText_TheBardsSong2[] = _("La nuova canzone");
const u8 gText_CombineTwoWordsOrPhrases[] = _("Combina due parole o frasi");
const u8 gText_AndMakeATrendySaying[] = _("e crea un'espressione di moda.");
const u8 gText_TheTrendySaying[] = _("L'espressione di moda");
const u8 gText_IsAsShownOkay[] = _("va bene così?");
const u8 gText_CombineTwoWordsOrPhrases2[] = _("Combina due parole o frasi");
const u8 gText_ToTeachHerAGoodSaying[] = _("e insegnale un bel detto.");
const u8 gText_FindWordsWhichFit[] = _("Trova le parole adatte");
const u8 gText_TheTrainersImage[] = _("all'immagine dell'Allenatore.");
const u8 gText_TheImage[] = _("L'immagine:");
const u8 gText_OutOfTheListedChoices[] = _("Tra le scelte elencate,");
const u8 gText_SelectTheAnswerToTheQuiz[] = _("seleziona la risposta al quiz!");
const u8 gText_AndCreateAQuiz[] = _("e crea un quiz!");
const u8 gText_PickAWordOrPhraseAnd[] = _("Scegli una parola o una frase e");
const u8 gText_SetTheQuizAnswer[] = _("imposta la risposta al quiz.");
const u8 gText_TheAnswerColon[] = _("La risposta:");
const u8 gText_TheQuizColon[] = _("Il quiz:"); // Unused
const u8 gText_ApprenticePhrase[] = _("Frase dell'apprendista:");
const u8 gText_QuitEditing[] = _("Interrompere la modifica?");
const u8 gText_StopGivingPkmnMail[] = _("Rinunci a dare il Messaggio?");
const u8 gText_AndFillOutTheQuestionnaire[] = _("e compila il questionario.");
const u8 gText_LetsReplyToTheInterview[] = _("e rispondi all'intervista!");
const u8 gText_AllTextBeingEditedWill[] = _("Tutto il testo che stai modificando");
const u8 gText_BeDeletedThatOkay[] = _("verrà cancellato. Va bene?");
const u8 gText_QuitEditing2[] = _("Interrompere la modifica?"); // Unused
const u8 gText_EditedTextWillNotBeSaved[] = _("Le modifiche non saranno salvate."); // Unused
const u8 gText_IsThatOkay[] = _("Va bene?"); // Unused
const u8 gText_PleaseEnterPhraseOrWord[] = _("Inserisci una parola o una frase."); // Unused
const u8 gText_EntireTextCantBeDeleted[] = _("Non puoi cancellare tutto il testo.");
const u8 gText_OnlyOnePhrase[] = _("Puoi cambiare una sola frase.");
const u8 gText_OriginalSongWillBeUsed[] = _("Verrà usata la canzone originale.");
const u8 gText_ThatsTrendyAlready[] = _("È già di moda!"); // Unused
const u8 gText_CombineTwoWordsOrPhrases3[] = _("Combina due parole o frasi.");
const u8 gText_QuitGivingInfo[] = _("Smettere di dare informazioni?"); // Unused
const u8 gText_StopGivingPkmnMail2[] = _("Rinunci a dare il Messaggio?"); // Unused
const u8 gText_CreateAQuiz2[] = _("Crea un quiz!"); // Unused
const u8 gText_SetTheAnswer[] = _("Imposta la risposta!"); // Unused
const u8 gText_CancelSelection[] = _("Annullare la scelta?"); // Unused
const u8 gText_Profile[] = _("Profilo");
const u8 gText_AtTheBattlesStart[] = _("A inizio lotta:");
const u8 gText_UponWinningABattle[] = _("In caso di vittoria:");
const u8 gText_UponLosingABattle[] = _("In caso di sconfitta:");
const u8 gText_TheBardsSong[] = _("La canzone del Bardo");
const u8 gText_WhatsHipAndHappening[] = _("Cosa va di moda?");
const u8 gText_Interview[] = _("Intervista");
const u8 gText_GoodSaying[] = _("Bel detto");
const u8 gText_FansQuestion[] = _("Domanda del fan");
const u8 gJPText_WhatIsTheQuizAnswer[] = _("クイズの こたえは？"); // Unused
const u8 gText_ApprenticesPhrase[] = _("Frase dell'apprendista");
const u8 gText_Questionnaire[] = _("Questionario");
const u8 gText_YouCannotQuitHere[] = _("Non puoi uscire ora.");
const u8 gText_SectionMustBeCompleted[] = _("Devi completare questa sezione.");
const u8 gText_F700sQuiz[] = _("Quiz: {DYNAMIC 0}");
const u8 gText_Lady[] = _("Signora");
const u8 gText_AfterYouHaveReadTheQuiz[] = _("Dopo aver letto la domanda del quiz,");
const u8 gText_QuestionPressTheAButton[] = _("premi il pulsante A.");
const u8 gText_TheQuizAnswerIs[] = _("Qual è la risposta?");
const u8 gText_LikeToQuitQuiz[] = _("Vuoi rinunciare a questa sfida");
const u8 gText_ChallengeQuestionMark[] = _("a quiz?");
const u8 gText_IsThisQuizOK[] = _("Il quiz va bene così?");
const u8 gText_CreateAQuiz[] = _("Crea un quiz!");
const u8 gText_SelectTheAnswer[] = _("Scegli la risposta!");
const u8 gText_LyricsCantBeDeleted[] = _("Non puoi cancellare il testo.");
const u8 gText_PokemonLeague[] = _("Lega Pokémon");
const u8 gText_PokemonCenter[] = _("Centro Pokémon");
const u8 gText_Coolness[] = _("Classe ");
const u8 gText_Beauty3[] = _("Bellezza ");
const u8 gText_Cuteness[] = _("Grazia ");
const u8 gText_Smartness[] = _("Acume ");
const u8 gText_Toughness[] = _("Grinta ");
const u8 gText_SaveFailedCheckingBackup[] = _("Salvataggio non riuscito. Controllo\ndella memoria di backup… Attendi.\n{COLOR RED}“Tempo necessario: circa 1 minuto”");
const u8 gText_BackupMemoryDamaged[] = _("La memoria di backup è danneggiata o\nla batteria interna è esaurita.\nPuoi giocare, ma non salvare.");
const u8 gText_GamePlayCannotBeContinued[] = _("{COLOR RED}“Impossibile continuare la partita.\nRitorno alla schermata del titolo…”");
const u8 gText_CheckCompleted[] = _("Controllo completato.\nNuovo tentativo di salvataggio.\nAttendi.");
const u8 gText_SaveCompleteGameCannotContinue[] = _("Salvataggio completato.\n{COLOR RED}“Impossibile continuare la partita.\nRitorno alla schermata del titolo.”");
const u8 gText_SaveCompletePressA[] = _("Salvataggio completato.\n{COLOR RED}“Premi il pulsante A.”");
const u8 gText_Ferry[] = _("Traghetto");
const u8 gText_SecretBase[] = _("Base Segreta");
const u8 gText_Hideout[] = _("Covo");
const u8 gText_ResetRTCConfirmCancel[] = _("Reimpostare l'orologio?\nA: Conferma, B: Annulla");
const u8 gText_PresentTime[] = _("Ora attuale nel gioco");
const u8 gText_PreviousTime[] = _("Ora precedente nel gioco");
const u8 gText_PleaseResetTime[] = _("Reimposta l'ora.");
const u8 gText_ClockHasBeenReset[] = _("L'orologio è stato reimpostato.\nSalvataggio dei dati. Attendi.");
const u8 gText_SaveCompleted[] = _("Salvataggio completato.");
const u8 gText_SaveFailed[] = _("Salvataggio non riuscito…");
const u8 gText_NoSaveFileCantSetTime[] = _("Non c'è nessun file di salvataggio,\nquindi non puoi impostare l'ora.");
const u8 gText_InGameClockUsable[] = _("Ora puoi regolare l'orologio interno\ndel gioco.");
const u8 gText_Spicy2[] = _("piccante");
const u8 gText_Dry2[] = _("secca");
const u8 gText_Sweet2[] = _("dolce");
const u8 gText_Bitter2[] = _("amara");
const u8 gText_Sour2[] = _("aspra");
const u8 gText_Single[] = _("Singola");
const u8 gText_Double[] = _("Doppia");
const u8 gText_Knockout[] = _("Eliminazione");
const u8 gText_Mixed[] = _("Mista");
const u8 gText_First[] = _("primo");
const u8 gText_Second[] = _("secondo");
const u8 gText_Third[] = _("terzo");
#if OW_POISON_DAMAGE < GEN_4
const u8 gText_PkmnFainted_FldPsn[] = _("{STR_VAR_1} è esausto…\p\n");
#else
const u8 gText_PkmnFainted_FldPsn[] = _("{STR_VAR_1} ha resistito al veleno.\nL'avvelenamento è svanito!\p");
#endif
const u8 gText_Marco[] = _("Marco");
const u8 gText_TrainerCardName[] = _("Nome: ");
const u8 gText_TrainerCardIDNo[] = _("N.ID ");
const u8 gText_TrainerCardMoney[] = _("Soldi");
const u8 gText_PokeDollar[] = _("¥"); // Unused
const u8 gText_TrainerCardPokedex[] = _("Pokédex");
const u8 gText_EmptyString6[] = _("");
const u8 gText_Colon2[] = _(":");
const u8 gText_Points[] = _(" punti"); // Unused
const u8 gText_TrainerCardTime[] = _("Tempo");
const u8 gJPText_BattlePoints[] = _("ゲ-ムポイント"); // Unused. Name presumed, translation is Game Points
const u8 gText_Var1sTrainerCard[] = _("Scheda Allenatore di {STR_VAR_1}");
const u8 gText_HallOfFameDebut[] = _("Debutto Sala d'Onore  ");
const u8 gText_LinkBattles[] = _("Lotte in link");
const u8 gText_LinkCableBattles[] = _("Lotte via cavo");
const u8 gText_WinsLosses[] = _("V:{COLOR RED}{SHADOW LIGHT_RED}{STR_VAR_1}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}  S:{COLOR RED}{SHADOW LIGHT_RED}{STR_VAR_2}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}");
const u8 gText_PokemonTrades[] = _("Scambi Pokémon");
const u8 gText_UnionTradesAndBattles[] = _("Scambi e lotte Unione");
const u8 gText_BerryCrush[] = _("Macinabacche");
const u8 gText_WaitingTrainerFinishReading[] = _("Attendi che l'altro Allenatore finisca\ndi leggere la tua Scheda Allenatore.");
const u8 gText_PokeblocksWithFriends[] = _("Pokémelle con amici");
const u8 gText_NumPokeblocks[] = _("{STR_VAR_1}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}");
const u8 gText_WonContestsWFriends[] = _("Gare vinte con amici");
const u8 gText_BattlePtsWon[] = _("Punti Lotta ottenuti");
const u8 gText_NumBP[] = _("{STR_VAR_1}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}PL");
const u8 gText_BattleTower[] = _("Torre Lotta");
const u8 gText_WinsStraight[] = _("V/{COLOR RED}{SHADOW LIGHT_RED}{STR_VAR_1}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}  Serie/{COLOR RED}{SHADOW LIGHT_RED}{STR_VAR_2}");
const u8 gText_BattleTower2[] = _("Torre Lotta");
const u8 gText_BattleDome[] = _("Cupola Lotta");
const u8 gText_BattlePalace[] = _("Palazzo Lotta");
const u8 gText_BattleFactory[] = _("Azienda Lotta");
const u8 gText_BattleArena[] = _("Dojo Lotta");
const u8 gText_BattlePike[] = _("Serpe Lotta");
const u8 gText_BattlePyramid[] = _("Piramide Lotta");

ALIGNED(4) const u8 gText_FacilitySingle[] = _("{STR_VAR_1} Singola");
ALIGNED(4) const u8 gText_FacilityDouble[] = _("{STR_VAR_1} Doppia");
ALIGNED(4) const u8 gText_FacilityMulti[] = _("{STR_VAR_1} Multipla");
ALIGNED(4) const u8 gText_FacilityLink[] = _("{STR_VAR_1} Link");
ALIGNED(4) const u8 gText_Facility[] = _("{STR_VAR_1}");

const u8 gText_Give[] = _("Dai");
const u8 gText_NoNeed[] = _("Non serve");
const u8 gText_AnnouncingResults[] = _("Ecco i risultati!");
const u8 gText_PreliminaryResults[] = _("I risultati preliminari!");
const u8 gText_Round2Results[] = _("Risultati del secondo turno!");
const u8 gText_ContestantsMonWon[] = _("Vince {STR_VAR_1} con {STR_VAR_2}!");
const u8 gText_CommunicationStandby[] = _("In attesa di comunicazione…");
const u8 gText_ColorDarkGray[] = _("{COLOR DARK_GRAY}");
const u8 gText_ColorDynamic6WhiteDynamic5[] = _("{BACKGROUND WHITE}{TEXT_COLORS DYNAMIC_COLOR6 DYNAMIC_COLOR5 WHITE}"); // Unused
const u8 gText_HealthboxNickname[] = _("{BACKGROUND DARK_GRAY}{ACCENT DARK_GRAY}");
const u8 gText_EmptySpace2[] = _(" "); // Unused
const u8 gText_HealthboxGender_Male[] = _("{COLOR DYNAMIC_COLOR2}♂");
const u8 gText_HealthboxGender_Female[] = _("{COLOR DYNAMIC_COLOR1}♀");
const u8 gText_HealthboxGender_None[] = _("{COLOR DYNAMIC_COLOR2}");
const u8 gText_Upper[] = _("MAIUSC.");
const u8 gText_Lower[] = _("minusc.");
const u8 gText_Others[] = _("Altri");
const u8 gText_Symbols[] = _("Simboli");
const u8 gText_Register2[] = _("Registra");
const u8 gText_Exit2[] = _("Esci");
const u8 gText_QuitChatting[] = _("Vuoi uscire dalla chat?");
const u8 gText_RegisterTextWhere[] = _("Dove registrare il testo?");
const u8 gText_RegisterTextHere[] = _("Registrare il testo qui?");
const u8 gText_InputText[] = _("Inserisci il testo.");
const u8 gText_F700JoinedChat[] = _("{DYNAMIC 0} è in chat!");
const u8 gText_F700LeftChat[] = _("{DYNAMIC 0} ha lasciato la chat.");
const u8 gJPText_PlayersXPokemon[] = _("{DYNAMIC 0}の{DYNAMIC 1}ひきめ:"); // Unused
const u8 gJPText_PlayersXPokmonDoesNotExist[] = _("{DYNAMIC 0}の{DYNAMIC 1}ひきめは いません"); // Unused
const u8 gText_ExitingChat[] = _("Uscita dalla chat…");
const u8 gText_LeaderLeftEndingChat[] = _("{DYNAMIC 0}, il capogruppo, ha\nlasciato. La chat è terminata.");
const u8 gText_RegisteredTextChangedOKToSave[] = _("Il testo registrato è stato modificato.\nVuoi salvare la partita?");
const u8 gText_AlreadySavedFile_Chat[] = _("C'è già un file di salvataggio.\nVuoi sovrascriverlo?");
const u8 gText_SavingDontTurnOff_Chat[] = _("Salvataggio in corso…\nNon spegnere la console.");
const u8 gText_PlayerSavedGame_Chat[] = _("{DYNAMIC 0} ha salvato la partita.");
const u8 gText_IfLeaderLeavesChatEnds[] = _("Se il capogruppo esce, la chat\nterminerà. Va bene?");
const u8 gText_Hello[] = _("Ciao");
const u8 gText_Pokemon2[] = _("Pokémon");
const u8 gText_Trade[] = _("Scambio");
const u8 gText_Battle[] = _("Lotta");
const u8 gText_Lets[] = _("Dai");
const u8 gText_Ok[] = _("OK!");
const u8 gText_Sorry[] = _("Scusa");
const u8 gText_YaySmileEmoji[] = _("Evvai{EMOJI_BIGSMILE}");
const u8 gText_ThankYou[] = _("Grazie");
const u8 gText_ByeBye[] = _("A presto");
const u8 gText_HatchedFromEgg[] = _("Dall'Uovo è uscito {STR_VAR_1}!");
const u8 gText_NicknameHatchPrompt[] = _("Vuoi dare un soprannome al\n{STR_VAR_1} appena nato?");
ALIGNED(4) const u8 gText_ReadyPickBerry[] = _("Pronto per il Macinabacche?\nScegli una Bacca da usare.\p");
ALIGNED(4) const u8 gText_WaitForAllChooseBerry[] = _("Attendi che ogni partecipante\nscelga una Bacca.");
ALIGNED(4) const u8 gText_EndedWithXUnitsPowder[] = _("{PAUSE_MUSIC}{PLAY_BGM MUS_LEVEL_UP}Hai ottenuto {STR_VAR_1} unità di\nfinissima Farina di Bacche.{RESUME_MUSIC}\pIn totale hai {STR_VAR_2} unità\ndi Farina di Bacche.\p");
ALIGNED(4) const u8 gText_RecordingGameResults[] = _("Registrazione dei risultati nel\nfile di salvataggio.\lAttendi.");
ALIGNED(4) const u8 gText_PlayBerryCrushAgain[] = _("Vuoi giocare ancora a Macinabacche?");
ALIGNED(4) const u8 gText_YouHaveNoBerries[] = _("Non hai nessuna Bacca.\nIl gioco verrà annullato.");
ALIGNED(4) const u8 gText_MemberDroppedOut[] = _("Un partecipante si è ritirato.\nIl gioco verrà annullato.");
ALIGNED(4) const u8 gText_TimesUpNoGoodPowder[] = _("Tempo scaduto.\pNon è stato possibile ottenere\nuna buona Farina di Bacche…\p");
ALIGNED(4) const u8 gText_CommunicationStandby2[] = _("In attesa di comunicazione…");
ALIGNED(4) const u8 gText_1DotBlueF700[] = _("1. {COLOR BLUE}{SHADOW LIGHT_BLUE}{DYNAMIC 0}");
ALIGNED(4) const u8 gText_1DotF700[] = _("1. {DYNAMIC 0}");
ALIGNED(4) const u8 gText_SpaceTimes2[] = _(" volte");
ALIGNED(4) const u8 gText_XDotY[] = _("{STR_VAR_1},{STR_VAR_2}");
ALIGNED(4) const u8 gText_Var1Berry[] = _("Bacca {STR_VAR_1}");
ALIGNED(4) const u8 gText_TimeColon[] = _("Tempo:");
ALIGNED(4) const u8 gText_PressingSpeed[] = _("Velocità:");
ALIGNED(4) const u8 gText_Silkiness[] = _("Finezza:");
ALIGNED(4) const u8 gText_StrVar1[] = _("{STR_VAR_1}");
ALIGNED(4) const u8 gText_SpaceMin[] = _(" min. ");
ALIGNED(4) const u8 gText_XDotY2[] = _("{STR_VAR_1},{STR_VAR_2}");
ALIGNED(4) const u8 gText_SpaceSec[] = _(" sec.");
ALIGNED(4) const u8 gText_XDotY3[] = _("{STR_VAR_1},{STR_VAR_2}");
ALIGNED(4) const u8 gText_TimesPerSec[] = _(" volte/s");
ALIGNED(4) const u8 gText_Var1Percent[] = _("{STR_VAR_1}%");
ALIGNED(4) const u8 gText_PressesRankings[] = _("Classifica pressioni");
ALIGNED(4) const u8 gText_CrushingResults[] = _("Risultati");
ALIGNED(4) const u8 gText_NeatnessRankings[] = _("Classifica precisione");
ALIGNED(4) const u8 gText_CoopRankings[] = _("Classifica intesa");
ALIGNED(4) const u8 gText_PressingPowerRankings[] = _("Classifica potenza");
const u8 gText_BerryCrush2[] = _("Macinabacche");
const u8 gText_PressingSpeedRankings[] = _("Classifica velocità");
const u8 gText_Var1Players[] = _("{STR_VAR_1} giocatori");
const u8 gText_SymbolsEarned[] = _("Simboli ottenuti");
const u8 gText_BattleRecord[] = _("Registro lotte");
const u8 gText_BattlePoints[] = _("Punti Lotta");
const u8 gText_UnusedCancel[] = _("Annulla"); // Unused
const u8 gText_EmptyString7[] = _("");
const u8 gText_CheckFrontierMap[] = _("Consulta la mappa del Parco Lotta.");
const u8 gText_CheckTrainerCard[] = _("Consulta la Scheda Allenatore.");
const u8 gText_ViewRecordedBattle[] = _("Guarda la lotta registrata.");
const u8 gText_PutAwayFrontierPass[] = _("Metti via il Pass Lotta.");
const u8 gText_CurrentBattlePoints[] = _("I tuoi Punti Lotta attuali.");
const u8 gText_CollectedSymbols[] = _("I Simboli che hai ottenuto.");
const u8 gText_BattleTowerAbilitySymbol[] = _("Torre Lotta - Simbolo Abilità");
const u8 gText_BattleDomeTacticsSymbol[] = _("Cupola Lotta - Simbolo Tattica");
const u8 gText_BattlePalaceSpiritsSymbol[] = _("Palazzo Lotta - Simbolo Spirito");
const u8 gText_BattleArenaGutsSymbol[] = _("Dojo Lotta - Simbolo Grinta");
const u8 gText_BattleFactoryKnowledgeSymbol[] = _("Azienda Lotta - Simbolo Sapere");
const u8 gText_BattlePikeLuckSymbol[] = _("Serpe Lotta - Simbolo Fortuna");
const u8 gText_BattlePyramidBraveSymbol[] = _("Piramide Lotta - Simbolo Coraggio");
const u8 gText_ThereIsNoBattleRecord[] = _("Non c'è nessuna lotta registrata.");
const u8 gText_BattleTower3[] = _("Torre Lotta");
const u8 gText_BattleDome2[] = _("Cupola Lotta");
const u8 gText_BattlePalace2[] = _("Palazzo Lotta");
const u8 gText_BattleArena2[] = _("Dojo Lotta");
const u8 gText_BattleFactory2[] = _("Azienda Lotta");
const u8 gText_BattlePike2[] = _("Serpe Lotta");
const u8 gText_BattlePyramid2[] = _("Piramide Lotta");
const u8 gText_BattleTowerDesc[] = _("Batti gli avversari e punta alla vetta!\nMetti alla prova la tua abilità.");
const u8 gText_BattleDomeDesc[] = _("Continua a vincere nel torneo!\nMetti alla prova la tua tattica.");
const u8 gText_BattlePalaceDesc[] = _("Guarda lottare i tuoi Pokémon!\nMetti alla prova il tuo spirito.");
const u8 gText_BattleArenaDesc[] = _("Vinci lottando con Pokémon affiatati!\nMetti alla prova la tua grinta.");
const u8 gText_BattleFactoryDesc[] = _("Vinci con dei Pokémon a noleggio!\nMetti alla prova il tuo sapere.");
const u8 gText_BattlePikeDesc[] = _("Scegli uno dei tre percorsi e lotta!\nMetti alla prova la tua fortuna.");
const u8 gText_BattlePyramidDesc[] = _("Raggiungi la vetta esplorando!\nMetti alla prova il tuo coraggio.");
const u8 gText_Powder[] = _("Polvere");
const u8 gText_BerryPickingRecords[] = _("Record Raccolta Bacche Dodrio");
const u8 gText_BerriesPicked[] = _("Bacche raccolte:");
const u8 gText_BestScore[] = _("Miglior punteggio:");
const u8 gText_BerriesInRowFivePlayers[] = _("Bacche raccolte di fila\ncon cinque giocatori:");
const u8 gText_BerryPickingResults[] = _("Ecco i risultati della raccolta!");
const u8 gText_10P30P50P50P[] = _("{CLEAR_TO 3}10P{CLEAR_TO 43}30P{CLEAR_TO 83}50P{CLEAR_TO 119}{EMOJI_MINUS}50P");
const u8 gText_AnnouncingRankings[] = _("Ecco la classifica!");
const u8 gText_AnnouncingPrizes[] = _("Ecco i premi!");
const u8 gText_1Colon[] = _("1:");
const u8 gText_2Colon[] = _("2:");
const u8 gText_3Colon[] = _("3:");
const u8 gText_4Colon[] = _("4:");
const u8 gText_5Colon[] = _("5:");
const u8 gText_FirstPlacePrize[] = _("Premio per il primo posto:\n{DYNAMIC 0}!");
const u8 gText_CantHoldAnyMore[] = _("Non hai più spazio!");
const u8 gText_FilledStorageSpace[] = _("Lo spazio nella Borsa è esaurito.");
const u8 gText_WantToPlayAgain[] = _("Vuoi giocare ancora?");
const u8 gText_SomeoneDroppedOut[] = _("Qualcuno si è ritirato.\nIl collegamento verrà chiuso.");
const u8 gText_SpacePoints[] = _(" punti");
const u8 gText_CommunicationStandby3[] = _("Comunicazione in corso…");
const u8 gText_SpacePoints2[] = _(" punti");
const u8 gText_SpaceTimes3[] = _(" volte");
const u8 gText_PkmnJumpRecords[] = _("Record Salto Pokémon");
const u8 gText_JumpsInARow[] = _("Salti di fila:");
const u8 gText_BestScore2[] = _("Miglior punteggio:");
const u8 gText_ExcellentsInARow[] = _("Eccellenti di fila:");
const u8 gText_AwesomeWonF701F700[] = _("Punteggio fantastico!\nHai vinto {DYNAMIC 1} {DYNAMIC 0}!");
const u8 gText_FilledStorageSpace2[] = _("Lo spazio nella Borsa è esaurito.");
const u8 gText_CantHoldMore[] = _("Non hai più spazio!");
const u8 gText_WantToPlayAgain2[] = _("Vuoi giocare ancora?");
const u8 gText_SomeoneDroppedOut2[] = _("Qualcuno si è ritirato.\nIl collegamento verrà chiuso.");
const u8 gText_CommunicationStandby4[] = _("Comunicazione in corso…");
const u8 gText_LinkContestResults[] = _("Risultati Gare in Link di {PLAYER}");
const u8 gText_1st[] = _("1º");
const u8 gText_2nd[] = _("2º");
const u8 gText_3rd[] = _("3º");
const u8 gText_4th[] = _("4º");
const u8 gText_Friend[] = _("Amico");
const u8 gText_Pokemon3[] = _("Pokémon"); // Unused
const u8 gJPText_MysteryGift[] = _("ふしぎなもらいもの");
const u8 gJPText_DecideStop[] = _("{A_BUTTON}けってい {B_BUTTON}やめる");
const u8 gJPText_ReceiveMysteryGiftWithEReader[] = _("カードeリーダー{PLUS}　で\nふしぎなもらいものを　よみこみます");
const u8 gJPText_SelectConnectFromEReaderMenu[] = _("カードeリーダー{PLUS}の　メニューから\n‘つうしん'を　えらび");
const u8 gJPText_SelectConnectWithGBA[] = _("‘ゲームボーイアドバンスとつうしん'\nを　せんたく　してください");
const u8 gJPText_SelectConnectAndPressA[] = _("カードeリーダー{PLUS}の　‘つうしん'を\nえらんで　Aボタンを　おしてください"); // Unused
const u8 gJPText_LinkIsIncorrect[] = _("せつぞくが　まちがっています");
const u8 gJPText_CardReadingHasBeenHalted[] = _("カードの　よみこみを\nちゅうし　しました");
const u8 gJPText_UnableConnectWithEReader[] = _("カードeリーダー{PLUS}と\nつうしん　できません"); // Unused
const u8 gJPText_Connecting[] = _("つうしん　ちゅう　です");
const u8 gJPText_ConnectionErrorCheckLink[] = _("つうしん　エラーです\nせつぞくを　たしかめて　ください");
const u8 gJPText_ConnectionErrorTryAgain[] = _("つうしん　エラーです\nはじめから　やりなおして　ください"); // Link error
const u8 gJPText_AllowEReaderToLoadCard[] = _("カードeリーダー{PLUS}　に\nカードを　よみこませて　ください");
const u8 gJPText_ConnectionComplete[] = _("つうしん　しゅうりょう！");
const u8 gJPText_NewTrainerHasComeToHoenn[] = _("あらたな　トレーナーが\nホウエンに　やってきた！");
const u8 gJPText_PleaseWaitAMoment[] = _("しばらく　おまちください");
const u8 gJPText_WriteErrorUnableToSaveData[] = _("かきこみ　エラー　です\nデータが　ほぞん　できませんでした");
const u8 gText_SingleBattleRoomResults[] = _("Risultati Lotta Singola di {PLAYER}");
const u8 gText_DoubleBattleRoomResults[] = _("Risultati Lotta Doppia di {PLAYER}");
const u8 gText_MultiBattleRoomResults[] = _("Risultati Lotta Multipla di {PLAYER}");
const u8 gText_LinkMultiBattleRoomResults[] = _("Risultati Lotta Multipla Link di {PLAYER}");
const u8 gText_SingleBattleTourneyResults[] = _("Risultati Torneo Singolo di {PLAYER}");
const u8 gText_DoubleBattleTourneyResults[] = _("Risultati Torneo Doppio di {PLAYER}");
const u8 gText_SingleBattleHallResults[] = _("Risultati Lotta Singola di {PLAYER}");
const u8 gText_DoubleBattleHallResults[] = _("Risultati Lotta Doppia di {PLAYER}");
const u8 gText_BattleChoiceResults[] = _("Risultati Lotta a Scelta di {PLAYER}");
const u8 gText_SetKOTourneyResults[] = _("Risultati Torneo KO di {PLAYER}");
const u8 gText_BattleSwapSingleResults[] = _("Risultati Scambio Singolo di {PLAYER}");
const u8 gText_BattleSwapDoubleResults[] = _("Risultati Scambio Doppio di {PLAYER}");
const u8 gText_BattleQuestResults[] = _("Risultati Esplorazione di {PLAYER}");
const u8 gText_Lv502[] = _("Liv. 50");
const u8 gText_OpenLv[] = _("Liv. Lib.");
const u8 gText_WinStreak[] = _("Vittorie: {STR_VAR_1}");
const u8 gText_Current[] = _("Attuale");
const u8 gText_Record[] = _("Record");
const u8 gText_Prev[] = _("Prec.");
const u8 gText_RentalSwap[] = _("Noleggi");
const u8 gText_Total[] = _("Totale");
const u8 gText_ClearStreak[] = _("Tornei vinti: {STR_VAR_1}");
const u8 gText_Championships[] = _("Titoli: {STR_VAR_1}");
const u8 gText_RoomsCleared[] = _("Stanze: {STR_VAR_1}");
const u8 gText_TimesCleared[] = _("Completata:{CLEAR 5}{STR_VAR_1}");
const u8 gText_KOsInARow[] = _("KO di fila: {STR_VAR_1}");
const u8 gText_TimesVar1[] = _("Volte: {STR_VAR_1}");
const u8 gText_FloorsCleared[] = _("Piani superati: {STR_VAR_1}");

ALIGNED(4) const u8 gText_RecordsLv50[] = _("Liv. 50");
ALIGNED(4) const u8 gText_RecordsOpenLevel[] = _("Liv. Libero");
ALIGNED(4) const u8 gText_FrontierFacilityWinStreak[] = _("Vittorie: {STR_VAR_2}");
ALIGNED(4) const u8 gText_FrontierFacilityClearStreak[] = _("Tornei vinti: {STR_VAR_2}");
ALIGNED(4) const u8 gText_FrontierFacilityRoomsCleared[] = _("Stanze superate: {STR_VAR_2}");
ALIGNED(4) const u8 gText_FrontierFacilityKOsStreak[] = _("KO di fila: {STR_VAR_2}");
ALIGNED(4) const u8 gText_FrontierFacilityFloorsCleared[] = _("Piani superati: {STR_VAR_2}");
ALIGNED(4) const u8 gText_123Dot[][3] = {_("1."), _("2."), _("3.")};
const u8 gText_FrontierFacilityTotalCaughtSpeciesBanned[] = _(" e {STR_VAR_2} specie di Pokémon\nche hai catturato non sono ammesse");
const u8 gText_FrontierFacilityIncluding[] = _(".\pTra queste: ");
const u8 gText_FrontierFacilityAreInelegible[] = _(" non sono ammesse");

const u8 gText_YesNo[] = _("Sì\nNo");
const u8 gText_SelectorArrow3[] = _("▶");
const u8 gText_Peekaboo[] = _("Cucù!");
const u8 gText_CommErrorCheckConnections[] = _("Errore di comunicazione…\nControlla tutti i collegamenti,\npoi spegni e riaccendi la console.");
const u8 gText_CommErrorEllipsis[] = _("Errore di comunicazione…");
const u8 gText_MoveCloserToLinkPartner[] = _("Avvicinati agli altri giocatori.\nEvita gli ostacoli tra le console.");
const u8 gText_ABtnRegistrationCounter[] = _("Pulsante A: torna al bancone");
const u8 gText_ABtnTitleScreen[] = _("Pulsante A: schermata del titolo");
const u8 gText_NumPlayerLink[] = _("Link a {STR_VAR_1}");
const u8 gText_BronzeCard[] = _("Bronzo");
const u8 gText_CopperCard[] = _("Rame");
const u8 gText_SilverCard[] = _("Argento");
const u8 gText_GoldCard[] = _("Oro");
const u8 gText_Day[] = _(" gg ");
const u8 gText_Colon3[] = _(":");
const u8 gText_Confirm2[] = _("OK");
const u8 gText_Days[] = _("Gg."); // Unused
const u8 gText_TimeColon2[] = _("Ora:"); // Unused
const u8 gText_GameTime[] = _("Ora gioco"); // Unused
const u8 gText_RTCTime[] = _("Ora RTC"); // Unused
const u8 gText_UpdatedTime[] = _("Ora nuova"); // Unused
const u8 gText_MenuPokedex[] = _("Pokédex");
const u8 gText_MenuPokemon[] = _("Pokémon");
const u8 gText_MenuBag[] = _("Borsa");
const u8 gText_MenuPokenav[] = _("PokéNav");
const u8 gText_MenuPlayer[] = _("{PLAYER}");
const u8 gText_MenuSave[] = _("Salva");
const u8 gText_MenuOption[] = _("Opzioni");
const u8 gText_MenuExit[] = _("Esci");
const u8 gText_MenuRetire[] = _("Ritirati");
const u8 gText_MenuRest[] = _("Riposa");
const u8 gText_MenuDexNav[] = _("DEXNAV");
const u8 gText_SafariBallStock[] = _("Safari Ball\nScorte: {STR_VAR_1}");
const u8 gText_MenuSafariStats[] = _("{STR_VAR_1}/{STR_VAR_2}\nBall  {STR_VAR_3}");
const u8 gText_BattlePyramidFloor[] = _("Piramide Lotta\n{STR_VAR_1}");
const u8 gText_Floor1[] = _("Piano 1");
const u8 gText_Floor2[] = _("Piano 2");
const u8 gText_Floor3[] = _("Piano 3");
const u8 gText_Floor4[] = _("Piano 4");
const u8 gText_Floor5[] = _("Piano 5");
const u8 gText_Floor6[] = _("Piano 6");
const u8 gText_Floor7[] = _("Piano 7");
const u8 gText_Peak[] = _("Vetta");
const u8 gText_LinkStandby2[] = _("In attesa di collegamento…\n… … Pulsante B: Annulla");
const u8 gText_PressAToLoadEvent[] = _("Premi il pulsante A per caricare.\n… … Pulsante B: Annulla");
const u8 gText_LoadingEvent[] = _("Caricamento evento…");
const u8 gText_DontRemoveCableTurnOff[] = _("Non scollegare il Cavo Game Link.\nNon spegnere la console.");
const u8 gText_EventSafelyLoaded[] = _("Evento caricato con successo.");
const u8 gText_LoadErrorEndingSession[] = _("Errore di caricamento.\nFine della sessione.");
const u8 gJPText_Player[] = _("プレイヤー"); // Unused
const u8 gJPText_Sama[] = _("さま"); // Unused
const u8 gText_DexHoenn[] = _("di Hoenn");
const u8 gText_DexNational[] = _("Nazionale");
const u8 gText_PokedexDiploma[] = _("Nome: {CLEAR 16}{COLOR RED}{SHADOW LIGHT_RED}{PLAYER}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}\n\nQuesto documento certifica\nche hai completato con\nsuccesso il tuo Pokédex\n{STR_VAR_1}.\n\n{CLEAR_TO 66}{COLOR RED}{SHADOW LIGHT_RED}GAME FREAK");
const u8 gJPText_GameFreak[] = _("{COLOR RED}{SHADOW LIGHT_RED}ゲ-ムフリ-ク"); // Unused
const u8 gText_DiplomaEmpty[] = _("{COLOR RED}{SHADOW LIGHT_RED}"); // Unused
const u8 gText_Hoenn[] = _("Hoenn");
const u8 gText_Kanto[] = _("Kanto");
const u8 gText_XWillBeSentToY[] = _("{STR_VAR_2} sta per\nandare da {STR_VAR_1}.");
const u8 gText_ByeByeVar1[] = _("Ciao ciao, {STR_VAR_2}!");
const u8 gText_XSentOverY[] = _("{STR_VAR_1} ti invia {STR_VAR_3}.");
const u8 gText_TakeGoodCareOfX[] = _("Abbi cura di {STR_VAR_3}!");

const u8 gText_ThreeQuestionMarks[] = _("???");
const u8 gText_MaxHP[] = _("PS");
const u8 gText_Attack[] = _("Attacco");
const u8 gText_Defense[] = _("Difesa");
const u8 gText_Speed[] = _("Velocità");
const u8 gText_SpAtk[] = _("Att. Sp.");
const u8 gText_SpDef[] = _("Dif. Sp.");
const u8 gText_Plus[] = _("{PLUS}");
const u8 gText_Dash[] = _("-");
const u8 gText_MixingRecords[] = _("Mix record in corso…");
const u8 gText_RecordMixingComplete[] = _("Mix record completato.\nGrazie per l'attesa.");
const u8 gText_RentalPkmn2[] = _("Noleggio Pokémon");
const u8 gText_SelectFirstPkmn[] = _("Scegli il primo Pokémon.");
const u8 gText_SelectSecondPkmn[] = _("Scegli il secondo Pokémon.");
const u8 gText_SelectThirdPkmn[] = _("Scegli il terzo Pokémon.");
const u8 gText_Rent[] = _("Noleggia");
const u8 gText_Summary[] = _("Info");
const u8 gText_Others2[] = _("Altri");
const u8 gText_Deselect[] = _("Togli");
const u8 gText_TheseThreePkmnOkay[] = _("Confermi questi tre Pokémon?");
const u8 gText_Yes2[] = _("Sì");
const u8 gText_No2[] = _("No");
const u8 gText_CantSelectSamePkmn[] = _("Hai già scelto questo {PKMN}.");
const u8 gText_PkmnSwap[] = _("Scambio Pokémon");
const u8 gText_SelectPkmnToSwap[] = _("Scegli il Pokémon da cedere.");
const u8 gText_SelectPkmnToAccept[] = _("Scegli il Pokémon da ricevere.");
const u8 gText_Swap[] = _("Scambia");
const u8 gText_Summary2[] = _("Info");
const u8 gText_Rechoose[] = _("Cambia");
const u8 gText_QuitSwapping[] = _("Smetti di scambiare?");
const u8 gText_Yes3[] = _("Sì");
const u8 gText_No3[] = _("No");
const u8 gText_PkmnForSwap[] = _("{PKMN} in cambio");
const u8 gText_Cancel3[] = _("Annulla");
const u8 gText_Swap2[] = _("Scambia"); // Unused
const u8 gText_Accept[] = _("Prendi"); // Unused
const u8 gText_AcceptThisPkmn[] = _("Accetti questo Pokémon?");
const u8 gText_4Spaces[] = _("    "); // Unused
const u8 gText_SamePkmnInPartyAlready[] = _("Questo {PKMN} è già in squadra.");
const u8 gText_DecimalPoint[] = _(",");
const u8 gText_SavingPlayer[] = _("Giocatore");
const u8 gText_SavingBadges[] = _("Medaglie");
const u8 gText_SavingPokedex[] = _("Pokédex");
const u8 gText_SavingTime[] = _("Tempo");
const u8 gText_WirelessCommStatus[] = _("Stato Comunicazione Wireless");
const u8 gText_PeopleTrading[] = _("In scambio:");
const u8 gText_PeopleBattling[] = _("In lotta:");
const u8 gText_PeopleInUnionRoom[] = _("Nella Sala Unione:");
const u8 gText_PeopleCommunicating[] = _("In comunicazione:");
const u8 gText_F700Players[] = _("{DYNAMIC 0} gioc.");
const u8 gText_F701Players[] = _("{DYNAMIC 1} gioc.");
const u8 gText_F702Players[] = _("{DYNAMIC 2} gioc.");
const u8 gText_F703Players[] = _("{DYNAMIC 3} gioc.");

const u8 *const gTextTable_Players[] = {
    gText_F700Players,
    gText_F701Players,
    gText_F702Players,
    gText_F703Players
};

ALIGNED(4) const u8 gText_WonderCards[] = _("Carte Dono");
ALIGNED(4) const u8 gText_WonderNews[] = _("Notizie Dono");
ALIGNED(4) const u8 gText_WirelessCommunication[] = _("Comunicazione Wireless");
ALIGNED(4) const u8 gText_Friend2[] = _("Amico");
ALIGNED(4) const u8 gText_Exit3[] = _("Esci");
ALIGNED(4) const u8 gText_Receive[] = _("Ricevi");
ALIGNED(4) const u8 gText_Send[] = _("Invia");
ALIGNED(4) const u8 gText_Toss[] = _("Getta");
ALIGNED(4) const u8 gText_VarietyOfEventsImportedWireless[] = _("Vari eventi verranno importati\ntramite la Comunicazione Wireless.");
ALIGNED(4) const u8 gText_WonderCardsInPossession[] = _("Leggi le Carte Dono\nin tuo possesso.");
ALIGNED(4) const u8 gText_ReadNewsThatArrived[] = _("Leggi le Notizie arrivate.");
ALIGNED(4) const u8 gText_ReturnToTitle[] = _("Torna al titolo.");
ALIGNED(4) const u8 gText_DontHaveCardNewOneInput[] = _("Non hai una Carta Dono, quindi\nne verrà inserita una nuova.");
ALIGNED(4) const u8 gText_DontHaveNewsNewOneInput[] = _("Non hai Notizie Dono, quindi\nne verranno inserite di nuove.");
ALIGNED(4) const u8 gText_WhereShouldCardBeAccessed[] = _("Da dove vuoi ricevere\nla Carta Dono?");
ALIGNED(4) const u8 gText_WhereShouldNewsBeAccessed[] = _("Da dove vuoi ricevere\nle Notizie Dono?");
ALIGNED(4) const u8 gText_CommunicationStandbyBButtonCancel[] = _("Comunicazione in corso…\nPulsante B: Annulla"); // Unused
ALIGNED(4) const u8 gText_Communicating[] = _("Comunicazione in corso…");
ALIGNED(4) const u8 gText_CommunicationCompleted[] = _("Comunicazione completata.");
ALIGNED(4) const u8 gText_CommunicationError[] = _("Errore di comunicazione.");
ALIGNED(4) const u8 gText_CommunicationCanceled[] = _("La comunicazione è stata annullata.");
ALIGNED(4) const u8 gText_ThrowAwayWonderCard[] = _("Vuoi gettare la Carta Dono\ne inserirne una nuova?");
ALIGNED(4) const u8 gText_HaventReceivedCardsGift[] = _("Non hai ricevuto il dono della Carta.\nVuoi inserirne comunque una nuova?");
ALIGNED(4) const u8 gText_WonderCardReceivedFrom[] = _("Hai ricevuto una Carta Dono\nda {STR_VAR_1}.");
ALIGNED(4) const u8 gText_WonderNewsReceivedFrom[] = _("Hai ricevuto delle Notizie Dono\nda {STR_VAR_1}.");
ALIGNED(4) const u8 gText_WonderCardReceived[] = _("Hai ricevuto una nuova\nCarta Dono.");
ALIGNED(4) const u8 gText_WonderNewsReceived[] = _("Hai ricevuto delle nuove\nNotizie Dono.");
ALIGNED(4) const u8 gText_NewStampReceived[] = _("Hai ricevuto un nuovo Timbro.");
ALIGNED(4) const u8 gText_NewTrainerReceived[] = _("È arrivato un nuovo Allenatore.");
ALIGNED(4) const u8 gText_AlreadyHadCard[] = _("Hai già questa\nCarta Dono.");
ALIGNED(4) const u8 gText_AlreadyHadNews[] = _("Hai già queste\nNotizie Dono.");
ALIGNED(4) const u8 gText_AlreadyHadStamp[] = _("Hai già questo\nTimbro.");
ALIGNED(4) const u8 gText_NoMoreRoomForStamps[] = _("Non c'è più spazio per\naltri Timbri.");
ALIGNED(4) const u8 gText_RecordUploadedViaWireless[] = _("Il tuo record è stato inviato tramite\nComunicazione Wireless.");
ALIGNED(4) const u8 gText_CantAcceptCardFromTrainer[] = _("Non puoi accettare una Carta Dono\nda questo Allenatore.");
ALIGNED(4) const u8 gText_CantAcceptNewsFromTrainer[] = _("Non puoi accettare Notizie Dono\nda questo Allenatore.");
ALIGNED(4) const u8 gText_NothingSentOver[] = _("Non è stato inviato nulla…");
ALIGNED(4) const u8 gText_WhatToDoWithCards[] = _("Cosa vuoi fare con\nle Carte Dono?");
ALIGNED(4) const u8 gText_WhatToDoWithNews[] = _("Cosa vuoi fare con\nle Notizie Dono?");
ALIGNED(4) const u8 gText_SendingWonderCard[] = _("Invio della Carta Dono…");
ALIGNED(4) const u8 gText_SendingWonderNews[] = _("Invio delle Notizie Dono…");
ALIGNED(4) const u8 gText_WonderCardSentTo[] = _("La tua Carta Dono è stata\ninviata a {STR_VAR_1}.");
ALIGNED(4) const u8 gText_WonderNewsSentTo[] = _("Le tue Notizie Dono sono state\ninviate a {STR_VAR_1}.");
ALIGNED(4) const u8 gText_StampSentTo[] = _("Hai inviato un Timbro a {STR_VAR_1}.");
ALIGNED(4) const u8 gText_GiftSentTo[] = _("Hai inviato un dono a {STR_VAR_1}.");
ALIGNED(4) const u8 gText_OtherTrainerHasCard[] = _("L'altro Allenatore ha già\nla stessa Carta Dono.");
ALIGNED(4) const u8 gText_OtherTrainerHasNews[] = _("L'altro Allenatore ha già\nle stesse Notizie Dono.");
ALIGNED(4) const u8 gText_OtherTrainerHasStamp[] = _("L'altro Allenatore ha già\nlo stesso Timbro.");
ALIGNED(4) const u8 gText_OtherTrainerCanceled[] = _("L'altro Allenatore ha\nannullato la comunicazione.");
ALIGNED(4) const u8 gText_CantSendGiftToTrainer[] = _("Non puoi inviare un Dono Segreto\na questo Allenatore.");
ALIGNED(4) const u8 gText_IfThrowAwayCardEventWontHappen[] = _("Se getti la Carta, l'evento\nnon avrà luogo. Va bene?");
ALIGNED(4) const u8 gText_OkayToDiscardNews[] = _("Vuoi davvero eliminare\nqueste Notizie?");
ALIGNED(4) const u8 gText_HaventReceivedGiftOkayToDiscard[] = _("Non hai ricevuto il dono.\nVuoi davvero eliminarla?");
ALIGNED(4) const u8 gText_DataWillBeSaved[] = _("Salvataggio dei dati.\nAttendi.");
ALIGNED(4) const u8 gText_SaveCompletedPressA[] = _("Salvataggio completato.\nPremi il pulsante A.");
ALIGNED(4) const u8 gText_WonderCardThrownAway[] = _("La Carta Dono è stata gettata.");
ALIGNED(4) const u8 gText_WonderNewsThrownAway[] = _("Le Notizie Dono sono state gettate.");
ALIGNED(4) const u8 gText_MysteryGift[] = _("Dono Segreto");
ALIGNED(4) const u8 gText_PickOKExit[] = _("{DPAD_UPDOWN}Scegli {A_BUTTON}OK {B_BUTTON}Esci");
ALIGNED(4) const u8 gText_PickOKCancel[] = _("{DPAD_UPDOWN}Scegli {A_BUTTON}OK {B_BUTTON}Annulla");
const u8 gText_PlayersBattleResults[] = _("Risultati lotte di {PLAYER}");
const u8 gText_TotalRecordWLD[] = _("Totale V:{STR_VAR_1} S:{STR_VAR_2} P:{STR_VAR_3}");
const u8 gText_WinLoseDraw[] = _("{CLEAR_TO 83}Vinte{CLEAR_TO 128}Perse{CLEAR_TO 176}Pari");
const u8 gText_CommunicationStandby5[] = _("Comunicazione in corso…");
const u8 gDaycareText_GetAlongVeryWell[] = _("I due sembrano andare\nmolto d'accordo.");
const u8 gDaycareText_GetAlong[] = _("I due sembrano andare d'accordo.");
const u8 gDaycareText_DontLikeOther[] = _("I due non sembrano piacersi\nmolto.");
const u8 gDaycareText_PlayOther[] = _("I due preferiscono giocare\ncon altri Pokémon.");
const u8 gText_NewLine2[] = _("\n");
const u8 gText_Exit4[] = _("Esci");
const u8 gText_Lv[] = _("{LV}");
const u8 gText_TimeBoard[] = _("Tabella tempi");
const u8 gText_TimeCleared[] = _("Tempo impiegato ");
const u8 gText_XMinYDotZSec[] = _("{STR_VAR_1} min {STR_VAR_2},{STR_VAR_3} s");
const u8 gText_TrainerHill1F[] = _("1P");
const u8 gText_TrainerHill2F[] = _("2P");
const u8 gText_TrainerHill3F[] = _("3P");
const u8 gText_TrainerHill4F[] = _("4P");
const u8 gText_TeachWhichMoveToPkmn[] = _("Quale {STR_VAR_3} insegnare\na {STR_VAR_1}?");
const u8 gText_MoveRelearnerTeachMoveConfirm[] = _("Insegnare {STR_VAR_2}?");
const u8 gText_MoveRelearnerTeachMoveConfirmUseTm[] = _("Insegnare {STR_VAR_2}?\nVerrà consumata la {STR_VAR_3}.");
const u8 gText_MoveRelearnerPkmnLearnedMove[] = _("{STR_VAR_1} impara\n{STR_VAR_2}!");
const u8 gText_MoveRelearnerPkmnTryingToLearnMove[] = _("{STR_VAR_1} vuole imparare\n{STR_VAR_2}.\pMa {STR_VAR_1} non può avere\npiù di quattro mosse.\pVuoi cancellare una mossa per\nfar posto a {STR_VAR_2}?");
const u8 gText_MoveRelearnerStopTryingToTeachMove[] = _("Smetti di insegnare\n{STR_VAR_2}?");
const u8 gText_MoveRelearnerAndPoof[] = _("{PAUSE 32}1, {PAUSE 15}2 e {PAUSE 15}… {PAUSE 15}… {PAUSE 15}… {PAUSE 15}{PLAY_SE SE_BALL_BOUNCE_1}Puff!\p");
const u8 gText_MoveRelearnerPkmnForgotMoveAndLearnedNew[] = _("{STR_VAR_1} scorda {STR_VAR_3}.\pE…\p{STR_VAR_1} impara {STR_VAR_2}.");
const u8 gText_MoveRelearnedPkmnDidNotLearnMove[] = _("{STR_VAR_1} non ha imparato\nla mossa {STR_VAR_2}."); // Unused
const u8 gText_MoveRelearnerGiveUp[] = _("Rinunciare a insegnare una\nmossa a {STR_VAR_1}?");
const u8 gText_MoveRelearnerStop[] = _("Smettere di insegnare\nmosse a {STR_VAR_1}?");;
const u8 gText_MoveRelearnerWhichMoveToForget[] = _("Quale mossa deve\ndimenticare?\p");
const u8 gText_MoveRelearnerBattleMoves[] = _("Mosse lotta");
const u8 gText_MoveRelearnerContestMovesTitle[] = _("Mosse gara");
const u8 gText_MoveRelearnerType[] = _("Tipo/"); // Unused
const u8 gText_MoveRelearnerPP[] = _("PP/");
const u8 gText_MoveRelearnerPower[] = _("Potenza/");
const u8 gText_MoveRelearnerAccuracy[] = _("Precisione/");
const u8 gText_MoveRelearnerAppeal[] = _("Esibiz.");
const u8 gText_MoveRelearnerJam[] = _("Disturbo");
const u8 gText_ClearAllSaveData[] = _("Cancellare tutti i dati salvati?");
const u8 gText_ClearingData[] = _("Cancellazione dati…\nAttendi.");
const u8 gText_IsThisTheCorrectTime[] = _("L'ora è corretta?");
const u8 gText_Confirm3[] = _("Conferma");
const u8 gText_Cancel4[] = _("Annulla");
const u8 gText_CommStandbyAwaitingOtherPlayer[] = _("Comunicazione in corso…\nL'altro giocatore sta scegliendo.");
const u8 gText_BattleWasRefused[] = _("La lotta è stata rifiutata.{PAUSE 60}");
const u8 gText_RefusedBattle[] = _("Hai rifiutato la lotta.{PAUSE 60}");
const u8 gText_NoWeather[] = _("NO WEATHER"); // Below are unused debug names for weather types
const u8 gText_Sunny[] = _("SUNNY"); // Unused
const u8 gText_Sunny2[] = _("SUNNY2"); // Unused
const u8 gText_Rain[] = _("RAIN"); // Unused
const u8 gText_Snow[] = _("SNOW"); // Unused
const u8 gText_Lightning[] = _("LIGHTNING"); // Unused
const u8 gText_Fog[] = _("FOG"); // Unused
const u8 gText_VolcanoAsh[] = _("VOLCANO ASH"); // Unused
const u8 gText_Sandstorm[] = _("SANDSTORM"); // Unused
const u8 gText_Fog2[] = _("FOG2"); // Unused
const u8 gText_Seafloor[] = _("SEAFLOOR"); // Unused
const u8 gText_Cloudy[] = _("CLOUDY"); // Unused
const u8 gText_Sunny3[] = _("SUNNY3"); // Unused
const u8 gText_HeavyRain[] = _("HEAVY RAIN"); // Unused
const u8 gText_Seafloor2[] = _("SEAFLOOR2"); // Unused
const u8 gText_DelAll[] = _("Svuota");
const u8 gText_Cancel5[] = _("Annulla");
const u8 gText_Ok2[] = _("OK");
const u8 gText_Quiz[] = _("QUIZ");
const u8 gText_Answer[] = _("Risposta");
const u8 gText_PokeBalls[] = _("Poké Ball");
const u8 gText_Berry[] = _("Bacca");
const u8 gText_Berries[] = _("Bacche");
const u8 gText_ExpShareOn[] = _("Hai attivato il Condividi Esp.{PAUSE_UNTIL_PRESS}");
const u8 gText_ExpShareOff[] = _("Hai disattivato il Condividi Esp.{PAUSE_UNTIL_PRESS}");
ALIGNED(4) const u8 gText_Ghost[] = _("Spettro");
const u8 gText_Boulderbadge[] = _("Medaglia Sasso");
const u8 gText_Cascadebadge[] = _("Medaglia Cascata");
const u8 gText_Thunderbadge[] = _("Medaglia Tuono");
const u8 gText_Rainbowbadge[] = _("Medaglia Arcobaleno");
const u8 gText_Soulbadge[] = _("Medaglia Anima");
const u8 gText_Marshbadge[] = _("Medaglia Palude");
const u8 gText_Volcanobadge[] = _("Medaglia Vulcano");
const u8 gText_Earthbadge[] = _("Medaglia Terra");
const u8 gText_OakImportantToGetToKnowPokemonThroughly[] = _("Oak: È importante conoscere a fondo\ni tuoi Pokémon.\p");
const u8 gText_OakThisIsListOfPokemon[] = _("Questa è la lista dei tuoi Pokémon,\n{PLAYER}.\pAprila per controllare le abilità\ne le mosse dei tuoi Pokémon.\pQui puoi anche scegliere il Pokémon\nsu cui usare uno strumento.{PAUSE_UNTIL_PRESS}");
