SlateportCity_SternsShipyard_2F_MapScripts::
	.byte 0

SlateportCity_SternsShipyard_2F_EventScript_Scientist1::
	msgbox SlateportCity_SternsShipyard_2F_Text_ShipDesignMoreLikeBuilding, MSGBOX_NPC
	end

SlateportCity_SternsShipyard_2F_EventScript_Scientist2::
	msgbox SlateportCity_SternsShipyard_2F_Text_FloatsBecauseBuoyancy, MSGBOX_NPC
	end

SlateportCity_SternsShipyard_2F_Text_ShipDesignMoreLikeBuilding:
	.string "Progettare una grande nave somiglia\n"
	.string "più a costruire un palazzo che a\l"
	.string "montare un mezzo di trasporto.$"

SlateportCity_SternsShipyard_2F_Text_FloatsBecauseBuoyancy:
	.string "Non trovi strano che una nave fatta\n"
	.string "di ferro pesante riesca a galleggiare?\p"
	.string "Galleggia grazie a un principio\n"
	.string "chiamato spinta di Archimede.$"

