OldaleTown_House1_MapScripts::
	.byte 0

OldaleTown_House1_EventScript_Woman::
	msgbox OldaleTown_House1_Text_LeftPokemonGoesOutFirst, MSGBOX_NPC
	end

OldaleTown_House1_Text_LeftPokemonGoesOutFirst:
	.string "Quando inizia una lotta, scende in\n"
	.string "campo il primo Pokémon della lista.\p"
	.string "Quindi, quando avrai più Pokémon in\n"
	.string "squadra, prova a cambiare l'ordine\l"
	.string "dei tuoi compagni.\p"
	.string "Potrebbe darti un bel vantaggio!$"

