SootopolisCity_House5_MapScripts::
	.byte 0

SootopolisCity_House5_EventScript_Maniac::
	msgbox SootopolisCity_House5_Text_SootopolisMtPyreConnection, MSGBOX_NPC
	end

SootopolisCity_House5_EventScript_Girl::
	msgbox SootopolisCity_House5_Text_BrotherUsedToStudySea, MSGBOX_NPC
	end

SootopolisCity_House5_Text_SootopolisMtPyreConnection:
	.string "Sembra che tra Ceneride e il Monte\n"
	.string "Pira esista un legame misterioso.\p"
	.string "Io e i miei colleghi lo studiavamo,\n"
	.string "nel laboratorio dove lavoravo…\l"
	.string "prima che chiudesse tutto.$"

SootopolisCity_House5_Text_BrotherUsedToStudySea:
	.string "Il mio fratellone studiava il mare.$"

