PetalburgCity_House1_MapScripts::
	.byte 0

PetalburgCity_House1_EventScript_Man::
	msgbox PetalburgCity_House1_Text_TravelingIsWonderful, MSGBOX_NPC
	end

PetalburgCity_House1_EventScript_Woman::
	msgbox PetalburgCity_House1_Text_GoOnAdventure, MSGBOX_NPC
	end

PetalburgCity_House1_Text_TravelingIsWonderful:
	.string "Viaggiare è meraviglioso!\p"
	.string "Da giovane ho girato per mari\n"
	.string "e per monti!\p"
	.string "Oggi i ragazzi sognano di attraversare\n"
	.string "un Varco… Ai miei tempi bastava una\l"
	.string "bella montagna!$"

PetalburgCity_House1_Text_GoOnAdventure:
	.string "Ahh…\p"
	.string "Quanto vorrei partire all'avventura\n"
	.string "con qualche Pokémon…\p"
	.string "Strisciare nell'erba umida…\n"
	.string "Scalare montagne aspre e rocciose…\p"
	.string "Attraversare mari in tempesta…\n"
	.string "Vagare in grotte buie…\p"
	.string "Magari scovare un Varco appena\n"
	.string "aperto…\p"
	.string "E ogni tanto, perfino sentire un po'\n"
	.string "di nostalgia di casa…\p"
	.string "Dev'essere favoloso, viaggiare!$"

