gText_ApprenticeChallenge0::
	.string "Ehm, sono l'apprendista n. {STR_VAR_2}\n"
	.string "di {STR_VAR_1}… Sniff… che ansia…$"

gText_ApprenticeChallenge1::
	.string "Sono l'apprendista n. {STR_VAR_2}\n"
	.string "di {STR_VAR_1}! Fatti sotto!$"

gText_ApprenticeChallenge2::
	.string "Sono l'apprendista numero {STR_VAR_2}\n"
	.string "di {STR_VAR_1}! Accetta la mia sfida!$"

gText_ApprenticeChallenge3::
	.string "Ehm… sono l'apprendista n. {STR_VAR_2}\n"
	.string "di {STR_VAR_1}… Pensi che io possa vincere?$"

gText_ApprenticeChallenge4::
	.string "Sono l'apprendista n. {STR_VAR_2}\n"
	.string "di {STR_VAR_1}! Ti concedo di sfidarmi!$"

gText_ApprenticeChallenge5::
	.string "Ho mille impegni, ma sono anche\n"
	.string "l'apprendista n. {STR_VAR_2} di {STR_VAR_1}.$"

gText_ApprenticeChallenge6::
	.string "Sono l'apprendista n. {STR_VAR_2}\n"
	.string "di {STR_VAR_1}. Piacere di conoscerti!$"

gText_ApprenticeChallenge7::
	.string "Sono l'umile apprendista n. {STR_VAR_2}\n"
	.string "di {STR_VAR_1}. Posso cominciare?$"

gText_ApprenticeChallenge8::
	.string "Iiih! Sono l'apprendista n. {STR_VAR_2}\n"
	.string "di {STR_VAR_1}! Ce la metterò tutta!$"

gText_ApprenticeChallenge9::
	.string "Iuhuu! Sono l'apprendista n. {STR_VAR_2}\n"
	.string "di {STR_VAR_1}! Su i pugni, scalatore!$"

gText_ApprenticeChallenge10::
	.string "Sono l'apprendista n. 1000 di {STR_VAR_1}!\n"
	.string "Scherzo, sono il n. {STR_VAR_2}! Si parte!$"

gText_ApprenticeChallenge11::
	.string "Yo! Sono l'apprendista n. {STR_VAR_2}\n"
	.string "di {STR_VAR_1}! Diamoci dentro col rock!$"

gText_ApprenticeChallenge12::
	.string "Yuppi-yahoo! Ecco a voi l'apprendista\n"
	.string "n. {STR_VAR_2} di {STR_VAR_1}!$"

gText_ApprenticeChallenge13::
	.string "Coff! Sono l'apprendista n. {STR_VAR_2}\n"
	.string "di {STR_VAR_1}. Piacere! Coff, coff!$"

gText_ApprenticeChallenge14::
	.string "Che tensione, mi tremano le gambe…\n"
	.string "Sono l'apprendista n. {STR_VAR_2} di {STR_VAR_1}.$"

gText_ApprenticeChallenge15::
	.string "Sono l'apprendista n. {STR_VAR_2}\n"
	.string "di {STR_VAR_1}, parola di gentiluomo.$"

gText_ApprenticePleaseTeach0::
	.string "Sei… sei {PLAYER}?\n"
	.string "Oh! Sniff… sigh…\p"
	.string "Oh! S-scusa…\n"
	.string "Sono così emozionato che piango…\p"
	.string "Mi chiamo {STR_VAR_1} e ti ammiro\n"
	.string "tantissimo, {PLAYER}.\p"
	.string "Ho… ho sempre sognato di incontrarti\n"
	.string "e di farti un sacco di domande.\p"
	.string "Ti prego, ti prego, {PLAYER}!\n"
	.string "Insegnami tutto sui Pokémon!$"

gText_ApprenticeRejectTeaching0::
	.string "Oh… M-ma…\n"
	.string "Sniff… Uaaaaaah!\p"
	.string "Ti prego!\n"
	.string "Ti supplico, ti prego!$"

gText_ApprenticeWhichLevelMode0::
	.string "Davvero? Accetti?\n"
	.string "Fantastico! Mitico! Uaooh!\p"
	.string "Oh… scusa…\n"
	.string "Sono così felice che piango…\p"
	.string "Ehm… allora dimmi una cosa!\n"
	.string "Riguarda la Torre Lotta.\p"
	.string "Cosa mi conviene di più: il Livello 50\n"
	.string "o il Livello Libero?$"

gText_ApprenticeLevelModeThanks0::
	.string "{STR_VAR_1}?\n"
	.string "Uaaaaah!\p"
	.string "Oh! Scusa tanto!\n"
	.string "Hai scelto il livello per me, e sono\l"
	.string "così felice che mi viene da piangere…\p"
	.string "Sniff…\n"
	.string "Grazie mille!\l"
	.string "Torna a parlare con me, ok?$"

gText_ApprenticePleaseTeach1::
	.string "Uao! Tu sei {PLAYER}, vero?\n"
	.string "Quello fortissimo, giusto?\p"
	.string "Io sono {STR_VAR_1}!\n"
	.string "Sono appena diventato Allenatore!\p"
	.string "Ti prego, {PLAYER}!\n"
	.string "Mi fai da maestro e mi spieghi\l"
	.string "tutto su come si fa l'Allenatore?$"

gText_ApprenticeRejectTeaching1::
	.string "Uffa, perché?\n"
	.string "Dai, ti prego! Per favore, per favore!\l"
	.string "Fammi da maestro, dai!$"

gText_ApprenticeWhichLevelMode1::
	.string "Evviva! Grande!\p"
	.string "La prima cosa che volevo chiederti\n"
	.string "riguarda la Torre Lotta!\p"
	.string "Le sale del Livello 50 e del Livello\n"
	.string "Libero… quale fa al caso mio?$"

gText_ApprenticeLevelModeThanks1::
	.string "{STR_VAR_1}, eh? Hai ragione!\n"
	.string "Ce la metterò tutta!\p"
	.string "Se ci rivediamo qui, insegnami\n"
	.string "qualcos'altro, maestro!$"

gText_ApprenticePleaseTeach2::
	.string "Ehm… sei tu {PLAYER}?\n"
	.string "Io mi chiamo {STR_VAR_1}.\p"
	.string "Voglio diventare un Allenatore di\n"
	.string "Pokémon, ma non so da dove iniziare…\p"
	.string "Così ho pensato di chiedere consiglio\n"
	.string "a te, visto che sei tanto famoso.\p"
	.string "{PLAYER}, mi daresti un consiglio?$"

gText_ApprenticeRejectTeaching2::
	.string "Oh, ma…\p"
	.string "Io voglio davvero diventare un\n"
	.string "Allenatore di Pokémon!\p"
	.string "Per favore, rispondi alle mie domande!$"

gText_ApprenticeWhichLevelMode2::
	.string "Grazie!\n"
	.string "Ecco subito la mia prima domanda!\p"
	.string "Alla Torre Lotta ci sono due livelli,\n"
	.string "Livello 50 e Livello Libero, giusto?\p"
	.string "Quale pensi che sia più adatto\n"
	.string "a me?$"

gText_ApprenticeLevelModeThanks2::
	.string "Oh, {STR_VAR_1}, dici?\n"
	.string "Ricevuto!\p"
	.string "Se avrò un'altra domanda, tornerò\n"
	.string "qui a chiederti consiglio!$"

gText_ApprenticePleaseTeach3::
	.string "Eh? Cosa? Tu sei…\n"
	.string "No, non può essere vero.\p"
	.string "Non è possibile che una come me\n"
	.string "incontri {PLAYER}.\p"
	.string "…Sei davvero {PLAYER}?\n"
	.string "Non ci credo, sto parlando con te!\p"
	.string "Quando mi succede una cosa così bella,\n"
	.string "poi arrivano solo disgrazie… Magari\l"
	.string "mi si apre un Varco sotto i piedi…\p"
	.string "…Scusa…\n"
	.string "Io sono… {STR_VAR_1}…\p"
	.string "Non ho niente di speciale di cui\n"
	.string "andare fiera…\p"
	.string "Non dovrei nemmeno presentarmi,\n"
	.string "tanto ti dimenticherai di me…\p"
	.string "Sognavo che, se mai ti avessi\n"
	.string "incontrato, {PLAYER}, ti avrei chiesto\l"
	.string "qualche consiglio da Allenatrice.\p"
	.string "Ma non credo che accetteresti\n"
	.string "una cosa del genere.\p"
	.string "…Oppure saresti così gentile\n"
	.string "da darmi qualche consiglio?$"

gText_ApprenticeRejectTeaching3::
	.string "Lo sapevo…\p"
	.string "Doveva andare così, perché sono\n"
	.string "proprio una nullità noiosa…\p"
	.string "Però speravo che, forse…\n"
	.string "Non ci ripenseresti, vero?\p"
	.string "Ma non posso arrendermi così.\n"
	.string "Ci riprovo finché ho fortuna!\p"
	.string "Ti prego, saresti così gentile\n"
	.string "da darmi qualche consiglio?$"

gText_ApprenticeWhichLevelMode3::
	.string "Davvero? Non ci posso credere!\n"
	.string "Mi darai davvero dei consigli?\l"
	.string "Io… sono così felice…\p"
	.string "Quello che voglio chiederti è una\n"
	.string "sciocchezza, ma non so decidermi…\p"
	.string "Alla Torre Lotta si può scegliere\n"
	.string "tra Livello 50 e Livello Libero.\p"
	.string "In quale pensi che perfino io\n"
	.string "potrei avere una possibilità?$"

gText_ApprenticeLevelModeThanks3::
	.string "{STR_VAR_1}? D'accordo!\n"
	.string "Ma pensi davvero che una come me\l"
	.string "abbia qualche possibilità?\p"
	.string "Ce la metterò tutta, anche se\n"
	.string "secondo me non funzionerà.\p"
	.string "Grazie di cuore per aver perso\n"
	.string "tempo con una come me.$"

gText_ApprenticePleaseTeach4::
	.string "Oh! Tu sei {PLAYER}{KUN}, giusto?\p"
	.string "Ho sentito che te la cavi alla\n"
	.string "grande con i Pokémon!\p"
	.string "Io sono {STR_VAR_1}!\n"
	.string "Diventerò tua amica!\p"
	.string "Lo sapevi?\p"
	.string "Al Parco Lotta arriveranno Allenatori\n"
	.string "da chissà quali mondi, e per batterli\l"
	.string "non basta quello che insegnano\l"
	.string "alla Scuola Allenatori.\p"
	.string "Sono disposta ad ascoltare i tuoi\n"
	.string "consigli. Accetti, ovviamente?$"

gText_ApprenticeRejectTeaching4::
	.string "Eh? Perché mi dici di no?\n"
	.string "Sono io che te lo sto chiedendo!\l"
	.string "Devi ripensarci!$"

gText_ApprenticeWhichLevelMode4::
	.string "Bene, allora c'è una certa cosa.\n"
	.string "Voglio che la decida tu per me.\p"
	.string "Sai che alla Torre Lotta ci sono\n"
	.string "il Livello 50 e il Livello Libero?\p"
	.string "Quale pensi che sia meglio per me,\n"
	.string "{PLAYER}{KUN}?$"

gText_ApprenticeLevelModeThanks4::
	.string "Ok, quindi {STR_VAR_1} fa per me?\n"
	.string "Grazie!\p"
	.string "Visto che hai deciso tu, {PLAYER}{KUN},\n"
	.string "se perdo la colpa sarà tua.\l"
	.string "Così almeno non mi arrabbio!\p"
	.string "Bene, verrò ancora a chiederti consigli.\n"
	.string "Ciao!$"

gText_ApprenticePleaseTeach5::
	.string "Ehi, ciao! {PLAYER}{KUN}!\n"
	.string "Ti conosco, sei famoso!\l"
	.string "Chiamami {STR_VAR_1}! Piacere!\p"
	.string "Sono un Triatleta, quindi mi tengo\n"
	.string "in forma mentre alleno i Pokémon.\p"
	.string "E poi ho mille altri impegni: lavoro,\n"
	.string "pisolini, ballo da sala…\p"
	.string "Con tutto questo da fare, non è facile\n"
	.string "diventare un Allenatore decente.\p"
	.string "Quindi ho una proposta!\p"
	.string "Se ci siamo incontrati, un motivo c'è.\n"
	.string "Allora, {PLAYER}{KUN}, che ne dici di\l"
	.string "darmi qualche dritta ogni tanto?$"

gText_ApprenticeRejectTeaching5::
	.string "Oh, dai, per favore!\n"
	.string "Uno come me ha bisogno di uno\l"
	.string "come te, {PLAYER}{KUN}!\p"
	.string "Sul serio, mi servono i tuoi consigli!$"

gText_ApprenticeWhichLevelMode5::
	.string "Grazie! Così mi piaci!\n"
	.string "Allora, cominciamo con una facile!\p"
	.string "Conosci i due percorsi della Torre\n"
	.string "Lotta, vero?\l"
	.string "Sai, Livello 50 e Livello Libero.\p"
	.string "Da tipo indaffarato quale sono, su\n"
	.string "quale mi conviene puntare?$"

gText_ApprenticeLevelModeThanks5::
	.string "{STR_VAR_1}, eh? Ok, ricevuto.\n"
	.string "Troverò il tempo e ci proverò!\p"
	.string "…Ops, devo correre al lavoro!\n"
	.string "Grazie! Ci si vede!$"

gText_ApprenticePleaseTeach6::
	.string "Non ci credo! No, no!\n"
	.string "Sei per caso il vero {PLAYER}?\p"
	.string "Ah-ha! Fantastico! Sono {STR_VAR_1},\n"
	.string "piacere di conoscerti!\p"
	.string "{PLAYER}, sei fortissimo,\n"
	.string "vero?\p"
	.string "Parlano tutti di te! Scommetto che\n"
	.string "lo sanno perfino oltre i Varchi!\p"
	.string "Oh! Mi è venuta un'idea geniale!\n"
	.string "Mi farò dare consigli da {PLAYER}!\l"
	.string "Così diventerò più forte di sicuro!\p"
	.string "Non è un'idea fantastica?\n"
	.string "Ti prego, voglio i tuoi consigli!$"

gText_ApprenticeRejectTeaching6::
	.string "Ahahah, puoi fare il duro quanto vuoi,\n"
	.string "ma a me non la fai!\l"
	.string "In realtà vuol dire sì, giusto?$"

gText_ApprenticeWhichLevelMode6::
	.string "Evviva! Lo sapevo che avevi un cuore\n"
	.string "grande, {PLAYER}!\p"
	.string "Cosa ti chiedo per prima cosa?\n"
	.string "…Ah, mi è venuto in mente!\p"
	.string "Rullo di tamburi, prego!\n"
	.string "La mia domanda è…\p"
	.string "Se affrontassi una sfida alla Torre\n"
	.string "Lotta, quale strada dovrei scegliere?\p"
	.string "Livello 50 o Livello Libero?\n"
	.string "Quale mi si addice di più?$"

gText_ApprenticeLevelModeThanks6::
	.string "Oh-oh-oh!\n"
	.string "{STR_VAR_1}, dici!\l"
	.string "Grazie per la risposta super!\p"
	.string "Credo che per oggi sia tutto quello\n"
	.string "che volevo chiederti.\p"
	.string "Rivediamoci qui, va bene?\n"
	.string "Grazie!$"

gText_ApprenticePleaseTeach7::
	.string "Chiedo scusa, ma…\n"
	.string "Lei è forse {PLAYER}?\p"
	.string "Sono {STR_VAR_1}, ed è un vero piacere\n"
	.string "fare la sua conoscenza.\p"
	.string "Da tempo sono una sua grande\n"
	.string "ammiratrice…\p"
	.string "… … … … … …\p"
	.string "Ehm… spero che non trovi questa\n"
	.string "richiesta troppo impegnativa, ma…\p"
	.string "Potrei diventare sua apprendista,\n"
	.string "{PLAYER}?$"

gText_ApprenticeRejectTeaching7::
	.string "Oh…!\p"
	.string "… … … … … …\n"
	.string "… … … … … …\p"
	.string "…Devo essere svenuta per lo shock.\n"
	.string "Mi scusi, devo aver capito male.\p"
	.string "La prego! Mi dica che mi accetterà\n"
	.string "come sua apprendista!$"

gText_ApprenticeWhichLevelMode7::
	.string "Oh… ne sono lieta!\p"
	.string "Non desidero rubarle tempo,\n"
	.string "quindi mi consigli su questo.\p"
	.string "Ho intenzione di affrontare presto\n"
	.string "una sfida alla Torre Lotta.\p"
	.string "Tuttavia, ci sono due livelli…\p"
	.string "Quale sarebbe più adatto a me?\n"
	.string "Livello 50 o Livello Libero?$"

gText_ApprenticeLevelModeThanks7::
	.string "La sua scelta è {STR_VAR_1}!\n"
	.string "Capisco. Farò del mio meglio!\p"
	.string "Grazie, {PLAYER}.\n"
	.string "Spero di poter contare ancora su di lei.\l"
	.string "Si riguardi!$"

gText_ApprenticePleaseTeach8::
	.string "Iiih! Iiih! {PLAYER}!\n"
	.string "Mi hai rivolto la parola!\l"
	.string "Io… io sboccio di gioia!\p"
	.string "Io! Mi chiamo {STR_VAR_1}!\n"
	.string "Sono appena diventata Allenatrice!\p"
	.string "Che gioia averti incontrato, {PLAYER},\n"
	.string "il nome più famoso del mondo Pokémon!\p"
	.string "Oh-oh-oh, ci sono!\n"
	.string "Posso chiederti un favorone, {PLAYER}?\p"
	.string "Prendimi come tua apprendista!\n"
	.string "Voglio imparare da te!$"

gText_ApprenticeRejectTeaching8::
	.string "Uaaaah!\n"
	.string "{PLAYER} mi ha detto di no…\l"
	.string "È… è un'esperienza preziosissima!\p"
	.string "{PLAYER}, ti prego! Stavolta voglio\n"
	.string "sentirti dire di sì!\p"
	.string "Ti supplico, fammi da guida!$"

gText_ApprenticeWhichLevelMode8::
	.string "Iiiieeh! {PLAYER} ha detto sì!\n"
	.string "{PLAYER} ha detto sì!\p"
	.string "Stanotte non chiuderò occhio…\n"
	.string "Grazie infinite!\p"
	.string "Allora, ecco la mia domanda!\p"
	.string "Alla Torre Lotta, cosa fa per me:\n"
	.string "Livello 50 o Livello Libero?$"

gText_ApprenticeLevelModeThanks8::
	.string "{STR_VAR_1}! Capito alla perfezione!\n"
	.string "Ho capito perfettamente!\l"
	.string "Sono in fiore dalla contentezza!\p"
	.string "Spero che vorrai insegnarmi\n"
	.string "qualcos'altro un'altra volta.$"

gText_ApprenticePleaseTeach9::
	.string "Ehilà! Possibile che tu sia…\n"
	.string "Che tu sia… {PLAYER}{KUN}?!\l"
	.string "Quel famoso Allenatore fortissimo?\l"
	.string "Ma guarda che fortuna sfacciata!\p"
	.string "Salve, il mio nome è {STR_VAR_1}!\p"
	.string "Cercavo un maestro di Pokémon come\n"
	.string "si cerca la vetta nella nebbia.\p"
	.string "E con un tempismo impeccabile,\n"
	.string "ecco che arrivi tu, {PLAYER}{KUN}!\p"
	.string "Quindi è deciso, {PLAYER}{KUN}!\n"
	.string "Fammi diventare tuo apprendista!$"

gText_ApprenticeRejectTeaching9::
	.string "Uaaargh!\n"
	.string "Sei proprio un osso duro…\p"
	.string "Non fare così, dai.\n"
	.string "Te lo sto chiedendo per favore!$"

gText_ApprenticeWhichLevelMode9::
	.string "Oh, sì! Questa sì che è una risposta!\n"
	.string "Eccellente, oserei dire!\p"
	.string "Allora, che ne dici di un primo\n"
	.string "consiglio sulla Torre Lotta?\p"
	.string "Se ci andassi, cosa sarebbe meglio?\n"
	.string "Livello 50 o Livello Libero?$"

gText_ApprenticeLevelModeThanks9::
	.string "Ah-ha, {STR_VAR_1} sia!\n"
	.string "Ok, tutto ok!\l"
	.string "Vado a mostrare quanto valgo, yeah!\p"
	.string "Bene, da oggi sarai il mio mentore!\n"
	.string "Alla prossima vetta!$"

gText_ApprenticePleaseTeach10::
	.string "Oh, ehi, sei {PLAYER}{KUN}, giusto?\n"
	.string "Ti stava cercando la polizia!\p"
	.string "… … …\n"
	.string "Ma è ovvio che mento!\p"
	.string "Io sono {STR_VAR_1}. Anche se non si\n"
	.string "direbbe, sono il Campione Pokémon!\l"
	.string "…Anche questa è una frottola!\p"
	.string "Questa invece non è una bugia:\n"
	.string "non sono molto bravo a lottare.\p"
	.string "Allora, che ne dici di farmi da\n"
	.string "maestro in tutto ciò che è Pokémon?$"

gText_ApprenticeRejectTeaching10::
	.string "Se fai il freddo così, adesso ti\n"
	.string "faccio vedere io cosa faccio!\p"
	.string "Uaaah! Uaaah! Uaaah!\n"
	.string "Hic!\p"
	.string "Ahahah, era solo Falselacrime!\p"
	.string "Dai, vuoi essere il mio maestro\n"
	.string "di Pokémon?$"

gText_ApprenticeWhichLevelMode10::
	.string "Evviva!\n"
	.string "Per questo ti regalo una barca!\p"
	.string "Ovvio che sto mentendo di nuovo!\n"
	.string "Però… grazie, maestro!\p"
	.string "Sai che alla Torre Lotta ci sono il\n"
	.string "Livello 50 e il Livello Libero?\p"
	.string "Non riesco a decidere quale\n"
	.string "livello affrontare…\p"
	.string "Decidi tu per me, maestro?$"

gText_ApprenticeLevelModeThanks10::
	.string "Ok, quindi è meglio {STR_VAR_1}!\n"
	.string "Allora andrò nell'altro livello!\p"
	.string "Scherzavo!\n"
	.string "Seguirò i tuoi insegnamenti, maestro!\p"
	.string "Grazie, maestro!\n"
	.string "Spero che continuerai a insegnarmi!$"

gText_ApprenticePleaseTeach11::
	.string "A-H-O-Y!\n"
	.string "Si legge ahoy, è un saluto col botto!\p"
	.string "Sono {STR_VAR_1}, Marinaio rappatore,\n"
	.string "rappo sul ponte a tutte le ore!\p"
	.string "Ora tocca a te, parlami un po' di te,\n"
	.string "dai, presentati: uno, due, tre!\p"
	.string "Ah-ha, ah-ha!\n"
	.string "{PLAYER}{KUN} ti chiami tu,\l"
	.string "e coi Pokémon non ce n'è di più!\p"
	.string "E sei in quell'età delicata\n"
	.string "in cui ogni Varco è una nuova strada!\p"
	.string "Comunque, ti volevo dire\n"
	.string "che sei il decimo Allenatore\l"
	.string "che incontro oggi, da impazzire!\p"
	.string "Facciamo festa, che ne dici?\n"
	.string "Fammi da mentore e saremo amici!$"

gText_ApprenticeRejectTeaching11::
	.string "Ma no, ma no!\n"
	.string "Devi stare con me, oh-oh!\p"
	.string "Non farmi i dispetti, per favore!\n"
	.string "Diventa il mio mentore!$"

gText_ApprenticeWhichLevelMode11::
	.string "Così si fa!\n"
	.string "{PLAYER}, sei un vero asso, ah-ha!\p"
	.string "Ecco la prima domanda, ascolta bene:\n"
	.string "un tuo consiglio mi conviene!\p"
	.string "Riguarda la Torre Lotta,\n"
	.string "dove si vince o si va in rotta!\p"
	.string "Livello 50 o Libero, amico mio:\n"
	.string "quale fa per me? Decidi tu, non io!$"
gText_ApprenticeLevelModeThanks11::
	.string "{STR_VAR_1}, dici tu? Ricevuto!\n"
	.string "Salpo subito, e ti saluto!\p"
	.string "Se un consiglio mi servirà,\n"
	.string "{PLAYER}, la tua voce mi guiderà!$"

gText_ApprenticePleaseTeach12::
	.string "Ehi, ehi, ma tu non sei {PLAYER}?\n"
	.string "Che faccio? Ti parlo o no?\l"
	.string "Ma ti sto già parlando, lo so!\p"
	.string "{PLAYER}, ti ho lasciato di stucco?\n"
	.string "Ti dico chi sono, senza trucco!\p"
	.string "Il mio nome è {STR_VAR_1}, sì!\n"
	.string "La stella più lucente del rock\l"
	.string "sono io, proprio qui!\p"
	.string "Mi ricevi, amico? Passo!\n"
	.string "Mi ricevi forte e chiaro! Che spasso!\p"
	.string "La fortuna è dalla mia,\n"
	.string "ti faccio una richiesta, e così sia!\p"
	.string "{PLAYER}, fammi da maestro, dai!\n"
	.string "Insegnami tutto quello che sai!$"

gText_ApprenticeRejectTeaching12::
	.string "Mi dici di no? Che peccato!\n"
	.string "Te lo richiedo, sono ostinato!\p"
	.string "{PLAYER}, sii il mio maestro, dai!\n"
	.string "Insegnami tutto quello che sai!$"

gText_ApprenticeWhichLevelMode12::
	.string "Yeah, che fortuna, evviva!\n"
	.string "Ecco una domanda, eccola che arriva!\p"
	.string "Visto che c'è la Torre Lotta,\n"
	.string "la domanda è bell'e cotta!\p"
	.string "Tra le scelte che hai davanti,\n"
	.string "qual è quella giusta per andare avanti?$"

gText_ApprenticeLevelModeThanks12::
	.string "Se mi dici {STR_VAR_1}, è deciso:\n"
	.string "è la scelta migliore, te lo leggo in viso!\p"
	.string "Ora, {PLAYER}, il palco mi chiama,\n"
	.string "ma non scordarti di me e della mia fama!\p"
	.string "Alla prossima, amico geniale!$"

gText_ApprenticePleaseTeach13::
	.string "Ehi, ciao! Tu, proprio tu!\n"
	.string "Mi faresti un massaggio alla spalla?\p"
	.string "…Sì, lì! Proprio lì!\n"
	.string "Ahi, ahi! Ooooh, che sollievo!\p"
	.string "Mi chiamo {STR_VAR_1}.\n"
	.string "Faccio karate, ma il mio fisico\l"
	.string "non regge tutte quelle botte…\p"
	.string "Così ho deciso di lottare con i\n"
	.string "Pokémon per irrobustirmi un po'.\p"
	.string "Tu sei {PLAYER}{KUN}, vero?\n"
	.string "Il Campione della Lega Pokémon?\p"
	.string "Senti, mi daresti qualche\n"
	.string "consiglio?$"

gText_ApprenticeRejectTeaching13::
	.string "Eh? Perché no?\p"
	.string "Non ti darò fastidio, te lo giuro!\n"
	.string "Per favore?$"

gText_ApprenticeWhichLevelMode13::
	.string "Grazie! Sei davvero gentile!\n"
	.string "…Coff! Coff!\p"
	.string "Uff, devo irrobustirmi in fretta…\p"
	.string "Vado subito alla Torre Lotta,\n"
	.string "ma cosa mi conviene di più?\l"
	.string "Il Livello 50 o il Livello Libero?$"

gText_ApprenticeLevelModeThanks13::
	.string "Mh, va bene. Allora {STR_VAR_1}.\n"
	.string "Ci vado subito.\p"
	.string "Spero di poterti chiedere aiuto\n"
	.string "ancora: in fondo, sei il mio maestro!$"

gText_ApprenticePleaseTeach14::
	.string "Ehm… Ecco…\n"
	.string "{PLAYER}{KUN}…?\p"
	.string "Ti prego, non guardarmi così.\n"
	.string "Mi fai sentire in imbarazzo.\p"
	.string "I-io… sono {STR_VAR_1}.\p"
	.string "Mi vergogno un po' a dirlo, ma\n"
	.string "esploro rovine antiche e cose così.\p"
	.string "Cerco frammenti caduti dai Varchi\n"
	.string "tremila anni fa… Ecco, l'ho detto.\p"
	.string "E mi vergogno ancora di più ad\n"
	.string "ammettere che il Parco Lotta mi attira.\p"
	.string "{PLAYER}{KUN}, tutti dicono che sei\n"
	.string "un Allenatore fortissimo…\p"
	.string "Faccio fatica a dirlo, ma\n"
	.string "vorrei chiederti una cosa.\p"
	.string "Potresti farmi da maestro e\n"
	.string "darmi qualche consiglio?$"

gText_ApprenticeRejectTeaching14::
	.string "Ti prego, non liquidarmi così!\n"
	.string "Non reggerei l'umiliazione.\p"
	.string "Diventa il mio maestro, ti prego!\n"
	.string "Ho bisogno dei tuoi consigli!$"

gText_ApprenticeWhichLevelMode14::
	.string "G-grazie…\p"
	.string "Però non guardarmi in quel modo.\n"
	.string "Mi agito tutto.\p"
	.string "Rispondimi senza guardarmi\n"
	.string "negli occhi, per favore.\p"
	.string "Alla Torre Lotta…\n"
	.string "Quale livello dovrei affrontare?$"

gText_ApprenticeLevelModeThanks14::
	.string "Oh… D'accordo!\n"
	.string "Proverò con quello.\p"
	.string "Spero di affrontare la sfida con\n"
	.string "coraggio, senza andare nel panico…\p"
	.string "Grazie, {PLAYER}{KUN}.\n"
	.string "Se ci rivedremo, spero che sarai\l"
	.string "di nuovo così gentile.$"

gText_ApprenticePleaseTeach15::
	.string "Mh? Sembreresti {PLAYER}{KUN}…\n"
	.string "Ma sei proprio tu, in carne e ossa?\p"
	.string "Con tutti questi Varchi, non si sa\n"
	.string "mai chi spunti da un altro mondo.\p"
	.string "Puoi chiamarmi {STR_VAR_1}.\p"
	.string "Da tempo accarezzo l'idea di fare\n"
	.string "da apprendista a un Allenatore forte.\p"
	.string "Che fortuna, dunque, incontrarti!\n"
	.string "…Sei davvero {PLAYER}{KUN}, vero?\p"
	.string "No, no, se sei tu, va benissimo.\n"
	.string "Desidero soltanto che tu mi accetti\l"
	.string "come tuo apprendista.$"

gText_ApprenticeRejectTeaching15::
	.string "Oh?\n"
	.string "E cosa mai ti spinge a rifiutare?\p"
	.string "Ti chiedo scusa per aver dubitato\n"
	.string "della tua identità.\p"
	.string "Accetta le mie scuse, ti prego,\n"
	.string "e accetta me come apprendista.$"

gText_ApprenticeWhichLevelMode15::
	.string "Mi accetti davvero?\n"
	.string "Non vorrei festeggiare troppo presto.\p"
	.string "Se è così, perdona i miei dubbi.\n"
	.string "Ora, però, mi serve un consiglio.\p"
	.string "Se entrassi nella Torre Lotta,\n"
	.string "quale livello sarebbe degno di me?\l"
	.string "Il Livello 50 o il Livello Libero?$"

gText_ApprenticeLevelModeThanks15::
	.string "{STR_VAR_1}?\n"
	.string "Ne sei certo?\p"
	.string "Capisco. Se è così, va benissimo.\n"
	.string "Ti ringrazio per il tuo tempo.\p"
	.string "So di essere un po' pedante, ma sono\n"
	.string "lieto che tu mi abbia accettato.\p"
	.string "Arrivederci, alla prossima!$"

gText_ApprenticeWhatHeldItem0::
	.string "Sniff… Sob…\n"
	.string "Oh, {PLAYER}!\p"
	.string "Sono intrappolato in un dilemma,\n"
	.string "come un insetto in una ragnatela…\p"
	.string "Non so proprio quale strumento\n"
	.string "far tenere al mio {STR_VAR_1}.\p"
	.string "Ti prego, {PLAYER}, dimmelo tu.\n"
	.string "Che strumento gli faccio tenere?$"

gText_ApprenticeHoldNothing0::
	.string "Davvero? Non devo far tenere\n"
	.string "niente al mio {STR_VAR_1}?$"

gText_ApprenticeThanksNoHeldItem0::
	.string "Ah, ok! Che bello, è deciso!\n"
	.string "Fantastico! Mitico! Evvivaaa!\p"
	.string "Grazie mille!$"

gText_ApprenticeThanksHeldItem0::
	.string "Oh, che sollievo…\n"
	.string "Mi sa che {STR_VAR_1} ce l'ho anch'io.\p"
	.string "Che bello, è deciso!\n"
	.string "Fantastico! Mitico! Evvivaaa!\p"
	.string "Grazie mille!$"

gText_ApprenticeItemAlreadyRecommended0::
	.string "Uaaaah! Non essere cattivo!\p"
	.string "Lo strumento {STR_VAR_1} me l'hanno\n"
	.string "già consigliato, sob…\p"
	.string "O vuoi dire che non devo far tenere\n"
	.string "niente al mio {STR_VAR_2}?$"

gText_ApprenticeWhatHeldItem1::
	.string "Evviva! È {PLAYER}!\n"
	.string "Volevo proprio chiederti una cosa!\p"
	.string "I tuoi Pokémon tengono strumenti?\n"
	.string "Anch'io vorrei darne ai miei, però…\p"
	.string "Che strumento andrebbe bene\n"
	.string "per {STR_VAR_1}?\p"
	.string "Tu che ne dici?$"

gText_ApprenticeHoldNothing1::
	.string "Eh? Vuoi dire che il mio {STR_VAR_1}\n"
	.string "non deve tenere niente?$"

gText_ApprenticeThanksNoHeldItem1::
	.string "Ah, ho capito! Farò così!\n"
	.string "Grazie della lezione!$"

gText_ApprenticeThanksHeldItem1::
	.string "Wow! {STR_VAR_1}, eh?\n"
	.string "Ok, farò così!\p"
	.string "Grazie della lezione!$"

gText_ApprenticeItemAlreadyRecommended1::
	.string "Ehm, no, non intendevo questo.\n"
	.string "Vorrei conoscere uno strumento\l"
	.string "diverso da quelli che so già.\p"
	.string "O vuoi dire che stavolta il mio\n"
	.string "Pokémon non deve tenere niente?$"

gText_ApprenticeWhatHeldItem2::
	.string "Ciao, {PLAYER}!\n"
	.string "Si tratta del mio {STR_VAR_1}…\p"
	.string "Vorrei fargli tenere uno strumento\n"
	.string "utile. Cosa gli starebbe bene?$"

gText_ApprenticeHoldNothing2::
	.string "Ah, quindi il mio {STR_VAR_1}\n"
	.string "non deve tenere niente?$"

gText_ApprenticeThanksNoHeldItem2::
	.string "Ok, ricevuto!\n"
	.string "Alla prossima!$"

gText_ApprenticeThanksHeldItem2::
	.string "Ah, lo strumento {STR_VAR_1}?\n"
	.string "Ricevuto!\p"
	.string "Farò di tutto per trovarlo!\n"
	.string "Alla prossima!$"

gText_ApprenticeItemAlreadyRecommended2::
	.string "Qualcuno mi ha già parlato\n"
	.string "di {STR_VAR_1}.\p"
	.string "Vorrei far tenere al mio Pokémon\n"
	.string "uno strumento diverso.\p"
	.string "O pensi che {STR_VAR_2} non debba\n"
	.string "tenere niente?$"

gText_ApprenticeWhatHeldItem3::
	.string "Ciao, {PLAYER}…\n"
	.string "Scusa il disturbo, ma c'è un'altra\l"
	.string "cosa che volevo chiederti.\p"
	.string "Non credo di essere così brava da\n"
	.string "vincere da sola, perciò vorrei dare\l"
	.string "uno strumento al mio {STR_VAR_1}.\p"
	.string "Però non so cosa sarebbe meglio.\p"
	.string "{PLAYER}, per favore, potresti\n"
	.string "scegliere tu per me?$"

gText_ApprenticeHoldNothing3::
	.string "Il Pokémon di una come me starebbe\n"
	.string "meglio senza strumenti?$"

gText_ApprenticeThanksNoHeldItem3::
	.string "Ho capito…\n"
	.string "Non devo affidarmi agli strumenti.\l"
	.string "Farò del mio meglio!\p"
	.string "Grazie mille!$"

gText_ApprenticeThanksHeldItem3::
	.string "Lo strumento {STR_VAR_1}, va bene.\n"
	.string "Non so se riuscirò a trovarlo…\l"
	.string "No! Ce la metterò tutta!\p"
	.string "Grazie mille!$"

gText_ApprenticeItemAlreadyRecommended3::
	.string "Oh, ma…\n"
	.string "Mi pare di averne già sentito parlare…\p"
	.string "Forse perché non ho saputo usare\n"
	.string "bene lo strumento {STR_VAR_1}?\p"
	.string "O vuoi dire che non devo far tenere\n"
	.string "niente al mio {STR_VAR_2}?$"

gText_ApprenticeWhatHeldItem4::
	.string "Oh, {PLAYER}{KUN}.\n"
	.string "Volevo chiederti una cosa.\p"
	.string "Ti ricordi quando hai scelto quale\n"
	.string "Pokémon dovevo tenere in squadra?\p"
	.string "Però non ti ho mai chiesto quale\n"
	.string "strumento fargli tenere.\p"
	.string "Visto che mi hai già consigliata,\n"
	.string "perché non vai fino in fondo?\p"
	.string "Cosa andrebbe bene? Vorrei far\n"
	.string "tenere qualcosa al mio {STR_VAR_1}.$"

gText_ApprenticeHoldNothing4::
	.string "Oh! Quindi il mio {STR_VAR_1} deve\n"
	.string "cavarsela a mani vuote?$"

gText_ApprenticeThanksNoHeldItem4::
	.string "Se pensi che sia meglio, farò così.\p"
	.string "Sapendo che l'hai deciso tu,\n"
	.string "{PLAYER}{KUN}, se perdo non ci\l"
	.string "resterò troppo male.\p"
	.string "Ok, ti chiederò ancora consiglio.\n"
	.string "Ciao ciao!$"

gText_ApprenticeThanksHeldItem4::
	.string "Lo strumento {STR_VAR_1}, eh?\n"
	.string "Niente male. Lo userò!\p"
	.string "Sapendo che l'hai deciso tu,\n"
	.string "{PLAYER}{KUN}, se perdo non ci\l"
	.string "resterò troppo male.\p"
	.string "Ok, ti chiederò ancora consiglio.\n"
	.string "Ciao ciao!$"

gText_ApprenticeItemAlreadyRecommended4::
	.string "Eh? Ma che dici?\n"
	.string "Di {STR_VAR_1} mi avevi\l"
	.string "già parlato.\p"
	.string "O vuoi dire che il mio {STR_VAR_2}\n"
	.string "deve cavarsela a mani vuote?$"

gText_ApprenticeWhatHeldItem5::
	.string "Ehilà, {PLAYER}{KUN}!\p"
	.string "Siamo due tipi impegnati, eppure\n"
	.string "ci incrociamo spesso, eh!\p"
	.string "Oggi devo portare a spasso, pulire\n"
	.string "e spazzolare i miei Pokémon.\p"
	.string "Non ho avuto neanche il tempo di\n"
	.string "comprare niente al mio {STR_VAR_1}.\p"
	.string "Il tempo mi manca, quindi perché\n"
	.string "non mi consigli tu cosa far tenere\l"
	.string "al mio {STR_VAR_1}?$"

gText_ApprenticeHoldNothing5::
	.string "Ah, visto che sono sempre di corsa,\n"
	.string "al mio {STR_VAR_1} non serve niente?$"

gText_ApprenticeThanksNoHeldItem5::
	.string "Ok, capito.\n"
	.string "Così non perdo neanche tempo.\p"
	.string "Grazie per oggi!\n"
	.string "Ci si vede in giro!$"

gText_ApprenticeThanksHeldItem5::
	.string "Ok, capito.\n"
	.string "Troverò il tempo in qualche modo\l"
	.string "per cercare {STR_VAR_1}.\p"
	.string "Sono contento di avere un maestro\n"
	.string "come te. Grazie! Ci si vede in giro!$"

gText_ApprenticeItemAlreadyRecommended5::
	.string "Eh? Lo conosco già,\n"
	.string "{STR_VAR_1}.\p"
	.string "Ah, giusto, ho capito.\n"
	.string "Visto che sono sempre di corsa,\l"
	.string "al mio {STR_VAR_2} non serve niente?$"

gText_ApprenticeWhatHeldItem6::
	.string "Ciao ciao, {PLAYER}! Sono io!\n"
	.string "Oggi mi serve di nuovo il tuo\l"
	.string "cervellone. Dammi un consiglio!\p"
	.string "Rullo di tamburi, prego!\n"
	.string "La mia domanda è…\p"
	.string "Se volessi far tenere qualcosa\n"
	.string "al mio {STR_VAR_1}, cosa sceglieresti?$"

gText_ApprenticeHoldNothing6::
	.string "Davvero? Dici che il mio {STR_VAR_1}\n"
	.string "non ha bisogno di strumenti.$"

gText_ApprenticeThanksNoHeldItem6::
	.string "Ok, farò proprio così!\p"
	.string "Direi che per oggi è tutto quello\n"
	.string "che volevo chiederti.\p"
	.string "Ci rivediamo qui, d'accordo?\n"
	.string "Grazie!$"

gText_ApprenticeThanksHeldItem6::
	.string "Aha! {STR_VAR_1}.\n"
	.string "Che scelta forte!\l"
	.string "Lo proverò di sicuro!\p"
	.string "Direi che per oggi è tutto quello\n"
	.string "che volevo chiederti.\p"
	.string "Ci rivediamo qui, d'accordo?\n"
	.string "Grazie!$"

gText_ApprenticeItemAlreadyRecommended6::
	.string "Ahahah! Che buffo!\n"
	.string "Mi avevi già parlato di\l"
	.string "{STR_VAR_1}!\p"
	.string "Ti senti bene, {PLAYER}?\p"
	.string "Ah, aspetta! Allora il mio {STR_VAR_2}\n"
	.string "non ha bisogno di strumenti.$"

gText_ApprenticeWhatHeldItem7::
	.string "Buongiorno, {PLAYER}. Spero che tu\n"
	.string "stia bene.\p"
	.string "Posso chiederti un consiglio?\p"
	.string "In una lotta recente, l'avversario\n"
	.string "aveva fatto tenere uno strumento\l"
	.string "al suo Pokémon.\p"
	.string "E così, sono stata sconfitta…\p"
	.string "Non voglio restare indietro.\n"
	.string "Vorrei far tenere uno strumento\l"
	.string "anche al mio {STR_VAR_1}.\p"
	.string "Mi farebbe piacere se scegliessi tu\n"
	.string "quello più adatto al mio Pokémon…$"

gText_ApprenticeHoldNothing7::
	.string "In altre parole… il mio Pokémon\n"
	.string "non ha bisogno di strumenti?$"

gText_ApprenticeThanksNoHeldItem7::
	.string "Ora mi è tutto chiaro!\n"
	.string "Continuerò a impegnarmi così.\p"
	.string "Grazie, {PLAYER}.\n"
	.string "Spero di poter contare ancora su te.\l"
	.string "Abbi cura di te!$"

gText_ApprenticeThanksHeldItem7::
	.string "{STR_VAR_1}, dunque!\n"
	.string "Lo ordinerò subito.\p"
	.string "Grazie, {PLAYER}.\n"
	.string "Spero di poter contare ancora su te.\l"
	.string "Abbi cura di te!$"

gText_ApprenticeItemAlreadyRecommended7::
	.string "Me ne avevi già parlato,\n"
	.string "e ce l'ho già.\p"
	.string "O forse intendi dire… che il mio\n"
	.string "Pokémon non ha bisogno di strumenti?$"

gText_ApprenticeWhatHeldItem8::
	.string "Iiih! {PLAYER}!\n"
	.string "S-sono felicissima di rivederti!\p"
	.string "Oh-oh-oh! C'è una cosa che dovevo\n"
	.string "assolutamente chiederti, {PLAYER}!\p"
	.string "Decidi tu cosa deve tenere\n"
	.string "il mio {STR_VAR_1}!$"

gText_ApprenticeHoldNothing8::
	.string "Oh! Non mi aspettavo questa risposta!\n"
	.string "Quindi lo strumento non serve?$"

gText_ApprenticeThanksNoHeldItem8::
	.string "Capito alla perfezione!\n"
	.string "Andrò avanti senza strumenti!\p"
	.string "Spero che vorrai insegnarmi\n"
	.string "qualcos'altro, un'altra volta.$"

gText_ApprenticeThanksHeldItem8::
	.string "{STR_VAR_1}! Userò quello!\p"
	.string "Ehm… Non è che anche tu, {PLAYER},\n"
	.string "lo fai tenere ai tuoi Pokémon?\p"
	.string "Me lo procurerò di sicuro!\n"
	.string "Spero che vorrai insegnarmi\l"
	.string "qualcos'altro, un'altra volta.$"

gText_ApprenticeItemAlreadyRecommended8::
	.string "Oh? Mi avevi già consigliato\n"
	.string "{STR_VAR_1}, anche prima.\p"
	.string "È forse lo strumento migliore?\n"
	.string "O vuoi dire che il mio {STR_VAR_2}\l"
	.string "non ha bisogno di tenere niente?$"

gText_ApprenticeWhatHeldItem9::
	.string "Hola!\n"
	.string "Mio maestro, {PLAYER}{KUN}!\p"
	.string "Vorrei un consiglio sugli strumenti\n"
	.string "per Pokémon.\p"
	.string "Cosa starebbe bene in mano\n"
	.string "al mio {STR_VAR_1}?\p"
	.string "Niente timidezza, eh.\n"
	.string "Sputa il rospo!$"

gText_ApprenticeHoldNothing9::
	.string "Oh? Quindi il mio {STR_VAR_1} può\n"
	.string "vincere anche senza strumenti?$"

gText_ApprenticeThanksNoHeldItem9::
	.string "Sì, bueno!\n"
	.string "Ci darò dentro, tipo, sbam!\p"
	.string "Ok, grazie come sempre!\n"
	.string "Adiós!$"

gText_ApprenticeThanksHeldItem9::
	.string "Aha, quindi {STR_VAR_1}?\n"
	.string "Sì, bueno!\l"
	.string "Vado a cercarlo, tipo, zac!\p"
	.string "Ok, grazie come sempre!\n"
	.string "Adiós!$"

gText_ApprenticeItemAlreadyRecommended9::
	.string "No, no! Mi avevi già parlato\n"
	.string "di {STR_VAR_1}, quell'affare lì.\p"
	.string "Oh, aspetta un attimo…\n"
	.string "Quindi il mio {STR_VAR_2} può\l"
	.string "vincere anche senza strumenti?$"

gText_ApprenticeWhatHeldItem10::
	.string "{PLAYER}{KUN}, è successa una cosa\n"
	.string "incredibile!\p"
	.string "Stamattina ho pescato un Pokémon\n"
	.string "uscito da un Varco… con 10 Pepite!\p"
	.string "Ma figurati, è una bugia!\n"
	.string "Uahahaha!\p"
	.string "Questa però non è una bugia:\n"
	.string "non sono bravo a capire quali\l"
	.string "strumenti far tenere ai Pokémon.\p"
	.string "Allora, maestro, perché non decidi\n"
	.string "tu cosa far tenere al mio {STR_VAR_1}?$"

gText_ApprenticeHoldNothing10::
	.string "Che vuol dire?\n"
	.string "Non devo fargli tenere niente?$"

gText_ApprenticeThanksNoHeldItem10::
	.string "Ok, quindi niente strumenti.\n"
	.string "Allora gliene compro subito uno!\p"
	.string "Scherzo!\n"
	.string "Seguirò il tuo insegnamento, maestro!\p"
	.string "Grazie, maestro!\n"
	.string "Continua a insegnarmi, eh!$"

gText_ApprenticeThanksHeldItem10::
	.string "Ah, quindi {STR_VAR_1}!\n"
	.string "Gli faccio tenere tutto tranne quello!\p"
	.string "Hai abboccato? Scherzo, scherzo!\n"
	.string "Seguirò i tuoi insegnamenti, maestro!\p"
	.string "Grazie, maestro!\n"
	.string "Spero che continuerai a istruirmi!$"

gText_ApprenticeItemAlreadyRecommended10::
	.string "Ehm, questo me l'hai già detto,\n"
	.string "o sbaglio?\p"
	.string "Non c'è qualcos'altro?\p"
	.string "Oppure intendi dire che il mio\n"
	.string "{STR_VAR_2} non deve tenere niente?$"

gText_ApprenticeWhatHeldItem11::
	.string "O-H-I-S-S-A!\n"
	.string "Oh issa, si salpa, si va!\p"
	.string "Il Marinaio rapper sono io!\n"
	.string "Ti porto una domanda, amico mio,\l"
	.string "col ritmo del mare e un po' di brio!\p"
	.string "È una domanda sugli strumenti,\n"
	.string "e voglio i tuoi suggerimenti!\p"
	.string "Al mio {STR_VAR_1} serve uno strumento:\n"
	.string "qual è il migliore? Dimmelo al momento!$"

gText_ApprenticeHoldNothing11::
	.string "Ho capito bene, amico marino?\n"
	.string "Il mio {STR_VAR_1} a mani vuote,\l"
	.string "senza neanche un piccolo bottino?$"

gText_ApprenticeThanksNoHeldItem11::
	.string "Ricevuto, forte e chiaro, che bello!\n"
	.string "Il mio Pokémon va senza fardello!\p"
	.string "Se un consiglio mi servirà,\n"
	.string "{PLAYER}, la tua voce mi guiderà!$"

gText_ApprenticeThanksHeldItem11::
	.string "Ricevuto: {STR_VAR_1}, sissignore!\n"
	.string "Lo userò con tutto il cuore!\l"
	.string "Chiederlo a te? Un colpo d'autore!\p"
	.string "Se un consiglio mi servirà,\n"
	.string "{PLAYER}, la tua voce mi guiderà!$"

gText_ApprenticeItemAlreadyRecommended11::
	.string "{STR_VAR_1}, dici? Ma dai!\n"
	.string "Me l'hai già detto, lo sai!\l"
	.string "Mi serve un'idea nuova, se ce l'hai!\p"
	.string "Oppure, aspetta, ho capito bene?\n"
	.string "Il mio Pokémon non deve tenere\l"
	.string "niente di niente, gli va bene?$"

gText_ApprenticeWhatHeldItem12::
	.string "Ehi, ehi, {PLAYER}!\n"
	.string "Anche oggi ti ho trovato, eccoti qua!\p"
	.string "Che faccio? Ti chiedo un consiglio?\n"
	.string "Perché no? Tanto ti sto già parlando!\p"
	.string "{PLAYER}, ti sto stufando, per caso?\n"
	.string "Ma no, impossibile, ci scommetto il naso!\p"
	.string "Mi ascolti? Mi serve un parere,\n"
	.string "ed è di questo che volevo sapere.\p"
	.string "Parlo di uno strumento da tenere\n"
	.string "per il mio {STR_VAR_1}: quale sarà?\l"
	.string "L'indecisione mi rovina la serata!$"

gText_ApprenticeHoldNothing12::
	.string "Il mio {STR_VAR_1} non vuole niente?\n"
	.string "Nessuno strumento, assolutamente?$"

gText_ApprenticeThanksNoHeldItem12::
	.string "Se niente è la scelta migliore,\n"
	.string "farò come dici, con tutto il cuore!\p"
	.string "Be', {PLAYER}, ora devo andare,\n"
	.string "ma di me non ti scordare!\p"
	.string "Ci vediamo, amico mio geniale!$"

gText_ApprenticeThanksHeldItem12::
	.string "Se {STR_VAR_1} è la scelta\n"
	.string "migliore, lo userò con tutto il cuore!\p"
	.string "Be', {PLAYER}, ora devo andare,\n"
	.string "ma di me non ti scordare!\p"
	.string "Ci vediamo, amico mio geniale!$"

gText_ApprenticeItemAlreadyRecommended12::
	.string "Ma {STR_VAR_1} non me l'avevi\n"
	.string "già consigliato un'altra volta?\l"
	.string "Ne sono sicuro, è la verità!\p"
	.string "Mi serve qualcosa di nuovo!\n"
	.string "O il mio {STR_VAR_2} non vuole niente?\l"
	.string "Nessuno strumento, assolutamente?$"

gText_ApprenticeWhatHeldItem13::
	.string "Ahia! Ahi! {PLAYER}{KUN}, il braccio!\n"
	.string "Me lo sono rotto! Non toccarlo!\p"
	.string "Devo essermelo rotto mentre facevo\n"
	.string "provare strumenti diversi a tutta la\l"
	.string "mia banda di Pokémon.\p"
	.string "Quindi, visto come stanno le cose,\n"
	.string "devi decidere tu al posto mio.\p"
	.string "{PLAYER}{KUN}, cosa sarebbe meglio\n"
	.string "far tenere al mio {STR_VAR_1}?$"

gText_ApprenticeHoldNothing13::
	.string "Ahia…\p"
	.string "Quindi secondo te il mio {STR_VAR_1}\n"
	.string "non deve tenere niente?$"

gText_ApprenticeThanksNoHeldItem13::
	.string "Mh, va bene. Per me sarebbe più comodo,\n"
	.string "viste le condizioni in cui sono.\p"
	.string "Spero di poter continuare a scroccarti\n"
	.string "consigli come questo.$"

gText_ApprenticeThanksHeldItem13::
	.string "Mh, va bene. Quindi {STR_VAR_1}.\n"
	.string "Il braccio del mio Pokémon sta bene,\l"
	.string "quindi glielo faccio tenere subito.\p"
	.string "Spero di poter continuare a scroccarti\n"
	.string "consigli come questo.$"

gText_ApprenticeItemAlreadyRecommended13::
	.string "No, no, {STR_VAR_1} me l'avevi già\n"
	.string "consigliato, ricordi?\p"
	.string "Perché non mi dici qualcosa\n"
	.string "di ancora meglio?\p"
	.string "Ah, aspetta un attimo.\n"
	.string "Quindi secondo te il mio {STR_VAR_2}\l"
	.string "non deve tenere niente?$"

gText_ApprenticeWhatHeldItem14::
	.string "Ehm… Uhm…\n"
	.string "{PLAYER}{KUN}…\p"
	.string "Ti prego, non guardarmi così.\n"
	.string "I miei Pokémon non hanno strumenti.\p"
	.string "Mi… mi vergogno tantissimo,\n"
	.string "ma ho proprio bisogno di un consiglio.\p"
	.string "Non so quale strumento renderebbe\n"
	.string "forte il mio {STR_VAR_1}.\p"
	.string "{PLAYER}{KUN}, secondo te cosa\n"
	.string "andrebbe bene?$"

gText_ApprenticeHoldNothing14::
	.string "Oh… Quindi pensi che sarebbe meglio\n"
	.string "se il mio {STR_VAR_1} non tenesse niente?$"

gText_ApprenticeThanksNoHeldItem14::
	.string "Oh… D'accordo!\n"
	.string "Andrò senza strumenti.\p"
	.string "Però che agitazione…\n"
	.string "Non sembrerò uno che se la tira?\p"
	.string "Grazie, {PLAYER}{KUN}.\n"
	.string "Se ci rivedremo, spero che sarai\l"
	.string "di nuovo così gentile.$"

gText_ApprenticeThanksHeldItem14::
	.string "Oh… D'accordo!\n"
	.string "Proverò con {STR_VAR_1}.\p"
	.string "Però che agitazione…\n"
	.string "Non sembrerò uno che se la tira?\p"
	.string "Grazie, {PLAYER}{KUN}.\n"
	.string "Se ci rivedremo, spero che sarai\l"
	.string "di nuovo così gentile.$"

gText_ApprenticeItemAlreadyRecommended14::
	.string "M-ma questo me l'avevi già detto.\p"
	.string "Ti prego, non liquidarmi così!\n"
	.string "Non reggerei l'umiliazione.\p"
	.string "Oh… Sto saltando alle conclusioni?\n"
	.string "Pensi che sarebbe meglio se il mio\l"
	.string "{STR_VAR_2} non tenesse niente?$"

gText_ApprenticeWhatHeldItem15::
	.string "Mh? Sembri proprio {PLAYER}{KUN}…\n"
	.string "Ma lo sei davvero?\l"
	.string "O un tuo doppio uscito da un Varco?\p"
	.string "Oh, no, no, no, non badarci!\n"
	.string "Se sei davvero {PLAYER}, ti prego\l"
	.string "di perdonare la mia scortesia.\p"
	.string "Desidererei ancora qualcuno dei tuoi\n"
	.string "preziosi consigli.\p"
	.string "Ho qui il mio {STR_VAR_1}, a cui\n"
	.string "vorrei far tenere uno strumento utile.\p"
	.string "Cosa sarebbe degno di lui?$"

gText_ApprenticeHoldNothing15::
	.string "Sarebbe meglio se non tenesse niente?\n"
	.string "Ne sei certo?$"

gText_ApprenticeThanksNoHeldItem15::
	.string "Capisco. Se è così, per me va bene.\n"
	.string "Ti ringrazio per il tuo tempo.\p"
	.string "Rivediamoci presto!$"

gText_ApprenticeThanksHeldItem15::
	.string "{STR_VAR_1}?\n"
	.string "Ne sei certo?\p"
	.string "Capisco. Se è così, per me va bene.\n"
	.string "Ti ringrazio per il tuo tempo.\p"
	.string "Confido che il mio Pokémon saprà\n"
	.string "farne buon uso.\p"
	.string "Rivediamoci presto!$"

gText_ApprenticeItemAlreadyRecommended15::
	.string "No, no, un momento.\n"
	.string "Mi pare che me l'avessi già detto.\p"
	.string "Vorrei che stavolta mi consigliassi\n"
	.string "qualcosa di diverso.\p"
	.string "Forse intendi dire che il mio\n"
	.string "{STR_VAR_2} non deve tenere niente?\l"
	.string "Ne sei certo?$"

gText_ApprenticeWhichMonFirst0::
	.string "Uaaah, {PLAYER}!\n"
	.string "Ho un dilemma, snif…\p"
	.string "Voglio cominciare a lottare con gli altri,\n"
	.string "ma non so cosa fare.\p"
	.string "Come devo schierare i miei Pokémon\n"
	.string "perché siano al massimo della forza?\p"
	.string "Dimmelo, ti prego, {PLAYER}.\n"
	.string "Se fossi in me, quale di questi Pokémon\l"
	.string "manderesti in campo per primo?$"

gText_ApprenticeMonFirstThanks0::
	.string "Il mio {STR_VAR_1} deve andare per primo?\n"
	.string "Uaaaaah!\p"
	.string "Oh! Scusami tanto!\n"
	.string "Hai scelto il mio primo Pokémon e sono\l"
	.string "così contento che piango di gioia…\p"
	.string "Grazie mille!$"

gText_ApprenticeWhichMonFirst1::
	.string "Evviva! C'è {PLAYER}!\n"
	.string "Volevo proprio chiederti una cosa!\p"
	.string "Ehm, tra i miei Pokémon, quale pensi\n"
	.string "che dovrebbe andare in campo per primo?$"

gText_ApprenticeMonFirstThanks1::
	.string "Il mio {STR_VAR_1}? Hai ragione.\n"
	.string "Ok, farò così!\p"
	.string "Grazie per la lezione!$"

gText_ApprenticeWhichMonFirst2::
	.string "{PLAYER}, ciao!\p"
	.string "Secondo me, in lotta, conta tantissimo\n"
	.string "quale Pokémon va in campo per primo.\p"
	.string "Tra i Pokémon che ho, quale sarebbe\n"
	.string "meglio mandare in campo per primo?$"

gText_ApprenticeMonFirstThanks2::
	.string "Il mio {STR_VAR_1} va per primo?\n"
	.string "Ok, ricevuto!\p"
	.string "Alla prossima!$"

gText_ApprenticeWhichMonFirst3::
	.string "Ciao, {PLAYER}…\n"
	.string "Scusa se ti disturbo di nuovo con\l"
	.string "un'altra domanda.\p"
	.string "Ho così poca fiducia in me stessa che\n"
	.string "non so cosa farei senza di te, {PLAYER}.\p"
	.string "Forse è una perdita di tempo anche solo\n"
	.string "preoccuparsene, ma proprio non riesco\l"
	.string "a decidermi…\p"
	.string "Quale dei miei Pokémon dovrei mandare\n"
	.string "in campo per primo in una lotta?$"

gText_ApprenticeMonFirstThanks3::
	.string "Il mio {STR_VAR_1}?\n"
	.string "Ricevuto!\p"
	.string "Non ci credo che tu abbia voglia di\n"
	.string "rispondere sempre alle mie domande!\p"
	.string "Ti sono così grata anche solo perché\n"
	.string "mi rivolgi la parola… Grazie!$"

gText_ApprenticeWhichMonFirst4::
	.string "Oh, {PLAYER}{KUN}! Sono io!\n"
	.string "Che bello vederti, perché ho proprio\l"
	.string "un piccolo problema.\p"
	.string "Non so come schierare i miei Pokémon.\n"
	.string "Potresti decidere tu al posto mio?\p"
	.string "Oh, non serve che tu decida tutta\n"
	.string "la squadra adesso.\p"
	.string "Che ne dici di scegliere per me solo\n"
	.string "il primo Pokémon?$"

gText_ApprenticeMonFirstThanks4::
	.string "Il mio {STR_VAR_1}? Perfetto!\p"
	.string "Sapendo che hai deciso tu, {PLAYER}{KUN},\n"
	.string "se perdo non me la prenderò\l"
	.string "troppo.\p"
	.string "Ok, tornerò a chiederti consiglio.\n"
	.string "Ciao!$"

gText_ApprenticeWhichMonFirst5::
	.string "Ciao, maestro {PLAYER}{KUN}!\n"
	.string "Anche oggi sono pieno di impegni!\p"
	.string "Devo pedalare, fare la spesa\n"
	.string "e canticchiare un po'.\p"
	.string "Non ho avuto neanche il tempo di decidere\n"
	.string "come schierare la mia squadra.\p"
	.string "Allora, che ne dici di darle un'occhiata?\n"
	.string "Chi dovrebbe andare per primo?$"

gText_ApprenticeMonFirstThanks5::
	.string "Ok, ricevuto.\n"
	.string "Almeno il tempo di mettere il mio\l"
	.string "{STR_VAR_1} in testa alla fila ce l'ho!\p"
	.string "Ops, la mia ragazza mi aspetta!\n"
	.string "Grazie! Ci si vede!$"

gText_ApprenticeWhichMonFirst6::
	.string "Ehilà! Ciao, {PLAYER}!\n"
	.string "Vai sempre in giro con l'aria da duro!\p"
	.string "Senti, mi serve di nuovo una cosa\n"
	.string "da te! La solita!\p"
	.string "Rullo di tamburi, prego!\n"
	.string "La mia domanda riguarda la squadra.\p"
	.string "Quale dei miei Pokémon dovrebbe\n"
	.string "scendere in campo per primo?$"

gText_ApprenticeMonFirstThanks6::
	.string "Mhmh!\n"
	.string "Il mio {STR_VAR_1}, dici!\l"
	.string "Che risposta fighissima, grazie!\p"
	.string "Direi che per oggi era tutto\n"
	.string "quello che volevo chiederti.\p"
	.string "Rivediamoci qui, ok?\n"
	.string "Grazie!$"

gText_ApprenticeWhichMonFirst7::
	.string "Grazie infinite per esserti fermato\n"
	.string "a chiacchierare con me, {PLAYER}.\p"
	.string "So di approfittare della tua gentilezza,\n"
	.string "ma posso chiederti un consiglio?\p"
	.string "Vorrei che fossi tu a decidere l'ordine\n"
	.string "della mia squadra di Pokémon.\p"
	.string "Mi farebbe molto piacere se decidessi\n"
	.string "quale Pokémon deve andare per primo.$"

gText_ApprenticeMonFirstThanks7::
	.string "Il mio {STR_VAR_1}, allora!\n"
	.string "Lo metterò subito in prima posizione!\p"
	.string "Grazie, {PLAYER}.\n"
	.string "Spero di poter contare ancora su di te.\l"
	.string "Abbi cura di te!$"

gText_ApprenticeWhichMonFirst8::
	.string "Iiih! {PLAYER}!\n"
	.string "Che… che gioia rivederti!\p"
	.string "I miei Pokémon sono diventati\n"
	.string "molto più forti!\p"
	.string "Ma non vinco sempre. Sembra che\n"
	.string "dipenda da quale Pokémon va per primo.\p"
	.string "{PLAYER}, ti prego, mi serve il tuo aiuto!\p"
	.string "Decidi tu quale dei miei Pokémon\n"
	.string "deve scendere in campo per primo!$"

gText_ApprenticeMonFirstThanks8::
	.string "Sigh… Sono travolta dalla felicità…\p"
	.string "Sembra un sogno che sia tu a decidere\n"
	.string "per me, {PLAYER}.\p"
	.string "Ma ho capito perfettamente!\n"
	.string "Manderò per primo il mio {STR_VAR_1}!\p"
	.string "Spero che un giorno vorrai darmi\n"
	.string "qualche altra lezione.$"

gText_ApprenticeWhichMonFirst9::
	.string "Ciao, ciao!\n"
	.string "Mio mentore, {PLAYER}{KUN}!\l"
	.string "Sparami uno dei tuoi saggi consigli!\p"
	.string "Vedi, ho messo insieme una squadra di\n"
	.string "tre Pokémon. Fin qui, tutto bene.\p"
	.string "Ma l'ordine di lotta della squadra\n"
	.string "non è ancora deciso.\p"
	.string "Ed è qui che entri in gioco tu, {PLAYER}{KUN}!\n"
	.string "Decidi tu chi guida la cordata!\p"
	.string "Non fare il timido, su.\n"
	.string "Sputa il rospo!$"

gText_ApprenticeMonFirstThanks9::
	.string "Aha, il mio {STR_VAR_1} guida la cordata!\n"
	.string "Ok, tutto ok!\l"
	.string "Riordino la formazione, tipo, zac!\p"
	.string "Bene, grazie come sempre!\n"
	.string "Alla prossima vetta!$"

gText_ApprenticeWhichMonFirst10::
	.string "{PLAYER}{KUN}, ascolta!\n"
	.string "È una crisi grossa come un Wailord!\p"
	.string "I miei Pokémon, tutti e tre, scendono\n"
	.string "in campo contemporaneamente!\p"
	.string "Ma figurati, è impossibile!\n"
	.string "Ahahahah!\p"
	.string "Questa invece è la pura verità:\n"
	.string "non sono molto bravo a capire\l"
	.string "come schierare i miei Pokémon.\p"
	.string "Allora, maestro, perché non decidi tu\n"
	.string "quale Pokémon deve andare per primo?$"

gText_ApprenticeMonFirstThanks10::
	.string "Ah, quindi hai scelto il mio {STR_VAR_1}?\n"
	.string "Allora mando primo chiunque tranne lui!\p"
	.string "Hai abboccato? Scherzo, scherzo!\n"
	.string "Seguirò i tuoi insegnamenti, maestro!\p"
	.string "Grazie, maestro!\n"
	.string "Spero che continuerai a istruirmi!$"

gText_ApprenticeWhichMonFirst11::
	.string "O-H-I-S-S-A!\n"
	.string "Oh issa, si salpa, si va!\p"
	.string "Il Marinaio rapper sono io!\n"
	.string "Ti porto una domanda, amico mio,\l"
	.string "col ritmo del mare e un po' di brio!\p"
	.string "È una domanda sulla formazione,\n"
	.string "e mi serve la tua opinione!\p"
	.string "Di questa ciurma, chi deve andare\n"
	.string "per primo in campo a lottare?$"

gText_ApprenticeMonFirstThanks11::
	.string "Ricevuto, forte e chiaro, d'accordo!\n"
	.string "Cambio l'ordine e li metto a bordo!\p"
	.string "Se un consiglio mi servirà,\n"
	.string "{PLAYER}, la tua voce mi guiderà!$"

gText_ApprenticeWhichMonFirst12::
	.string "Yuhuu, {PLAYER}!\n"
	.string "Come va, come va?\p"
	.string "Che faccio? Te lo chiedo? Ma sì!\n"
	.string "Ho una domanda, eccola qui!\l"
	.string "Prova, prova… mi ricevi?\l"
	.string "Sì, mi ricevi! Uno, due, tre!\p"
	.string "Devi decidere chi dei miei Pokémon\n"
	.string "parte per primo in tour!\l"
	.string "Cioè, in lotta, volevo dire.$"

gText_ApprenticeMonFirstThanks12::
	.string "Il mio {STR_VAR_1}? Ma sì!\n"
	.string "Così va bene, si fa così!\p"
	.string "Be', {PLAYER}, ora devo andare,\n"
	.string "ma di me non ti scordare!\p"
	.string "Ci vediamo, amico mio geniale!$"

gText_ApprenticeWhichMonFirst13::
	.string "…Uff… ahi… {PLAYER}{KUN}…\n"
	.string "Mi è venuto un mal di pancia improvviso…\p"
	.string "…Ora va un po' meglio…\p"
	.string "Devo essermi fatto venire il mal di\n"
	.string "pancia a forza di scervellarmi su come\l"
	.string "schierare la mia banda di Pokémon.\p"
	.string "Quindi, visto come stanno le cose,\n"
	.string "devi decidere tu al posto mio.\p"
	.string "{PLAYER}{KUN}, quale dei miei Pokémon\n"
	.string "va per primo? Per vincere, dico.$"

gText_ApprenticeMonFirstThanks13::
	.string "Mh, va bene.\n"
	.string "Il mio {STR_VAR_1} va per primo.\p"
	.string "Sistemerò la formazione così dopo\n"
	.string "aver cenato.\p"
	.string "Spero di poter continuare a scroccarti\n"
	.string "consigli come questo.$"

gText_ApprenticeWhichMonFirst14::
	.string "Ehm… Uhm…\n"
	.string "{PLAYER}{KUN}?\p"
	.string "Ti prego, non guardarmi così.\n"
	.string "Mi fai sentire tutto agitato.\p"
	.string "Uhm…\n"
	.string "Ho proprio bisogno di un consiglio.\p"
	.string "Mi imbarazza un po' dirlo, ma ho\n"
	.string "scelto la mia squadra di 3 Pokémon.\l"
	.string "Però non riesco a decidere l'ordine.\p"
	.string "Quale Pokémon dovrei mandare per primo\n"
	.string "per sembrare almeno un po' capace?$"

gText_ApprenticeMonFirstThanks14::
	.string "Oh… D'accordo!\n"
	.string "Comincerò con il mio {STR_VAR_1}.\p"
	.string "Spero di dare il massimo senza\n"
	.string "agitarmi troppo.\p"
	.string "Grazie, {PLAYER}{KUN}.\n"
	.string "Se ci rivedremo, spero che sarai\l"
	.string "di nuovo così gentile.$"

gText_ApprenticeWhichMonFirst15::
	.string "Mh? Sembri proprio {PLAYER}{KUN}…\n"
	.string "Ma lo sei davvero?\l"
	.string "O forse sei un abile sosia?\p"
	.string "Oh, no, no, no, non badarci!\n"
	.string "Se sei davvero {PLAYER}, ti prego\l"
	.string "di perdonare la mia scortesia.\p"
	.string "Desidererei un tuo prezioso consiglio.\p"
	.string "Ho qui la mia squadra di Pokémon.\n"
	.string "Vorrei che mi dicessi quale dovrebbe\l"
	.string "scendere in campo per primo.$"

gText_ApprenticeMonFirstThanks15::
	.string "Il mio {STR_VAR_1}…\n"
	.string "Non mi stai prendendo in giro?\p"
	.string "Capisco. Se è così, mi sta bene.\n"
	.string "Ti ringrazio per il tuo tempo.\p"
	.string "Sono quel che sono, ma farò\n"
	.string "del mio meglio.\p"
	.string "Rivediamoci presto!$"

gText_ApprenticeWhichMon0::
	.string "Sniff…\n"
	.string "Oh, {PLAYER}!\p"
	.string "Arrivi proprio al momento giusto!\n"
	.string "C'è una cosa che non so decidere…\p"
	.string "Non so quale Pokémon dovrei\n"
	.string "usare.\p"
	.string "Sono indeciso tra {STR_VAR_1}\n"
	.string "e {STR_VAR_2}…\p"
	.string "{PLAYER}, quale darebbe una chance\n"
	.string "di vincere perfino a uno come me?$"

gText_ApprenticeMonThanks0::
	.string "Sniff… Ho… ho capito!\n"
	.string "Oh! Scusami tanto!\l"
	.string "Sono così felice che sto piangendo…\p"
	.string "Mi metto subito a caccia di\n"
	.string "{STR_VAR_1}!\p"
	.string "Grazie mille!$"

gText_ApprenticeWhichMon1::
	.string "Evviva! È {PLAYER}!\n"
	.string "E sei arrivato al momento giusto!\l"
	.string "Mi serve di nuovo un tuo consiglio!\p"
	.string "Ehm, sono in confusione… Meglio usare\n"
	.string "{STR_VAR_1} o {STR_VAR_2}…\p"
	.string "Quale dovrei allenare secondo te,\n"
	.string "{PLAYER}?$"

gText_ApprenticeMonThanks1::
	.string "Ah, quindi è meglio {STR_VAR_1}!\n"
	.string "Va bene, farò così!\p"
	.string "Grazie per avermelo insegnato!$"

gText_ApprenticeWhichMon2::
	.string "{PLAYER}, ciao!\n"
	.string "Avrei una domanda da farti.\p"
	.string "Non so proprio se allenare\n"
	.string "{STR_VAR_1} oppure {STR_VAR_2}.\p"
	.string "Quale Pokémon pensi che diventerà\n"
	.string "più forte?$"

gText_ApprenticeMonThanks2::
	.string "Scegli {STR_VAR_1}?\n"
	.string "Ricevuto!\p"
	.string "Vado subito a cercare {STR_VAR_1}\n"
	.string "e ne catturo uno fortissimo!\p"
	.string "A presto!$"

gText_ApprenticeWhichMon3::
	.string "Ciao, {PLAYER}…\p"
	.string "Ehm, probabilmente ti sarai già\n"
	.string "dimenticato di una come me…\p"
	.string "…Ma non importa, se solo potessi\n"
	.string "darmi un consiglio…\p"
	.string "Non riesco a decidere quale\n"
	.string "Pokémon allenare…\p"
	.string "Sono arrivata a scegliere tra\n"
	.string "{STR_VAR_1} e {STR_VAR_2}, ma poi\l"
	.string "mi sono bloccata…\p"
	.string "{PLAYER}, forse non ne hai voglia,\n"
	.string "ma ti prego, decidi tu per me.$"

gText_ApprenticeMonThanks3::
	.string "Ma un esemplare selvatico di\n"
	.string "{STR_VAR_1} mi darà mai retta?\p"
	.string "Ci proverò!\p"
	.string "Ma riuscirò mai a catturarne uno…\n"
	.string "No! Ce la metterò tutta!\p"
	.string "Grazie!$"

gText_ApprenticeWhichMon4::
	.string "Oh, {PLAYER}{KUN}! Che bello vederti!\n"
	.string "Stavo proprio per venirti a cercare!\p"
	.string "Puoi decidere tu che Pokémon\n"
	.string "dovrei usare?\p"
	.string "Per esempio…\n"
	.string "Che ne dici dei Pokémon {STR_VAR_1}\l"
	.string "e {STR_VAR_2}?\p"
	.string "Quale dei due pensi che sarebbe\n"
	.string "meglio?$"

gText_ApprenticeMonThanks4::
	.string "{STR_VAR_1}? Fantastico!\p"
	.string "Sapendo che la decisione è tua,\n"
	.string "{PLAYER}{KUN}, non me la prenderò\l"
	.string "troppo se perdo.\p"
	.string "Bene, ti chiederò ancora consiglio!\n"
	.string "Ciao ciao!$"

gText_ApprenticeWhichMon5::
	.string "Ma guarda, {PLAYER}{KUN}! Come va?\n"
	.string "Io sono impegnatissimo, come sempre!\p"
	.string "Vorrei farmi valere coi Pokémon,\n"
	.string "ma non riesco a decidere quale\l"
	.string "Pokémon usare.\p"
	.string "{STR_VAR_1} sembra forte, vero?\n"
	.string "Ma anche {STR_VAR_2} non scherza.\p"
	.string "{PLAYER}{KUN}, dammi uno dei tuoi buoni\n"
	.string "consigli! Quale fa al caso mio?$"

gText_ApprenticeMonThanks5::
	.string "Ok, ricevuto.\n"
	.string "Troverò un buco in agenda per\l"
	.string "andare a caccia di {STR_VAR_1}.\p"
	.string "Che fortuna aver trovato un mentore\n"
	.string "come te. Grazie! Ci si vede!$"

gText_ApprenticeWhichMon6::
	.string "Oh!\n"
	.string "Evviva, è {PLAYER}!\p"
	.string "Mi sono subito vantata con i miei\n"
	.string "amici di averti conosciuto!\p"
	.string "Oggi mi serve di nuovo il tuo genio.\n"
	.string "Per te sarà facilissimo!\p"
	.string "Rullo di tamburi, prego!\n"
	.string "La domanda è…\p"
	.string "Se dovessi allenare un Pokémon\n"
	.string "e potessi scegliere tra {STR_VAR_1}\l"
	.string "e {STR_VAR_2}, quale dovrei prendere?$"

gText_ApprenticeMonThanks6::
	.string "Ahhh!\n"
	.string "{STR_VAR_1}, dici!\l"
	.string "Grazie, che risposta da urlo!\p"
	.string "Credo che per oggi sia tutto quello\n"
	.string "che volevo chiederti.\p"
	.string "Ci rivediamo qui, d'accordo?\n"
	.string "Grazie!$"

gText_ApprenticeWhichMon7::
	.string "Oh, sei tu, {PLAYER}?\n"
	.string "Che piacere rivederti!\p"
	.string "Da quando sono la tua apprendista,\n"
	.string "la mia sicurezza è sbocciata.\p"
	.string "Credo di essere pronta ad allenare\n"
	.string "un Pokémon tutto mio!\p"
	.string "{PLAYER}, posso chiederti di scegliere\n"
	.string "tu il Pokémon da allenare?\p"
	.string "Le alternative sono i Pokémon\n"
	.string "{STR_VAR_1} o {STR_VAR_2}…\l"
	.string "Quale fa per me?$"

gText_ApprenticeMonThanks7::
	.string "Allora {STR_VAR_1}!\n"
	.string "Ne troverò subito uno!\p"
	.string "Grazie, {PLAYER}.\n"
	.string "Spero di poter contare ancora su di te.\l"
	.string "Abbi cura di te!$"

gText_ApprenticeWhichMon8::
	.string "Ih! {PLAYER}! Ti ho ritrovato!\n"
	.string "Che… che gioia immensa!\p"
	.string "Oh-oh-oh, ci sono!\n"
	.string "Non posso perdere quest'occasione!\p"
	.string "Posso chiederti un favorone, {PLAYER}?\n"
	.string "Scegli tu un Pokémon per me!\p"
	.string "Decidi quale sarebbe meglio:\n"
	.string "{STR_VAR_1} o {STR_VAR_2}!$"

gText_ApprenticeMonThanks8::
	.string "Che bello! Hai deciso per me!\n"
	.string "Allenerò {STR_VAR_1} al meglio\l"
	.string "delle mie capacità.\p"
	.string "Spero che un'altra volta vorrai\n"
	.string "insegnarmi qualcos'altro.$"

gText_ApprenticeWhichMon9::
	.string "Ehi, ehi!\n"
	.string "Il mio maestro, {PLAYER}{KUN}!\p"
	.string "Ciao! Ti cercavo per un altro\n"
	.string "dei tuoi saggi consigli!\p"
	.string "Quale Pokémon farebbe per me?\n"
	.string "{STR_VAR_1} o {STR_VAR_2}?\p"
	.string "Niente timidezze, su.\n"
	.string "Sputa il rospo!$"

gText_ApprenticeMonThanks9::
	.string "Ah-ha, allora {STR_VAR_1}!\n"
	.string "Ok, perfetto!\l"
	.string "Lo infilo in una Poké Ball, zac!\p"
	.string "Bene, grazie come sempre!\n"
	.string "Adiós!$"

gText_ApprenticeWhichMon10::
	.string "{PLAYER}{KUN}, senti qua! Notizia bomba!\n"
	.string "Ho pescato un Pokémon da un Varco!\p"
	.string "Ma figurati, è una bugia!\n"
	.string "Ahahahah!\p"
	.string "Questa invece è la verità:\n"
	.string "non sono molto bravo a catturare\l"
	.string "i Pokémon.\p"
	.string "Allora, che ne dici di scegliere tu\n"
	.string "quale Pokémon dovrei catturare,\l"
	.string "maestro?\p"
	.string "Quale sarebbe meglio?\n"
	.string "{STR_VAR_1} o {STR_VAR_2}?$"

gText_ApprenticeMonThanks10::
	.string "Ok, quindi hai scelto {STR_VAR_1}?\n"
	.string "Allora io prendo l'altro!\p"
	.string "Scherzo, scherzo!\n"
	.string "Seguirò i tuoi insegnamenti, maestro!\p"
	.string "Grazie, maestro!\n"
	.string "Continua a insegnarmi, eh!$"

gText_ApprenticeWhichMon11::
	.string "O-H-È!\n"
	.string "Si scrive così e si dice “ohè”!\p"
	.string "Il Marinaio rapper sono io, sì!\n"
	.string "Ti ricordi di me? Dimmi di sì!\p"
	.string "Ho un quesito sui Pokémon da fare,\n"
	.string "e solo un tuo consiglio mi può aiutare!\p"
	.string "La scelta è tra {STR_VAR_1}\n"
	.string "e {STR_VAR_2}, capisci?\l"
	.string "Quale catturo? Dai, suggerisci!$"

gText_ApprenticeMonThanks11::
	.string "{STR_VAR_1}, dici? Ehi, ehilà!\n"
	.string "Ne prendo uno subito, eccolo qua!\p"
	.string "Se mai un consiglio mi servirà,\n"
	.string "{PLAYER}, la tua parola mi guiderà!$"

gText_ApprenticeWhichMon12::
	.string "Oh, wow, ma guarda: è {PLAYER}!\p"
	.string "Che faccio? Ti chiedo un consiglio?\n"
	.string "Perché no? Tanto ti sto già parlando!\p"
	.string "Quanto tempo! Rompo il ghiaccio:\n"
	.string "anche oggi cerco un consiglio!\l"
	.string "Mi ricevi?\l"
	.string "Mi ricevi forte e chiaro!\p"
	.string "I miei Pokémon… chi dovrei usare?\n"
	.string "O {STR_VAR_1} o {STR_VAR_2}.\l"
	.string "Tu chi scegli?$"

gText_ApprenticeMonThanks12::
	.string "Se {STR_VAR_1} è il meglio che c'è,\n"
	.string "seguo il consiglio che arriva da te!\p"
	.string "Ora, {PLAYER}, devo andare a volare,\n"
	.string "ma di me non ti devi scordare.\p"
	.string "Alla prossima, amico geniale!$"

gText_ApprenticeWhichMon13::
	.string "Oh, ciao, {PLAYER}{KUN}…\n"
	.string "Ho un mal di testa terribile…\p"
	.string "Mi sono scervellato troppo su\n"
	.string "quale Pokémon allenare.\p"
	.string "Quindi, stando così le cose,\n"
	.string "ho bisogno che tu decida per me.\p"
	.string "{PLAYER}{KUN}, se dovessi scegliere tra\n"
	.string "i Pokémon {STR_VAR_1} e\l"
	.string "{STR_VAR_2}, quale dovrei prendere?$"

gText_ApprenticeMonThanks13::
	.string "Mh, {STR_VAR_1}, d'accordo.\n"
	.string "Lo cercherò appena starò meglio.\p"
	.string "Spero di poterti chiedere aiuto\n"
	.string "così anche in futuro.$"

gText_ApprenticeWhichMon14::
	.string "Ehm… Uhm…\n"
	.string "{PLAYER}{KUN}…?\p"
	.string "Ti prego, non guardarmi così.\n"
	.string "Mi fai agitare tutto…\l"
	.string "Io… mi serve un tuo consiglio.\p"
	.string "Io… che vergogna, ma non riesco\n"
	.string "a decidere che Pokémon usare.\p"
	.string "Se le scelte fossero {STR_VAR_1} o\n"
	.string "{STR_VAR_2}, quale sarebbe meglio?$"

gText_ApprenticeMonThanks14::
	.string "Oh… Va bene!\n"
	.string "Farò del mio meglio con {STR_VAR_1}.\p"
	.string "Spero di riuscirci senza\n"
	.string "agitarmi troppo.\p"
	.string "Grazie, {PLAYER}{KUN}.\n"
	.string "Se ci rivedremo, spero che sarai\l"
	.string "di nuovo così d'aiuto.$"

gText_ApprenticeWhichMon15::
	.string "Hm? Sembri proprio {PLAYER}{KUN}…\n"
	.string "O sei un riflesso uscito da un Varco?\p"
	.string "No, no, se sei reale, va benissimo.\n"
	.string "A proposito, vorrei avere un tuo\l"
	.string "consiglio.\p"
	.string "Riguarda il Pokémon che dovrò usare.\p"
	.string "Se le scelte sono i Pokémon\n"
	.string "{STR_VAR_1} e {STR_VAR_2}, quale\l"
	.string "è più degno di me?$"

gText_ApprenticeMonThanks15::
	.string "{STR_VAR_1}?\n"
	.string "Ne sei certo?\p"
	.string "Capisco. Se è così, mi sta bene.\n"
	.string "Ti ringrazio per il tuo tempo.\p"
	.string "Spero sia un Pokémon che perfino io\n"
	.string "saprò gestire con disinvoltura.\p"
	.string "Rivediamoci presto!$"

gText_ApprenticeWhichMove0::
	.string "Uaaah! Oh, {PLAYER}!\n"
	.string "Sniff… Hic…\p"
	.string "Ho un dilemma!\n"
	.string "Non so che mossa insegnare\l"
	.string "al mio {STR_VAR_1}…\p"
	.string "Ti prego, ti prego, {PLAYER}.\n"
	.string "Puoi decidere tu per me?\p"
	.string "Per il mio {STR_VAR_1}, quale mossa\n"
	.string "sarebbe meglio: {STR_VAR_2}\l"
	.string "o {STR_VAR_3}?$"

gText_ApprenticeMoveThanks0::
	.string "{STR_VAR_1}?\n"
	.string "Uaaaaah!\p"
	.string "Oh! Scusami tanto, {PLAYER}!\n"
	.string "Hai scelto tu la mossa e sono così\l"
	.string "felice che mi viene da piangere…\p"
	.string "Sniff…\n"
	.string "Grazie mille!$"

gText_ApprenticeWhichMove1::
	.string "Evviva! Ciao, {PLAYER}!\n"
	.string "Mi serve di nuovo un tuo consiglio!\p"
	.string "Voglio insegnare al mio {STR_VAR_1}\n"
	.string "una mossa da paura.\p"
	.string "Mi piacciono tutte e due le mosse,\n"
	.string "{STR_VAR_2} e {STR_VAR_3}.\l"
	.string "Tu cosa mi consigli?$"

gText_ApprenticeMoveThanks1::
	.string "Meglio {STR_VAR_1}? Hai ragione!\n"
	.string "Ok, vada per quella!\p"
	.string "Se ci rivediamo qui, insegnami\n"
	.string "qualcos'altro, maestro!$"

gText_ApprenticeWhichMove2::
	.string "{PLAYER}, ciao!\n"
	.string "Si tratta del mio {STR_VAR_1}: sono\l"
	.string "preoccupato per le sue mosse.\p"
	.string "Vedi, sono indeciso tra {STR_VAR_2}\n"
	.string "e {STR_VAR_3}.\p"
	.string "Qual è la più forte e la più adatta\n"
	.string "al mio {STR_VAR_1}?$"

gText_ApprenticeMoveThanks2::
	.string "Scegli {STR_VAR_1}?\n"
	.string "Ricevuto!\p"
	.string "Vado subito a insegnare {STR_VAR_1}\n"
	.string "al mio Pokémon!\p"
	.string "A presto!$"

gText_ApprenticeWhichMove3::
	.string "Ohhh, {PLAYER}…\n"
	.string "Sono un disastro, davvero!\p"
	.string "Ho deciso di allenare un Pokémon,\n"
	.string "ma adesso non so nemmeno quale\l"
	.string "mossa fargli imparare…\p"
	.string "Lo so che per te non significa\n"
	.string "niente, {PLAYER}.\p"
	.string "Ma per me significa tanto…\p"
	.string "Ti prego, {PLAYER}, sceglieresti\n"
	.string "una mossa per il mio {STR_VAR_1}?\p"
	.string "Anche solo scegliendo tra\n"
	.string "{STR_VAR_2} e {STR_VAR_3}…$"

gText_ApprenticeMoveThanks3::
	.string "Ho capito!\p"
	.string "Ma vorrà mai imparare\n"
	.string "{STR_VAR_1} per me…\l"
	.string "No! Ce la metterò tutta!\p"
	.string "Grazie!$"

gText_ApprenticeWhichMove4::
	.string "Oh, {PLAYER}{KUN}!\n"
	.string "Speravo proprio di vederti!\p"
	.string "Mi chiedevo quale mossa fosse\n"
	.string "adatta al mio {STR_VAR_1}.\p"
	.string "Non riesco a decidere… Puoi\n"
	.string "decidere tu al posto mio?\p"
	.string "Per esempio… Che ne dici delle mosse\n"
	.string "{STR_VAR_2} e {STR_VAR_3}?\l"
	.string "Quale sarebbe meglio?$"

gText_ApprenticeMoveThanks4::
	.string "{STR_VAR_1}? Fantastico!\p"
	.string "Sapendo che la decisione è tua,\n"
	.string "{PLAYER}{KUN}, non me la prenderò\l"
	.string "troppo se perdo.\p"
	.string "Bene, ti chiederò ancora consiglio!\n"
	.string "Ciao ciao!$"

gText_ApprenticeWhichMove5::
	.string "Ma come si fa a essere così impegnati?\n"
	.string "Ehi, ma guarda, è {PLAYER}{KUN}!\l"
	.string "Come va?\p"
	.string "Da stamattina ho già fatto jogging,\n"
	.string "nuotato e cucinato!\p"
	.string "Non hai idea di quanto sia impegnato!\p"
	.string "Non so nemmeno che mossa far\n"
	.string "imparare al mio {STR_VAR_1}!\p"
	.string "{STR_VAR_2} sembra buona, no?\n"
	.string "Ma anche {STR_VAR_3} non è male.\p"
	.string "{PLAYER}{KUN}, dammi uno dei tuoi buoni\n"
	.string "consigli! Quale mossa fa per me?$"

gText_ApprenticeMoveThanks5::
	.string "Ok, ricevuto.\n"
	.string "Farò spazio in agenda e gli\l"
	.string "insegnerò quella mossa.\p"
	.string "Che fortuna aver trovato un mentore\n"
	.string "come te. Grazie! Ci si vede!$"

gText_ApprenticeWhichMove6::
	.string "Oh! Che fortuna!\n"
	.string "Ti ho ritrovato, {PLAYER}!\l"
	.string "Oggi mi serve di nuovo il tuo genio.\p"
	.string "Rullo di tamburi, prego!\n"
	.string "La domanda è…\p"
	.string "Per il mio {STR_VAR_1}, qual è la mossa\n"
	.string "più adatta: {STR_VAR_2} o\l"
	.string "{STR_VAR_3}?$"

gText_ApprenticeMoveThanks6::
	.string "Ahhh!\n"
	.string "{STR_VAR_1}, dici!\l"
	.string "Grazie, che risposta da urlo!\p"
	.string "Credo che per oggi sia tutto quello\n"
	.string "che volevo chiederti.\p"
	.string "Ci rivediamo qui, d'accordo?\n"
	.string "Grazie!$"

gText_ApprenticeWhichMove7::
	.string "Oh, ciao, {PLAYER}.\n"
	.string "Spero che tu stia bene.\p"
	.string "Devo chiederti di nuovo un consiglio.\n"
	.string "Riguarda il mio adorato {STR_VAR_1}.\p"
	.string "Quale sarebbe la mossa ideale per\n"
	.string "il mio tenero {STR_VAR_1}?\l"
	.string "{STR_VAR_2} o {STR_VAR_3}?$"

gText_ApprenticeMoveThanks7::
	.string "Allora {STR_VAR_1}!\n"
	.string "Gliela insegnerò subito!\p"
	.string "Grazie, {PLAYER}.\n"
	.string "Spero di poter contare ancora su di te.\l"
	.string "Abbi cura di te!$"

gText_ApprenticeWhichMove8::
	.string "Ih! {PLAYER}! Ti ho ritrovato!\n"
	.string "Che… che gioia immensa!\p"
	.string "Quando ho bisogno, tu ci sei\n"
	.string "sempre per me, {PLAYER}!\p"
	.string "Oggi voglio che mi consigli\n"
	.string "una mossa!\p"
	.string "Scegli una mossa per\n"
	.string "il mio {STR_VAR_1}, ti prego!\p"
	.string "Quale sarebbe meglio,\n"
	.string "{STR_VAR_2} o {STR_VAR_3}?$"

gText_ApprenticeMoveThanks8::
	.string "Oh-oh-oh! Grazie!\n"
	.string "Allora {STR_VAR_1}!\l"
	.string "Ricevuto alla perfezione!\p"
	.string "Spero che un'altra volta vorrai\n"
	.string "insegnarmi qualcos'altro.$"

gText_ApprenticeWhichMove9::
	.string "Hola, {PLAYER}{KUN}! Che bello!\n"
	.string "Oggi spero in un altro dei tuoi\l"
	.string "saggi consigli!\p"
	.string "Quale sarebbe la mossa migliore per\n"
	.string "il mio {STR_VAR_1}?\p"
	.string "Dev'essere una mossa che mi faccia\n"
	.string "vincere in un lampo, come un Varco\l"
	.string "che si chiude!\p"
	.string "Sarà {STR_VAR_2}?\n"
	.string "O {STR_VAR_3}?$"

gText_ApprenticeMoveThanks9::
	.string "Ajá, allora {STR_VAR_1}!\n"
	.string "Sì, bueno!\l"
	.string "Gliela insegno subito, tipo… ka-blam!\p"
	.string "Perfetto, grazie come sempre!\n"
	.string "Adiós!$"

gText_ApprenticeWhichMove10::
	.string "{PLAYER}{KUN}, è una cosa pazzesca!\p"
	.string "Il mio Pokémon!\n"
	.string "Ha imparato sei mosse!\p"
	.string "Hai abboccato? Era una frottola!\n"
	.string "Bwahahah!\p"
	.string "Questo invece è vero.\n"
	.string "Non sono bravo a scegliere le mosse\l"
	.string "per i miei Pokémon.\p"
	.string "Che ne dici di decidere tu che tipo\n"
	.string "di mossa dovrei insegnargli?\p"
	.string "{STR_VAR_2} o {STR_VAR_3}… quale\n"
	.string "va meglio per il mio {STR_VAR_1}?$"

gText_ApprenticeMoveThanks10::
	.string "Ah, quindi hai scelto {STR_VAR_1}?\n"
	.string "Allora ne sceglierò un'altra!\p"
	.string "Ci sei cascato? Scherzavo!\n"
	.string "Seguirò il tuo insegnamento, maestro!\p"
	.string "Grazie, maestro!\n"
	.string "Spero che continuerai a insegnarmi!$"

gText_ApprenticeWhichMove11::
	.string "A-H-O-Y!\n"
	.string "Si legge “ahoy”, e salve a voi!\p"
	.string "Sono il Marinaio che rappa, yo!\n"
	.string "Sempre sul pezzo, il perché non lo so!\p"
	.string "Oggi c'è una mossa da scegliere\n"
	.string "e il tuo consiglio voglio cogliere!\p"
	.string "Le mosse in gara, che dilemma,\n"
	.string "son {STR_VAR_2} e {STR_VAR_3}:\l"
	.string "per il mio {STR_VAR_1}, qual è la gemma?$"

gText_ApprenticeMoveThanks11::
	.string "{STR_VAR_1}, dici tu? Ehi, ehi!\n"
	.string "La insegno, è proprio quel che vorrei!\p"
	.string "Se un consiglio mi servirà,\n"
	.string "{PLAYER}, la tua voce mi guiderà!$"

gText_ApprenticeWhichMove12::
	.string "Uooh, rock! Ma guarda, c'è {PLAYER}!\p"
	.string "Che faccio? Ti chiedo un consiglio?\n"
	.string "E perché no? Ti sto già parlando!\p"
	.string "{PLAYER}, ti ho stupito, eh? Lo so!\n"
	.string "Ma un consiglio, ecco, te lo chiederò!\p"
	.string "Mi ricevi? Pronto, pronto?\n"
	.string "Sì che mi ricevi!\p"
	.string "Il mio {STR_VAR_1}, che mossa deve usare?\n"
	.string "{STR_VAR_2} o {STR_VAR_3}?\l"
	.string "Dimmi tu, cosa devo fare?$"

gText_ApprenticeMoveThanks12::
	.string "Se {STR_VAR_1} è la migliore,\n"
	.string "la insegno con tutto il cuore!\p"
	.string "Be', {PLAYER}, il vento mi chiama via,\n"
	.string "ma ricordati della mia melodia!\p"
	.string "Alla prossima, amico geniale!$"

gText_ApprenticeWhichMove13::
	.string "Etciù! Coff coff! Oh, {PLAYER}{KUN}…\n"
	.string "Mi sono preso un raffreddore tremendo…\p"
	.string "Vorrei scegliere una mossa per il mio\n"
	.string "Pokémon, ma non ne ho la forza…\p"
	.string "Quindi, viste le circostanze,\n"
	.string "devi decidere tu per me.\p"
	.string "{PLAYER}{KUN}, se dovessi scegliere tra\n"
	.string "{STR_VAR_2} e {STR_VAR_3}\l"
	.string "per il mio {STR_VAR_1}, quale sarebbe?$"

gText_ApprenticeMoveThanks13::
	.string "Mh, {STR_VAR_1}, d'accordo. Coff!\n"
	.string "Gliela insegnerò appena guarisco.\p"
	.string "Spero di poter contare ancora\n"
	.string "sul tuo aiuto, come oggi.$"

gText_ApprenticeWhichMove14::
	.string "Ehm… Uhm…\n"
	.string "{PLAYER}{KUN}…?\p"
	.string "Ti prego, non guardarmi così.\n"
	.string "Mi sto agitando tutto…\l"
	.string "I-io… ho bisogno di un consiglio.\p"
	.string "M-mi vergogno tantissimo, ma non\n"
	.string "riesco a decidere quale mossa\l"
	.string "insegnare al mio Pokémon.\p"
	.string "È per il mio {STR_VAR_1}.\n"
	.string "Se la scelta fosse tra {STR_VAR_2}\l"
	.string "e {STR_VAR_3}, quale sarebbe meglio?$"

gText_ApprenticeMoveThanks14::
	.string "Oh… D'accordo!\n"
	.string "Proverò con {STR_VAR_1}.\p"
	.string "Spero di riuscire a insegnarla…\n"
	.string "Che ansia, che ansia…\p"
	.string "Grazie, {PLAYER}{KUN}.\n"
	.string "Se ci rivedremo, spero che mi sarai\l"
	.string "d'aiuto come oggi.$"

gText_ApprenticeWhichMove15::
	.string "Mh? Sembreresti {PLAYER}{KUN}…\n"
	.string "Ma sei davvero tu?\p"
	.string "Non sarai mica un altro {PLAYER},\n"
	.string "sbucato da un Varco chissà da dove?\p"
	.string "No, no, se sei quello vero, va bene.\n"
	.string "Non serve offendersi, te lo assicuro!\p"
	.string "A proposito, gradirei avere\n"
	.string "un tuo consiglio.\p"
	.string "Riguarda il mio {STR_VAR_1}.\p"
	.string "Quale mossa sarebbe meglio usare,\n"
	.string "{STR_VAR_2} o {STR_VAR_3}?$"

gText_ApprenticeMoveThanks15::
	.string "{STR_VAR_1}?\n"
	.string "Non hai alcun dubbio in merito?\p"
	.string "Capisco. Se è così, d'accordo.\n"
	.string "Ti ringrazio per il tuo tempo.\p"
	.string "Spero proprio che sia una mossa\n"
	.string "che il mio Pokémon possa imparare.\p"
	.string "Rivediamoci presto!$"

gText_ApprenticePickWinSpeech0::
	.string "Oh… {PLAYER}?\n"
	.string "Sei proprio tu, {PLAYER}!\l"
	.string "Oh! Sniff… sob… Ti prego, ascoltami!\p"
	.string "Io… quando lotto mi agito così tanto\n"
	.string "che piango anche quando vinco…\p"
	.string "Vorrei tanto dire qualcosa di figo\n"
	.string "quando vinco…\p"
	.string "Ti prego, ti prego, {PLAYER}!\n"
	.string "Mi insegni una frase figa da dire\l"
	.string "quando vinco, così non piango?$"

gText_ApprenticeWinSpeechThanks0::
	.string "{STR_VAR_1}\p"
	.string "Fantastica! Pazzesca! Uaaaah!\n"
	.string "È davvero figa!\p"
	.string "Oh… scusami…\n"
	.string "Sono così felice che piango…\p"
	.string "Sniff… {PLAYER}!\n"
	.string "Grazie di tutto, davvero!\p"
	.string "Lotterò con tutte le mie forze,\n"
	.string "anche per te, {PLAYER}!\p"
	.string "{PLAYER}…\n"
	.string "La prossima volta… lottiamo!$"

gText_ApprenticePickWinSpeech1::
	.string "Evviva! C'è {PLAYER}! Ciao!\n"
	.string "Volevo chiederti una cosa!\p"
	.string "Voglio dire qualcosa di figo quando\n"
	.string "vinco una lotta.\p"
	.string "Hai una bella frase ad effetto\n"
	.string "da consigliarmi?$"

gText_ApprenticeWinSpeechThanks1::
	.string "{STR_VAR_1}\p"
	.string "Wow! È fortissima!\n"
	.string "Va bene, dirò così!\p"
	.string "Grazie per avermi insegnato tanto!\n"
	.string "D'ora in poi darò il massimo,\l"
	.string "ovunque andrò!\p"
	.string "Quando ci rivedremo, sarà per\n"
	.string "una lotta!$"

gText_ApprenticePickWinSpeech2::
	.string "{PLAYER}, ciao!\p"
	.string "Io e i miei Pokémon siamo pronti\n"
	.string "a tutto, tranne che a una cosa.\p"
	.string "Mi servirebbe una frase da gridare\n"
	.string "quando vinco.\p"
	.string "Ti viene in mente qualcosa di\n"
	.string "bello da dire?$"

gText_ApprenticeWinSpeechThanks2::
	.string "{STR_VAR_1}\p"
	.string "…Forte!\n"
	.string "Userò questa!\p"
	.string "Ora partirò per lottare in ogni\n"
	.string "angolo di Hoenn.\p"
	.string "Chissà, magari un giorno lotterò\n"
	.string "proprio contro di te, {PLAYER}.\p"
	.string "La prossima volta, incontriamoci\n"
	.string "su un campo di lotta!$"

gText_ApprenticePickWinSpeech3::
	.string "Ciao, {PLAYER}…\n"
	.string "Scusa il disturbo, ma sono un disastro…\p"
	.string "Anche quando…\n"
	.string "Anche quando vinco, non ho niente\l"
	.string "di speciale da dire…\p"
	.string "Lo so che per te non conta\n"
	.string "niente, {PLAYER}.\p"
	.string "Ma per me conta tantissimo…\p"
	.string "Ti prego, {PLAYER}, cosa dovrei dire\n"
	.string "se vinco una lotta?$"

gText_ApprenticeWinSpeechThanks3::
	.string "{STR_VAR_1}\p"
	.string "È… geniale…\p"
	.string "Ehm… Una come me può davvero\n"
	.string "dire una cosa del genere?\p"
	.string "No! Ce la metterò tutta!\p"
	.string "{PLAYER}, grazie mille per avermi\n"
	.string "sopportata così a lungo…\p"
	.string "Prometto che d'ora in poi darò\n"
	.string "il massimo.\p"
	.string "Ti dimenticherai presto di una come\n"
	.string "me, lo so… ma spero che un giorno\l"
	.string "ci rivedremo, da qualche parte!$"

gText_ApprenticePickWinSpeech4::
	.string "Oh, {PLAYER}{KUN}.\n"
	.string "C'è una cosa che voglio dirti.\p"
	.string "Lo so che non sempre sembro\n"
	.string "gentile o educata…\p"
	.string "Quando vinco una lotta, credo di\n"
	.string "sembrare un po' arrogante.\p"
	.string "Non voglio che la gente mi detesti,\n"
	.string "quindi vorrei dire qualcosa di carino\l"
	.string "a chi ho battuto.\p"
	.string "Ma non mi viene in mente niente!\n"
	.string "Potresti pensarci tu per me?$"

gText_ApprenticeWinSpeechThanks4::
	.string "{STR_VAR_1}\p"
	.string "Niente male!\n"
	.string "Sì, userò proprio questa!\p"
	.string "Ora mi metto in viaggio e farò del\n"
	.string "mio meglio, con i tuoi insegnamenti\l"
	.string "nella testa e nel cuore.\p"
	.string "Scusa se sono stata così\n"
	.string "insistente con te!\p"
	.string "La prossima volta lottiamo, ok?\n"
	.string "Ci vediamo!$"

gText_ApprenticePickWinSpeech5::
	.string "Uff, non ho un attimo di respiro!\n"
	.string "Oh, ehi, ti cercavo, {PLAYER}{KUN}.\p"
	.string "Tutto bene come al solito?\n"
	.string "Per me non è cambiato niente.\p"
	.string "Devo correre, lottare, segnare i\n"
	.string "Varchi sulla mappa… Che stress!\p"
	.string "Però, anche se vado di fretta, sarebbe\n"
	.string "maleducato girare i tacchi dopo una\l"
	.string "vittoria senza dire una parola.\p"
	.string "Allora, che frase figa potrei dire\n"
	.string "per far colpo mentre me ne vado?\l"
	.string "{PLAYER}{KUN}, aiutami tu!$"

gText_ApprenticeWinSpeechThanks5::
	.string "{STR_VAR_1}\p"
	.string "Ok, ricevuto.\n"
	.string "Il tempo per dirla lo trovo!\p"
	.string "Sinceramente, sono contento di aver\n"
	.string "trovato un maestro bravo come te.\p"
	.string "In qualche modo troverò il tempo\n"
	.string "per dedicarmi alle lotte.\p"
	.string "Grazie di tutto, {PLAYER}{KUN}!\n"
	.string "Un giorno dobbiamo sfidarci, io e te!$"

gText_ApprenticePickWinSpeech6::
	.string "Che fortuna, di nuovo!\n"
	.string "{PLAYER}! Che bello vederti!\l"
	.string "Come al solito, mi serve un consiglio!\p"
	.string "Rullo di tamburi, prego!\n"
	.string "L'ultima domanda che ho è…\p"
	.string "Se vinco una lotta e voglio\n"
	.string "chiuderla con stile, cosa\l"
	.string "dovrei dire?$"

gText_ApprenticeWinSpeechThanks6::
	.string "{STR_VAR_1}\p"
	.string "È… è favolosa!\n"
	.string "Elegante e figa! La prendo io!\p"
	.string "…Senti, mi sa che sto diventando\n"
	.string "bravina, eh?\p"
	.string "Quindi d'ora in poi penso di sfidare\n"
	.string "altri Allenatori.\p"
	.string "{PLAYER}, i tuoi consigli mi sono\n"
	.string "serviti davvero tanto.\p"
	.string "Magari un giorno arriverà il momento\n"
	.string "di lottare tra noi!\p"
	.string "Grazie di tutto!$"

gText_ApprenticePickWinSpeech7::
	.string "Oh, {PLAYER}.\n"
	.string "Sono così lieta di averti conosciuto!\p"
	.string "Non ho più alcuna preoccupazione\n"
	.string "riguardo ai miei Pokémon.\p"
	.string "È di me stessa che mi preoccupo…\p"
	.string "Sai che gli Allenatori dicono sempre\n"
	.string "qualche parola dopo aver vinto?\p"
	.string "Mi piacerebbe tanto saperlo fare\n"
	.string "anch'io!\p"
	.string "Ti prego, cosa dovrei dire quando\n"
	.string "vinco una lotta?$"

gText_ApprenticeWinSpeechThanks7::
	.string "{STR_VAR_1}\p"
	.string "Ah! Che frase! Mi rinfresca l'animo\n"
	.string "e mi fa sentire rinata!\p"
	.string "Devo usarla immediatamente!\p"
	.string "E ora devo congedarmi,\n"
	.string "{PLAYER}…\p"
	.string "Sfiderò molti altri Allenatori,\n"
	.string "ma non dimenticherò mai\l"
	.string "i tuoi insegnamenti.\p"
	.string "Forse un giorno…\n"
	.string "Addio!$"

gText_ApprenticePickWinSpeech8::
	.string "Iiih! Ho avvistato {PLAYER}!\n"
	.string "S-sono felicissima di vederti!\p"
	.string "Oh-oh-oh! C'è una cosa che dovevo\n"
	.string "assolutamente chiederti!\p"
	.string "Poco fa ho vinto una lotta.\n"
	.string "Mi girava la testa dalla gioia!\p"
	.string "Ma ero così felice che mi si è\n"
	.string "chiusa la gola e non ho detto niente!\p"
	.string "Quindi, {PLAYER}, ti prego, inventa\n"
	.string "una frase d'uscita per quando vinco!$"

gText_ApprenticeWinSpeechThanks8::
	.string "{STR_VAR_1}\p"
	.string "Uaaaaah!\n"
	.string "Dovrò dire proprio questo?!\l"
	.string "S-sto delirando dalla gioia!\p"
	.string "G-g-grazie!\n"
	.string "Ora non ho più nessun rimpianto!\p"
	.string "Adesso partirò per lottare contro\n"
	.string "ogni genere di persona.\p"
	.string "Devo tutto a te, {PLAYER}.\n"
	.string "Davvero, davvero, grazie!\p"
	.string "Ora devo andare, ma un giorno\n"
	.string "incontriamoci in una lotta!$"

gText_ApprenticePickWinSpeech9::
	.string "Hola, bueno!\n"
	.string "{PLAYER}{KUN}!\p"
	.string "Sai, mi sta venendo voglia di girare\n"
	.string "per Hoenn e lottare dove capita.\p"
	.string "Ma prima vorrei un tuo consiglio,\n"
	.string "ancora una volta, por favor!\p"
	.string "Se vincessi una lotta, che frase\n"
	.string "da sbruffone potrei dire\l"
	.string "all'Allenatore che ho battuto?$"

gText_ApprenticeWinSpeechThanks9::
	.string "{STR_VAR_1}\p"
	.string "Ajá, che bella!\n"
	.string "Sì, bueno!\l"
	.string "Proverò a dirla, tipo… bam!\p"
	.string "E ora è il momento dei saluti!\n"
	.string "Grazie per tutto quanto!\p"
	.string "Un giorno lottiamo, d'accordo?\n"
	.string "Adiós!$"

gText_ApprenticePickWinSpeech10::
	.string "{PLAYER}{KUN}, c'è un guaio enorme!\p"
	.string "Quando vinco una lotta, me ne vanto\n"
	.string "per almeno un'ora di fila!\p"
	.string "Hai abboccato? Era una frottola!\n"
	.string "Bwahahah!\p"
	.string "Questo invece è vero.\n"
	.string "Non sono bravo a chiacchierare.\p"
	.string "Allora, che ne dici di decidere tu\n"
	.string "cosa dovrei dire dopo aver vinto\l"
	.string "una lotta, maestro?$"

gText_ApprenticeWinSpeechThanks10::
	.string "{STR_VAR_1}\p"
	.string "Dovrei dire questo, eh?\n"
	.string "Allora me ne guarderò bene!\p"
	.string "Ci sei cascato? Scherzavo!\n"
	.string "Seguirò il tuo insegnamento, maestro!\p"
	.string "Grazie per tutto quello che mi hai\n"
	.string "insegnato, maestro!\p"
	.string "Finalmente comincio a capire cosa\n"
	.string "vuol dire essere un Allenatore.\p"
	.string "Andrò a vincere lotte contro\n"
	.string "qualsiasi Allenatore.\p"
	.string "Magari un giorno toccherà a te!\p"
	.string "Questo è tutto!\n"
	.string "Addio, mio maestro!$"

gText_ApprenticePickWinSpeech11::
	.string "A-H-O-Y!\n"
	.string "Si legge “ahoy”, e salve a voi!\p"
	.string "Sono il Marinaio che rappa, yo!\n"
	.string "È l'ultima domanda, lo so,\l"
	.string "ma non piangere, no, no, no!\p"
	.string "Cerco una frase ad effetto\n"
	.string "e il tuo consiglio è perfetto!\p"
	.string "Se vinco una lotta, che dire\n"
	.string "con stile, per farli impazzire?$"

gText_ApprenticeWinSpeechThanks11::
	.string "{STR_VAR_1}\p"
	.string "Perfetta! È questa che userò!\n"
	.string "Ho fatto bene a chiedere, oh-oh!\p"
	.string "E ora credo sia meglio, così,\n"
	.string "che io spieghi le vele da qui!\p"
	.string "Grazie di tutto, maestro mio,\n"
	.string "vado a lottare! Ciao e addio!\p"
	.string "B-U-O-N V-I-A-G-G-I-O!\n"
	.string "Si legge “buon viaggio”, con coraggio,\l"
	.string "e a te va il mio omaggio!$"

gText_ApprenticePickWinSpeech12::
	.string "Uooh, rock! {PLAYER}!\n"
	.string "Ti ho trovato anche oggi!\p"
	.string "Che faccio? Ti chiedo di nuovo?\n"
	.string "Perché no? Te lo sto già chiedendo!\p"
	.string "Comunque, {PLAYER}…\n"
	.string "Mi ricevi? Pronto, pronto?\l"
	.string "Sì che mi ricevi!\l"
	.string "Mi serve ancora un tuo consiglio!\p"
	.string "Si tratta di un urlo da lanciare:\n"
	.string "una frase figa da sparare\l"
	.string "quando vinco, per farli saltare!\p"
	.string "Dai, voglio sentirtelo dire!$"

gText_ApprenticeWinSpeechThanks12::
	.string "{STR_VAR_1}\p"
	.string "Grande, grande, che bomba!\n"
	.string "La userò, suona come una tromba!\p"
	.string "Domande non ne ho più, mi sa:\n"
	.string "non resta che salutarti, ecco qua.\p"
	.string "Ma forse un giorno ci incontreremo,\n"
	.string "e chi dei due perderà, lo vedremo!\p"
	.string "Ma ora è davvero tempo di salutarci.\p"
	.string "Be', {PLAYER}, il vento mi chiama via,\n"
	.string "ma ricordati della mia melodia!\p"
	.string "Stammi bene, {PLAYER}!\n"
	.string "Un abbraccio!$"

gText_ApprenticePickWinSpeech13::
	.string "{PLAYER}{KUN}, sono distrutto…\n"
	.string "Il naso non smette di colare…\p"
	.string "Stavo cercando una frase figa\n"
	.string "da dire quando vinco una lotta.\p"
	.string "Mi sono emozionato così tanto che\n"
	.string "ho pianto, e ora il naso mi cola…\p"
	.string "Quindi, viste le circostanze, devi\n"
	.string "decidere tu per me, {PLAYER}{KUN}.\p"
	.string "Quando vinco una lotta,\n"
	.string "cosa dovrei dire?$"

gText_ApprenticeWinSpeechThanks13::
	.string "{STR_VAR_1}\p"
	.string "… … …Che bella.\n"
	.string "Anzi, è da brividi!\l"
	.string "Mi vengono di nuovo le lacrime!\p"
	.string "Ma nonostante lacrime e naso che\n"
	.string "cola, userò questa frase!\p"
	.string "Non ho più niente da chiederti,\n"
	.string "{PLAYER}{KUN}.\p"
	.string "D'ora in poi, siamo rivali!\n"
	.string "Grazie di tutto!$"

gText_ApprenticePickWinSpeech14::
	.string "Ehm… Uhm…\n"
	.string "{PLAYER}{KUN}…\p"
	.string "Ti prego, non guardarmi così.\n"
	.string "Mi metti in agitazione.\p"
	.string "I-io… ho di nuovo bisogno di un\n"
	.string "consiglio. Ma sarà l'ultimo, giuro…\p"
	.string "È davvero imbarazzante chiederlo,\n"
	.string "ma… e se vincessi una lotta?\l"
	.string "Cosa dovrei dire?$"

gText_ApprenticeWinSpeechThanks14::
	.string "{STR_VAR_1}\p"
	.string "Oh… D'accordo!\n"
	.string "Proverò a dirla!\l"
	.string "Magari sarò troppo agitato per farlo…\p"
	.string "Grazie, {PLAYER}{KUN}.\n"
	.string "Adesso devo salutarti.\p"
	.string "Seguirò tutti i tuoi insegnamenti,\n"
	.string "{PLAYER}{KUN}, e farò del mio meglio.$"

gText_ApprenticePickWinSpeech15::
	.string "Mh? Sembreresti {PLAYER}{KUN}…\n"
	.string "Ma lo sei davvero?\l"
	.string "O sei un pupazzo di {PLAYER} ben fatto?\p"
	.string "Oh, no, no, no, non preoccuparti!\n"
	.string "Se sei davvero tu, ti prego,\l"
	.string "dimentica la mia scortesia.\p"
	.string "Non serve arrabbiarsi tanto. Desidero\n"
	.string "solo un altro dei tuoi ottimi consigli.\p"
	.string "Riguarda una frase.\p"
	.string "Più precisamente: cosa dovrei dire\n"
	.string "se vinco una lotta?$"

gText_ApprenticeWinSpeechThanks15::
	.string "{STR_VAR_1}\p"
	.string "… … … … … …\n"
	.string "Quando vinco una lotta…\p"
	.string "{STR_VAR_1}\p"
	.string "…Dici sul serio?\p"
	.string "Capisco. Se sei serio, va bene così.\n"
	.string "Ti ringrazio per il tuo tempo.\p"
	.string "Spero di riuscire anch'io a fare\n"
	.string "buon uso di questa frase.\p"
	.string "Mi pare di aver esaurito i consigli\n"
	.string "di cui avevo bisogno.\p"
	.string "Credo sia giunto il momento di\n"
	.string "salutarti e proseguire da solo.\p"
	.string "Grazie, mio mentore!\n"
	.string "Perdona la mia diffidenza!$"
