FallarborTown_BattleTentLobby_Text_WelcomeToBattleTent:
	.string "Benvenuto alla Tenda Lotta\n"
	.string "di Brunifoglia!\p"
	.string "Sono la tua guida al Torneo KO!$"

FallarborTown_BattleTentLobby_Text_TakeChallenge:
	.string "Allora, vuoi cimentarti nella sfida\n"
	.string "del Torneo KO?$"

FallarborTown_BattleTentLobby_Text_AwaitAnotherChallenge:
	.string "Attendiamo la tua sfida\n"
	.string "in un'altra occasione!$"

FallarborTown_BattleTentLobby_Text_ExplainFallarborTent:
	.string "Alla Tenda Lotta di Brunifoglia\n"
	.string "si disputa il Torneo KO.\p"
	.string "Tutti i partecipanti si presentano\n"
	.string "con una squadra di tre Pokémon.\p"
	.string "I tre Pokémon vanno schierati\n"
	.string "nell'ordine in cui scenderanno in campo.\p"
	.string "Durante la lotta, i Pokémon entrano\n"
	.string "uno alla volta, nell'ordine stabilito.\p"
	.string "Una volta in campo, un Pokémon deve\n"
	.string "restarci finché l'incontro non è deciso.\p"
	.string "Se dopo tre turni l'incontro non è\n"
	.string "ancora deciso, si passa al giudizio.\p"
	.string "Se vuoi interrompere la sfida,\n"
	.string "ricordati di salvare il gioco.\p"
	.string "Se non salvi, non potrai\n"
	.string "proseguire la sfida.\p"
	.string "Se riuscirai nell'impresa di battere\n"
	.string "tre Allenatori di fila,\l"
	.string "riceverai un ottimo premio.$"

FallarborTown_BattleTentLobby_Text_SaveBeforeChallenge:
	.string "Prima di accompagnarti alla Tenda\n"
	.string "Lotta devo salvare. Va bene?$"

@ Unused
FallarborTown_BattleTentLobby_Text_WhichLevelMode:
	.string "Offriamo due livelli di sfida:\n"
	.string "Livello 50 e Livello Libero.\l"
	.string "Quale scegli?$"

FallarborTown_BattleTentLobby_Text_SelectThreeMons:
	.string "Molto bene. Ora scegli i tuoi\n"
	.string "tre Pokémon, per favore.$"

FallarborTown_BattleTentLobby_Text_NotEnoughValidMonsLv50:
	.string "Caro sfidante!\p"
	.string "Non hai i tre Pokémon richiesti\n"
	.string "per partecipare.\p"
	.string "Inoltre, i Pokémon non possono\n"
	.string "tenere strumenti uguali.\p"
	.string "Le Uova{STR_VAR_1}.\p"
	.string "Quando avrai fatto i tuoi preparativi,\n"
	.string "torna pure a trovarci.$"

FallarborTown_BattleTentLobby_Text_NotEnoughValidMonsLvOpen:
	.string "Caro sfidante!\p"
	.string "Non hai i tre Pokémon richiesti\n"
	.string "per partecipare.\p"
	.string "Per qualificarti, devi portare tre\n"
	.string "Pokémon di specie diverse.\p"
	.string "Inoltre, i Pokémon non possono\n"
	.string "tenere strumenti uguali.\p"
	.string "Le Uova{STR_VAR_1}.\p"
	.string "Quando avrai fatto i tuoi preparativi,\n"
	.string "torna pure a trovarci.$"

FallarborTown_BattleTentLobby_Text_GuideYouToBattleTent:
	.string "Ora ti accompagno\n"
	.string "alla Tenda Lotta.$"

FallarborTown_BattleTentLobby_Text_DidntSaveBeforeQuitting:
	.string "Caro sfidante!\p"
	.string "Hai spento il gioco senza salvare,\n"
	.string "non è vero?\p"
	.string "Mi dispiace, ma questo ha\n"
	.string "comportato la tua squalifica\l"
	.string "dalla sfida.\p"
	.string "Naturalmente, puoi sempre iniziare\n"
	.string "una nuova sfida.$"

FallarborTown_BattleTentLobby_Text_BeatThreeTrainers:
	.string "Splendido! Hai battuto tre\n"
	.string "Allenatori di fila!$"

FallarborTown_BattleTentLobby_Text_WaitWhileSaveGame:
	.string "Attendi mentre salvo il gioco.$"

FallarborTown_BattleTentLobby_Text_PresentYouWithPrize:
	.string "Per celebrare le tue tre vittorie\n"
	.string "di fila, ecco a te questo premio.$"

FallarborTown_BattleTentLobby_Text_ReceivedPrize:
	.string "{PLAYER} riceve in premio\n"
	.string "{STR_VAR_1}.$"

FallarborTown_BattleTentLobby_Text_BagFullReturnForPrize:
	.string "Oh?\n"
	.string "Sembra che la tua Borsa sia piena.\p"
	.string "Ti prego, fai un po' di spazio e\n"
	.string "torna a ritirare il tuo premio.$"

FallarborTown_BattleTentLobby_Text_ThankYouWaitWhileSaving:
	.string "Grazie mille per aver partecipato!\p"
	.string "Attendi mentre salvo il gioco.$"

FallarborTown_BattleTentLobby_Text_AwaitAnotherChallenge2:
	.string "Attendiamo la tua sfida\n"
	.string "in un'altra occasione!$"

FallarborTown_BattleTentLobby_Text_LookingForwardToArrival:
	.string "Aspettavamo con ansia\n"
	.string "il tuo arrivo.\p"
	.string "Prima di accompagnarti alla Tenda\n"
	.string "Lotta devo salvare. Attendi un attimo.$"

VerdanturfTown_BattleTentLobby_Text_WelcomeToBattleTent:
	.string "Ti do il benvenuto alla Tenda Lotta\n"
	.string "di Mentania!\p"
	.string "Qui si mette alla prova la fiducia\n"
	.string "tra l'Allenatore e i suoi Pokémon.$"

VerdanturfTown_BattleTentLobby_Text_TakeChallenge:
	.string "Vuoi affrontare la sfida della\n"
	.string "Tenda Lotta di Mentania?$"

VerdanturfTown_BattleTentLobby_Text_ExplainVerdanturfTent:
	.string "Alla Tenda Lotta di Mentania vige\n"
	.string "una regola fondamentale che va\l"
	.string "rispettata.\p"
	.string "Gli Allenatori possono soltanto\n"
	.string "sostituire i propri Pokémon.\p"
	.string "Per il resto, è vietato dare\n"
	.string "ordini ai Pokémon.\p"
	.string "I Pokémon agiranno secondo la loro\n"
	.string "natura e lotteranno da soli.\p"
	.string "Devi riporre la tua fiducia nei tuoi\n"
	.string "Pokémon e vegliare su di loro.\p"
	.string "Se avrai l'onore di battere tre\n"
	.string "Allenatori di fila,\l"
	.string "riceverai un premio.\p"
	.string "Se vuoi interrompere la sfida,\n"
	.string "ricordati di salvare il gioco.\p"
	.string "Se interrompi senza salvare,\n"
	.string "verrai squalificato.$"

VerdanturfTown_BattleTentLobby_Text_ReturnFortified:
	.string "Quando avrai fortificato il tuo cuore\n"
	.string "e i tuoi Pokémon, torna da noi.$"

@ Unused
VerdanturfTown_BattleTentLobby_Text_WhichLevelMode:
	.string "Ci sono due livelli di difficoltà:\n"
	.string "Livello 50 e Livello Libero.\l"
	.string "Quale sfida scegli?$"

VerdanturfTown_BattleTentLobby_Text_NotEnoughValidMonsLv50:
	.string "Ahimè…\p"
	.string "Non hai i tre Pokémon richiesti\n"
	.string "per la sfida.\p"
	.string "Per partecipare, devi portare tre\n"
	.string "Pokémon di specie diverse.\p"
	.string "Inoltre, i Pokémon non possono\n"
	.string "tenere strumenti uguali.\p"
	.string "Le Uova{STR_VAR_1}.\p"
	.string "Torna quando avrai fatto\n"
	.string "i tuoi preparativi.$"

VerdanturfTown_BattleTentLobby_Text_NotEnoughValidMonsLvOpen:
	.string "Ahimè…\p"
	.string "Non hai i tre Pokémon richiesti\n"
	.string "per la sfida.\p"
	.string "Per partecipare, devi portare tre\n"
	.string "Pokémon di specie diverse.\p"
	.string "Inoltre, i Pokémon non possono\n"
	.string "tenere strumenti uguali.\p"
	.string "Le Uova{STR_VAR_1}.\p"
	.string "Torna quando avrai fatto\n"
	.string "i tuoi preparativi.$"

VerdanturfTown_BattleTentLobby_Text_SelectThreeMons:
	.string "Bene. Ora devi scegliere i tuoi\n"
	.string "tre Pokémon.$"

VerdanturfTown_BattleTentLobby_Text_SaveBeforeChallenge:
	.string "Devo salvare prima di accompagnarti\n"
	.string "alla Tenda Lotta. Va bene?$"

VerdanturfTown_BattleTentLobby_Text_NowFollowMe:
	.string "Bene.\n"
	.string "Ora seguimi.$"

VerdanturfTown_BattleTentLobby_Text_ResultsWillBeRecorded:
	.string "È stato un privilegio assistere\n"
	.string "alle imprese dei tuoi Pokémon.\p"
	.string "I risultati verranno registrati.\n"
	.string "Ti chiedo di attendere un istante.$"

VerdanturfTown_BattleTentLobby_Text_AchievedThreeWinStreak:
	.string "Tre vittorie di fila…\p"
	.string "Il legame tra il tuo cuore e i tuoi\n"
	.string "Pokémon sembra saldo e sincero.$"

VerdanturfTown_BattleTentLobby_Text_FeatWillBeRecorded:
	.string "La tua impresa verrà registrata.\n"
	.string "Ti chiedo di attendere un istante.$"

VerdanturfTown_BattleTentLobby_Text_PresentYouWithPrize:
	.string "Per l'impresa delle tre vittorie\n"
	.string "di fila, ecco a te questo premio.$"

SlateportCity_BattleTentLobby_Text_WelcomeToBattleTent:
	.string "Benvenuto alla Tenda Lotta\n"
	.string "di Porto Selcepoli!\p"
	.string "Sono la tua guida al Torneo\n"
	.string "Scambio Lotta.$"

SlateportCity_BattleTentLobby_Text_TakeChallenge:
	.string "Vuoi affrontare la sfida\n"
	.string "Scambio Lotta?$"

SlateportCity_BattleTentLobby_Text_ExplainSlateportTent:
	.string "Alla Tenda Lotta di Porto Selcepoli\n"
	.string "organizziamo eventi Scambio Lotta\l"
	.string "con Pokémon a noleggio.\p"
	.string "Per prima cosa, riceverai in prestito\n"
	.string "tre Pokémon scelti per l'evento.\p"
	.string "Con i Pokémon a noleggio forniti,\n"
	.string "dovrai disputare una Lotta in Singolo.\p"
	.string "Se vinci, potrai scambiare uno dei\n"
	.string "tuoi Pokémon a noleggio.\p"
	.string "Ripeti il ciclo di lotte e scambi:\n"
	.string "se vinci tre volte di fila,\l"
	.string "otterrai un ottimo premio.\p"
	.string "Se vuoi interrompere la sfida,\n"
	.string "ricordati di salvare il gioco.\p"
	.string "Se interrompi senza salvare,\n"
	.string "verrai squalificato.$"

SlateportCity_BattleTentLobby_Text_LookForwardToNextVisit:
	.string "Ti aspettiamo alla prossima visita!$"

@ Unused
SlateportCity_BattleTentLobby_Text_WhichLevelMode:
	.string "A quale livello vuoi sfidarci?\n"
	.string "Livello 50 o Livello 100?$"

SlateportCity_BattleTentLobby_Text_SaveBeforeChallenge:
	.string "Prima di iniziare la sfida devo\n"
	.string "salvare i dati. Va bene?$"

@ Unused
SlateportCity_BattleTentLobby_Text_HoldMonsForSafekeeping:
	.string "Bene, custodirò io i tuoi Pokémon\n"
	.string "mentre gareggi.$"

SlateportCity_BattleTentLobby_Text_StepThisWay:
	.string "Da questa parte, prego.$"

SlateportCity_BattleTentLobby_Text_ReturnRentalMonsSaveResults:
	.string "Grazie per aver partecipato!\p"
	.string "Ti restituisco i tuoi Pokémon in\n"
	.string "cambio di quelli a noleggio.\p"
	.string "Devo anche salvare i risultati\n"
	.string "dell'evento. Attendi, per favore.$"

@ Unused
SlateportCity_BattleTentLobby_Text_ReturnMonsExchangeRentals:
	.string "Ti restituisco i tuoi Pokémon in\n"
	.string "cambio di quelli a noleggio.$"

SlateportCity_BattleTentLobby_Text_WonThreeMatchesReturnMons:
	.string "Congratulazioni!\n"
	.string "Hai vinto tre incontri di fila!\p"
	.string "Ti restituisco i tuoi Pokémon in\n"
	.string "cambio di quelli a noleggio.\p"
	.string "Devo anche salvare i risultati\n"
	.string "dell'evento. Attendi, per favore.$"

SlateportCity_BattleTentLobby_Text_AwardYouThisPrize:
	.string "Per le tue tre vittorie di fila,\n"
	.string "ti assegniamo questo premio.$"

SlateportCity_BattleTentLobby_Text_NoRoomInBagMakeRoom:
	.string "Oh?\n"
	.string "Sembra che tu non abbia più spazio.\p"
	.string "Libera un po' di spazio nella Borsa\n"
	.string "e poi fammelo sapere.$"

SlateportCity_BattleTentLobby_Text_BeenWaitingForYou:
	.string "Ti stavamo aspettando!\p"
	.string "Prima di riprendere la sfida,\n"
	.string "devo salvare il gioco.$"

SlateportCity_BattleTentLobby_Text_DidntSaveBeforeQuitting:
	.string "Mi spiace dirtelo, ma l'ultima volta\n"
	.string "hai smesso di giocare senza salvare.\p"
	.string "Di conseguenza, sei stato squalificato\n"
	.string "dalla sfida.$"

@ Unused
SlateportCity_BattleTentLobby_Text_ReturnPersonalMons:
	.string "Ti restituiamo i tuoi Pokémon.$"

@ Unused
SlateportCity_BattleTentLobby_Text_ReceivedPrize:
	.string "{PLAYER} riceve in premio\n"
	.string "{STR_VAR_1}.$"

@ Unused
SlateportCity_BattleTentLobby_Text_RulesAreListed:
	.string "Ecco le regole dello Scambio Lotta.$"

@ Unused
SlateportCity_BattleTentLobby_Text_ReadWhichHeading:
	.string "Quale argomento vuoi leggere?$"

SlateportCity_BattleTentLobby_Text_ExplainBasicRules:
	.string "In un evento Scambio Lotta puoi\n"
	.string "usare solo tre Pokémon.\p"
	.string "Che tu li prenda a noleggio o li\n"
	.string "scambi, la tua squadra non può avere\l"
	.string "due o più Pokémon uguali.$"

SlateportCity_BattleTentLobby_Text_ExplainSwapPartnerRules:
	.string "Puoi scambiare Pokémon solo con\n"
	.string "l'Allenatore che hai appena battuto.\p"
	.string "Puoi ricevere solo i Pokémon\n"
	.string "usati dall'Allenatore sconfitto.$"

SlateportCity_BattleTentLobby_Text_ExplainSwapNumberRules:
	.string "Dopo ogni lotta vinta, puoi scambiare\n"
	.string "un tuo Pokémon con uno di quelli\l"
	.string "dell'avversario sconfitto.\p"
	.string "Non potrai scambiare Pokémon con\n"
	.string "il terzo Allenatore dell'evento.$"

SlateportCity_BattleTentLobby_Text_ExplainSwapNotes:
	.string "Ci sono due cose importanti da sapere\n"
	.string "quando si scambiano Pokémon.\p"
	.string "Primo: durante lo scambio non puoi\n"
	.string "controllare le statistiche del\l"
	.string "Pokémon che stai per ricevere.\p"
	.string "Secondo: i Pokémon della tua squadra\n"
	.string "sono schierati in sequenza, secondo\l"
	.string "l'ordine in cui li hai noleggiati.\p"
	.string "Questa sequenza non cambia,\n"
	.string "nemmeno dopo uno scambio.$"

SlateportCity_BattleTentLobby_Text_ExplainMonRules:
	.string "I Pokémon della Tenda Lotta di Porto\n"
	.string "Selcepoli sono tutti a noleggio.\p"
	.string "Alcuni sono nati a Hoenn, altri sono\n"
	.string "arrivati da chissà quale Varco!\p"
	.string "Tutti i Pokémon a noleggio sono\n"
	.string "di livello 30.$"

@ Unused
VerdanturfTown_BattleTentLobby_Text_RulesAreListed2:
	.string "Ecco le regole della Tenda Lotta\n"
	.string "di Mentania.$"

@ Unused
VerdanturfTown_BattleTentLobby_Text_ReadWhichHeading:
	.string "Quale argomento vuoi leggere?$"

@ Unused
VerdanturfTown_BattleTentLobby_Text_ExplainBasicRules:
	.string "Alla Tenda Lotta di Mentania, i\n"
	.string "Pokémon devono ragionare e lottare\l"
	.string "da soli.\p"
	.string "A differenza di quelli selvatici, i\n"
	.string "Pokémon che vivono con le persone\l"
	.string "si comportano secondo la loro natura.$"

@ Unused
VerdanturfTown_BattleTentLobby_Text_ExplainNatureRules:
	.string "A seconda della natura, un Pokémon\n"
	.string "può preferire attaccare a ogni costo.\p"
	.string "Un altro può preferire proteggersi\n"
	.string "da qualsiasi pericolo.\p"
	.string "Un altro ancora può divertirsi a\n"
	.string "infastidire o confondere i nemici.\p"
	.string "A seconda della natura, un Pokémon\n"
	.string "avrà delle mosse preferite, che sa\l"
	.string "usare bene.\p"
	.string "Potrebbe anche detestare certe\n"
	.string "mosse che fatica a usare.$"

@ Unused
VerdanturfTown_BattleTentLobby_Text_ExplainMoveRules:
	.string "Ci sono mosse offensive, che\n"
	.string "infliggono danni diretti al nemico.\p"
	.string "Ci sono mosse difensive, usate per\n"
	.string "prepararsi agli attacchi nemici\l"
	.string "o per recuperare PS, e così via.\p"
	.string "E ci sono mosse un po' particolari,\n"
	.string "che indeboliscono i nemici con\l"
	.string "alterazioni di stato come veleno\l"
	.string "e paralisi.\p"
	.string "I Pokémon valuteranno se usare le\n"
	.string "mosse di queste tre categorie.$"

@ Unused
VerdanturfTown_BattleTentLobby_Text_ExplainUnderpoweredRules:
	.string "Senza gli ordini del suo Allenatore,\n"
	.string "un Pokémon potrebbe non riuscire\l"
	.string "a usare bene certe mosse.\p"
	.string "Un Pokémon non è bravo a usare\n"
	.string "le mosse che non gli piacciono.\p"
	.string "Se un Pokémon conosce solo mosse\n"
	.string "non adatte alla sua natura, spesso\l"
	.string "non riuscirà a dare il meglio di sé.$"

@ Unused
VerdanturfTown_BattleTentLobby_Text_ExplainWhenInDangerRules:
	.string "A seconda della natura, un Pokémon\n"
	.string "in difficoltà può iniziare a usare\l"
	.string "mosse non adatte alla sua natura.\p"
	.string "Se un Pokémon si comporta in modo\n"
	.string "strano quando è alle strette,\l"
	.string "osservalo con attenzione.$"

BattleTentLobby_Text_ExplainLevelRules:
	.string "In questa Tenda Lotta, il livello\n"
	.string "degli avversari verrà adattato\l"
	.string "a quello dei tuoi Pokémon.\p"
	.string "Tuttavia, nessun Allenatore che\n"
	.string "affronterai avrà Pokémon sotto\l"
	.string "il livello 30.$"

VerdanturfTown_BattleTentLobby_Text_RulesAreListed:
	.string "Ecco le regole della Tenda Lotta\n"
	.string "di Mentania.$"
