PetalburgCity_Gym_Text_GiveEnigmaBerry:
	.string "Papà: Ah, {PLAYER}. Sei qui.\p"
	.string "Mi è arrivata una Bacca molto rara.\n"
	.string "Dicono sia caduta da un Varco.\p"
	.string "Voglio che la tenga tu.$"

Route104_Text_PlantBerriesInSoilTakeThis:
	.string "Se vedi delle Bacche crescere nel\n"
	.string "terreno soffice, prendile pure.\p"
	.string "Ma ricordati di piantare una Bacca\n"
	.string "nello stesso punto. È buona educazione.\p"
	.string "Tieni, questa te la regalo.$"

Route104_Text_TrainersOftenMakeMonHoldBerries:
	.string "Da come ti muovi, direi che sei un\n"
	.string "Allenatore, giusto?\p"
	.string "Gli Allenatori fanno spesso tenere\n"
	.string "le Bacche ai loro Pokémon.\p"
	.string "Sta a te decidere se coltivarle\n"
	.string "oppure usarle.$"

Route111_Text_WateredPlantsEveryDayTakeBerry:
	.string "Ho annaffiato le piantine ogni giorno\n"
	.string "e sono spuntati tantissimi fiori.\p"
	.string "E mi hanno dato anche un sacco\n"
	.string "di Bacche!\p"
	.string "Ecco qua!\n"
	.string "È tutta tua!$"

Route111_Text_GoingToTryToMakeDifferentColorBerries:
	.string "Mi impegnerò tantissimo per far\n"
	.string "crescere Bacche di tutti i colori.\p"
	.string "Magari anche di un colore mai visto,\n"
	.string "arrivato da oltre un Varco!\p"
	.string "Spero che anche tu ti impegni!$"

Route111_Text_WhatColorBerriesToLookForToday:
	.string "Chissà di che colore saranno le\n"
	.string "Bacche che cercherò oggi?$"

Route114_Text_LoveUsingBerryCrushShareBerry:
	.string "Adoro usare il Macinabacche,\n"
	.string "per questo colleziono Bacche.\p"
	.string "Se ti va, te ne regalo una.$"

Route114_Text_TryBerryCrushWithFriends:
	.string "Dovresti provare il Macinabacche\n"
	.string "insieme ai tuoi amici.$"

Route114_Text_FunToThinkAboutBerries:
	.string "Quale Bacca conviene piantare?\n"
	.string "Meglio usarle o tenerle da parte?\p"
	.string "È divertente pensarci su.$"

Route120_Text_BerriesExpressionOfLoveIsntIt:
	.string "Le Bacche crescono assorbendo\n"
	.string "la luce del sole.\p"
	.string "Noi le aiutiamo a crescere\n"
	.string "annaffiandole con regolarità.\p"
	.string "È un gesto d'amore, non trovi?$"

Route120_Text_YesYouUnderstand:
	.string "Sì, sì.\n"
	.string "Capisci proprio cosa intendo.\p"
	.string "Tieni, prendi questa.$"

Route120_Text_MakeYourOwnImpressions:
	.string "Oh… Ma in fondo è giusto che ognuno\n"
	.string "si faccia la propria idea…\p"
	.string "Tieni, è per te.$"

Route120_Text_BerryIsRareRaiseItWithCare:
	.string "Credo che quella Bacca sia rara.\n"
	.string "Spero che la coltiverai con amore.$"

Route120_Text_IllGetMoreBerriesFromBerryMaster:
	.string "Andrò a farmi dare altre Bacche\n"
	.string "da Bacco Bacchini, il gran maestro!$"

LilycoveCity_Text_BerrySuitsYou:
	.string "A conti fatti…\p"
	.string "Come l'abito si addice a me,\n"
	.string "la brezza frizzante si addice al mare.\p"
	.string "E a te, una Bacca si addice\n"
	.string "alla perfezione…\p"
	.string "Come mai, secondo te?$"

LilycoveCity_Text_BecauseYoureTrainer:
	.string "A conti fatti…\p"
	.string "È perché sei un Allenatore!$"

LilycoveCity_Text_PokeblocksSuitPokemon:
	.string "A conti fatti…\p"
	.string "Come a me si addice una dignitosa\n"
	.string "semplicità, ai Pokémon si addicono\l"
	.string "le Pokémelle.$"

Route123_BerryMastersHouse_Text_YoureDeservingOfBerry:
	.string "Chiamami pure Bacco Bacchini,\n"
	.string "il maestro delle Bacche!\p"
	.string "Sogno di riempire il mondo di fiori\n"
	.string "meravigliosi, perciò coltivo Bacche\l"
	.string "e le regalo a tutti quanti.\p"
	.string "E se i Varchi portano davvero ad\n"
	.string "altri mondi, farò fiorire anche quelli!\p"
	.string "Tu te ne meriti proprio una!$"

Route123_BerryMastersHouse_Text_WhyBeStingyTakeAnother:
	.string "Perché fare il tirchio?\n"
	.string "Prendine un'altra!$"

Route123_BerryMastersHouse_Text_VisitPrettyPetalFlowerShop:
	.string "Fai un salto al Fiorista Bel Petalo,\n"
	.string "vicino a Ferrugipoli.\p"
	.string "Che i fiori riempiano il mondo!$"

Route123_BerryMastersHouse_Text_DoneForToday:
	.string "Per oggi ho finito.\n"
	.string "Torna a trovarmi un altro giorno.\p"
	.string "Che i fiori riempiano il mondo!$"

Route123_BerryMastersHouse_Text_HeardAGoodSayingLately:
	.string "Nessuno al mondo coltiva le Bacche\n"
	.string "come mio marito, sai?\p"
	.string "Sono proprio fiera di lui, eh sì.\p"
	.string "A proposito, giovanotto, hai sentito\n"
	.string "qualche bel detto, di recente?$"

Route123_BerryMastersHouse_Text_InspirationalTakeThis:
	.string "Ah! Che detto straordinario!\n"
	.string "Davvero illuminante!\p"
	.string "Voglio che tu abbia questa.$"

Route123_BerryMastersHouse_Text_GoodSayingTakeThis:
	.string "Oh! Proprio un bel detto.\n"
	.string "Sei davvero in gamba.\p"
	.string "Voglio che tu abbia questa.$"

Route123_BerryMastersHouse_Text_JoyNeverGoesOutOfMyLife:
	.string "I nostri quattro nipotini diventeranno\n"
	.string "ancora più bravi di mio marito.\p"
	.string "La gioia non mi abbandona mai!$"

Route123_BerryMastersHouse_Text_Ah:
	.string "Ah…$"

Route104_PrettyPetalFlowerShop_Text_ThisIsPrettyPetalFlowerShop:
	.string "Ciao!\p"
	.string "Questo è il Fiorista Bel Petalo.\n"
	.string "Copriamo il mondo di fiori!$"

Route104_PrettyPetalFlowerShop_Text_LearnAboutBerries:
	.string "{PLAYER}{KUN}, vuoi sapere qualcosa\n"
	.string "sulle Bacche?$"

Route104_PrettyPetalFlowerShop_Text_IntroLearnAboutBerries:
	.string "Come ti chiami?\p"
	.string "{PLAYER}{KUN}.\n"
	.string "Che bel nome!\p"
	.string "{PLAYER}{KUN}, vuoi sapere qualcosa\n"
	.string "sulle Bacche?$"

Route104_PrettyPetalFlowerShop_Text_BerriesExplanation:
	.string "Le Bacche nascono da piante che\n"
	.string "crescono solo nel terreno soffice.\p"
	.string "Se raccogli delle Bacche, ricordati\n"
	.string "di ripiantarne una nel terreno soffice.\p"
	.string "Una Bacca piantata germoglia presto,\n"
	.string "cresce, fa dei fiori bellissimi\l"
	.string "e poi produce altre Bacche.\p"
	.string "Voglio vedere il mondo intero\n"
	.string "pieno di fiori meravigliosi.\l"
	.string "È il mio sogno.\p"
	.string "Aiutami, {PLAYER}{KUN}! Pianta Bacche\n"
	.string "e porta più fiori nel mondo.$"

Route104_PrettyPetalFlowerShop_Text_FlowersBringHappiness:
	.string "I fiori rendono le persone\n"
	.string "così felici, non trovi?$"

Route104_PrettyPetalFlowerShop_Text_YouCanHaveThis:
	.string "Ciao!\p"
	.string "Più attenzioni dai ai fiori,\n"
	.string "più belli sbocciano.\p"
	.string "Sono sicura che ti piacerà curarli.\n"
	.string "Tieni, questo è per te.$"

Route104_PrettyPetalFlowerShop_Text_WailmerPailExplanation:
	.string "Mentre le piante di Bacche crescono,\n"
	.string "annaffiale con il Vaso Wailmer.\p"
	.string "Ah, un'altra cosa.\p"
	.string "Se non raccogli le Bacche per un po',\n"
	.string "cadranno a terra.\l"
	.string "Ma poi germoglieranno di nuovo.\p"
	.string "Non è fantastico?\n"
	.string "È come se avessero voglia di vivere.$"

Route104_PrettyPetalFlowerShop_Text_ImGrowingFlowers:
	.string "Voglio essere come le mie sorelle\n"
	.string "grandi. Anch'io coltivo i fiori!\p"
	.string "Ecco qua!\n"
	.string "È per te!$"

Route104_PrettyPetalFlowerShop_Text_MachineMixesBerries:
	.string "Puoi piantare una Bacca e farla\n"
	.string "crescere, o farla tenere a un Pokémon.\p"
	.string "Ma adesso c'è anche una macchina che\n"
	.string "mescola Bacche diverse e ci fa\l"
	.string "delle caramelle per Pokémon.\p"
	.string "Anch'io voglio le caramelle!$"

SootopolisCity_Text_NameIsKiriHaveOneOfThese:
	.string "Ciao, come ti chiami?\p"
	.string "… … …  … … …  … … …\n"
	.string "Ok. Che bello!\p"
	.string "Io mi chiamo Kira.\p"
	.string "Mamma e papà mi hanno chiamata così\n"
	.string "perché crescessi sana e di buon cuore.\l"
	.string "È quello che desideravano.\p"
	.string "Tieni, prendine una.$"

SootopolisCity_Text_GiveYouThisBerryToo:
	.string "Kira ti regala anche questa Bacca!\n"
	.string "Mi piace tantissimo!$"

SootopolisCity_Text_WhatKindOfWishInYourName:
	.string "Chissà quale desiderio è nascosto\n"
	.string "dentro il tuo nome.$"

SootopolisCity_Text_LikeSeasonBornIn:
	.string "Primavera, estate, autunno e inverno.\p"
	.string "Se nasci in primavera, ti piace la\n"
	.string "primavera? E se nasci d'estate,\l"
	.string "ti piace l'estate?$"

SootopolisCity_Text_ThenILoveAutumn:
	.string "Allora Kira è nata in autunno,\n"
	.string "e quindi adoro l'autunno!\p"
	.string "Tu che stagione preferisci?$"

SootopolisCity_Text_OhDoesntMatter:
	.string "Oh…\n"
	.string "Non importa…\p"
	.string "Ci sono così tante cose che vorrei\n"
	.string "sapere…$"
