gText_Birch_Welcome::
	.string "Ciao! Scusa se ti ho fatto aspettare!\p"
	.string "Ero sul campo, e guarda qua… sono\n"
	.string "ancora tutto infangato! Ah ah!\p"
	.string "Benvenuto nel mondo dei Pokémon!\p"
	.string "Mi chiamo Birch.\p"
	.string "Ma tutti mi chiamano semplicemente\n"
	.string "il Professore dei Pokémon.\p"
	.string "$"

gText_Birch_Pokemon::
	.string "Questo è ciò che chiamiamo “Pokémon”.\p"
	.string "\n"
	.string "$"

gText_Birch_MainSpeech::
	.string "Questo mondo è abitato da creature\n"
	.string "che chiamiamo Pokémon.\p"
	.string "Noi umani viviamo insieme a loro:\n"
	.string "a volte sono amici con cui giocare,\l"
	.string "a volte preziosi compagni di lavoro.\p"
	.string "E a volte facciamo squadra con loro\n"
	.string "per lottare contro altri come noi.\p"
	.string "Ultimamente, però, questo mondo è\n"
	.string "pieno anche di Pokémon che vengono…\l"
	.string "da altri mondi!\p"
	.string "Ogni tanto l'aria si strappa e si\n"
	.string "apre un Varco, uno squarcio di luce.\p"
	.string "Quando si richiude, qualcuno è\n"
	.string "arrivato di qua. Straordinario, no?\p"
	.string "Per quanto ci siano vicini, dei\n"
	.string "Pokémon sappiamo ancora poco.\p"
	.string "I loro segreti sono tantissimi…\n"
	.string "e i Varchi li moltiplicano!\p"
	.string "Per svelare questi misteri, faccio\n"
	.string "ricerca sul campo, giorno e notte.\l"
	.string "È il mio lavoro!\p"
	.string "$"

gText_Birch_AndYouAre::
	.string "E tu chi sei?$"

gText_Birch_BoyOrGirl::
	.string "Sei un ragazzo?\n"
	.string "O sei una ragazza?$"

gText_Birch_WhatsYourName::
	.string "Piacere!\n"
	.string "Come ti chiami?$"

gText_Birch_SoItsPlayer::
	.string "Quindi ti chiami {PLAYER}{KUN}?$"

gText_Birch_YourePlayer::
	.string "Ah, ma certo!\p"
	.string "Tu sei {PLAYER}{KUN}! Il figlio di Norman\n"
	.string "che si trasferisce ad Albanova,\l"
	.string "il mio paese. Ora ho capito!\p"
	.string "$"

gText_Birch_AreYouReady::
	.string "Bene, sei pronto?\p"
	.string "La tua avventura personale sta\n"
	.string "per cominciare.\p"
	.string "Dietro ogni Varco c'è una storia\n"
	.string "che aspetta qualcuno…\l"
	.string "Chissà, magari proprio te!\p"
	.string "Fatti coraggio e tuffati nel mondo\n"
	.string "dei Pokémon, tra sogni, avventure\l"
	.string "e amicizie che ti aspettano!\p"
	.string "Bene, ci vediamo più tardi.\n"
	.string "Vieni a trovarmi nel mio Laboratorio!\p"
	.string "$"
