BerryBlender_Text_BlendWithTheBlendMaster:
	.string "Maestro Frullatore: Ebbene sì!\n"
	.string "Il Maestro Frullatore sono io!\p"
	.string "Frulla con me, e vedrai coi tuoi occhi\n"
	.string "di che maestria sono capace!$"

BerryBlender_Text_SeeMyMasteryInAction:
	.string "Maestro Frullatore: Mmm! Dunque vuoi\n"
	.string "vedere la mia maestria all'opera?$"

BerryBlender_Text_TooBusyNowIsee:
	.string "Mmm!\p"
	.string "Capisco, ora sei troppo indaffarato!\p"
	.string "Ma niente paura!\n"
	.string "Io resterò qui tutto il giorno!\l"
	.string "Sbriga le tue faccende e torna!$"

BerryBlender_Text_BlendMasterNoBerries:
	.string "Mmm!\p"
	.string "Non hai nemmeno una Bacca!\p"
	.string "Io resterò qui tutto il giorno!\n"
	.string "Torna presto con qualche Bacca!$"

BerryBlender_Text_BlendMasterKnowHowToMakePokeblocks:
	.string "Ma certo!\n"
	.string "Ma certo!\p"
	.string "A proposito…\n"
	.string "Sai come si preparano le Pokémelle\l"
	.string "frullando le Bacche?$"

BerryBlender_Text_BlendMasterExplainBerryBlending:
	.string "Mmm!\p"
	.string "Ah, ma è semplicissimo!\p"
	.string "Quando la freccia del Frullabacche\n"
	.string "passa sul tuo segno, premi il tasto A.\p"
	.string "Non devi fare altro.\p"
	.string "Quando vedrai con che precisione\n"
	.string "premo il tasto A, capirai.$"

BerryBlender_Text_BlendMasterLetsBerryBlender:
	.string "Perfetto!\p"
	.string "Allora cominciamo!\p"
	.string "Tutti insieme al Maestro Frullatore…\n"
	.string "via col Frullabacche!$"

BerryBlender_Text_BlendMasterNoPokeblockCase:
	.string "Mmm!\p"
	.string "A quanto pare non hai ancora\n"
	.string "un Portapokémelle!\p"
	.string "Io resterò qui tutto il giorno!\n"
	.string "Procurati un Portapokémelle e torna!$"

BerryBlender_Text_BlendMasterPokeblockCaseFull:
	.string "Mmm!\p"
	.string "Il tuo Portapokémelle è pieno!\p"
	.string "Io resterò qui tutto il giorno!\n"
	.string "Usa qualche Pokémella e torna!$"

BerryBlender_Text_WhoaAwesome:
	.string "Wow!\n"
	.string "Fantastico!$"

BerryBlender_Text_WickedlyFast:
	.string "Che velocità pazzesca!$"

BerryBlender_Text_WhatAnExpert:
	.string "Che mano da esperto!$"

BerryBlender_Text_MadeAmazingPokeblocksWithMaster:
	.string "Quando ho frullato col Maestro,\n"
	.string "abbiamo fatto Pokémelle incredibili!$"

BerryBlender_Text_QualitiesOfBlendMaster:
	.string "Occhi che seguono la freccia con\n"
	.string "la precisione di una macchina…\p"
	.string "Una mano che preme il tasto A\n"
	.string "con la puntualità di un orologio…\p"
	.string "Sono queste le doti che fanno\n"
	.string "grande il Maestro Frullatore.$"

BerryBlender_Text_MasterWorksOnSkillsInMountains:
	.string "Dicono che il Maestro Frullatore\n"
	.string "si alleni in segreto tra i monti.\p"
	.string "Ogni tanto scende a Porto Alghepoli\n"
	.string "e frulla Bacche tutto il giorno.\p"
	.string "C'è chi giura che usi perfino\n"
	.string "Bacche cadute dai Varchi!$"
