CableClub_Text_WelcomeWhichCableClubService:
	.string "Benvenuto al Club Cavo Pokémon.\p"
	.string "Quale dei nostri servizi desideri\n"
	.string "utilizzare?$"

CableClub_Text_WhichService:
	.string "Quale dei nostri servizi desideri\n"
	.string "utilizzare?$"

CableClub_Text_TradeUsingLinkCable::
	.string "Scambia Pokémon con un altro giocatore\n"
	.string "tramite il Cavo Game Link GBA.$"

CableClub_Text_BattleUsingLinkCable::
	.string "Lotta contro un altro Allenatore\n"
	.string "tramite il Cavo Game Link GBA.$"

CableClub_Text_RecordCornerUsingLinkCable::
	.string "Usa l'Angolo Record con altri\n"
	.string "tramite il Cavo Game Link GBA.$"

@ Unused
CableClub_Text_CloseThisMenu:
	.string "Chiudi questo menu.$"

CableClub_Text_NeedTwoMonsForDoubleBattle:
	.string "Per una Lotta Doppia devi avere\n"
	.string "almeno due Pokémon.$"

CableClub_Text_NeedTwoMonsToTrade:
	.string "Per fare scambi devi avere con te\n"
	.string "almeno due Pokémon.$"

CableClub_Text_CantTradeEnigmaBerry:
	.string "Un Pokémon che tiene la Bacca\n"
	.string "{STR_VAR_1} non può essere scambiato.$"

gText_PleaseWaitForLink::
	.string "Attendi, prego.\n"
	.string "… … Pulsante B: Annulla$"

gText_ConfirmLinkWhenPlayersReady::
	.string "Quando tutti i giocatori sono pronti…\n"
	.string "Pulsante A: Conferma\l"
	.string "Pulsante B: Annulla$"

gText_ConfirmStartLinkWithXPlayers::
	.string "Collegamento con {STR_VAR_1} giocatori.\n"
	.string "Pulsante A: Conferma\l"
	.string "Pulsante B: Annulla$"

gText_AwaitingLinkup::
	.string "In attesa di collegamento…\n"
	.string "… … Pulsante B: Annulla$"

@ Unused
CableClub_Text_OkayToSaveProgress::
	.string "Prima di collegarti devi salvare\n"
	.string "i tuoi progressi. Vuoi salvare?$"

CableClub_Text_PleaseEnter:
	.string "Prego, entra pure.$"

CableClub_Text_DirectYouToYourRoom:
	.string "Ora ti accompagno nella tua stanza.$"

Text_SomeoneIsNotReadyToLink:
	.string "Qualcuno non è pronto a collegarsi.\p"
	.string "Torna quando tutti avranno finito\n"
	.string "di prepararsi.$"

Text_LinkErrorPleaseReset:
	.string "Spiacenti, errore di collegamento…\n"
	.string "Riavvia il gioco e riprova.$"

Text_PlayersMadeDifferentSelections:
	.string "Sembra che i partecipanti abbiano\n"
	.string "fatto scelte diverse.$"

CableClub_Text_PleaseVisitAgain:
	.string "Torna a trovarci presto!$"

CableClub_Text_IncorrectNumberOfParticipants:
	.string "Il numero dei partecipanti non\n"
	.string "è corretto.$"

CableClub_Text_CantSingleBattleWithXPlayers:
	.string "La modalità Lotta Singola non si può\n"
	.string "giocare in {STR_VAR_1} giocatori.$"

CableClub_Text_CantDoubleBattleWithXPlayers:
	.string "La modalità Lotta Doppia non si può\n"
	.string "giocare in {STR_VAR_1} giocatori.$"

CableClub_Text_NeedFourPlayers:
	.string "Per questa modalità di lotta servono\n"
	.string "quattro giocatori.$"

CableClub_Text_PleaseConfirmNumberAndRestart:
	.string "Controlla il numero dei giocatori\n"
	.string "e ricomincia da capo.$"

Text_TerminateLinkConfirmation:
	.string "Se lasci la stanza, il collegamento\n"
	.string "verrà interrotto. Va bene?$"

Text_TerminateLinkPleaseWait:
	.string "Interruzione del collegamento…\n"
	.string "Ora verrai accompagnato fuori\l"
	.string "dalla stanza. Attendi, prego.$"

CableClub_Text_TooBusyToNotice:
	.string "Questo Allenatore è troppo\n"
	.string "impegnato per accorgersi di te…$"

CableClub_Text_GotToLookAtTrainerCard:
	.string "Grande! Hai sbirciato la Scheda\n"
	.string "Allenatore di {STR_VAR_1}!$"

CableClub_Text_GotToLookAtColoredTrainerCard:
	.string "Grande! Hai sbirciato la Scheda\n"
	.string "Allenatore di {STR_VAR_1}!\p"
	.string "È una Scheda {STR_VAR_2}!$"

BattleColosseum_2P_Text_TakePlaceStartBattle:
	.string "Prendi posto e dai inizio\n"
	.string "alla lotta.$"

TradeCenter_Text_TakeSeatStartTrade:
	.string "Accomodati e dai inizio\n"
	.string "allo scambio.$"

RecordCorner_Text_ThanksForComing:
	.string "Grazie della visita.$"

CableClub_Text_TrainerCardDataOverwritten:
	.string "I dati della Scheda Allenatore\n"
	.string "verranno sovrascritti.$"

CableClub_Text_HopeToSeeYouAgain:
	.string "Speriamo di rivederti presto!$"

CableClub_Text_NotSetUpForFarAwayRegion:
	.string "Mi dispiace davvero tanto.\p"
	.string "Non siamo ancora attrezzati per gli\n"
	.string "scambi con gli Allenatori che vivono\l"
	.string "in un'altra regione…\p"
	.string "Pare che la Soglia blocchi perfino\n"
	.string "i segnali. Ma un giorno, chissà…$"

CableClub_Text_OtherTrainerNotReady:
	.string "L'altro Allenatore non è pronto.$"

CableClub_Text_YouHaveAMonThatCantBeTaken:
	.string "Hai almeno un Pokémon che non\n"
	.string "puoi portare con te.$"

RecordCorner_Text_TakeSeatAndWait:
	.string "Accomodati e attendi, prego.$"

RecordCorner_Text_PlayerSentOverOneX:
	.string "{STR_VAR_1} ti ha inviato\n"
	.string "un regalo: {STR_VAR_2}!$"

CableClub_Text_CantMixWithJapaneseGame:
	.string "Spiacenti, errore di trasmissione.\p"
	.string "Non puoi mescolare i record con\n"
	.string "Rubino o Zaffiro giapponesi.\p"
	.string "Inoltre, non puoi mescolare i record\n"
	.string "con Smeraldo giapponese e Rubino o\l"
	.string "Zaffiro esteri nello stesso momento.$"

CableClub_Text_AdapterNotConnected:
	.string "L'Adattatore Wireless non è\n"
	.string "collegato correttamente.$"

CableClub_Text_ParticipantsStepUpToCounter:
	.string "I partecipanti sono pregati di\n"
	.string "avvicinarsi al bancone.$"

@ Unused
CableClub_Text_Hello:
	.string "Ciao!$"

@ Unused
CableClub_Text_PleaseWait:
	.string "Attendi, prego.$"

CableClub_Text_YouMayTradeHere::
	.string "Qui puoi scambiare i tuoi Pokémon\n"
	.string "con un altro Allenatore.$"

CableClub_Text_YouMayBattleHere::
	.string "Qui puoi lottare contro i tuoi\n"
	.string "amici.$"

CableClub_Text_CanMakeBerryPowder::
	.string "Da due a cinque Allenatori possono\n"
	.string "creare insieme Polvere di Bacche.$"

CableClub_Text_CanMixRecords::
	.string "Da due a quattro giocatori possono\n"
	.string "mescolare i loro record.$"

@ Unused
CableClub_Text_GuideToVariousServices:
	.string "Una guida ai vari servizi\n"
	.string "del Club Wireless.$"

CableClub_Text_CancelSelectedItem::
	.string "Annulla la voce di menu scelta.$"

@ Unused
CableClub_Text_WhichBattleMode:
	.string "Quale modalità di lotta preferisci?$"

@ Unused
CableClub_Text_ReturnsToPreviousStep:
	.string "Torna al passaggio precedente.$"

CableClub_Text_NeedBerryForBerryCrush:
	.string "Per usare il servizio Pestabacche\n"
	.string "devi avere almeno una Bacca.$"

CableClub_Text_NeedTwoMonsForUnionRoom:
	.string "Per entrare nella Sala Unione devi\n"
	.string "avere almeno due Pokémon.$"

CableClub_Text_NoEnigmaBerryInUnionRoom:
	.string "I Pokémon con la Bacca {STR_VAR_1}\n"
	.string "non possono entrare nella Sala Unione.$"

CableClub_Text_UnionRoomAdapterNotConnected:
	.string "Questa è la Sala Unione del Club\n"
	.string "Wireless Pokémon.\p"
	.string "Purtroppo il tuo Adattatore Wireless\n"
	.string "non è collegato correttamente.\p"
	.string "Torna pure a trovarci!$"

@ Unused
CableClub_Text_OhExcuseMe:
	.string "Oh…\n"
	.string "Chiedo scusa!$"

CableClub_Text_PlayerIsWaiting:
	.string "Sembra che {STR_VAR_1} stia giocando\n"
	.string "proprio adesso.\l"
	.string "Dacci dentro!$"

MossdeepCity_GameCorner_1F_Text_DescribeWhichGame:
	.string "Se vuoi, posso spiegarti\n"
	.string "le regole dei giochi.\p"
	.string "Di quale gioco vuoi sapere di più?$"

MossdeepCity_GameCorner_1F_Text_PokemonJumpInfo:
	.string "“Salto Pokémon”\p"
	.string "Fai saltare al tuo Pokémon la corda\n"
	.string "di Frustata premendo il tasto A.\p"
	.string "Possono partecipare solo Pokémon\n"
	.string "piccoli, alti circa 70 cm o meno.\p"
	.string "I Pokémon che sanno solo nuotare,\n"
	.string "scavare o volare non sono bravi\l"
	.string "a saltare.\p"
	.string "Per questo, quei Pokémon non\n"
	.string "possono partecipare.\p"
	.string "Se tutti saltano a tempo, succedono\n"
	.string "cose belle!$"

MossdeepCity_GameCorner_1F_Text_DodrioBerryPickingInfo:
	.string "“Raccolta Bacche Dodrio”\p"
	.string "Comanda le tre teste di Dodrio per\n"
	.string "afferrare le Bacche che cadono.\p"
	.string "Premi destra, su o sinistra sulla\n"
	.string "pulsantiera {PLUS} per muovere le teste.\p"
	.string "Per giocare devi avere\n"
	.string "un Dodrio.$"

MossdeepCity_GameCorner_1F_Text_TalkToOldManToPlay:
	.string "Se vuoi giocare, parlane con\n"
	.string "il signore qui accanto a me.$"

MossdeepCity_GameCorner_1F_Text_WelcomeCanYouWait:
	.string "Ciao, benvenuto!\n"
	.string "Sei qui per giocare tramite la\l"
	.string "Comunicazione Wireless?\p"
	.string "Puoi aspettare un attimino?$"

MossdeepCity_GameCorner_1F_Text_ComeAgain:
	.string "Va bene, torna quando vuoi!$"

MossdeepCity_GameCorner_1F_Text_AdapterNotConnected:
	.string "L'Adattatore Wireless non è collegato.\n"
	.string "Torna quando l'avrai collegato!$"

MossdeepCity_GameCorner_1F_Text_PlayWhichGame:
	.string "Bene, a quale gioco vuoi\n"
	.string "giocare?$"

MossdeepCity_GameCorner_1F_Text_EnterWhichPokemon:
	.string "Quale Pokémon vuoi far\n"
	.string "partecipare?$"

MossdeepCity_GameCorner_1F_Text_AllGoodToGo:
	.string "Perfetto, è tutto pronto.\n"
	.string "Non farti battere dagli altri!$"

@ Unused
MossdeepCity_GameCorner_1F_Text_LeavingDoComeAgain:
	.string "Te ne vai già?\n"
	.string "Torna a trovarci!$"

MossdeepCity_GameCorner_1F_Text_ExplainRequiredMon:
	.string "Sembra che tu non abbia nessun\n"
	.string "Pokémon che possa partecipare…\p"
	.string "Vuoi che ti spieghi quali Pokémon\n"
	.string "possono partecipare?$"

MossdeepCity_GameCorner_1F_Text_ShortJumpingPokemonAllowed:
	.string "Al “Salto Pokémon” possono\n"
	.string "partecipare i Pokémon alti circa\l"
	.string "70 cm o meno.\p"
	.string "Non possono partecipare i Pokémon\n"
	.string "che non sanno saltare.\p"
	.string "Sai, tipo quelli che sanno solo\n"
	.string "nuotare, scavare o volare.\p"
	.string "Ecco, è tutto quello che devi sapere.$"

MossdeepCity_GameCorner_1F_Text_OnlyDodrioAllowed:
	.string "Alla Raccolta Bacche Dodrio può\n"
	.string "partecipare solo Dodrio.$"

@ Unused
MossdeepCity_GameCorner_1F_Text_RetryPlease:
	.string "Potresti ricominciare tutto\n"
	.string "da capo, per favore?$"

CableClub_Text_WelcomeWhichDirectCornerRoom:
	.string "Benvenuto nell'Angolo Diretto del\n"
	.string "Club Wireless Pokémon.\p"
	.string "Qui puoi interagire direttamente\n"
	.string "con i tuoi amici.\p"
	.string "In quale stanza desideri\n"
	.string "entrare?$"

CableClub_Text_TradePokemon:
	.string "Vuoi scambiare dei Pokémon?$"

CableClub_Text_PlayWhichBattleMode:
	.string "Quale modalità di lotta vuoi\n"
	.string "giocare?$"

CableClub_Text_AccessRecordCorner:
	.string "Vuoi accedere\n"
	.string "all'Angolo Record?$"

CableClub_Text_UseBerryCrush:
	.string "Vuoi usare il sistema\n"
	.string "Pestabacche?$"

CableClub_Text_ExplainBattleModes:
	.string "Ci sono tre modalità di lotta.\p"
	.string "La Lotta Singola è per due\n"
	.string "Allenatori con uno o più Pokémon.\p"
	.string "Ogni Allenatore può avere in campo\n"
	.string "un solo Pokémon alla volta.\p"
	.string "La Lotta Doppia è per due\n"
	.string "Allenatori con due o più Pokémon.\p"
	.string "Ogni Allenatore manda in campo\n"
	.string "due Pokémon alla volta.\p"
	.string "La Lotta Multipla è per quattro\n"
	.string "Allenatori con uno o più Pokémon.\p"
	.string "Ogni Allenatore può avere in campo\n"
	.string "un solo Pokémon alla volta.$"

CableClub_Text_ChooseGroupLeaderOfTwo:
	.string "Decidete chi di voi due sarà\n"
	.string "il Capogruppo.\p"
	.string "L'altro giocatore dovrà poi\n"
	.string "scegliere “Unisciti al gruppo”.$"

CableClub_Text_ChooseGroupLeaderOfFour:
	.string "Decidete chi di voi quattro sarà\n"
	.string "il Capogruppo.\p"
	.string "Gli altri giocatori dovranno poi\n"
	.string "scegliere “Unisciti al gruppo”.$"

CableClub_Text_ChooseGroupLeader:
	.string "Decidete chi di voi sarà\n"
	.string "il Capogruppo.\p"
	.string "Gli altri giocatori dovranno poi\n"
	.string "scegliere “Unisciti al gruppo”.$"

CableClub_Text_WelcomeUnionRoomEnter:
	.string "Benvenuto nella Sala Unione del\n"
	.string "Club Wireless Pokémon.\p"
	.string "Qui puoi interagire direttamente\n"
	.string "con altri Allenatori, anche con\l"
	.string "chi non conosci ancora.\p"
	.string "Vuoi entrare nella Sala?$"

CableClub_Text_UnionRoomInfo:
	.string "Nella Sala Unione troverai gli\n"
	.string "Allenatori vicini a te che sono\l"
	.string "entrati anche loro nella Sala.\p"
	.string "Qui puoi fare tante cose, come\n"
	.string "per esempio scambiarvi un saluto.\p"
	.string "Puoi schierare due Pokémon fino al\n"
	.string "livello 30 per una lotta uno contro uno.\p"
	.string "Puoi partecipare a una chat\n"
	.string "con due fino a cinque persone.\p"
	.string "Oppure puoi registrare un Pokémon\n"
	.string "da scambiare.\p"
	.string "Vuoi entrare nella Sala?$"

CableClub_Text_EnjoyUnionRoom:
	.string "Spero che ti divertirai nella\n"
	.string "Sala Unione.$"

CableClub_Text_FirstTimeRightThisWay:
	.string "Ciao!\n"
	.string "Mi chiamo Teala.\p"
	.string "Dev'essere la prima volta che\n"
	.string "sali quassù.\p"
	.string "Ti mostrerò come funziona il sistema\n"
	.string "di Comunicazione Wireless.\p"
	.string "Prima, però, devo mostrarti questo\n"
	.string "piano del Centro Pokémon.\p"
	.string "Da questa parte, prego.$"

CableClub_Text_ExplainWirelessClubFirstTime:
	.string "All'ultimo piano ci sono due\n"
	.string "stanze.\p"
	.string "La prima è la stanza a sinistra:\n"
	.string "la Sala Unione.\p"
	.string "Lì puoi collegarti con gli Allenatori\n"
	.string "vicini a te che sono entrati anche\l"
	.string "loro nella Sala Unione.\p"
	.string "Con loro puoi fare tante cose:\n"
	.string "chattare, lottare e scambiare.\p"
	.string "La seconda, la stanza a destra,\n"
	.string "è l'Angolo Diretto.\p"
	.string "Lì puoi scambiare Pokémon o lottare\n"
	.string "con i tuoi amici.\p"
	.string "Se l'Adattatore Wireless non è\n"
	.string "collegato, puoi comunque collegarti\l"
	.string "con un Cavo Game Link GBA.\p"
	.string "In quel caso, devi andare\n"
	.string "all'Angolo Diretto.\p"
	.string "Spero che il sistema di Comunicazione\n"
	.string "Wireless ti piaccia!$"

CableClub_Text_AskAboutLinking:
	.string "Ciao, {PLAYER}!\p"
	.string "Sono io, Teala, l'addetta al piano\n"
	.string "superiore del Centro Pokémon.\p"
	.string "Volevi chiedermi qualcosa\n"
	.string "sui collegamenti?$"

CableClub_Text_ExplainWirelessClub:
	.string "Ti spiego come funziona il\n"
	.string "Club Wireless Pokémon.\p"
	.string "Qui, all'ultimo piano, ci sono\n"
	.string "due stanze.\p"
	.string "La prima è la stanza a sinistra:\n"
	.string "la Sala Unione.\p"
	.string "Lì puoi collegarti con gli Allenatori\n"
	.string "vicini a te che sono entrati anche\l"
	.string "loro nella Sala Unione.\p"
	.string "Con loro puoi fare tante cose:\n"
	.string "chattare, lottare e scambiare.\p"
	.string "La seconda, la stanza a destra,\n"
	.string "è l'Angolo Diretto.\p"
	.string "Lì puoi scambiare Pokémon o lottare\n"
	.string "con i tuoi amici.\p"
	.string "A volte potresti non riuscire a\n"
	.string "trovare i tuoi amici nella Sala\l"
	.string "Unione o nell'Angolo Diretto.\p"
	.string "In quel caso, prova ad avvicinarti\n"
	.string "ai tuoi amici.\p"
	.string "Se l'Adattatore Wireless non è\n"
	.string "collegato, puoi comunque collegarti\l"
	.string "con un Cavo Game Link GBA.\p"
	.string "In quel caso, devi andare\n"
	.string "all'Angolo Diretto.\p"
	.string "Spero che il sistema di Comunicazione\n"
	.string "Wireless ti piaccia!$"

CableClub_Text_HopeYouEnjoyWirelessSystem:
	.string "Spero che il sistema di Comunicazione\n"
	.string "Wireless ti piaccia!$"
