Text_PictureBookShelf:
	.string "Una serie di libri illustrati sui Pokémon.$"

Text_BookShelf:
	.string "È pieno di libri di ogni genere.$"

Text_PokemonCenterBookShelf:
	.string "Riviste sui Pokémon!\n"
	.string "PokéAmici…\p"
	.string "Il Grande Manuale dei Pokémon…\n"
	.string "Varchi: istruzioni per l'uso…$"

Text_Vase:
	.string "Questo vaso sembra costoso…\n"
	.string "Diamo una sbirciatina dentro…\p"
	.string "Niente, è vuoto.$"

Text_EmptyTrashCan:
	.string "È vuoto.$"

Text_ShopShelf:
	.string "Gli scaffali traboccano di articoli\n"
	.string "a tema Pokémon di ogni tipo.$"

Text_Blueprint:
	.string "Una specie di progetto tecnico?\n"
	.string "È troppo complicato!$"
