EventTicket_Text_ShowOldSeaMap:
	.string "Il traghetto per Porto Selcepoli è…\p"
	.string "Come, scusa?\n"
	.string "Vuoi navigare fin qui, su questa mappa?\p"
	.string "Conosco qualcuno che può aiutarti\n"
	.string "meglio di me. Aspetta un momento.$"

EventTicket_Text_ThatPass:
	.string "Il traghetto per Porto Selcepoli è…\p"
	.string "Oh?\n"
	.string "Quel biglietto…$"

EventTicket_Text_ShowEonTicket:
	.string "Ehilà, giovanotto! Sei tu che hai\n"
	.string "quel biglietto così strano?\p"
	.string "Te lo dico io: vuoi arrivare a un\n"
	.string "fazzoletto d'isola sperduto a sud.\p"
	.string "Chissà cosa troveremo, una volta\n"
	.string "arrivati, eh già.\l"
	.string "Mi vengono i brividi fino alla chiglia!\p"
	.string "Tutti a bordo!$"

EventTicket_Text_SouthernIslandSailBack:
	.string "Ehi, giovanotto, su quest'isoletta\n"
	.string "non c'è niente da vedere né da fare.\p"
	.string "Che ne dici, torniamo a Porto\n"
	.string "Alghepoli?$"

EventTicket_Text_SailHome:
	.string "Bene, allora!\n"
	.string "Si torna a casa!$"

EventTicket_Text_AsYouLike:
	.string "Come preferisci, giovanotto.$"

SouthernIsland_Interior_Text_Sign:
	.string "“Ogni sogno è soltanto un'altra realtà.\n"
	.string "Non dimenticarlo mai…”$"

SouthernIsland_Exterior_Text_Sign:
	.string "“Chi sente i ricordi svanire cerca\n"
	.string "di inciderli nel proprio cuore…”$"
