LilycoveCity_DepartmentStore_1F_Text_LotteryCornerDrawTicket:
	.string "Benvenuto all'Angolo Lotteria Pokémon!\p"
	.string "Ogni cliente del Centro Commerciale\n"
	.string "può pescare un Biglietto del Pokélotto.\p"
	.string "Se il numero del biglietto coincide\n"
	.string "con il numero ID di un tuo Pokémon,\l"
	.string "vincerai un regalo favoloso!\p"
	.string "Vuoi pescare un Biglietto\n"
	.string "del Pokélotto?$"

LilycoveCity_DepartmentStore_1F_Text_ComeBackTomorrow:
	.string "Un biglietto al giorno! Torna domani.$"

LilycoveCity_DepartmentStore_1F_Text_PleaseVisitAgain:
	.string "Torna a trovarci quando vuoi!$"

LilycoveCity_DepartmentStore_1F_Text_PleasePickTicket:
	.string "Prego, pesca un biglietto!\n"
	.string "…{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}…{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}…{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

LilycoveCity_DepartmentStore_1F_Text_TicketNumberIsXPleaseWait:
	.string "Il numero del biglietto è {STR_VAR_1}.\p"
	.string "Ora controllo se coincide con il\n"
	.string "numero ID di uno dei tuoi Pokémon.\l"
	.string "Un attimo di pazienza, prego.$"

LilycoveCity_DepartmentStore_1F_Text_TicketMatchesPartyMon:
	.string "Congratulazioni!\p"
	.string "Il numero del biglietto coincide\n"
	.string "con il numero ID di {STR_VAR_1}\l"
	.string "della tua squadra!$"

LilycoveCity_DepartmentStore_1F_Text_TicketMatchesPCMon:
	.string "Congratulazioni!\p"
	.string "Il numero del biglietto coincide\n"
	.string "con il numero ID di {STR_VAR_1}\l"
	.string "che tieni nel Box del PC!$"

LilycoveCity_DepartmentStore_1F_Text_NoNumbersMatched:
	.string "Mi dispiace, oggi niente fortuna.\n"
	.string "Nessun numero corrisponde.$"

LilycoveCity_DepartmentStore_1F_Text_TwoDigitsMatched:
	.string "Due cifre corrispondono: hai vinto\n"
	.string "il terzo premio!\l"
	.string "Ecco a te: {STR_VAR_1}!$"

LilycoveCity_DepartmentStore_1F_Text_ThreeDigitsMatched:
	.string "Tre cifre corrispondono: hai vinto\n"
	.string "il secondo premio!\l"
	.string "Ecco a te: {STR_VAR_1}!$"

LilycoveCity_DepartmentStore_1F_Text_FourDigitsMatched:
	.string "Quattro cifre corrispondono: hai\n"
	.string "vinto il primo premio!\l"
	.string "Ecco a te: {STR_VAR_1}!$"

LilycoveCity_DepartmentStore_1F_Text_AllFiveDigitsMatched:
	.string "Roba da non credere! Tutte e cinque\n"
	.string "le cifre corrispondono!\p"
	.string "Hai fatto jackpot!\n"
	.string "Il superpremio è tuo: {STR_VAR_1}!$"

LilycoveCity_DepartmentStore_1F_Text_NoRoomForThis:
	.string "Oh?\n"
	.string "Sembra che tu non abbia più spazio.\p"
	.string "Fai un po' di posto nello Zaino e\n"
	.string "torna da me: te lo terrò da parte.$"

LilycoveCity_DepartmentStore_1F_Text_PrizeWeveBeenHolding:
	.string "{PLAYER}?\n"
	.string "Sì, ti stavo proprio aspettando.\p"
	.string "Ecco il premio che abbiamo tenuto\n"
	.string "da parte per te.$"

LilycoveCity_DepartmentStore_1F_Text_PleaseVisitAgain2:
	.string "Torna domani a tentare la fortuna!$"
