MatchCall_WildBattleText1::
	.string "Ciao ciao, {PLAYER}{KUN}!\n"
	.string "Sono {STR_VAR_1}.\p"
	.string "Poco fa ho visto un {STR_VAR_2},\n"
	.string "ma mi è sfuggito per un pelo.\p"
	.string "Era lì, a un passo da me!\n"
	.string "Beh, ci sentiamo!$"

MatchCall_WildBattleText2::
	.string "Salve, {PLAYER}{KUN}.\n"
	.string "Sono {STR_VAR_1}.\p"
	.string "Poco fa ho provato a catturare\n"
	.string "un bell'esemplare di {STR_VAR_2}.\p"
	.string "Ma mi è scappato.\n"
	.string "Che delusione, davvero!\p"
	.string "Bene, a presto!$"

MatchCall_WildBattleText3::
	.string "Ehilà, {PLAYER}!\n"
	.string "Sono io, {STR_VAR_1}.\p"
	.string "Ho appena provato a catturare\n"
	.string "un {STR_VAR_2}, ma se l'è filata.\p"
	.string "Mancava tanto così, accidenti!\p"
	.string "Mi ha rovinato la giornata…\n"
	.string "Va be', ci si sente!$"

MatchCall_WildBattleText4::
	.string "Ehi, {PLAYER}{KUN}.\n"
	.string "Qui {STR_VAR_1}.\p"
	.string "Hai presente il Pokémon {STR_VAR_2}?\n"
	.string "Per poco non ne prendevo uno.\p"
	.string "È successo poco fa.\n"
	.string "Pensavo fosse fatta, e invece…\p"
	.string "Se lo rivedo, però, stavolta\n"
	.string "non mi scappa di sicuro.\p"
	.string "Ok, ci si becca.$"

MatchCall_WildBattleText5::
	.string "Oilà, {PLAYER}{KUN}!\n"
	.string "Sono {STR_VAR_1}.\l"
	.string "Preso qualche Pokémon, di recente?\p"
	.string "Poco fa ne stavo per acchiappare\n"
	.string "uno, ma si è liberato.\p"
	.string "Dai, stammi bene!$"

MatchCall_WildBattleText6::
	.string "Ehi, {PLAYER}{KUN}.\n"
	.string "Sono {STR_VAR_1}.\l"
	.string "Catturato qualche Pokémon?\p"
	.string "L'altro giorno ne avevo quasi uno.\n"
	.string "Ma chissà come, è sgusciato via.\p"
	.string "Abbi cura di te.$"

MatchCall_WildBattleText7::
	.string "…Ehm, {PLAYER}{KUN}?\n"
	.string "Sono io, {STR_VAR_1}.\p"
	.string "Oh, aspetta! Aspetta!\n"
	.string "Questo {STR_VAR_2} è mio…\p"
	.string "Aaargh! Se l'è svignata!\n"
	.string "Era a un millimetro da me!$"

MatchCall_WildBattleText8::
	.string "Oh, {PLAYER}{KUN}, come va?\n"
	.string "Qui parla {STR_VAR_1}.\p"
	.string "Hai avuto fortuna, di recente,\n"
	.string "nel catturare Pokémon?\p"
	.string "Poco fa ci è mancato davvero poco,\n"
	.string "ma la mia preda è fuggita.\p"
	.string "Devo impegnarmi di più!\n"
	.string "A risentirci!$"

MatchCall_WildBattleText9::
	.string "Oh, {PLAYER}{KUN}, ciao ciao!\n"
	.string "Sono {STR_VAR_1}!\p"
	.string "Allora? La tua collezione di\n"
	.string "Pokémon cresce?\p"
	.string "Io sto passando un periodaccio!\n"
	.string "Mi scappano tutti, manco avessero\l"
	.string "un Varco dietro l'angolo!\p"
	.string "Ci vediamo!$"

MatchCall_WildBattleText10::
	.string "Oh, {PLAYER}{KUN}, ciao…\n"
	.string "Sono {STR_VAR_1}.\p"
	.string "Senti, per un soffio non catturavo\n"
	.string "un {STR_VAR_2}…\p"
	.string "Ma mi è sgusciato via…\p"
	.string "Devo impegnarmi di più.\n"
	.string "Ci si vede.$"

MatchCall_WildBattleText11::
	.string "Ah, {PLAYER}{KUN}.\n"
	.string "Sono {STR_VAR_1}.\l"
	.string "Come te la passi?\p"
	.string "Prima ho cercato di catturare\n"
	.string "un {STR_VAR_2}, ma mi è fuggito.\p"
	.string "Che smacco…$"

MatchCall_WildBattleText12::
	.string "Salve, {PLAYER}{KUN}.\n"
	.string "Sono io, {STR_VAR_1}.\l"
	.string "Catturi ancora Pokémon?\p"
	.string "Anch'io ci provo, sai,\n"
	.string "ma non è affatto facile.\p"
	.string "La via dei Pokémon è profonda!$"

MatchCall_WildBattleText13::
	.string "Ah, buongiorno, {PLAYER}{KUN}!\n"
	.string "Sono {STR_VAR_1}!\l"
	.string "Hai catturato dei Pokémon?\p"
	.string "Anch'io ci sto provando,\n"
	.string "ma con scarsi risultati.\p"
	.string "La via dei Pokémon è profonda!$"

MatchCall_WildBattleText14::
	.string "Oh, ciao, {PLAYER}{KUN}! Come stai?\n"
	.string "Sono {STR_VAR_1}.\p"
	.string "Ho appena provato a catturare\n"
	.string "un {STR_VAR_2} tenerissimo.\p"
	.string "Però è scappato!\n"
	.string "Che delusione, non hai idea!\p"
	.string "Ciao ciao!$"

MatchCall_WildBattleText15::
	.string "Ehi, {PLAYER}!\n"
	.string "Sono {STR_VAR_1}!\p"
	.string "Stavo pensando di catturarmi\n"
	.string "qualche Pokémon.\p"
	.string "Ma non ne trovo neanche uno.\n"
	.string "Saranno spariti tutti in un Varco?\p"
	.string "Non so più che pesci pigliare!\n"
	.string "Ci vediamo!$"

MatchCall_NegativeBattleText1::
	.string "Ciao ciao, {PLAYER}{KUN}!\n"
	.string "Sono {STR_VAR_1}.\p"
	.string "Ho sfidato un altro Allenatore,\n"
	.string "ma ho perso.\p"
	.string "Che delusione, davvero.\n"
	.string "Beh, ci sentiamo!$"

MatchCall_NegativeBattleText2::
	.string "Salve, {PLAYER}{KUN}.\n"
	.string "Sono {STR_VAR_1}.\p"
	.string "Dopo la nostra lotta ho sfidato\n"
	.string "qualcun altro.\p"
	.string "Mancava poco, ma alla fine\n"
	.string "ho perso. Pazienza!$"

MatchCall_NegativeBattleText3::
	.string "Ehilà, {PLAYER}!\n"
	.string "Sono io, {STR_VAR_1}.\p"
	.string "Ho appena preso una bella batosta.\p"
	.string "Devo allenare ancora un po'\n"
	.string "la mia squadra!$"

MatchCall_NegativeBattleText4::
	.string "Ehi, {PLAYER}.\n"
	.string "Qui {STR_VAR_1}.\p"
	.string "Ieri ho fatto un'altra lotta,\n"
	.string "ma la vittoria non è arrivata.\p"
	.string "La mia squadra deve crescere.\n"
	.string "Ok, ci si becca.$"

MatchCall_NegativeBattleText5::
	.string "Oilà, {PLAYER}!\n"
	.string "Sono {STR_VAR_1}.\p"
	.string "Come ti vanno le cose?\p"
	.string "Io continuo a lottare,\n"
	.string "ma vinco di rado.\p"
	.string "Non riesco a ingranare.\n"
	.string "Dai, stammi bene!$"

MatchCall_NegativeBattleText6::
	.string "Ehi, {PLAYER}.\n"
	.string "Sono {STR_VAR_1}.\p"
	.string "Come ti va?\p"
	.string "Ultimamente lotto parecchio,\n"
	.string "ma con pochi risultati.\p"
	.string "Non riesco a trovare il ritmo.\n"
	.string "Abbi cura di te.$"

MatchCall_NegativeBattleText7::
	.string "Sono {STR_VAR_1}.\n"
	.string "Come va ultimamente?\p"
	.string "Ieri ho perso una lotta,\n"
	.string "e non riesco a pensare ad altro.\p"
	.string "Devo escogitare un piano…\n"
	.string "Ciao.$"

MatchCall_NegativeBattleText8::
	.string "Oh, {PLAYER}{KUN}, come va?\n"
	.string "Qui parla {STR_VAR_1}.\p"
	.string "Come stanno i tuoi Pokémon?\n"
	.string "L'altro giorno ho perso una lotta.\p"
	.string "Devo impegnarmi di più!\n"
	.string "A risentirci!$"

MatchCall_NegativeBattleText9::
	.string "Oh, {PLAYER}{KUN}, ciao ciao!\n"
	.string "Sono {STR_VAR_1}!\p"
	.string "Senti, senti, devi proprio\n"
	.string "sentire questa!\p"
	.string "Poco fa ho fatto una lotta Pokémon\n"
	.string "e ho perso all'ultimo secondo.\p"
	.string "Che rabbia, mi brucia ancora!$"

MatchCall_NegativeBattleText10::
	.string "Oh, {PLAYER}{KUN}, ciao…\n"
	.string "Sono {STR_VAR_1}.\p"
	.string "Poco fa ho fatto una lotta.\n"
	.string "Ma ho perso.\p"
	.string "Devo allenare di più i miei Pokémon.\n"
	.string "Ci si vede.$"

MatchCall_NegativeBattleText11::
	.string "Ah, {PLAYER}{KUN}.\n"
	.string "Sono {STR_VAR_1}.\l"
	.string "Come stanno i tuoi Pokémon?\p"
	.string "Ho appena perso l'ennesima lotta.\p"
	.string "Beh, ci sentiamo!$"

MatchCall_NegativeBattleText12::
	.string "Salve, {PLAYER}{KUN}.\n"
	.string "Sono io, {STR_VAR_1}.\l"
	.string "Continui a lottare con impegno?\p"
	.string "Io di recente ho perso, quindi\n"
	.string "sto riallenando la squadra da capo.\p"
	.string "Rivediamoci presto.$"

MatchCall_NegativeBattleText13::
	.string "Ah, buongiorno, {PLAYER}{KUN}!\n"
	.string "Sono {STR_VAR_1}!\p"
	.string "Spero che tu stia bene.\p"
	.string "Poco prima di chiamarti\n"
	.string "ho fatto una lotta.\p"
	.string "{PLAYER}{KUN}, datti da fare come me!\n"
	.string "A risentirci!$"

MatchCall_NegativeBattleText14::
	.string "Oh, ciao, {PLAYER}{KUN}.\n"
	.string "Sono {STR_VAR_1}.\p"
	.string "Tutto bene?\p"
	.string "Ogni tanto, però, dovresti\n"
	.string "fare un salto a casa, eh!\p"
	.string "Ciao ciao!$"

MatchCall_PositiveBattleText1::
	.string "Ciao ciao, {PLAYER}{KUN}!\n"
	.string "Sono {STR_VAR_1}!\p"
	.string "Prima ho sfidato un altro Allenatore.\n"
	.string "Ho vinto! Ho vinto!\p"
	.string "Il mio {STR_VAR_2} ce l'ha messa\n"
	.string "tutta per me. Che bello!$"

MatchCall_PositiveBattleText2::
	.string "Salve, {PLAYER}{KUN}!\n"
	.string "Sono {STR_VAR_1}!\p"
	.string "Ieri ho fatto una lotta e\n"
	.string "ho vinto! È fantastico!$"

MatchCall_PositiveBattleText3::
	.string "Ehilà, {PLAYER}!\n"
	.string "Sono io, {STR_VAR_1}!\l"
	.string "Come vanno le tue lotte?\p"
	.string "Io l'altro giorno ho lottato,\n"
	.string "e il mio {STR_VAR_2} ha spaccato!\p"
	.string "La prossima volta che lottiamo,\n"
	.string "{PLAYER}, a perdere non sarò io!$"

MatchCall_PositiveBattleText4::
	.string "Ehi, {PLAYER}.\n"
	.string "Qui {STR_VAR_1}.\p"
	.string "Poco fa ho fatto un incontro.\n"
	.string "Ho vinto, ma per un soffio.\p"
	.string "Il mio {STR_VAR_2} ha dato\n"
	.string "spettacolo.$"

MatchCall_PositiveBattleText5::
	.string "Oilà, {PLAYER}{KUN}!\n"
	.string "Sono {STR_VAR_1}.\p"
	.string "Come ti vanno le cose?\n"
	.string "Lotti parecchio?\p"
	.string "Io ho appena vinto!\n"
	.string "Il mio {STR_VAR_2} è un fenomeno!\p"
	.string "Aspetta e vedrai: la prossima\n"
	.string "volta ti batto! Dai, stammi bene!$"

MatchCall_PositiveBattleText6::
	.string "Ehi, {PLAYER}{KUN}.\n"
	.string "Sono {STR_VAR_1}.\p"
	.string "Come ti va?\p"
	.string "Sto attraversando un periodo d'oro.\n"
	.string "Pensa, ho appena vinto una lotta.\p"
	.string "Alla nostra prossima sfida,\n"
	.string "stai certo che non perderò!$"

MatchCall_PositiveBattleText7::
	.string "{PLAYER}{KUN}?\n"
	.string "Sono {STR_VAR_1}.\p"
	.string "Il mio {STR_VAR_2} è una forza!\n"
	.string "Mi ha fatto vincere un'altra lotta!\p"
	.string "Non vedo l'ora di avere\n"
	.string "la rivincita con te.$"

MatchCall_PositiveBattleText8::
	.string "Oh, {PLAYER}{KUN}, come va?\n"
	.string "Qui parla {STR_VAR_1}.\p"
	.string "Spero che tu stia bene.\n"
	.string "Volevo dirti che ho appena vinto.\p"
	.string "Il mio {STR_VAR_2} si è impegnato\n"
	.string "tantissimo per la vittoria.\p"
	.string "A risentirci!$"

MatchCall_PositiveBattleText9::
	.string "Oh, {PLAYER}{KUN}, ciao ciao!\n"
	.string "Sono {STR_VAR_1}!\p"
	.string "Come stanno i tuoi Pokémon?\n"
	.string "I miei hanno vinto una lotta!\p"
	.string "Il mio {STR_VAR_2} è stato\n"
	.string "spettacolare, lasciatelo dire!\p"
	.string "Peccato che tu non l'abbia visto!\n"
	.string "Ci vediamo!$"

MatchCall_PositiveBattleText10::
	.string "Oh, {PLAYER}{KUN}, ciao…\n"
	.string "Sono {STR_VAR_1}.\p"
	.string "Come ti tratta la vita?\p"
	.string "I miei Pokémon sembrano carichi\n"
	.string "di energia.\p"
	.string "Ho appena vinto una lotta con loro.\n"
	.string "Ci si vede.$"

MatchCall_PositiveBattleText11::
	.string "Ah, {PLAYER}{KUN}.\n"
	.string "Sono {STR_VAR_1}.\p"
	.string "Fatto qualche lotta, di recente?\n"
	.string "Io oggi ne ho vinta un'altra!\p"
	.string "Sono inarrestabile! Gahahaha!\n"
	.string "Beh, ci sentiamo!$"

MatchCall_PositiveBattleText12::
	.string "Salve, {PLAYER}{KUN}.\n"
	.string "Sono io, {STR_VAR_1}.\p"
	.string "Confido che tu stia bene.\n"
	.string "Io scoppio ancora di salute!\p"
	.string "Proprio ora ho vinto un'altra sfida.\n"
	.string "Non ho alcuna intenzione di farmi\l"
	.string "da parte per voi giovani!$"

MatchCall_PositiveBattleText13::
	.string "Ah, buongiorno, {PLAYER}{KUN}!\n"
	.string "Sono {STR_VAR_1}!\p"
	.string "Spero che tu stia bene.\n"
	.string "Ho ancora l'argento vivo addosso!\p"
	.string "Ho appena vinto di nuovo, pensa.\n"
	.string "Oh, non mi lascio ancora battere\l"
	.string "da voi giovani!\p"
	.string "A risentirci!$"

MatchCall_PositiveBattleText14::
	.string "Oh, ciao, {PLAYER}{KUN}.\n"
	.string "Sono {STR_VAR_1}.\p"
	.string "Di recente ho fatto una lotta, e il\n"
	.string "mio {STR_VAR_2} è stato un asso!\p"
	.string "Peccato che tu non l'abbia visto,\n"
	.string "{PLAYER}{KUN}. Ciao ciao!$"

MatchCall_SameRouteBattleRequestText1::
	.string "Ciao ciao, {PLAYER}!\n"
	.string "Sono {STR_VAR_1}.\p"
	.string "Eh? Aspetta, sei in zona\n"
	.string "{STR_VAR_2}?\p"
	.string "Wow, allora dobbiamo lottare!\n"
	.string "Ti aspetto! A tra poco!$"

MatchCall_SameRouteBattleRequestText2::
	.string "Salve, {PLAYER}!\n"
	.string "Sono {STR_VAR_1}.\p"
	.string "Oh? Proprio adesso sei in zona\n"
	.string "{STR_VAR_2}?\p"
	.string "Ti va di lottare subito?\n"
	.string "Ti aspetto! A tra poco!$"

MatchCall_SameRouteBattleRequestText3::
	.string "Ehilà, {PLAYER}!\n"
	.string "Sono io, {STR_VAR_1}.\p"
	.string "Ehi, ma adesso sei in zona\n"
	.string "{STR_VAR_2}?\p"
	.string "Che ne dici di lottare con me,\n"
	.string "qui e ora?\p"
	.string "Stavolta non perdo!\n"
	.string "Ti aspetto! A prestissimo!$"

MatchCall_SameRouteBattleRequestText4::
	.string "Ehi, {PLAYER}{KUN}.\n"
	.string "Qui {STR_VAR_1}.\p"
	.string "Dove sei di bello, adesso?\n"
	.string "Eh? {STR_VAR_2}?\p"
	.string "Facciamo una lotta?\n"
	.string "Ti aspetto. A dopo!$"

MatchCall_SameRouteBattleRequestText5::
	.string "Oilà, {PLAYER}{KUN}!\n"
	.string "Sono {STR_VAR_1}.\l"
	.string "Come ti vanno le cose?\p"
	.string "Dove sei, adesso?\n"
	.string "{STR_VAR_2}?\p"
	.string "Allora che ne dici di una rivincita\n"
	.string "lampo, subito?\p"
	.string "Ti tengo d'occhio.\n"
	.string "A tra poco!$"

MatchCall_SameRouteBattleRequestText6::
	.string "Ehi, {PLAYER}{KUN}.\n"
	.string "Sono {STR_VAR_1}.\l"
	.string "Come stanno i tuoi Pokémon?\p"
	.string "Ah, davvero? Sei in zona\n"
	.string "{STR_VAR_2}?\p"
	.string "Beh, allora ci tocca fare\n"
	.string "una rivincita.\p"
	.string "Posso aspettare, tranquillo.\n"
	.string "Ciao!$"

MatchCall_SameRouteBattleRequestText7::
	.string "…Ehm, {PLAYER}{KUN}?\n"
	.string "Sono {STR_VAR_1}…\p"
	.string "Oh, per caso sei in zona\n"
	.string "{STR_VAR_2}?\p"
	.string "Allora lottiamo.\n"
	.string "Subito, intendo.\p"
	.string "Ti farò vedere i miei Pokémon.\n"
	.string "Ti aspetto.$"

MatchCall_SameRouteBattleRequestText8::
	.string "Oh, {PLAYER}{KUN}, come va?\n"
	.string "Qui parla {STR_VAR_1}.\p"
	.string "Spero che tu stia bene.\n"
	.string "Oh, sei in zona {STR_VAR_2}.\p"
	.string "Allora ti andrebbe di fare\n"
	.string "una lotta con me?\p"
	.string "Ti aspetto.\n"
	.string "A presto!$"

MatchCall_SameRouteBattleRequestText9::
	.string "Oh, {PLAYER}{KUN}, ciao ciao!\n"
	.string "Sono {STR_VAR_1}!\p"
	.string "Tutto a posto?\n"
	.string "Oh, sei in zona {STR_VAR_2}?\p"
	.string "Ma allora non pensi che dovremmo\n"
	.string "lottare?\p"
	.string "Non farmi aspettare troppo!$"

MatchCall_SameRouteBattleRequestText10::
	.string "Oh, {PLAYER}{KUN}, ciao…\n"
	.string "Sono {STR_VAR_1}.\p"
	.string "Come ti vanno le cose?\n"
	.string "Oh, sei in zona {STR_VAR_2}.\p"
	.string "Allora dovremmo fare una lotta.\p"
	.string "Ti aspetto, è tutto pronto.\n"
	.string "Fai presto!$"

MatchCall_SameRouteBattleRequestText11::
	.string "Ah, {PLAYER}{KUN}.\n"
	.string "Sono {STR_VAR_1}.\p"
	.string "Ah, quindi adesso ti trovi in zona\n"
	.string "{STR_VAR_2}?\p"
	.string "Beh, allora dobbiamo proprio fare\n"
	.string "una lotta, non credi?\p"
	.string "Ti aspetto qui!\n"
	.string "Vedi di sbrigarti!$"

MatchCall_SameRouteBattleRequestText12::
	.string "Salve, {PLAYER}{KUN}.\n"
	.string "Sono io, {STR_VAR_1}.\l"
	.string "Dove ti trovi, adesso?\p"
	.string "{STR_VAR_2}?\n"
	.string "Ma è qui vicino!\p"
	.string "Che ne dici di fare una lotta\n"
	.string "adesso?\p"
	.string "Posso aspettare.\n"
	.string "Ciao!$"

MatchCall_SameRouteBattleRequestText13::
	.string "Ah, buongiorno, {PLAYER}{KUN}!\n"
	.string "Sono {STR_VAR_1}!\p"
	.string "Spero che tu stia bene.\n"
	.string "Oh, sei in zona {STR_VAR_2}?\p"
	.string "Non è molto lontano da qui:\n"
	.string "vieni a trovarmi per una lotta.\p"
	.string "Ti aspetto.\n"
	.string "A presto.$"

MatchCall_SameRouteBattleRequestText14::
	.string "Oh, ciao, {PLAYER}{KUN}!\n"
	.string "Sono {STR_VAR_1}.\p"
	.string "Dove sei? …{STR_VAR_2}?\n"
	.string "Ma è vicinissimo!\p"
	.string "Non pensi che dovremmo proprio\n"
	.string "fare una bella lotta?\p"
	.string "Vengo subito a cercarti!\n"
	.string "Ciao ciao!$"

MatchCall_DifferentRouteBattleRequestText1::
	.string "Ehi! {PLAYER}, ciao!\n"
	.string "Sono {STR_VAR_1}.\p"
	.string "Ti va di lottare con me?\p"
	.string "Ti aspetto in zona\n"
	.string "{STR_VAR_2}!$"

MatchCall_DifferentRouteBattleRequestText2::
	.string "Ciao, {PLAYER}!\n"
	.string "Sono {STR_VAR_1}.\p"
	.string "Ti andrebbe di lottare ancora\n"
	.string "una volta con me?\p"
	.string "Mi trovi in zona {STR_VAR_2}.\n"
	.string "Ti aspetto!$"

MatchCall_DifferentRouteBattleRequestText3::
	.string "Ehilà, {PLAYER}!\n"
	.string "Sono io, {STR_VAR_1}.\p"
	.string "I miei Pokémon sono diventati\n"
	.string "molto più forti di prima.\p"
	.string "Voglio vedere come se la cavano\n"
	.string "contro i tuoi, {PLAYER}.\p"
	.string "Quindi, sfidiamoci!\p"
	.string "Ti aspetto in zona\n"
	.string "{STR_VAR_2}.$"

MatchCall_DifferentRouteBattleRequestText4::
	.string "Ehi, {PLAYER}{KUN}.\n"
	.string "Qui {STR_VAR_1}.\l"
	.string "Come ti vanno le cose?\p"
	.string "I miei Pokémon si sono fatti\n"
	.string "parecchio robusti, ultimamente.\p"
	.string "Che ne dici di fare un'altra\n"
	.string "lotta con me?\p"
	.string "Vediamoci in zona\n"
	.string "{STR_VAR_2}, d'accordo?$"

MatchCall_DifferentRouteBattleRequestText5::
	.string "Ehi ehi, {PLAYER}{KUN}!\n"
	.string "Sono {STR_VAR_1}.\p"
	.string "I miei Pokémon stanno crescendo\n"
	.string "proprio come si deve.\p"
	.string "Mi piacerebbe un sacco fare\n"
	.string "un'altra lotta con te.\p"
	.string "Ti tengo d'occhio in zona\n"
	.string "{STR_VAR_2}. A presto!$"

MatchCall_DifferentRouteBattleRequestText6::
	.string "Ehi, {PLAYER}{KUN}.\n"
	.string "Sono {STR_VAR_1}.\l"
	.string "Spero che vada tutto alla grande.\p"
	.string "Stavo pensando: mi va un'altra\n"
	.string "lotta con te. Che ne dici?\p"
	.string "Se hai voglia di sfidarmi,\n"
	.string "vieni in zona {STR_VAR_2}.\p"
	.string "A dopo!$"

MatchCall_DifferentRouteBattleRequestText7::
	.string "…Ehm, {PLAYER}{KUN}?\n"
	.string "Sono {STR_VAR_1}…\l"
	.string "Allora? I tuoi Pokémon crescono?\p"
	.string "I miei si sono fatti fortissimi.\n"
	.string "Vorrei fartelo vedere.\p"
	.string "Sono in zona {STR_VAR_2}.\n"
	.string "Passa a trovarmi per una lotta.\p"
	.string "Ci si vede…$"

MatchCall_DifferentRouteBattleRequestText8::
	.string "Oh, {PLAYER}{KUN}, come stai?\n"
	.string "Ti parla {STR_VAR_1}.\p"
	.string "Spero che vada tutto bene.\n"
	.string "I miei Pokémon sono vivacissimi.\p"
	.string "Se passi dalle mie parti, ti prego,\n"
	.string "concedimi una rivincita.\p"
	.string "Mi trovi in zona {STR_VAR_2}.\n"
	.string "Fino ad allora, arrivederci!$"

MatchCall_DifferentRouteBattleRequestText9::
	.string "Oh, {PLAYER}{KUN}, ciao!\n"
	.string "Sono {STR_VAR_1}!\l"
	.string "Come stanno i tuoi Pokémon?\p"
	.string "I miei migliorano ogni giorno.\n"
	.string "Voglio fartelo vedere, {PLAYER}{KUN}.\p"
	.string "Ora sono in zona {STR_VAR_2}:\n"
	.string "se sei vicino, lottiamo!\p"
	.string "Spero di vederti presto!$"

MatchCall_DifferentRouteBattleRequestText10::
	.string "Oh, {PLAYER}{KUN}, ciao…\n"
	.string "Sono {STR_VAR_1}.\l"
	.string "Allora, come te la passi?\p"
	.string "I miei Pokémon sono molto più\n"
	.string "forti di prima.\p"
	.string "Mi piacerebbe tanto lottare\n"
	.string "di nuovo con te, {PLAYER}{KUN}.\p"
	.string "Sono in zona {STR_VAR_2}.\n"
	.string "Vieni a trovarmi, se sei vicino.$"

MatchCall_DifferentRouteBattleRequestText11::
	.string "Ah, {PLAYER}{KUN}.\n"
	.string "Sono {STR_VAR_1}.\l"
	.string "Dove ti trovi di bello?\p"
	.string "I miei Pokémon sono pieni di vita.\n"
	.string "Sembra proprio che non vedano\l"
	.string "l'ora di vedere i tuoi, {PLAYER}{KUN}.\p"
	.string "Ora sono in zona {STR_VAR_2}.\n"
	.string "Spero che verrai a cercarci.$"

MatchCall_DifferentRouteBattleRequestText12::
	.string "Salve, {PLAYER}{KUN}.\n"
	.string "Sono io, {STR_VAR_1}.\p"
	.string "Devo dirti che i miei Pokémon\n"
	.string "si sono fatti piuttosto robusti.\p"
	.string "Mi piacerebbe vederli lottare\n"
	.string "contro di te, {PLAYER}{KUN}.\p"
	.string "Siamo in zona {STR_VAR_2}.\n"
	.string "Vieni a trovarci quando vuoi!$"

MatchCall_DifferentRouteBattleRequestText13::
	.string "Ah, ciao, {PLAYER}{KUN}!\n"
	.string "Sono {STR_VAR_1}!\l"
	.string "I tuoi Pokémon stanno bene?\p"
	.string "I miei sono in forma smagliante:\n"
	.string "sembrano incapaci di perdere!\p"
	.string "Mi farebbe davvero piacere\n"
	.string "lottare di nuovo con te.\p"
	.string "Se passi da {STR_VAR_2},\n"
	.string "vieni a trovarci, mi raccomando.$"

MatchCall_DifferentRouteBattleRequestText14::
	.string "Oh, ciao, {PLAYER}{KUN}.\n"
	.string "Sono {STR_VAR_1}.\l"
	.string "Spero che tu stia bene.\p"
	.string "Oh, sì! I miei Pokémon sono\n"
	.string "molto più forti di prima.\p"
	.string "Non pensi che dovremmo fare\n"
	.string "una lotta, {PLAYER}{KUN}?\p"
	.string "Ti aspettiamo in zona\n"
	.string "{STR_VAR_2}.\p"
	.string "Vieni quando vuoi, d'accordo?$"

MatchCall_PersonalizedText1::
	.string "Sono io, {STR_VAR_1},\n"
	.string "l'amante delle montagne!\p"
	.string "Allora, da quando ci siamo visti,\n"
	.string "hai imparato ad amare le vette?\p"
	.string "In montagna ti vedo di rado…\p"
	.string "La prossima volta ci vediamo\n"
	.string "in zona {STR_VAR_2}.$"

MatchCall_PersonalizedText2::
	.string "Sono {STR_VAR_1}.\n"
	.string "Ciao!\p"
	.string "Stavo giusto parlando di te\n"
	.string "a un'Allenatrice alle prime armi.\p"
	.string "Le ho raccontato di un Allenatore\n"
	.string "forte e premuroso con i Pokémon.\p"
	.string "Spero che diventerai un Allenatore\n"
	.string "ammirato da tutti.\p"
	.string "Spero di rivederti presto!$"

MatchCall_PersonalizedText3::
	.string "Ciao! Sono {STR_VAR_1}.\p"
	.string "Adoro il posto in cui mi trovo:\n"
	.string "c'è un profumo dolcissimo!\p"
	.string "Qualcuno deve aver piantato delle\n"
	.string "Bacche, e ora sono tutte in fiore.\p"
	.string "Alla prossima!$"

MatchCall_PersonalizedText4::
	.string "Salve! Trent'anni di esplorazioni:\n"
	.string "{STR_VAR_1}, al tuo servizio!\p"
	.string "Vedo che te ne vai in giro di qua\n"
	.string "e di là con grande energia.\p"
	.string "Hai scoperto nuove rovine? O magari\n"
	.string "un reperto caduto da un Varco?\l"
	.string "Se sì, raccontami tutto!\p"
	.string "Ora, se vuoi scusarmi,\n"
	.string "ho delle rovine da esplorare.$"

MatchCall_PersonalizedText5::
	.string "Sono {STR_VAR_1}!\p"
	.string "Sai cosa faccio oggi?\n"
	.string "Guardo le onde dalla spiaggia!\p"
	.string "Sigh… Le onde luccicano tutte.\n"
	.string "Da qui il mare è bellissimo.\l"
	.string "Mi è venuta fame, ciao ciao!$"

MatchCall_PersonalizedText6::
	.string "Gnam gnam…\n"
	.string "Oh, ciao, sono {STR_VAR_1}.\l"
	.string "Adoro fare merenda in spiaggia.\p"
	.string "Io e i miei Pokémon stiamo\n"
	.string "benone. Pieni di energia!\l"
	.string "Vado a fare un tuffo. Ciao!$"

MatchCall_PersonalizedText7::
	.string "Ciao, sono {STR_VAR_1}…\p"
	.string "Comincio a essere stufo di questa\n"
	.string "storia del Fantallenatore…\p"
	.string "Tutti pensano che io sia un\n"
	.string "Allenatore perfetto, e così mi\l"
	.string "tocca sempre essere all'altezza.\p"
	.string "Ma immagino che faccia parte\n"
	.string "dell'essere un Fantallenatore.\p"
	.string "Dovrò rimboccarmi le maniche…\n"
	.string "e sorridere stringendo i denti.\p"
	.string "Sei l'unica persona con cui posso\n"
	.string "confidarmi così.\p"
	.string "Ma la prossima volta che ci vediamo,\n"
	.string "tranquillo: niente lagne!$"

MatchCall_PersonalizedText8::
	.string "Evviva, sono {STR_VAR_1}!\n"
	.string "Come va?\p"
	.string "Ho allenato i miei Pokémon\n"
	.string "pensando solo a batterti.\p"
	.string "Non ho intenzione di perdere\n"
	.string "alla prossima lotta.\p"
	.string "Che bello avere amici Allenatori,\n"
	.string "vero? Rivediamoci presto!$"

MatchCall_PersonalizedText9::
	.string "Sono {STR_VAR_1}…\n"
	.string "Proprio adesso, dietro di te…\l"
	.string "Non c'era forse qualcosa…?\p"
	.string "Il potere dei Pokémon che\n"
	.string "riposano qui sul Monte Pira…\p"
	.string "Mi parla di te… e di un Varco\n"
	.string "che respira, lontano…\p"
	.string "Dovresti allontanarti in fretta,\n"
	.string "senza voltarti mai indietro…\p"
	.string "Ihihih…\n"
	.string "Addio…$"

MatchCall_PersonalizedText10::
	.string "Sono {STR_VAR_1}.\n"
	.string "Come stai?\p"
	.string "Che comodità poter chiacchierare\n"
	.string "così, anche a distanza!\p"
	.string "Prima, se volevo parlare con\n"
	.string "qualcuno, dovevo farmi\l"
	.string "accompagnare in auto da papà…\p"
	.string "Ora devo proprio andare.\n"
	.string "Che bella chiacchierata!$"

MatchCall_PersonalizedText11::
	.string "Sono {STR_VAR_1}!\n"
	.string "Mi ascolti un attimo?\p"
	.string "Adoro la Zona Safari, ma ogni\n"
	.string "volta che ci vado mi perdo!\p"
	.string "Tutta quell'erba alta!\n"
	.string "Ed è davvero troppo grande!\p"
	.string "Ah, sfogarmi mi fa sentire\n"
	.string "molto meglio!\p"
	.string "Torno subito alla Zona Safari!\n"
	.string "Ci sentiamo!$"

MatchCall_PersonalizedText12::
	.string "Salve, qui {STR_VAR_1}.\n"
	.string "Sì, esatto, sono ricco. Sì.\p"
	.string "Devo informarti che il mio\n"
	.string "patrimonio è cresciuto ancora.\p"
	.string "E non solo: anche i miei Pokémon\n"
	.string "sono diventati più forti.\p"
	.string "Ho la netta sensazione che il\n"
	.string "mondo… anzi, il multiverso…\l"
	.string "esista solo per me!\p"
	.string "Oh, non serve che tu dica nulla!\n"
	.string "Lo sanno tutti che è così!\p"
	.string "Ora scusami, mi attende\n"
	.string "una cena di gala.$"

MatchCall_PersonalizedText13::
	.string "Ufufufufu…\n"
	.string "Sono io, {STR_VAR_1}…\p"
	.string "Indovina cosa sto guardando?\n"
	.string "Due {STR_VAR_2} che lottano.\p"
	.string "Magari catturo il vincitore…\n"
	.string "Ufufufufufu…\p"
	.string "Io… sono un po' impegnato, ora.\n"
	.string "Devo andare.$"

MatchCall_PersonalizedText14::
	.string "Oh, sono {STR_VAR_1}!\p"
	.string "Stavo giusto pensando che la\n"
	.string "Vecchia Nave inizia ad annoiarmi.\p"
	.string "Ma visto che sono già qui,\n"
	.string "e che voglio batterti almeno\l"
	.string "una volta, resterò ancora un po'.\p"
	.string "Se ne hai voglia, perché\n"
	.string "non passi a trovarmi?\p"
	.string "Credo che oggi sia il giorno in\n"
	.string "cui sfiderò finalmente il tizio\l"
	.string "della cabina accanto.\p"
	.string "A presto!$"

MatchCall_PersonalizedText15::
	.string "Sono {STR_VAR_1}!\n"
	.string "L'uomo del mare!\p"
	.string "Sai cosa penso?\p"
	.string "Gli Allenatori che stanno in mare\n"
	.string "sono i più duri dei duri!\p"
	.string "Dovresti imparare da me e\n"
	.string "allenarti in mare aperto…\p"
	.string "Ops, arriva un'onda gigante!\p"
	.string "Ottima occasione per allenarsi!\n"
	.string "Scusa, ma devo andare!$"

MatchCall_PersonalizedText16::
	.string "Sono {STR_VAR_1}! Senti, ho\n"
	.string "insegnato karate ai miei Pokémon.\p"
	.string "Ma ora sono più bravi di me!\n"
	.string "Non faccio che perdere con loro!\p"
	.string "Però, anche se perdo contro\n"
	.string "i Pokémon, contro un altro\l"
	.string "Allenatore no, signore!\p"
	.string "Dobbiamo lottare di nuovo!\n"
	.string "Uuuaaah!$"

MatchCall_PersonalizedText17::
	.string "Sono io, {STR_VAR_1}.\n"
	.string "Come procede il tuo viaggio?\p"
	.string "…Wow, davvero?\n"
	.string "Roba da far vibrare le corde!\p"
	.string "Potrei scrivere una canzone\n"
	.string "su una delle tue avventure.\p"
	.string "…Oh, ehi, la sento arrivare.\n"
	.string "Ho già i riff in testa.\p"
	.string "Devo scriverla subito, prima che\n"
	.string "svanisca! Scappo! Ciao!$"

MatchCall_PersonalizedText18::
	.string "Sono {STR_VAR_1}…\n"
	.string "Senti la mia nuova canzone.\p"
	.string "Lalalà, {STR_VAR_2}, {STR_VAR_2}!\n"
	.string "Perché sei così {STR_VAR_2}?\l"
	.string "Perché non sono te, {STR_VAR_2}?\l"
	.string "Lalà, {STR_VAR_2} e {STR_VAR_1},\l"
	.string "{STR_VAR_1} e {STR_VAR_2}…\p"
	.string "Ritornello, sfumando…$"

MatchCall_PersonalizedText19::
	.string "Sono {STR_VAR_1}, sai,\n"
	.string "l'esperto di campeggio!\p"
	.string "Quando abbiamo lottato, non ho\n"
	.string "potuto fare altro che perdere.\p"
	.string "Del resto, la mia specialità\n"
	.string "è il campeggio.\p"
	.string "Ma che vinca o perda, adoro\n"
	.string "lottare quando sono in tenda.\p"
	.string "Lotta ancora con noi, va bene?\n"
	.string "E andiamo anche in campeggio!$"

MatchCall_PersonalizedText20::
	.string "Sono io, io, {STR_VAR_1}!\p"
	.string "A dire il vero, vorrei scalare\n"
	.string "anche altre montagne.\p"
	.string "Ma non so se ci sarebbero ragazze\n"
	.string "carine come sul Monte Camino.\p"
	.string "Se conosci un'altra montagna\n"
	.string "con delle ragazze, fammi sapere!\p"
	.string "Ehehehe, ci si vede!$"

MatchCall_PersonalizedText21::
	.string "… … … … … …\n"
	.string "… … … … … …\l"
	.string "Sono {STR_VAR_1}…\p"
	.string "… … … … … …\n"
	.string "… … … … … …\l"
	.string "Per oggi è tutto…$"

MatchCall_PersonalizedText22::
	.string "Sono {STR_VAR_1}. Oggi sentivo\n"
	.string "che ti avrei parlato.\p"
	.string "Il mio desiderio di batterti\n"
	.string "cresce giorno e notte.\p"
	.string "Anche tu hai un rivale così, vero?\n"
	.string "Vorrei tanto essere io…\p"
	.string "Grazie per avermi ascoltato.\n"
	.string "A presto!$"

MatchCall_PersonalizedText23::
	.string "Sono {STR_VAR_1}.\p"
	.string "Quando c'è un Allenatore forte\n"
	.string "nei paraggi, a volte lo sento,\l"
	.string "come quando si apre un Varco.\p"
	.string "Sei passato di qui, {PLAYER}{KUN}?\n"
	.string "Forse eri proprio tu.\p"
	.string "Aspetto la tua visita.\n"
	.string "Ciao!$"

MatchCall_PersonalizedText24::
	.string "Salve, sono {STR_VAR_1}.\n"
	.string "Ti sento in forma, {PLAYER}{KUN}.\p"
	.string "Ho girato Hoenn in lungo e in\n"
	.string "largo, ma devo dire che mi sono\l"
	.string "affezionato a questa zona.\p"
	.string "Conto di fermarmi qui per un po'.\n"
	.string "Magari ci rivedremo?\p"
	.string "Non ho dimenticato le tue\n"
	.string "tecniche sfavillanti.\p"
	.string "Spero proprio in una rivincita.$"

MatchCall_PersonalizedText25::
	.string "Snif… Sono… {STR_VAR_1}…\n"
	.string "…Sigh…\p"
	.string "Oggi in classe Petra mi ha\n"
	.string "fatto una bella ramanzina.\p"
	.string "Ma non ce l'ho mica con lei.\p"
	.string "Petra mi spiega sempre cosa\n"
	.string "ho sbagliato, così imparo.\p"
	.string "Puoi scommetterci: domani torno\n"
	.string "alla Scuola Allenatori!\p"
	.string "Ci vediamo!$"

MatchCall_PersonalizedText26::
	.string "Sono {STR_VAR_1}!\p"
	.string "Ieri Petra mi ha concesso\n"
	.string "una lotta con lei!\p"
	.string "Il risultato…\n"
	.string "Un disastro, inutile chiederlo.\p"
	.string "Ma ero felicissima che Petra\n"
	.string "mi lasciasse sfidarla!\p"
	.string "Non immagini quanto la ammiri\n"
	.string "ancora di più adesso!\p"
	.string "Mi impegnerò al massimo!\n"
	.string "Ora devo scappare!$"

MatchCall_PersonalizedText27::
	.string "Ciao, sono Anna! Anche oggi\n"
	.string "sono con la mia piccola Meg.\p"
	.string "Adoro prendermi cura di Meg e\n"
	.string "dei Pokémon. Sono così carini!\p"
	.string "Vorrei occuparmi di loro come\n"
	.string "se fossero miei fratellini!\p"
	.string "Oh, ciao, Meg!\n"
	.string "Hai preso i panini?\p"
	.string "Eh? No, no, non ti sto trattando\n"
	.string "come la mia servetta!\p"
	.string "Hai perso la lotta, quindi per\n"
	.string "punizione vai tu a prendere il pane!\p"
	.string "Non ti tratterei mai da servetta,\n"
	.string "Meg! Sei troppo speciale per me!\p"
	.string "Ora devo andare.\n"
	.string "È l'ora della merenda!$"

MatchCall_PersonalizedText28::
	.string "Adoro i Pokémon!\n"
	.string "Sono {STR_VAR_1} del Fan Club!\p"
	.string "Devi sentire questa!\n"
	.string "Il mio dolce Pokémon…\p"
	.string "Pfff! Uahahah!\n"
	.string "Non posso dire altro! È un segreto!\l"
	.string "È troppo carino per descriverlo!\p"
	.string "Oh, il mio tesoro {STR_VAR_2}\n"
	.string "mi chiede una Pokémella!\p"
	.string "È il ritratto della dolcezza!\p"
	.string "Scusa, ma ora non posso parlare!\n"
	.string "Te lo racconto la prossima volta!$"

MatchCall_PersonalizedText29::
	.string "Ohoho!\p"
	.string "Sono {STR_VAR_1}! Non vedo l'ora\n"
	.string "di parlarti del mio amato Pokémon!\p"
	.string "Ti prego, devi proprio ascoltarmi.\n"
	.string "Parlo del mio tesoro, {STR_VAR_2}.\p"
	.string "Chiunque lo sollevi da terra,\n"
	.string "lui torna a saltarmi in braccio!\p"
	.string "Oh… Oh… Esiste forse qualcosa\n"
	.string "di più dolce al mondo?\p"
	.string "Oh, è una sensazione paradisiaca!\p"
	.string "Che bello aver condiviso un po'\n"
	.string "della mia felicità con te.\p"
	.string "Bene, ora devo proprio andare.\n"
	.string "Ciao ciao!$"

MatchCall_PersonalizedText30::
	.string "Sono… {STR_VAR_1}.\n"
	.string "La gente mi chiama Esperto.\p"
	.string "Ma c'è una cosa che so per certo.\n"
	.string "Non sarei mai diventato Esperto\l"
	.string "con le mie sole forze.\p"
	.string "Solo con l'aiuto dei Pokémon\n"
	.string "un Allenatore diventa un Esperto.\p"
	.string "Hmpf! Credo di aver appena detto\n"
	.string "qualcosa di molto profondo!\p"
	.string "Ti lascio a meditare su questa perla!$"

MatchCall_PersonalizedText31::
	.string "Sono {STR_VAR_1}.\n"
	.string "Che piacere chiacchierare con te!\p"
	.string "Mi sento rinata, immersa in questa\n"
	.string "vasca di acqua termale.\p"
	.string "Da quando ci siamo conosciuti ho\n"
	.string "sfidato tanti giovani Allenatori,\l"
	.string "ma tu resti il migliore di tutti.\p"
	.string "Scommetto che da vecchio diventerai\n"
	.string "un Esperto! Ohohoho…$"

MatchCall_PersonalizedText32::
	.string "Evvai! Sono {STR_VAR_1}!\n"
	.string "Come va?\p"
	.string "Forse me lo immagino, ma quando\n"
	.string "vinco, i miei pantaloncini sono,\l"
	.string "tipo, più belli. Al tatto, dico.\p"
	.string "Cosa intendo?\n"
	.string "È un po' difficile da spiegare…\l"
	.string "Come posso dire…\l"
	.string "Diventano più morbidi!\p"
	.string "E quando ho lottato con te, {PLAYER}{KUN},\n"
	.string "erano ruvidi e appiccicosi.\p"
	.string "… … … … … …\n"
	.string "Non ci avrai mica creduto?\l"
	.string "Eheheh, tutto qui! Ciao!$"

MatchCall_PersonalizedText33::
	.string "Ahoy!\n"
	.string "Qui {STR_VAR_1}!\p"
	.string "Come sempre, sto pescando\n"
	.string "come un matto!\p"
	.string "Esistono altri posti dove pescare,\n"
	.string "oltre al mare e ai fiumi?\p"
	.string "Ho una voglia matta di lanciare la\n"
	.string "lenza ovunque. Pure in un Varco!\p"
	.string "Oh, accidenti, mannaggia!\n"
	.string "Mi si è aggrovigliata la lenza!\p"
	.string "Devo scappare!\n"
	.string "Trovami nuovi posti dove pescare!$"

MatchCall_PersonalizedText34::
	.string "Ehilà! Sono {STR_VAR_1}.\n"
	.string "Te la stai prendendo comoda?\p"
	.string "Fin da piccolo, sai, sono sempre\n"
	.string "stato un tipo tranquillo, eh?\p"
	.string "Mai stato uno che si agita\n"
	.string "o che fa le cose di fretta.\p"
	.string "Eppure, guarda un po',\n"
	.string "adesso sono un Triatleta.\p"
	.string "Non si sa mai dove ti porta la vita,\n"
	.string "se capisci cosa intendo.\p"
	.string "Ora sei un Allenatore, ma chi lo sa\n"
	.string "cosa ti riserva il futuro, eh?\p"
	.string "Immaginati come insegnante,\n"
	.string "o magari artista. Forte, eh?\p"
	.string "Ma ehi, niente stress. Con calma.\n"
	.string "Ci si vede in giro.$"

MatchCall_PersonalizedText35::
	.string "Sono {STR_VAR_1}!\n"
	.string "Sto pedalando proprio adesso.\p"
	.string "Adoro nuotare e correre,\n"
	.string "ma la bici è il mio primo amore!\p"
	.string "Mi sembra che tutto il mio corpo\n"
	.string "diventi una cosa sola col vento.\p"
	.string "È esaltante, come se stessi\n"
	.string "volando!\p"
	.string "Bene! Oggi batterò il record\n"
	.string "della Pista Ciclabile!\p"
	.string "Dovresti provarci anche tu!\n"
	.string "A presto!$"

MatchCall_PersonalizedText36::
	.string "Ehi, sono {STR_VAR_1}! Sono nel bel\n"
	.string "mezzo di un triathlon!\p"
	.string "Ma per due chiacchiere il tempo\n"
	.string "lo trovo sempre!\p"
	.string "Allenarsi con i Pokémon\n"
	.string "è una vera goduria!\p"
	.string "Senza bisogno di parole, siamo\n"
	.string "in sintonia, come un cuore solo.\p"
	.string "È fonte d'ispirazione!\p"
	.string "Uff… Parlare mentre corro…\n"
	.string "Mi sto sfinendo…\l"
	.string "Uff… Devo… andare…$"

MatchCall_PersonalizedText37::
	.string "Ciao, sono {STR_VAR_1}.\n"
	.string "Se vuoi migliorare la resistenza,\l"
	.string "allenati in alta quota!\p"
	.string "Prova a correre in cima a un monte.\n"
	.string "Resterai senza fiato in un attimo!\p"
	.string "Anch'io sto finendo l'ossigeno!\n"
	.string "A presto!$"

MatchCall_PersonalizedText38::
	.string "Oh, sono {STR_VAR_1}, ciao.\p"
	.string "Nuoto tantissimo, ma non riesco\n"
	.string "ancora ad arrivare a Iridopoli.\p"
	.string "Forse sto solo girando in tondo.\p"
	.string "No, no, non è possibile.\n"
	.string "Wahahaha.\l"
	.string "Stammi bene!$"

MatchCall_PersonalizedText39::
	.string "Ehi, sono {STR_VAR_1}…\n"
	.string "Ops!\p"
	.string "Splash!\p"
	.string "Blub-blub-blub-blub…\p"
	.string "Splosh!\p"
	.string "Pfff-pfff! Pfff-pfff!\p"
	.string "Ehi! Scusa tanto!\n"
	.string "Mi ero appena messo l'olio solare.\p"
	.string "E il PokéNav mi è scivolato di mano,\n"
	.string "dritto in acqua!\p"
	.string "Però il PokéNav della Devon è un\n"
	.string "osso duro. Ha retto al tuffo!\p"
	.string "Comunque, ora sto prendendo il sole,\n"
	.string "quindi ci sentiamo un'altra volta.$"

MatchCall_PersonalizedText40::
	.string "Ciao, sono {STR_VAR_1}.\p"
	.string "Delle tre prove del triathlon,\n"
	.string "il nuoto è la mia preferita.\p"
	.string "Ma se resto in mare troppo a lungo,\n"
	.string "non diventerò tutta raggrinzita?\p"
	.string "Uh, il triathlon è una prova di\n"
	.string "resistenza durissima! Ciao!$"

MatchCall_PersonalizedText41::
	.string "Ciao, {PLAYER}{KUN}.\n"
	.string "Sono {STR_VAR_1}.\p"
	.string "Come stanno i tuoi Pokémon?\p"
	.string "I miei Pokémon Drago sembrano\n"
	.string "in forma smagliante. A presto.$"

MatchCall_PersonalizedText42::
	.string "Sono {STR_VAR_1}.\p"
	.string "Il mio {STR_VAR_2} si è fatto ancora\n"
	.string "più forte dell'ultima volta.\p"
	.string "Non perderò di nuovo contro di te.\n"
	.string "Aspetta e vedrai!\p"
	.string "Ci si vede!$"

MatchCall_PersonalizedText43::
	.string "Sono io, {STR_VAR_1}.\p"
	.string "Ho continuato a studiare\n"
	.string "l'arte di nascondersi.\p"
	.string "Ma sono diventato troppo bravo.\n"
	.string "Nessuno riesce più a trovarmi.\l"
	.string "Il successo mi fa sentire solo…\p"
	.string "Svanisco come il fumo!\n"
	.string "Addio!$"

MatchCall_PersonalizedText44::
	.string "Sono {STR_VAR_1}.\n"
	.string "Mi alleno senza sosta da allora.\p"
	.string "Il mio {STR_VAR_2} sta diventando\n"
	.string "davvero forte.\p"
	.string "Allenarsi in spiaggia funziona,\n"
	.string "proprio come pensavo. Ciao!$"

MatchCall_PersonalizedText45::
	.string "Come va?\n"
	.string "Sono {STR_VAR_1}.\p"
	.string "Chissà quando smetterà di cadere\n"
	.string "questa orribile cenere vulcanica…\p"
	.string "Se si accumula troppo, coprirà\n"
	.string "i disegni del mio parasole…\p"
	.string "Promettiamoci di rivederci!$"

MatchCall_PersonalizedText46::
	.string "Ciao, sono {STR_VAR_1}.\p"
	.string "Lo sapevi che in mare si galleggia\n"
	.string "più facilmente che in piscina?\p"
	.string "Basta stare fermi e il corpo\n"
	.string "galleggia da solo.\p"
	.string "Ma se galleggi troppo a lungo,\n"
	.string "attento a non farti trascinare\l"
	.string "troppo al largo.\p"
	.string "…Ma dove sono finita, a proposito?\n"
	.string "Meglio che vada!$"

MatchCall_PersonalizedText47::
	.string "Oh, {PLAYER}{KUN}, ciao!\n"
	.string "Sono {STR_VAR_1}.\l"
	.string "Adesso sono in montagna.\p"
	.string "Ma il terreno è troppo irregolare.\n"
	.string "Qui non riesco a piantare la tenda…\p"
	.string "Oh, mi è venuta un'idea geniale!\p"
	.string "Magari i miei Pokémon possono\n"
	.string "spianarmi il terreno!\p"
	.string "Ci provo subito!\n"
	.string "Ciao ciao!$"

MatchCall_PersonalizedText48::
	.string "Oh, ciao, ciao, sono {STR_VAR_1}!\p"
	.string "Alleno i Pokémon insieme a Liv!\n"
	.string "Ci stiamo impegnando tantissimo!\p"
	.string "Se ci impegniamo ancora di più,\n"
	.string "diventeremo le numero uno? Ciao!$"

MatchCall_PersonalizedText49::
	.string "Sono {STR_VAR_1}!\p"
	.string "Sono un Marinaio, ma adesso non\n"
	.string "sono su una nave.\p"
	.string "E mi chiedo: come si chiama un\n"
	.string "Marinaio sulla terraferma?\p"
	.string "È quello a cui penso mentre\n"
	.string "guardo le onde all'orizzonte.\p"
	.string "Va bene, alla prossima!$"

MatchCall_PersonalizedText50::
	.string "Sono {STR_VAR_1}.\n"
	.string "Allora? Altri Pokémon catturati?\p"
	.string "Se ne catturi uno nuovo, devi\n"
	.string "venire a farmelo vedere. Magari\l"
	.string "uno arrivato da un Varco!\p"
	.string "Non te lo chiederò in regalo, giuro.\n"
	.string "Ti aspetto. Ciao.$"

MatchCall_PersonalizedText51::
	.string "Sono {STR_VAR_1}.\p"
	.string "Stai allevando i tuoi Pokémon\n"
	.string "nel modo migliore?\p"
	.string "Qui dove sono io l'aria è pulita.\n"
	.string "È l'ambiente perfetto per\l"
	.string "crescere i Pokémon.\p"
	.string "Se vuoi dedicarti all'allevamento\n"
	.string "dei Pokémon, vieni qui in zona\l"
	.string "{STR_VAR_2}. Abbi cura di te.$"

MatchCall_PersonalizedText52::
	.string "Ciao, sono {STR_VAR_1}.\p"
	.string "Ho dato una Pokémella al mio\n"
	.string "{STR_VAR_2}. Gli è piaciuta tanto.\p"
	.string "Pare che i Pokémon abbiano gusti\n"
	.string "precisi in fatto di Pokémelle.\p"
	.string "Lo trovo davvero affascinante.\n"
	.string "Abbi cura di te.$"

MatchCall_PersonalizedText53::
	.string "Sono {STR_VAR_1}.\p"
	.string "Se collabori con i Pokémon,\n"
	.string "si sta bene anche nella natura.\p"
	.string "Tutti dovrebbero capirlo e\n"
	.string "collaborare di più con i Pokémon.\p"
	.string "Sarebbe l'ideale.\n"
	.string "Lo penso davvero.\p"
	.string "Secondo me sei sulla strada giusta!\n"
	.string "Ci sentiamo!$"

MatchCall_PersonalizedText54::
	.string "Ciao, sono {STR_VAR_1}! Sì, quella\n"
	.string "che è sempre pronta a tutto!\p"
	.string "{PLAYER}{KUN}, hai abbastanza strumenti?\n"
	.string "La tua squadra è in piena forma?\p"
	.string "Tenere sempre tutto in perfetto\n"
	.string "ordine è il segreto per portare\l"
	.string "avanti il tuo viaggio.\p"
	.string "Meglio che vada a controllare\n"
	.string "le mie scorte! Occhi aperti!$"

MatchCall_PersonalizedText55::
	.string "Sono {STR_VAR_1}!\n"
	.string "Sono {STR_VAR_1}!\p"
	.string "{STR_VAR_2} è un posto molto\n"
	.string "trafficato, così ogni giorno mi\l"
	.string "sfidano Allenatori di ogni tipo.\p"
	.string "Oggi ho vinto cinque lotte e ne ho\n"
	.string "perse solo tre!\p"
	.string "E a te com'è andata oggi?\n"
	.string "Raccontamelo la prossima volta, ok?$"

MatchCall_PersonalizedText56::
	.string "Sono io, {STR_VAR_1}.\p"
	.string "Sono popolare perché ho un sacco\n"
	.string "di Pokémon Coleottero, giusto?\p"
	.string "Beh, oggi ho portato a scuola\n"
	.string "un po' dei miei insetti preferiti.\p"
	.string "E una ragazza che mi piace si è\n"
	.string "messa a piangere! Ridi pure.\p"
	.string "Devo spiegarle perché i Pokémon\n"
	.string "Coleottero sono così fantastici.\p"
	.string "Sniff…\n"
	.string "Ciao!$"

MatchCall_PersonalizedText57::
	.string "Anf! Anf! Anf! Anf!\p"
	.string "Ciao! Sono {STR_VAR_1}! Anf! Anf!\p"
	.string "Chiacchierare…\n"
	.string "mentre scalo…\l"
	.string "è un esercizio durissimo… Anf! Anf!\p"
	.string "Urgh! Uff…\n"
	.string "Ora si fa più ripido…\l"
	.string "Ci sentiamo… un'altra volta…\l"
	.string "Anf! Anf! Anf!$"

MatchCall_PersonalizedText58::
	.string "Oh, ciao!\p"
	.string "Sto ancora cercando tesori\n"
	.string "insieme a Kira!\p"
	.string "Forse qui di tesori\n"
	.string "non ce ne sono proprio…\p"
	.string "Ma la cosa importante è cercare\n"
	.string "fianco a fianco con Kira.\p"
	.string "Oh, ehi, Kira!\n"
	.string "P-perché sei arrabbiata?\p"
	.string "Non ti sto ignorando, tesoro!\n"
	.string "Sei la mia unica e sola!\p"
	.string "…{PLAYER}, devo andare, ciao!$"

MatchCall_PersonalizedText59::
	.string "Sono {STR_VAR_1}!\p"
	.string "Sono tornato alla Palestra di\n"
	.string "Bluruvia per allenarmi.\p"
	.string "Rudi, il Capopalestra, sembra\n"
	.string "ancora più forte di prima.\p"
	.string "Dice che le onde selvagge\n"
	.string "lo hanno temprato…\p"
	.string "Ma resta affascinante come sempre.\n"
	.string "Le ragazze lo adorano!\l"
	.string "Sinceramente, un po' lo invidio.\p"
	.string "Mi chiedo… I lottatori degli altri\n"
	.string "mondi saranno tutti come Rudi?\p"
	.string "Sai, sudati, un po' puzzolenti,\n"
	.string "sempre lì a dire “Cavalca l'onda!”,\l"
	.string "roba del genere.\p"
	.string "Ma ehi, questa gelosia non è\n"
	.string "molto dignitosa, vero?\p"
	.string "Facciamo finta che questa chiamata\n"
	.string "non ci sia mai stata, eh? Ciao!$"

MatchCall_PersonalizedText60::
	.string "È un piacere chiacchierare con\n"
	.string "un giovane Allenatore come te.\p"
	.string "Sono sicuro che amerai i Pokémon\n"
	.string "a qualunque età.\p"
	.string "Non sarebbe bello avere\n"
	.string "un'intesa come la nostra?\p"
	.string "Ma certo, {PLAYER}{KUN}, tu godi già\n"
	.string "della fiducia e dell'affetto\l"
	.string "dei tuoi Pokémon.\p"
	.string "Hai già tutto ciò che serve per\n"
	.string "legami lunghi e duraturi!\p"
	.string "Ahahah!\n"
	.string "Non scoraggiarti mai!$"

MatchCall_PersonalizedText61::
	.string "Ciao, sono {STR_VAR_1}!\n"
	.string "Abbiamo appena vinto una lotta!\p"
	.string "Non vinciamo spesso, ma era contro\n"
	.string "un Nuotatore tutto muscoli.\p"
	.string "Mia sorella era furiosa!\p"
	.string "Voleva fingersi debole\n"
	.string "per fare colpo su di lui!\p"
	.string "Mi sgrida sempre, che vinciamo\n"
	.string "o che perdiamo!\p"
	.string "{PLAYER}{KUN}, la prossima volta\n"
	.string "le dici qualcosa tu?\p"
	.string "Ok, ciao!$"

MatchCall_PersonalizedText62::
	.string "Sono {STR_VAR_1}, sì.\n"
	.string "Ieri sono partito per mare.\p"
	.string "Speravo di trovare nuove rovine\n"
	.string "da esplorare.\p"
	.string "Ma le maree, chissà come, mi hanno\n"
	.string "riportato al punto di partenza.\p"
	.string "E sono ancora scarso a lottare…\n"
	.string "Prendimi pure in giro…\l"
	.string "Ma non mi arrenderò.\p"
	.string "Verrà il mio giorno, quando\n"
	.string "scoprirò delle rovine nuove!\p"
	.string "Ho detto tutto!\n"
	.string "Alla prossima!$"

MatchCall_PersonalizedText63::
	.string "Ahoy!\n"
	.string "Sono io, {STR_VAR_1}!\l"
	.string "Sono sul Percorso 108!\l"
	.string "Cioè, dove sto sempre!\p"
	.string "Oggi una splendida Nuotatrice\n"
	.string "mi è passata accanto a nuoto!\p"
	.string "Così l'ho spaventata con un urlo!\p"
	.string "Lei mi ha fulminato con lo sguardo!\p"
	.string "È tutto dal Percorso 108!\n"
	.string "In diretta, {STR_VAR_1}!$"

MatchCall_PersonalizedText64::
	.string "Sono {STR_VAR_1}!\p"
	.string "Sono un po' impegnata, ma volevo\n"
	.string "farti sapere che anche oggi\l"
	.string "ho battuto cinque Allenatori.\p"
	.string "Se continuo con questo ritmo,\n"
	.string "la prossima volta batterò anche te.\p"
	.string "Credo che saremo ottimi rivali,\n"
	.string "io e te. Ciao, alla prossima!$"

MatchCall_BattleFrontierStreakText1::
	.string "Ciao! Sono {STR_VAR_1}.\n"
	.string "Ho saputo la notizia!\p"
	.string "Dicono che sei andato fortissimo\n"
	.string "nella sfida {STR_VAR_2}.\p"
	.string "{STR_VAR_3} vittorie di fila? Pazzesco!\n"
	.string "A presto!$"

MatchCall_BattleFrontierStreakText2::
	.string "Ciao, sono {STR_VAR_1}!\n"
	.string "Ho sentito parlare di te!\p"
	.string "Dicono che hai vinto {STR_VAR_3} lotte\n"
	.string "di fila nella sfida {STR_VAR_2}.\p"
	.string "Niente male! Devo impegnarmi\n"
	.string "di più anch'io! A presto!$"

MatchCall_BattleFrontierStreakText3::
	.string "Ehilà, {PLAYER}!\n"
	.string "Sono io, {STR_VAR_1}.\p"
	.string "Ho sentito che hai fatto faville al\n"
	.string "Parco Lotta: {STR_VAR_2}!\p"
	.string "Una serie di {STR_VAR_3} vittorie…\n"
	.string "È un gran bel record, eh?\p"
	.string "Devo darmi una mossa anch'io!\n"
	.string "Ci sentiamo!$"

MatchCall_BattleFrontierStreakText4::
	.string "Ehi, {PLAYER}{KUN}.\n"
	.string "Sono {STR_VAR_1}. Come va?\p"
	.string "Gira voce che tu abbia messo\n"
	.string "in fila {STR_VAR_3} vittorie\l"
	.string "nella sfida {STR_VAR_2}.\p"
	.string "Devo darci dentro anch'io.\n"
	.string "Ciao!$"

MatchCall_BattleFrontierStreakText5::
	.string "Ciao ciao, {PLAYER}{KUN}!\n"
	.string "Sono {STR_VAR_1}.\p"
	.string "Ho saputo! Sfida {STR_VAR_2}:\n"
	.string "{STR_VAR_3} vittorie di fila?\l"
	.string "Ma dai, roba da matti!\p"
	.string "Devo allenare di più i miei Pokémon.\n"
	.string "A presto!$"

MatchCall_BattleFrontierStreakText6::
	.string "Ehi, {PLAYER}{KUN}.\n"
	.string "Sono {STR_VAR_1}. Come va?\p"
	.string "Senti, ho saputo che hai messo a\n"
	.string "segno {STR_VAR_3} vittorie consecutive\l"
	.string "nella sfida {STR_VAR_2}.\p"
	.string "Mi hai dato la carica: ora penso\n"
	.string "solo ad allenare la mia squadra.$"

MatchCall_BattleFrontierStreakText7::
	.string "…Ehm, {PLAYER}{KUN}?\n"
	.string "Sono {STR_VAR_1}…\p"
	.string "Ah, sì, eri al Parco Lotta,\n"
	.string "nella sfida {STR_VAR_2}, no?\p"
	.string "E hai vinto {STR_VAR_3} lotte di fila.\p"
	.string "Oh! Un Pokémon raro uscito da un\n"
	.string "Varco! Devo andare!$"

MatchCall_BattleFrontierStreakText8::
	.string "Oh, {PLAYER}{KUN}, buongiorno!\n"
	.string "Sono {STR_VAR_1}.\l"
	.string "Spero che tu stia bene.\p"
	.string "Ma che domande, certo che stai bene!\n"
	.string "Ho saputo delle {STR_VAR_3} vittorie di\l"
	.string "fila nella sfida {STR_VAR_2}.\p"
	.string "Davvero notevole!\n"
	.string "Ti auguro di continuare così.$"

MatchCall_BattleFrontierStreakText9::
	.string "Oh, {PLAYER}{KUN}, ciao!\n"
	.string "Sono {STR_VAR_1}!\p"
	.string "Ho saputo! {STR_VAR_3} vittorie di fila\n"
	.string "nella sfida {STR_VAR_2}!\p"
	.string "Troppo forte!\n"
	.string "Devo impegnarmi di più anch'io!$"

MatchCall_BattleFrontierStreakText10::
	.string "Oh, {PLAYER}{KUN}, ciao…\n"
	.string "Sono {STR_VAR_1}.\p"
	.string "Hai vinto {STR_VAR_3} lotte consecutive\n"
	.string "nella sfida {STR_VAR_2}?\p"
	.string "È un bel traguardo…\n"
	.string "Devo impegnarmi di più.$"

MatchCall_BattleFrontierStreakText11::
	.string "Ah, {PLAYER}{KUN}.\n"
	.string "Sono {STR_VAR_1}.\p"
	.string "Dicono che sei il terrore\n"
	.string "del Parco Lotta.\p"
	.string "Nella sfida {STR_VAR_2} hai\n"
	.string "vinto, che so, {STR_VAR_3} di fila?\p"
	.string "Ci sai fare, tu.\n"
	.string "Chissà quanti ne vincerei io…$"

MatchCall_BattleFrontierStreakText12::
	.string "Salve, {PLAYER}{KUN}.\n"
	.string "Sono io, {STR_VAR_1}.\l"
	.string "Stai bene?\p"
	.string "Mi è giunta voce di una tua impresa:\n"
	.string "{STR_VAR_3} vittorie di fila in un posto\l"
	.string "chiamato {STR_VAR_2}, vero?\p"
	.string "Roba da raccontare ai nipoti!\n"
	.string "Alla prossima!$"

MatchCall_BattleFrontierStreakText13::
	.string "Oh, ciao, {PLAYER}{KUN}!\n"
	.string "Sono {STR_VAR_1}!\l"
	.string "Spero che tu stia bene.\p"
	.string "Hai vinto {STR_VAR_3} lotte di fila,\n"
	.string "nella sfida {STR_VAR_2}, dicono.\p"
	.string "Che energia, ti ammiro!\n"
	.string "Ciao, caro.$"

MatchCall_BattleFrontierStreakText14::
	.string "Oh, ciao, {PLAYER}{KUN}.\n"
	.string "Sono {STR_VAR_1}.\p"
	.string "Ho sentito parlare di te!\n"
	.string "Non hai appena vinto {STR_VAR_3} lotte\l"
	.string "di fila nella sfida {STR_VAR_2}?\p"
	.string "Sei il mio idolo!\n"
	.string "Ciao ciao!$"

MatchCall_BattleFrontierRecordStreakText1::
	.string "Ciao! Sono {STR_VAR_1}.\n"
	.string "Ho sentito la notizia!\p"
	.string "Dicono che sei andato alla grande\n"
	.string "nella sfida {STR_VAR_2}.\p"
	.string "{STR_VAR_3} vittorie di fila? Pazzesco!\n"
	.string "A presto!$"

MatchCall_BattleFrontierRecordStreakText2::
	.string "Ciao, sono {STR_VAR_1}!\n"
	.string "Ho sentito parlare di te!\p"
	.string "Dicono che hai vinto {STR_VAR_3} lotte\n"
	.string "di fila nella sfida {STR_VAR_2}.\p"
	.string "Che forza! Devo darmi da fare\n"
	.string "anch'io! A presto!$"

MatchCall_BattleFrontierRecordStreakText3::
	.string "Ehilà, {PLAYER}!\n"
	.string "Sono io, {STR_VAR_1}.\p"
	.string "Ho saputo che hai fatto faville\n"
	.string "nella sfida {STR_VAR_2}!\p"
	.string "{STR_VAR_3} vittorie di fila…\n"
	.string "Questo sì che è un record, eh?\p"
	.string "Devo darmi una mossa anch'io!\n"
	.string "Ci sentiamo!$"

MatchCall_BattleFrontierRecordStreakText4::
	.string "Ehi, {PLAYER}{KUN}.\n"
	.string "Sono {STR_VAR_1}. Che si dice?\p"
	.string "Gira voce che tu abbia infilato\n"
	.string "{STR_VAR_3} vittorie di fila\l"
	.string "nella sfida {STR_VAR_2}.\p"
	.string "Devo alzare il livello anch'io.\n"
	.string "A presto!$"

MatchCall_BattleFrontierRecordStreakText5::
	.string "Ciao ciao, {PLAYER}{KUN}!\n"
	.string "Sono {STR_VAR_1}.\p"
	.string "Nella sfida {STR_VAR_2} hai vinto\n"
	.string "{STR_VAR_3} lotte di fila?\l"
	.string "Ma dai, roba da matti!\p"
	.string "Io? Diciamo che sto migliorando.\n"
	.string "A presto!$"

MatchCall_BattleFrontierRecordStreakText6::
	.string "Ehi, {PLAYER}{KUN}.\n"
	.string "Sono {STR_VAR_1}. Come va?\p"
	.string "A proposito, ho saputo che hai messo\n"
	.string "a segno {STR_VAR_3} vittorie di fila\l"
	.string "nella sfida {STR_VAR_2}.\p"
	.string "Devo impegnarmi di più anch'io!\n"
	.string "A presto!$"

MatchCall_BattleFrontierRecordStreakText7::
	.string "…Ehm, {PLAYER}{KUN}?\n"
	.string "Sono {STR_VAR_1}…\p"
	.string "Ah, già, sei stato al Parco Lotta,\n"
	.string "nella sfida {STR_VAR_2}, vero?\p"
	.string "E hai vinto {STR_VAR_3} lotte di fila.\p"
	.string "Oh! Laggiù, un Pokémon raro!\n"
	.string "Scusa, scappo!$"

MatchCall_BattleFrontierRecordStreakText8::
	.string "Oh, {PLAYER}{KUN}, buongiorno!\n"
	.string "Sono {STR_VAR_1}.\l"
	.string "Spero che tu stia bene.\p"
	.string "Ma certo che stai bene! Ho saputo\n"
	.string "delle tue {STR_VAR_3} vittorie di fila\l"
	.string "nella sfida {STR_VAR_2}.\p"
	.string "Davvero notevole! Devo curare\n"
	.string "meglio anche i miei Pokémon!$"

MatchCall_BattleFrontierRecordStreakText9::
	.string "Oh, {PLAYER}{KUN}, ciao!\n"
	.string "Sono {STR_VAR_1}!\p"
	.string "Wow! Nella sfida {STR_VAR_2}\n"
	.string "hai vinto {STR_VAR_3} lotte di fila!\p"
	.string "Fortissimo!\n"
	.string "Devo impegnarmi di più anch'io!$"

MatchCall_BattleFrontierRecordStreakText10::
	.string "Oh, {PLAYER}{KUN}, ciao…\n"
	.string "Sono {STR_VAR_1}.\p"
	.string "Nella sfida {STR_VAR_2} hai vinto\n"
	.string "{STR_VAR_3} lotte consecutive?\p"
	.string "È proprio un bel risultato…\n"
	.string "Devo impegnarmi di più.$"

MatchCall_BattleFrontierRecordStreakText11::
	.string "Ah, {PLAYER}{KUN}.\n"
	.string "Sono {STR_VAR_1}.\p"
	.string "Dicono che sei il terrore\n"
	.string "del Parco Lotta.\p"
	.string "Nella sfida {STR_VAR_2} sei\n"
	.string "arrivato a quota {STR_VAR_3}, no?\p"
	.string "Ci sai fare, tu.\n"
	.string "Chissà fin dove arriverei io…$"

MatchCall_BattleFrontierRecordStreakText12::
	.string "Salve, {PLAYER}{KUN}.\n"
	.string "Sono io, {STR_VAR_1}.\l"
	.string "Stai bene?\p"
	.string "Qualcuno mi ha raccontato di te:\n"
	.string "{STR_VAR_3} vittorie di fila in un posto\l"
	.string "chiamato {STR_VAR_2}, giusto?\p"
	.string "Che storia, ragazzo mio!\n"
	.string "Alla prossima!$"

MatchCall_BattleFrontierRecordStreakText13::
	.string "Oh, ciao, {PLAYER}{KUN}!\n"
	.string "Sono {STR_VAR_1}!\l"
	.string "Spero che tu stia bene.\p"
	.string "Ben {STR_VAR_3} lotte vinte di fila\n"
	.string "nella sfida {STR_VAR_2}!\p"
	.string "Che grinta, ti ammiro!\n"
	.string "Ciao, caro.$"

MatchCall_BattleFrontierRecordStreakText14::
	.string "Oh, ciao, {PLAYER}{KUN}.\n"
	.string "Sono {STR_VAR_1}.\l"
	.string "Ho sentito parlare di te!\p"
	.string "Non hai appena vinto {STR_VAR_3} lotte\n"
	.string "di fila nella sfida {STR_VAR_2}?\p"
	.string "Sei il mio idolo!\n"
	.string "Ciao ciao!$"

MatchCall_BattleDomeText1::
	.string "Ciao! {PLAYER}?\n"
	.string "Sono {STR_VAR_1}!\l"
	.string "Ho sentito la notizia!\p"
	.string "Hai vinto il torneo della\n"
	.string "{STR_VAR_2} {STR_VAR_3} volte?\p"
	.string "Pazzesco! Devo migliorare!\n"
	.string "A presto!$"

MatchCall_BattleDomeText2::
	.string "Ciao, sono {STR_VAR_1}!\n"
	.string "Ho sentito parlare di te!\p"
	.string "Dicono che hai vinto ben {STR_VAR_3}\n"
	.string "tornei alla {STR_VAR_2}.\p"
	.string "Fantastico! Chissà se un giorno\n"
	.string "vincerò un torneo anch'io…$"

MatchCall_BattleDomeText3::
	.string "Ehilà, {PLAYER}!\n"
	.string "Sono io, {STR_VAR_1}.\l"
	.string "Come te la passi?\p"
	.string "Ho saputo dei tuoi {STR_VAR_3} tornei\n"
	.string "vinti alla {STR_VAR_2}!\p"
	.string "La prossima volta fanne uno in più!\n"
	.string "Ci sentiamo!$"

MatchCall_BattleDomeText4::
	.string "Ehi, {PLAYER}{KUN}.\n"
	.string "Sono {STR_VAR_1}.\p"
	.string "Ho saputo che hai vinto il torneo\n"
	.string "della {STR_VAR_2} {STR_VAR_3} volte.\p"
	.string "Ti stai dando da fare, eh?\n"
	.string "Cercherò di starti dietro!$"

MatchCall_BattleDomeText5::
	.string "Ciao ciao, {PLAYER}{KUN}!\n"
	.string "Sono {STR_VAR_1}.\p"
	.string "Hai stravinto {STR_VAR_3} volte\n"
	.string "alla {STR_VAR_2}, ho saputo!\p"
	.string "Devo darmi una mossa anch'io!\n"
	.string "A presto!$"

MatchCall_BattleDomeText6::
	.string "Ehi, {PLAYER}{KUN}?\n"
	.string "Sono {STR_VAR_1}. Come va?\p"
	.string "A proposito, ho saputo che hai vinto\n"
	.string "il torneo {STR_VAR_3} volte\l"
	.string "alla {STR_VAR_2}.\p"
	.string "Devo allenare i miei Pokémon prima\n"
	.string "che tu mi lasci indietro del tutto.$"

MatchCall_BattleDomeText7::
	.string "{PLAYER}{KUN}?\n"
	.string "Sono {STR_VAR_1}.\p"
	.string "Sei stato alla {STR_VAR_2}\n"
	.string "e hai vinto {STR_VAR_3} tornei?\p"
	.string "Forte. Senti, hai preso qualche\n"
	.string "Pokémon raro, ultimamente?\p"
	.string "Ah, ecco.\n"
	.string "Ok, ciao.$"

MatchCall_BattleDomeText8::
	.string "Oh, {PLAYER}{KUN}, buongiorno!\n"
	.string "Sono {STR_VAR_1}.\l"
	.string "Spero che tu stia bene.\l"
	.string "Ma certo che stai bene!\p"
	.string "Ho saputo dei tuoi {STR_VAR_3} tornei\n"
	.string "vinti alla {STR_VAR_2}.\p"
	.string "Crescerò i miei Pokémon come te.\n"
	.string "Alla prossima.$"

MatchCall_BattleDomeText9::
	.string "Oh, {PLAYER}{KUN}, ciao!\n"
	.string "Sono {STR_VAR_1}!\p"
	.string "Ho saputo! Hai vinto il torneo\n"
	.string "{STR_VAR_3} volte alla {STR_VAR_2}!\p"
	.string "Troppo forte!\n"
	.string "Devo impegnarmi di più anch'io!$"

MatchCall_BattleDomeText10::
	.string "Oh, {PLAYER}{KUN}, ciao.\n"
	.string "Sono {STR_VAR_1}.\p"
	.string "Hai vinto {STR_VAR_3} tornei di fila\n"
	.string "alla {STR_VAR_2}?\p"
	.string "È un bel traguardo…\n"
	.string "Devo impegnarmi di più.$"

MatchCall_BattleDomeText11::
	.string "Ah, {PLAYER}{KUN}.\n"
	.string "Sono {STR_VAR_1}.\p"
	.string "Dicono che sei il terrore\n"
	.string "della {STR_VAR_2}.\p"
	.string "Hai vinto, quanto, {STR_VAR_3} tornei\n"
	.string "di fila, ormai?\p"
	.string "Chissà se un giorno vincerò\n"
	.string "un torneo anch'io…\p"
	.string "…Praticamente impossibile, eh?\n"
	.string "Be', ci si sente!$"

MatchCall_BattleDomeText12::
	.string "Salve, {PLAYER}{KUN}.\n"
	.string "Sono io, {STR_VAR_1}.\l"
	.string "Stai bene?\p"
	.string "Hai vinto {STR_VAR_3} tornei in un posto\n"
	.string "chiamato {STR_VAR_2}?\p"
	.string "Roba da raccontare ai nipoti!\n"
	.string "Alla prossima!$"

MatchCall_BattleDomeText13::
	.string "Oh, ciao, {PLAYER}{KUN}!\n"
	.string "Sono {STR_VAR_1}!\l"
	.string "Spero che tu stia bene.\p"
	.string "Dicono che hai vinto {STR_VAR_3}\n"
	.string "tornei alla {STR_VAR_2}.\p"
	.string "Che energia, ti ammiro!\n"
	.string "Ciao, caro.$"

MatchCall_BattleDomeText14::
	.string "Oh, ciao, {PLAYER}{KUN}.\n"
	.string "Sono {STR_VAR_1}.\l"
	.string "Ho sentito parlare di te!\p"
	.string "Non hai vinto {STR_VAR_3} tornei\n"
	.string "alla {STR_VAR_2}?\p"
	.string "Sei il mio idolo!\n"
	.string "Alla prossima!$"

MatchCall_BattlePikeText1::
	.string "Ciao! {PLAYER}?\n"
	.string "Sono {STR_VAR_1}!\l"
	.string "Ho sentito la notizia!\p"
	.string "Hai superato {STR_VAR_3} stanze\n"
	.string "nella sfida {STR_VAR_2}!\p"
	.string "Fantastico!\n"
	.string "A presto!$"

MatchCall_BattlePikeText2::
	.string "Ciao, sono {STR_VAR_1}!\n"
	.string "Ho sentito parlare di te!\p"
	.string "Dicono che hai superato {STR_VAR_3}\n"
	.string "stanze nella sfida {STR_VAR_2}.\p"
	.string "Devo impegnarmi molto di più!\n"
	.string "Ciao!$"

MatchCall_BattlePikeText3::
	.string "Ehilà, {PLAYER}!\n"
	.string "Sono io, {STR_VAR_1}.\l"
	.string "Come te la passi?\p"
	.string "Ho saputo che hai superato {STR_VAR_3}\n"
	.string "stanze nella sfida {STR_VAR_2}!\p"
	.string "La prossima volta fai ancora meglio!\n"
	.string "Ci sentiamo!$"

MatchCall_BattlePikeText4::
	.string "Ehi, {PLAYER}{KUN}.\n"
	.string "Sono {STR_VAR_1}.\p"
	.string "Alla sfida {STR_VAR_2}, dicono,\n"
	.string "hai spazzato via {STR_VAR_3} stanze.\p"
	.string "Devo allenare i miei Pokémon per\n"
	.string "starti dietro!$"

MatchCall_BattlePikeText5::
	.string "Ciao ciao, {PLAYER}{KUN}!\n"
	.string "Sono {STR_VAR_1}.\p"
	.string "Ho saputo che hai passato {STR_VAR_3}\n"
	.string "stanze nella sfida {STR_VAR_2}.\p"
	.string "Devo darmi una mossa anch'io!\n"
	.string "A presto!$"

MatchCall_BattlePikeText6::
	.string "Ehi, {PLAYER}{KUN}?\n"
	.string "Sono {STR_VAR_1}. Come va?\p"
	.string "A proposito, ho saputo che hai\n"
	.string "superato {STR_VAR_3} stanze\l"
	.string "nella sfida {STR_VAR_2}.\p"
	.string "Devo allenare i miei Pokémon prima\n"
	.string "che tu mi lasci ancora più indietro.$"

MatchCall_BattlePikeText7::
	.string "{PLAYER}{KUN}?\n"
	.string "Sono {STR_VAR_1}.\p"
	.string "Eri nella sfida {STR_VAR_2}\n"
	.string "e hai superato {STR_VAR_3} stanze?\p"
	.string "Una bomba.\p"
	.string "Oh! Un Varco… e ne esce un Pokémon\n"
	.string "raro! Ok, ciao.$"

MatchCall_BattlePikeText8::
	.string "Oh, {PLAYER}{KUN}, buongiorno!\n"
	.string "Sono {STR_VAR_1}.\l"
	.string "Spero che tu stia bene.\l"
	.string "Ma certo che stai bene!\p"
	.string "Nella sfida {STR_VAR_2} hai\n"
	.string "superato {STR_VAR_3} stanze, vero?\p"
	.string "Davvero notevole!\n"
	.string "Crescerò i miei Pokémon come te.\l"
	.string "Alla prossima.$"

MatchCall_BattlePikeText9::
	.string "Oh, {PLAYER}{KUN}, ciao!\n"
	.string "Sono {STR_VAR_1}!\p"
	.string "Wow! Nella sfida {STR_VAR_2}\n"
	.string "hai superato {STR_VAR_3} stanze!\p"
	.string "Troppo forte!\n"
	.string "Devo impegnarmi di più anch'io!$"

MatchCall_BattlePikeText10::
	.string "Oh, {PLAYER}{KUN}, ciao.\n"
	.string "Sono {STR_VAR_1}.\p"
	.string "Hai superato {STR_VAR_3} stanze\n"
	.string "nella sfida {STR_VAR_2}?\p"
	.string "È un bel traguardo…\n"
	.string "Devo impegnarmi di più.$"

MatchCall_BattlePikeText11::
	.string "Ah, {PLAYER}{KUN}.\n"
	.string "Sono {STR_VAR_1}.\p"
	.string "Dicono che sei il terrore\n"
	.string "della sfida {STR_VAR_2}.\p"
	.string "Ben {STR_VAR_3} stanze superate?\n"
	.string "Mica poco, eh.\p"
	.string "Chissà se un giorno diventerò\n"
	.string "un campione anch'io…\p"
	.string "…Praticamente impossibile, eh?\n"
	.string "Be', ci si sente!$"

MatchCall_BattlePikeText12::
	.string "Salve, {PLAYER}{KUN}.\n"
	.string "Sono io, {STR_VAR_1}.\l"
	.string "Stai bene?\p"
	.string "Hai superato {STR_VAR_3} stanze in un\n"
	.string "posto chiamato {STR_VAR_2}?\p"
	.string "Roba da raccontare ai nipoti!\n"
	.string "Alla prossima!$"

MatchCall_BattlePikeText13::
	.string "Oh, ciao, {PLAYER}{KUN}!\n"
	.string "Sono {STR_VAR_1}!\l"
	.string "Spero che tu stia bene.\p"
	.string "Hai vinto in {STR_VAR_3} stanze\n"
	.string "della sfida {STR_VAR_2}, dicono.\p"
	.string "Che energia, ti ammiro!\n"
	.string "Ciao, caro.$"

MatchCall_BattlePikeText14::
	.string "Oh, ciao, {PLAYER}{KUN}.\n"
	.string "Sono {STR_VAR_1}.\l"
	.string "Ho sentito parlare di te!\p"
	.string "Non hai superato {STR_VAR_3} stanze\n"
	.string "nella sfida {STR_VAR_2}?\p"
	.string "Sei il mio idolo!\n"
	.string "Alla prossima!$"

MatchCall_BattlePyramidText1::
	.string "Ciao! {PLAYER}?\n"
	.string "Sono {STR_VAR_1}!\l"
	.string "Ho sentito la notizia!\p"
	.string "Hai scalato {STR_VAR_3} piani dentro\n"
	.string "la {STR_VAR_2}, giusto?\p"
	.string "Fantastico!\n"
	.string "Dovrei provarci anch'io.$"

MatchCall_BattlePyramidText2::
	.string "Ciao, sono {STR_VAR_1}!\n"
	.string "Ho sentito parlare di te!\p"
	.string "Hai conquistato {STR_VAR_3} piani\n"
	.string "della {STR_VAR_2}, dicono!\p"
	.string "Wow, fantastico!\n"
	.string "Devo allenare anch'io i miei Pokémon!$"

MatchCall_BattlePyramidText3::
	.string "Ehilà, {PLAYER}!\n"
	.string "Sono io, {STR_VAR_1}.\l"
	.string "Come te la passi?\p"
	.string "Ho saputo che hai scalato {STR_VAR_3}\n"
	.string "piani della {STR_VAR_2}!\p"
	.string "La prossima volta fai ancora meglio!\n"
	.string "Ci sentiamo!$"

MatchCall_BattlePyramidText4::
	.string "Ehi, {PLAYER}{KUN}.\n"
	.string "Qui {STR_VAR_1}.\p"
	.string "So che hai scalato {STR_VAR_3} piani\n"
	.string "nella {STR_VAR_2}.\p"
	.string "Devo darmi da fare anch'io,\n"
	.string "o non ti starò mai dietro!$"

MatchCall_BattlePyramidText5::
	.string "Ciao, {PLAYER}{KUN}!\n"
	.string "Sono {STR_VAR_1}.\p"
	.string "Pare che tu sia salito di\n"
	.string "{STR_VAR_3} piani nella {STR_VAR_2}.\p"
	.string "Mi sa che devo darmi una mossa!\n"
	.string "A presto!$"

MatchCall_BattlePyramidText6::
	.string "Ehi, {PLAYER}{KUN}?\n"
	.string "Sono {STR_VAR_1}. Come stai?\p"
	.string "A proposito, so che hai superato\n"
	.string "{STR_VAR_3} piani nella {STR_VAR_2}.\p"
	.string "Devo allenare i miei Pokémon prima\n"
	.string "che tu mi stacchi del tutto.$"

MatchCall_BattlePyramidText7::
	.string "{PLAYER}{KUN}?\n"
	.string "Sono {STR_VAR_1}.\p"
	.string "Sei stato nella {STR_VAR_2}\n"
	.string "e hai superato {STR_VAR_3} piani?\p"
	.string "Forte. C'erano Pokémon rari?\n"
	.string "Magari arrivati da un Varco?\p"
	.string "No, eh?\n"
	.string "Ok, ciao.$"

MatchCall_BattlePyramidText8::
	.string "Oh, {PLAYER}{KUN}, come va?\n"
	.string "Sono {STR_VAR_1}.\l"
	.string "Spero che tu stia bene.\l"
	.string "Ah, ma certo che stai bene.\p"
	.string "Mi hanno detto che hai superato\n"
	.string "{STR_VAR_3} piani nella {STR_VAR_2}.\p"
	.string "Davvero notevole!\n"
	.string "Devo allenare i Pokémon come te.\l"
	.string "Alla prossima.$"

MatchCall_BattlePyramidText9::
	.string "Oh, {PLAYER}{KUN}, ciao!\n"
	.string "Sono {STR_VAR_1}!\p"
	.string "L'ho saputo! Hai superato ben\n"
	.string "{STR_VAR_3} piani nella {STR_VAR_2}!\p"
	.string "Che forza!\n"
	.string "Devo impegnarmi di più anch'io!$"

MatchCall_BattlePyramidText10::
	.string "Oh, {PLAYER}{KUN}, salve.\n"
	.string "Sono {STR_VAR_1}.\p"
	.string "Hai scalato {STR_VAR_3} piani dentro\n"
	.string "la {STR_VAR_2}?\p"
	.string "È un bel traguardo.\n"
	.string "Devo impegnarmi di più.$"

MatchCall_BattlePyramidText11::
	.string "Ah, {PLAYER}{KUN}.\n"
	.string "Sono {STR_VAR_1}.\p"
	.string "Dicono che sei il terrore\n"
	.string "della {STR_VAR_2}.\p"
	.string "Hai superato, quanti, {STR_VAR_3} piani?\n"
	.string "Qualcosa vorrà pur dire.\p"
	.string "Chissà se un giorno diventerò\n"
	.string "anch'io un Campione.\p"
	.string "…Praticamente impossibile, eh?\n"
	.string "Beh, ci vediamo!$"

MatchCall_BattlePyramidText12::
	.string "Salve, {PLAYER}{KUN}.\n"
	.string "Sono io, {STR_VAR_1}.\l"
	.string "Tutto bene?\p"
	.string "Hai superato {STR_VAR_3} piani in\n"
	.string "un posto chiamato {STR_VAR_2}?\p"
	.string "Che storia!\n"
	.string "Ci vediamo!$"

MatchCall_BattlePyramidText13::
	.string "Ah, ciao, {PLAYER}{KUN}!\n"
	.string "Sono {STR_VAR_1}!\l"
	.string "Spero che tu stia bene.\p"
	.string "Si dice in giro che hai scalato\n"
	.string "{STR_VAR_3} piani nella {STR_VAR_2}.\p"
	.string "Ammiro la tua energia!\n"
	.string "A presto.$"

MatchCall_BattlePyramidText14::
	.string "Oh, ciao, {PLAYER}{KUN}.\n"
	.string "Sono {STR_VAR_1}.\l"
	.string "Ho sentito parlare di te!\p"
	.string "Non hai superato {STR_VAR_3} piani\n"
	.string "nella {STR_VAR_2}?\p"
	.string "Sei una fonte d'ispirazione!\n"
	.string "Alla prossima!$"

MatchCall_Text_Mom1::
	.string "Mamma: Tu, tuo padre…\n"
	.string "Siete tutti stregati dai Pokémon.\p"
	.string "Cos'avranno di così speciale?\p"
	.string "Io?\n"
	.string "Io adoro i Pokémon che mi danno\l"
	.string "una mano con le faccende di casa.$"

MatchCall_Text_Mom2::
	.string "Mamma: Ciao, {PLAYER}!\n"
	.string "Tuo padre si è chiuso a chiave\l"
	.string "nella Palestra di Petalipoli.\p"
	.string "Ogni tanto passa da casa.\n"
	.string "Ma appena ha svuotato il frigo,\l"
	.string "torna dritto in Palestra.\p"
	.string "Secondo me perdere contro di te\n"
	.string "gli ha bruciato parecchio!$"

MatchCall_Text_Mom3::
	.string "Mamma: {PLAYER}…\n"
	.string "Non pensare a me né alla casa.\p"
	.string "Consuma quelle Scarpe da Corsa\n"
	.string "finché non cadono a pezzi, tesoro!\p"
	.string "E mangia qualcosa, mi raccomando!$"

MatchCall_Text_Roxanne_Preparing::
	.string "Petra: Oh, ciao, {PLAYER}!\p"
	.string "Da quando ci siamo affrontati,\n"
	.string "sto ripassando tutto da capo.\p"
	.string "Mi serve ancora un po' di tempo\n"
	.string "prima di riaprire la Palestra.\p"
	.string "Ma quando sarà pronta, vieni a\n"
	.string "trovarmi per la rivincita!$"

MatchCall_Text_Roxanne_PreparingPostGame::
	.string "Petra: Sei tu, {PLAYER}?\n"
	.string "Congratulazioni!\l"
	.string "Mi sono arrivate notizie di te!\p"
	.string "Io invece ho bisogno di altro tempo\n"
	.string "prima di riaprire la Palestra.\p"
	.string "Ma quando sarà pronta, vieni a\n"
	.string "trovarmi per la rivincita!$"

MatchCall_Text_Roxanne_RematchReady::
	.string "Petra: {PLAYER}!\n"
	.string "La mia Palestra è pronta!\p"
	.string "Vieni a Ferrugipoli quando\n"
	.string "vuoi: si ripassa insieme!$"

MatchCall_Text_Roxanne_PostRematch::
	.string "Petra: Alla Palestra di Ferrugipoli\n"
	.string "siamo fieri di aver lottato\l"
	.string "contro di te, {PLAYER}.$"

MatchCall_Text_Brawly_Preparing::
	.string "Rudi: Ehi, ciao, {PLAYER}{KUN}!\p"
	.string "La nostra lotta mi ha insegnato\n"
	.string "un sacco di cose.\p"
	.string "Voglio rifare l'allenamento da capo\n"
	.string "e poi riaprire la Palestra.\p"
	.string "Ci vorrà un po' prima che sia\n"
	.string "pronto a gestirla di nuovo.\p"
	.string "Ma quando riaprirò, voglio che tu\n"
	.string "torni a sfidarci. Cavalca l'onda!$"

MatchCall_Text_Brawly_PreparingPostGame::
	.string "Rudi: Ehi, {PLAYER}{KUN}!\n"
	.string "Congratulazioni!\p"
	.string "Le notizie delle tue imprese sono\n"
	.string "arrivate fin qui con le maree!\p"
	.string "Pare che io debba allenarmi\n"
	.string "ancora un bel po'.\p"
	.string "Ci vorrà un po' prima che sia\n"
	.string "pronto a gestire la Palestra.\p"
	.string "Ma quando riaprirò, voglio che tu\n"
	.string "torni a sfidarci!$"

MatchCall_Text_Brawly_RematchReady::
	.string "Rudi: Ehi, {PLAYER}{KUN}!\n"
	.string "La mia Palestra è pronta!\p"
	.string "Torna a Bluruvia quando vuoi per\n"
	.string "un'altra sfida! Cavalca l'onda!$"

MatchCall_Text_Brawly_PostRematch::
	.string "Rudi: {PLAYER}{KUN}, lottare con te è\n"
	.string "un'onda che non mi stanca mai!$"

MatchCall_Text_Wattson_Preparing::
	.string "Walter: Oh, sei tu!\p"
	.string "Da quando te ne sei andato, ho\n"
	.string "ripreso ad allenarmi da zero.\p"
	.string "Diciamo che mi serve un pizzico\n"
	.string "di tempo per riaprire la Palestra.\p"
	.string "Dovrai aspettare fino ad allora!\n"
	.string "Uahahahah!$"

MatchCall_Text_Wattson_PreparingPostGame::
	.string "Walter: Uahahahah!\p"
	.string "Ce l'hai fatta davvero, eh?\n"
	.string "Mi sono arrivate voci su di te!\p"
	.string "A quanto pare devo allenarmi\n"
	.string "ancora un bel po'.\p"
	.string "Diciamo che mi serve un pizzico\n"
	.string "di tempo per riaprire la Palestra.\p"
	.string "Dovrai aspettare fino ad allora!\n"
	.string "Uahahahah!$"

MatchCall_Text_Wattson_RematchReady::
	.string "Walter: Oh, sei tu!\n"
	.string "La mia Palestra è pronta!\p"
	.string "Vieni a Ciclamipoli quando vuoi!\n"
	.string "Uahahahah!$"

MatchCall_Text_Wattson_PostRematch::
	.string "Walter: Uahahah!\p"
	.string "Lottare con te è sempre una\n"
	.string "scarica di pura adrenalina!$"

MatchCall_Text_Flannery_Preparing::
	.string "Fiammetta: {PLAYER}…\p"
	.string "Quando abbiamo lottato, ho capito\n"
	.string "quanto fossi ancora acerba.\p"
	.string "Ma non è finita qui!\p"
	.string "Rifarò tutto l'allenamento e\n"
	.string "riaprirò la Palestra.\p"
	.string "Quando sarà il momento, {PLAYER},\n"
	.string "vieni a sfidarci di nuovo.$"

MatchCall_Text_Flannery_PreparingPostGame::
	.string "Fiammetta: Pronto, {PLAYER}?\n"
	.string "Congratulazioni!\p"
	.string "La notizia del tuo successo ci è\n"
	.string "arrivata come una vampata di lava!\p"
	.string "Qui l'allenamento procede\n"
	.string "alla grande.\p"
	.string "Quando la Palestra sarà pronta,\n"
	.string "accanto al mio nome comparirà\l"
	.string "un segno nella rubrica del PokéNav.$"

MatchCall_Text_Flannery_RematchReady::
	.string "Fiammetta: Oh, {PLAYER}?\n"
	.string "La nostra Palestra è pronta!\p"
	.string "Vieni a Cuordilava: un bagno nelle\n"
	.string "terme e poi una bella sfida!$"

MatchCall_Text_Flannery_PostRematch::
	.string "Fiammetta: {PLAYER}…\n"
	.string "Ne sono certa: ogni volta che ti\l"
	.string "sento, sei un Allenatore migliore.$"

MatchCall_Text_Winona_Preparing::
	.string "Alice: Ciao, {PLAYER}!\p"
	.string "Grazie alla nostra lotta ho capito\n"
	.string "quali sono i miei punti deboli!\p"
	.string "Quando riaprirò la Palestra,\n"
	.string "non precipiterò mai più!$"

MatchCall_Text_Winona_PreparingPostGame::
	.string "Alice: Ce l'hai fatta, {PLAYER}!\p"
	.string "La notizia del nuovo Campione\n"
	.string "è volata fino a Forestopoli!\p"
	.string "Ma… la prossima volta che lotteremo,\n"
	.string "non finirà allo stesso modo.$"

MatchCall_Text_Winona_RematchReady::
	.string "Alice: Sei {PLAYER}?\n"
	.string "La nostra Palestra ha riaperto!\p"
	.string "Ti aspettiamo a Forestopoli,\n"
	.string "dove il cielo è più vicino!$"

MatchCall_Text_Winona_PostRematch::
	.string "Alice: {PLAYER}…\n"
	.string "Anche se ho perso, le mie ali\l"
	.string "non si spezzeranno mai.\p"
	.string "Proprio come tu non hai mai perso\n"
	.string "di vista il tuo sogno.$"

MatchCall_Text_TateLiza_Preparing::
	.string "Tell: Oh! Ma tu sei…\n"
	.string "Pat: …{PLAYER}!\p"
	.string "Tell: Ci stiamo riallenando…\n"
	.string "Pat: …per riaprire la Palestra!\p"
	.string "Tell: Quando la Palestra è pronta…\n"
	.string "Pat: Quando la Palestra è pronta…\p"
	.string "Tell: …un segno comparirà accanto…\n"
	.string "Pat: …al nostro nome nel PokéNav.$"

MatchCall_Text_TateLiza_PreparingPostGame::
	.string "Tell: {PLAYER}, congratulazioni!\n"
	.string "Pat: {PLAYER}, congratulazioni!\p"
	.string "Tell: Noi due siamo…\n"
	.string "Pat: …ancora in allenamento!\p"
	.string "Tell: Ci serve altro tempo, ma…\n"
	.string "Pat: …quando la Palestra è pronta…\p"
	.string "Tell: …un segno comparirà accanto…\n"
	.string "Pat: …al nostro nome nel PokéNav.$"

MatchCall_Text_TateLiza_RematchReady::
	.string "Tell: {PLAYER}!\n"
	.string "Pat: {PLAYER}!\p"
	.string "Tell: La Palestra è pronta!\n"
	.string "Pat: La Palestra è pronta!\p"
	.string "Tell: Vieni a trovarci…\n"
	.string "Pat: …a Verdeazzupoli quando vuoi!$"

MatchCall_Text_TateLiza_PostRematch::
	.string "Tell: {PLAYER}, la nostra lotta…\n"
	.string "Pat: …è stata un'esperienza unica.\p"
	.string "Tell: Sarebbe bello se…\n"
	.string "Pat: …potessimo lottare ancora!$"

MatchCall_Text_Juan_Preparing::
	.string "Rodolfo: Mmh…\n"
	.string "{PLAYER}{KUN}… dico bene?\p"
	.string "La nostra lotta mi ha riportato\n"
	.string "alla mente il mio primo incontro\l"
	.string "con Adriano.\p"
	.string "Forse sei un genio che un giorno\n"
	.string "potrebbe superare persino Adriano!$"

MatchCall_Text_Juan_PreparingPostGame::
	.string "Rodolfo: Fufu… {PLAYER}{KUN}…\n"
	.string "Hai finalmente raggiunto la meta.\p"
	.string "Il mio occhio per il talento\n"
	.string "non si era sbagliato…\p"
	.string "Desidero rivederti ancora, ora che\n"
	.string "hai raggiunto la vetta della forza\l"
	.string "e del prestigio.$"

MatchCall_Text_Juan_RematchReady::
	.string "Rodolfo: Hoho… {PLAYER}{KUN}…\p"
	.string "La Palestra di Ceneride ha\n"
	.string "finalmente riaperto i battenti.\p"
	.string "Se desideri vedermi, sei il\n"
	.string "benvenuto in qualsiasi momento.$"

MatchCall_Text_Juan_PostRematch::
	.string "Rodolfo: {PLAYER}{KUN}…\p"
	.string "Come la musica più raffinata, le\n"
	.string "nostre lotte fanno vibrare corde\l"
	.string "d'ispirazione nel mio cuore…\p"
	.string "Se chiudo gli occhi, ti vedo volare\n"
	.string "sulle ali della melodia…$"

MatchCall_Text_Sidney::
	.string "Fosco: Ehi, {PLAYER}!\p"
	.string "Se vuoi lottare di nuovo con me,\n"
	.string "torna pure alla Lega Pokémon\l"
	.string "quando ti pare.\p"
	.string "Io sono sempre qui!\n"
	.string "Ti aspetto! Facciamo rumore!$"

MatchCall_Text_Phoebe::
	.string "Ester: Ciao, {PLAYER}!\p"
	.string "Perché non torni a trovarci,\n"
	.string "una volta o l'altra?\p"
	.string "Vorrei vedere quanto è cresciuto\n"
	.string "il legame tra te e i tuoi\l"
	.string "Pokémon. Gli spiriti sono curiosi!$"

MatchCall_Text_Glacia::
	.string "Frida: Salve, {PLAYER}.\p"
	.string "Spero che tu non ti sia adagiato\n"
	.string "sugli allori della tua forza.\p"
	.string "Se senti il bisogno di raffreddare\n"
	.string "un po' le tue emozioni bollenti,\l"
	.string "vieni alla Lega Pokémon…$"

MatchCall_Text_Drake::
	.string "Drake: Questa voce… {PLAYER}, vero?\n"
	.string "Ti sento in forma…\p"
	.string "Mi risulta che ora esista un posto\n"
	.string "chiamato Parco Lotta, che mette\l"
	.string "alla prova l'abilità degli\l"
	.string "Allenatori.\p"
	.string "Ma se desideri lotte vere, nulla\n"
	.string "può sostituire la Lega Pokémon!\p"
	.string "Non sei d'accordo, {PLAYER}?$"

MatchCall_Text_Wallace::
	.string "Adriano: Ciao, {PLAYER}{KUN}.\n"
	.string "Hai conosciuto Rocco?\p"
	.string "Lui è…\n"
	.string "Davvero fortissimo, in realtà.\p"
	.string "Però è un tipo strano, che\n"
	.string "lotta molto di rado.\p"
	.string "Preferisce andare a caccia di\n"
	.string "pietre cadute da altri mondi.\p"
	.string "Starà scavando in qualche grotta\n"
	.string "o su un monte scosceso.\p"
	.string "Ma come si riconosce una pietra\n"
	.string "di un altro mondo? A me viene\l"
	.string "in mente solo il Meteorite…$"

MatchCall_Text_MayRayquazaCall:
	.string "… … … … … …\n"
	.string "… … … … … Bip!\p"
	.string "Arianna: Ciao, {PLAYER}{KUN}!\p"
	.string "Allora, allora! Poco fa ero\n"
	.string "a Orocea.\p"
	.string "Ho visto un enorme Pokémon verde\n"
	.string "volare alto sopra il mare.\p"
	.string "Io…\n"
	.string "Non ho mai visto niente del genere.\p"
	.string "Chissà cos'era.\n"
	.string "Una scoperta epocale? Segnato!\p"
	.string "… … … … … …\n"
	.string "… … … … … Clic!$"

MatchCall_Text_BrendanRayquazaCall:
	.string "… … … … … …\n"
	.string "… … … … … Bip!\p"
	.string "Arianna: Ehi, {PLAYER}!\n"
	.string "Sono appena stata a Orocea.\p"
	.string "Ho visto un gigantesco Pokémon\n"
	.string "verde attraversare il cielo.\p"
	.string "Non avevo mai visto niente di\n"
	.string "così incredibile.\p"
	.string "Peccato che tu non ci fossi,\n"
	.string "{PLAYER}. Ma io ho segnato tutto!\p"
	.string "… … … … … …\n"
	.string "… … … … … Clic!$"

MatchCall_Text_May1::
	.string "Arianna: Ciao, {PLAYER}{KUN}!\p"
	.string "Capitan Scoglio ha lasciato la\n"
	.string "vita da marinaio, ma ogni tanto\l"
	.string "lo vedo ancora in mare con Peeko.\p"
	.string "Il mare dev'essere ancora il suo\n"
	.string "grande amore.$"

MatchCall_Text_May2::
	.string "Arianna: Ciao, {PLAYER}{KUN}!\p"
	.string "Hai notato che paesini come\n"
	.string "Petalipoli e Bluruvia hanno\l"
	.string "una Palestra?\p"
	.string "Eppure una città grande come\n"
	.string "Porto Selcepoli non ce l'ha!\p"
	.string "Quando ne costruiranno una, mi\n"
	.string "candiderò come Capopalestra.\p"
	.string "Una Palestra dei Varchi…\n"
	.string "Allora, allora! Me lo segno!$"

MatchCall_Text_May3::
	.string "Arianna: Ciao, {PLAYER}{KUN}!\p"
	.string "Ti ricordi di un tizio chiamato\n"
	.string "Taglialegna, a Ferrugipoli?\l"
	.string "Aveva una casa lì, ricordi?\p"
	.string "Beh, ho scoperto che suo fratello\n"
	.string "minore vive a Ciclamipoli.\p"
	.string "Indovina un po' come si chiama?\p"
	.string "… … … … … …\n"
	.string "… … … … … …\p"
	.string "Il Signor Spaccaroccia!$"

MatchCall_Text_May4::
	.string "Arianna: {PLAYER}{KUN}?\p"
	.string "Il Tunnel Menferro…\n"
	.string "Si chiama così perché unisce\l"
	.string "Mentania e Ferrugipoli. Segnato!$"

MatchCall_Text_May5::
	.string "Arianna: {PLAYER}{KUN}, come va?\p"
	.string "Adesso sono sul Percorso 111.\p"
	.string "Mi fermo a riposare a casa di\n"
	.string "una simpatica vecchietta.\p"
	.string "Abita appena a nord\n"
	.string "del deserto.$"

MatchCall_Text_May6::
	.string "Arianna: Ciao, {PLAYER}{KUN}!\p"
	.string "Sai della Torre Miraggio,\n"
	.string "nel deserto?\p"
	.string "Dicono che, proprio come un miraggio,\n"
	.string "appaia e scompaia nel nulla.\p"
	.string "Secondo me è un Varco indeciso!\n"
	.string "Vorrei tanto vederla.$"

MatchCall_Text_May7::
	.string "Arianna: {PLAYER}{KUN}, ehilà!\n"
	.string "Sono sul Percorso 119.\p"
	.string "Qui c'è un grande fiume, e piove\n"
	.string "di continuo.\p"
	.string "Mi sono inzuppata! E anche il mio\n"
	.string "Taccuino dei Varchi…$"

MatchCall_Text_May8::
	.string "Arianna: {PLAYER}{KUN}, ciao.\p"
	.string "Il Monte Pira è un luogo dedicato\n"
	.string "ai Pokémon che non ci sono più.\p"
	.string "Forse per questo è pieno zeppo\n"
	.string "di Pokémon di tipo Spettro!$"

MatchCall_Text_May9::
	.string "Arianna: Ciao, {PLAYER}{KUN}!\p"
	.string "Volevo andare alle terme di\n"
	.string "Cuordilava.\p"
	.string "Ma per strada, al Passo Selvaggio,\n"
	.string "ho incrociato dei tipi loschi col\l"
	.string "mantello rosso. Che brutta aria!$"

MatchCall_Text_May10::
	.string "Arianna: Ciao, {PLAYER}{KUN}!\n"
	.string "Hai visto il telegiornale?\p"
	.string "Dicono che Capitan Stern abbia\n"
	.string "scoperto l'Antro Abissale durante\l"
	.string "la sua spedizione in sottomarino.$"

MatchCall_Text_May11::
	.string "Arianna: Ciao, {PLAYER}{KUN}!\n"
	.string "Non è geniale?\p"
	.string "Anche senza una barca, puoi\n"
	.string "attraversare il mare grazie\l"
	.string "alla mossa di un Pokémon.\p"
	.string "E sai una cosa? C'è di più!\p"
	.string "Esiste una mossa che ti porta\n"
	.string "fino in fondo al mare. Segnato!$"

MatchCall_Text_May12::
	.string "Arianna: Ciao, {PLAYER}{KUN}!\n"
	.string "Spero che vada tutto bene!\p"
	.string "Ti è mai capitato, in mare, di\n"
	.string "trovare la strada sbarrata\l"
	.string "dall'altra parte?\p"
	.string "Prova a immergerti e a seguire\n"
	.string "le fosse sul fondale.\p"
	.string "Quando arrivi dall'altra parte,\n"
	.string "risali in superficie. Facile!$"

MatchCall_Text_May13::
	.string "Arianna: Ciao, {PLAYER}{KUN}!\p"
	.string "Come va? Lo stai riempiendo,\n"
	.string "il tuo Pokédex?\p"
	.string "Gira voce che esistano Pokémon\n"
	.string "antichissimi, dei tempi del primo\l"
	.string "Grande Varco. E sarebbero tre!\p"
	.string "Primo, secondo, terzo…\n"
	.string "Me ne basterebbe vedere uno!$"

MatchCall_Text_May14::
	.string "Arianna: {PLAYER}{KUN}!\n"
	.string "Mi è arrivata la notizia!\p"
	.string "Hai battuto il Capopalestra\n"
	.string "di Ceneride?\p"
	.string "Allora ormai la Lega è a un\n"
	.string "passo, vero? Allora, allora!$"

MatchCall_Text_May15::
	.string "Arianna: In tutta Hoenn non c'è\n"
	.string "un Allenatore che non sappia chi\l"
	.string "sei, {PLAYER}{KUN}!\p"
	.string "Quando dico che sono amica di\n"
	.string "{PLAYER}{KUN}, restano tutti\l"
	.string "a bocca aperta!$"

MatchCall_Text_Brendan1::
	.string "Arianna: Ehi, {PLAYER}!\p"
	.string "Capitan Scoglio è in pensione,\n"
	.string "ma ogni tanto lo vedo ancora per\l"
	.string "mare insieme al suo Peeko.\p"
	.string "Il mare dev'essergli rimasto\n"
	.string "nel cuore.$"

MatchCall_Text_Brendan2::
	.string "Arianna: Ehi, {PLAYER}!\p"
	.string "Perché paesini come Petalipoli e\n"
	.string "Bluruvia hanno una Palestra…\p"
	.string "…e un porto enorme come Porto\n"
	.string "Selcepoli invece no?\p"
	.string "Quando ne apriranno una, mi\n"
	.string "candido io come Capopalestra!$"

MatchCall_Text_Brendan3::
	.string "Arianna: Ehilà, {PLAYER}!\p"
	.string "Ti ricordi del Taglialegna\n"
	.string "di Ferrugipoli?\l"
	.string "Quello che abita lì, no?\p"
	.string "Beh, pare che il suo fratellino\n"
	.string "viva a Ciclamipoli.\p"
	.string "Indovina come lo chiamano?\p"
	.string "… … … … … …\n"
	.string "… … … … … …\p"
	.string "Il Tizio dello Spaccaroccia!$"

MatchCall_Text_Brendan4::
	.string "Arianna: Questa voce… {PLAYER}?\p"
	.string "Il Tunnel Menferro si chiama così\n"
	.string "perché unisce Mentania e\l"
	.string "Ferrugipoli.\p"
	.string "Lo sapevi? Io l'ho segnato!$"

MatchCall_Text_Brendan5::
	.string "Arianna: {PLAYER}, come va?\p"
	.string "Senti, ora sono sul Percorso 111.\p"
	.string "Mi riposo un po' a casa di una\n"
	.string "signora, a nord del deserto.\p"
	.string "Se passi da queste parti, vai\n"
	.string "a trovarla anche tu!$"

MatchCall_Text_Brendan6::
	.string "Arianna: Ehi, {PLAYER}!\p"
	.string "Hai sentito della Torre Miraggio,\n"
	.string "nel deserto?\p"
	.string "Dicono che, come un miraggio, si\n"
	.string "veda solo ogni tanto.\p"
	.string "Per me è un Varco che non si\n"
	.string "decide! La voglio vedere!$"

MatchCall_Text_Brendan7::
	.string "Arianna: Chi è? Oh, {PLAYER}!\n"
	.string "Indovina? Sono sul Percorso 119.\p"
	.string "C'è un fiume enorme, e piove\n"
	.string "senza sosta. Varchi meteorologici?\p"
	.string "Sono fradicia fino alle ossa!$"

MatchCall_Text_Brendan8::
	.string "Arianna: {PLAYER}!\p"
	.string "Il Monte Pira è un luogo in memoria\n"
	.string "dei Pokémon che non ci sono più.\p"
	.string "Sarà per questo che è pieno\n"
	.string "di Pokémon di tipo Spettro!$"

MatchCall_Text_Brendan9::
	.string "Arianna: Ehilà, {PLAYER}.\p"
	.string "Stavo tornando alle terme\n"
	.string "di Cuordilava.\p"
	.string "Ma al Passo Selvaggio ho incrociato\n"
	.string "dei tipi davvero loschi.\p"
	.string "Mantelli rossi, facce scure…\n"
	.string "Secondo me erano del Team Alpha.$"

MatchCall_Text_Brendan10::
	.string "Arianna: Ciao, {PLAYER}!\n"
	.string "Hai visto il telegiornale?\p"
	.string "Dicono che Capitan Stern abbia\n"
	.string "scoperto l'Antro Abissale durante\l"
	.string "la sua spedizione in sottomarino.$"

MatchCall_Text_Brendan11::
	.string "Arianna: Ehilà, {PLAYER}!\n"
	.string "Non è fantastico?\p"
	.string "Anche senza una barca, puoi\n"
	.string "attraversare il mare grazie\l"
	.string "alla mossa di un Pokémon.\p"
	.string "E c'è perfino una mossa che ti\n"
	.string "porta fino in fondo al mare.\p"
	.string "I Pokémon sanno fare di tutto!$"

MatchCall_Text_Brendan12::
	.string "Arianna: Ciao, {PLAYER}!\n"
	.string "Come te la passi?\p"
	.string "In mare ti sei mai trovato la\n"
	.string "strada sbarrata?\p"
	.string "Prova a immergerti e a seguire\n"
	.string "le fosse sul fondale.\p"
	.string "Quando arrivi dall'altra parte,\n"
	.string "risali in superficie. Semplice!$"

MatchCall_Text_Brendan13::
	.string "Arianna: Ehilà, {PLAYER}!\p"
	.string "Come va? Il tuo Pokédex si sta\n"
	.string "riempiendo?\p"
	.string "Gira voce che esistano Pokémon\n"
	.string "antichissimi, dei tempi del primo\l"
	.string "Grande Varco. Non uno: tre!\p"
	.string "Me ne basterebbe catturare uno…$"

MatchCall_Text_Brendan14::
	.string "Arianna: {PLAYER}!\n"
	.string "Mi è arrivata la notizia!\p"
	.string "Hai battuto il Capopalestra di\n"
	.string "Ceneride? Grandioso!\p"
	.string "Ormai ci sei quasi!$"

MatchCall_Text_Brendan15::
	.string "Arianna: In tutta Hoenn non c'è\n"
	.string "un Allenatore che non sappia chi\l"
	.string "sei, {PLAYER}!\p"
	.string "Quando dico che sono amica di\n"
	.string "{PLAYER}, mi guardano tutti\l"
	.string "con invidia!$"

MatchCall_Text_Wally1::
	.string "Lino: Oh, {PLAYER}!\p"
	.string "Sto meglio, sai… Sono più in forze\n"
	.string "e non mi stanco più così tanto.\p"
	.string "Spero di diventare presto un\n"
	.string "Allenatore come te, {PLAYER}!$"

MatchCall_Text_Wally2::
	.string "Lino: {PLAYER}, ciao!\p"
	.string "Da quando il Tunnel Menferro è\n"
	.string "aperto, Wanda è felicissima!$"

MatchCall_Text_Wally3::
	.string "Lino: Oh, {PLAYER}!\p"
	.string "Io… sono andato via da casa\n"
	.string "di mio zio, a Mentania…\l"
	.string "senza dirlo a nessuno.\p"
	.string "Chissà se è arrabbiato con me…\p"
	.string "{PLAYER}, tu capisci come mi\n"
	.string "sento, vero?$"

MatchCall_Text_Wally4::
	.string "Lino: {PLAYER}?\n"
	.string "Sono io, Lino!\p"
	.string "Il mondo degli Allenatori è\n"
	.string "fantastico!\p"
	.string "Quando sono con i miei Pokémon,\n"
	.string "tutti mi salutano!\p"
	.string "È come se i Pokémon unissero\n"
	.string "le persone… Grazie, Pokémon.$"

MatchCall_Text_Wally5::
	.string "Lino: {PLAYER}? È incredibile!\n"
	.string "Il Ralts che abbiamo catturato\l"
	.string "insieme… si è evoluto, {PLAYER}!\p"
	.string "Forse ho un po' di talento…\p"
	.string "Oh, ma non devo montarmi\n"
	.string "la testa!\p"
	.string "Dopotutto, il merito è tutto\n"
	.string "dei miei Pokémon!$"

MatchCall_Text_Wally6::
	.string "… … … … … …\n"
	.string "… … … … … …\p"
	.string "Lino sembra essere fuori dalla\n"
	.string "copertura del PokéNav…$"

MatchCall_Text_Wally7::
	.string "Lino: Oh, {PLAYER}!\p"
	.string "Prima di conoscerti, non uscivo\n"
	.string "quasi mai di casa…\p"
	.string "E adesso sono in viaggio con\n"
	.string "i miei Pokémon…\p"
	.string "{PLAYER}…\n"
	.string "Grazie… davvero.$"

MatchCall_Text_Scott1::
	.string "Scott: Salve, {PLAYER}{KUN}!\p"
	.string "Hai notato che i Pokémon si\n"
	.string "trovano dappertutto?\p"
	.string "Sui monti, in mare, nell'erba alta…\n"
	.string "e ora perfino fuori dai Varchi!\p"
	.string "E come i Pokémon, anche gli\n"
	.string "Allenatori sono dappertutto.\p"
	.string "Così devo correre dappertutto\n"
	.string "anch'io. Che vita frenetica!$"

MatchCall_Text_Scott2::
	.string "Scott: Sono sul Percorso 119.\n"
	.string "È pieno zeppo di Allenatori!\p"
	.string "Ed è pieno zeppo anche di erba\n"
	.string "alta, a quanto pare.\p"
	.string "Girare in pantaloncini da queste\n"
	.string "parti mi fa un solletico tremendo!$"

MatchCall_Text_Scott3::
	.string "Scott: Ciao ciao, {PLAYER}{KUN}!\p"
	.string "Sei già salito sul\n"
	.string "Monte Pira?\p"
	.string "È un luogo in memoria dei\n"
	.string "Pokémon che non ci sono più.\p"
	.string "Ogni Allenatore dovrebbe salire\n"
	.string "fino in cima, almeno una volta.$"

MatchCall_Text_Scott4::
	.string "Scott: Ciao, {PLAYER}{KUN}!\p"
	.string "Ho sentito di certe bande strane\n"
	.string "che creano un sacco di guai.\p"
	.string "Il Team Alpha e il Team Omega,\n"
	.string "mi pare.\p"
	.string "Tra loro ci sarà pure qualche\n"
	.string "Allenatore di talento.\p"
	.string "…Ma se sono solo dei teppisti…$"

MatchCall_Text_Scott5::
	.string "Scott: Oh, ciao, {PLAYER}{KUN}.\p"
	.string "Chissà se in fondo al mare ci sono\n"
	.string "Allenatori forti…\p"
	.string "Non posso andare a controllare.\n"
	.string "Primo, non so nuotare.\l"
	.string "Secondo, non allevo Pokémon…$"

MatchCall_Text_Scott6::
	.string "Scott: Ciao ciao, {PLAYER}{KUN}!\p"
	.string "Lo sai che puoi sfidare la Lega\n"
	.string "Pokémon una volta raccolte tutte\l"
	.string "le Medaglie?\p"
	.string "Col tuo talento, diventare\n"
	.string "Campione non è un sogno.\p"
	.string "Ma lo sapevi?\n"
	.string "C'è un posto ancora più bello.\p"
	.string "Per ora, però, non posso dirti\n"
	.string "altro.\p"
	.string "Diciamo che è una sorpresa…\n"
	.string "grande come un mondo. Anzi, di più.\p"
	.string "Te ne parlerò quando la Lega sarà\n"
	.string "vinta e il tuo nome sarà nella\l"
	.string "Sala d'Onore!$"

MatchCall_Text_Scott7::
	.string "… … … … … …\n"
	.string "… … … … … …\p"
	.string "Scott sembra essere fuori dalla\n"
	.string "copertura del PokéNav…$"

MatchCall_Text_Norman1::
	.string "Papà: A Ferrugipoli c'è un uomo\n"
	.string "che si fa chiamare con lo strano\l"
	.string "nome di Taglialegna.\p"
	.string "Se passi da quelle parti, vai\n"
	.string "a trovarlo.$"

MatchCall_Text_Norman2::
	.string "Papà: Hm… Piano piano, ma senza\n"
	.string "mai fermarti, stai diventando più\l"
	.string "forte, {PLAYER}.\p"
	.string "Più diventi forte, più voli lontano\n"
	.string "e in alto, via da tua madre\l"
	.string "e da me…\p"
	.string "È una sensazione difficile da\n"
	.string "spiegare. Ehm. Coff, coff.$"

MatchCall_Text_Norman3::
	.string "Papà: Capisco…\n"
	.string "Hai raccolto quattro Medaglie…\p"
	.string "Ormai non si torna indietro.\n"
	.string "Lotteremo, come ti ho promesso.\p"
	.string "Vieni quando vuoi.\n"
	.string "Ti aspettiamo tutti in Palestra!$"

MatchCall_Text_Norman4::
	.string "Papà: {PLAYER}! Ogni tanto passa\n"
	.string "a trovare tua madre.\p"
	.string "Io resto qui a raddoppiare\n"
	.string "gli allenamenti.\p"
	.string "La via della lotta è profonda\n"
	.string "e non perdona!$"

MatchCall_Text_Norman5::
	.string "Papà: Oh, ciao, {PLAYER}!\p"
	.string "Come? Uno Stemma Alpha?\n"
	.string "Non so di cosa si tratti.\p"
	.string "Ma quelli dell'Alpha girano spesso\n"
	.string "dalle parti del vulcano…\p"
	.string "Forse c'entra qualcosa il\n"
	.string "Monte Camino!$"

MatchCall_Text_Norman_Preparing::
	.string "Papà: Hiaaa! Hah! Uaah!\p"
	.string "…Oh? {PLAYER}!\p"
	.string "Mi hai beccato nel bel mezzo di\n"
	.string "un allenamento con i Pokémon!$"

MatchCall_Text_Norman_PreparingPostGame::
	.string "Papà: {PLAYER}!\p"
	.string "Chi l'avrebbe mai detto che saresti\n"
	.string "diventato Campione della Lega…\p"
	.string "Bene!\n"
	.string "Non resterò indietro!$"

MatchCall_Text_Norman_RematchReady::
	.string "Papà: Hm? {PLAYER}?\n"
	.string "Giusto in tempo!\p"
	.string "Stavolta sono io a sfidarti\n"
	.string "a una lotta.\p"
	.string "Ti aspetto alla Palestra di\n"
	.string "Petalipoli. Vieni quando vuoi!$"

MatchCall_Text_Norman_PostRematch::
	.string "Papà: …Mi stupisci, {PLAYER}.\n"
	.string "Fin dove arriverai a volare?$"

MatchCall_Text_Steven1::
	.string "Rocco: Ciao, {PLAYER}{KUN}!\p"
	.string "Sei già stato a Ciclamipoli?\p"
	.string "Passa da Bici Rydel e fatti dare\n"
	.string "una Bici da corsa.\p"
	.string "Poi esplora per bene la Grotta\n"
	.string "Pietrosa. Ci sono pietre… curiose.\p"
	.string "Potresti fare una nuova scoperta.\n"
	.string "Interessante, no?$"

MatchCall_Text_Steven2::
	.string "Rocco: Ciao, {PLAYER}{KUN}!\p"
	.string "Finora ho conosciuto tanti\n"
	.string "Allenatori diversi.\p"
	.string "Ma tu sei unico.\n"
	.string "Come una pietra caduta da un altro\l"
	.string "mondo: non somigli a nessuno.$"

MatchCall_Text_Steven3::
	.string "Rocco: Ciao, {PLAYER}{KUN}!\p"
	.string "Quando sei in viaggio con i tuoi\n"
	.string "Pokémon, a cosa pensi?\p"
	.string "Li consideri compagni di lotta\n"
	.string "forti e affidabili?\p"
	.string "O amici con cui divertirti?\p"
	.string "A seconda di come la vedi, cambia\n"
	.string "il senso della tua avventura.$"

MatchCall_Text_Steven4::
	.string "Rocco: Pronto?\n"
	.string "{PLAYER}{KUN}?\p"
	.string "Sono alle prese con dei guai al\n"
	.string "Centro Spaziale.\p"
	.string "Scusa, ma non posso parlare.\n"
	.string "Ciao!$"

MatchCall_Text_Steven5::
	.string "Rocco: Oh!\n"
	.string "{PLAYER}{KUN}!\p"
	.string "Non serve parlare.\n"
	.string "Il tempo delle parole è finito.\p"
	.string "Devi credere in te stesso\n"
	.string "e fare ciò che è giusto.$"

MatchCall_Text_Steven6::
	.string "… … … … … …\p"
	.string "Rocco non sembra rispondere\n"
	.string "alla chiamata…$"

MatchCall_Text_Steven7::
	.string "Rocco: {PLAYER}{KUN}… Congratulazioni\n"
	.string "per l'ingresso nella Sala d'Onore.\p"
	.string "… … … … … …\n"
	.string "… … … … … …\p"
	.string "Spero che ci rivedremo,\n"
	.string "prima o poi!$"

MatchCall_Text_BirchRegisterCall:
	.string "Prof. Birch: Oh, {PLAYER}{KUN}!\n"
	.string "Ho già sentito parlare di te!\p"
	.string "Vedo che il tuo PokéNav è stato\n"
	.string "aggiornato con il Match Call.\p"
	.string "Allora mi registro anch'io!\p"
	.string "Così potrò esaminare il tuo\n"
	.string "Pokédex anche mentre sei in giro\l"
	.string "per Hoenn. Straordinario!\p"
	.string "… … … … … …$"

MatchCall_Text_RegisteredBirch:
	.string "Prof. Birch è stato registrato\n"
	.string "nel PokéNav.$"

MatchCall_Text_UnusedProfBirch:
	.string "Prof. Birch: Con Pokédex e PokéNav,\n"
	.string "studiare i Pokémon diventa ancora\l"
	.string "più divertente, eh?$"

MatchCall_Text_MrStone1::
	.string "Sig. Petri: Oh? {PLAYER}{KUN}!\p"
	.string "Se mi hai chiamato, vuol dire che\n"
	.string "il PokéNav funziona a dovere!\p"
	.string "Registrerai anche altre persone,\n"
	.string "quindi prova a chiamare pure loro!\p"
	.string "Bene! Bene!\n"
	.string "Mi sembri proprio contento!\p"
	.string "Hm…\n"
	.string "Come faccio a saperlo?\p"
	.string "Perché ti sto guardando dalla\n"
	.string "finestra del mio ufficio!\p"
	.string "Uahahaha!\n"
	.string "A presto!$"

MatchCall_Text_MrStone2::
	.string "Sig. Petri: Oh? {PLAYER}{KUN}!\p"
	.string "Che succede? Hai forse dimenticato\n"
	.string "quella mia piccola commissione?\p"
	.string "Devi consegnare la mia Lettera\n"
	.string "a Rocco, a Bluruvia.\p"
	.string "Poi devi portare la Merce Devon\n"
	.string "a Capitan Stern, a Porto Selcepoli.\p"
	.string "Te lo ricordi, vero?\p"
	.string "Ora devo scappare: un presidente\n"
	.string "ha mille impegni! Ciao ciao!$"

MatchCall_Text_MrStone3::
	.string "Sig. Petri: Oh! {PLAYER}{KUN}!\p"
	.string "Allora hai incontrato Rocco!\n"
	.string "Meriti una ricompensa!\p"
	.string "Quando torni a Ferrugipoli,\n"
	.string "passa nel mio ufficio.\p"
	.string "Ti aspetto!$"

MatchCall_Text_MrStone4::
	.string "Sig. Petri: Oh! {PLAYER}{KUN}!\p"
	.string "Sapevi che il Tunnel Menferro\n"
	.string "lo stava scavando la Devon?\p"
	.string "Ma abbiamo fermato i lavori per\n"
	.string "proteggere i Pokémon della zona.\p"
	.string "Una scelta ovvia, in fondo.\p"
	.string "Lasciar vivere in pace i Pokémon\n"
	.string "conta più della nostra comodità.$"

MatchCall_Text_MrStone5::
	.string "Sig. Petri: Pronto, pronto, {PLAYER}{KUN}!\p"
	.string "Qualcuno a Petalipoli mi ha detto\n"
	.string "che sei il figlio di Norman!\p"
	.string "Ecco perché sei così in\n"
	.string "gamba!$"

MatchCall_Text_MrStone6::
	.string "Sig. Petri: Come dici?\p"
	.string "Hai sfidato tuo padre in persona\n"
	.string "e l'hai sconfitto?\p"
	.string "Ma è straordinario!\p"
	.string "Non avevo idea di avere un amico\n"
	.string "così speciale! Uahaha!$"
MatchCall_Text_MrStone7::
	.string "Pronto!\n"
	.string "Qui è la Devon S.p.A…\l"
	.string "Oh, ciao, {PLAYER}!\p"
	.string "Il presidente era qui fino a poco\n"
	.string "fa, ma è appena uscito.\p"
	.string "Il presidente è sempre impegnato,\n"
	.string "ma anche tu non scherzi, {PLAYER}.$"

MatchCall_Text_MrStone8::
	.string "…Eh? …Come dici?\p"
	.string "Grou… Sì? …don?\p"
	.string "La linea è disturbata…\n"
	.string "…non sento…\p"
	.string "BZZZZ…$"

MatchCall_Text_MrStone9::
	.string "…Eh? …Come dici?\p"
	.string "Antro… Sì? …Abiss…?\p"
	.string "La linea è disturbata…\n"
	.string "…non sento…\p"
	.string "BZZZZ…$"

MatchCall_Text_MrStone10::
	.string "Sig. Petri: {PLAYER}{KUN}! Sono io!\p"
	.string "Pare che tu sia finito in mezzo a\n"
	.string "ogni sorta di faccende, ma io, con\l"
	.string "tutti i miei impegni, non so quali!\p"
	.string "Comunque, ti esorto a scegliere la\n"
	.string "strada in cui credi e a percorrerla.\p"
	.string "Io farò sempre il tifo per te!\n"
	.string "Abbi cura di te!$"

MatchCall_Text_MrStone11::
	.string "Sig. Petri: … … … … … …\n"
	.string "Sei forse {PLAYER}{KUN}?\p"
	.string "Hai una voce così sicura di sé\n"
	.string "che non ti avevo riconosciuto!\p"
	.string "Hm! Devi venire a trovarci alla\n"
	.string "Devon, prima o poi!$"
