@ Only contains the text for the Mauville Man named Giddy. The rest is in scripts/mauville_man.inc
GiddyText_SoPretty::
	.string " da favola!$"

GiddyText_SoDarling::
	.string " un tesoro!$"

GiddyText_SoRelaxed::
	.string " pura pace!$"

GiddyText_SoSunny::
	.string " solare!$"

GiddyText_SoDesirable::
	.string " un sogno!$"

GiddyText_SoExciting::
	.string " da brivido!$"

GiddyText_SoAmusing::
	.string " uno spasso!$"

GiddyText_SoMagical::
	.string " una magia!$"

GiddyText_Is::
	.string " è$"

GiddyText_DontYouAgree::
	.string "\n"
	.string "Non trovi?$"

GiddyText_ISoWantToGoOnAVacation::
	.string "Vorrei andare in vacanza, magari\n"
	.string "oltre un Varco! Conosci un bel posto?$"

GiddyText_IBoughtCrayonsWith120Colors::
	.string "Ho i pastelli da 120 colori!\n"
	.string "Non sono bellissimi?$"

GiddyText_WouldntItBeNiceIfWeCouldFloat::
	.string "Non sarebbe bello volare via\n"
	.string "su una nuvola di bolle di sapone?$"

GiddyText_WhenYouWriteOnASandyBeach::
	.string "Se scrivi sulla sabbia, il mare\n"
	.string "cancella tutto. Che malinconia!$"

GiddyText_WhatsTheBottomOfTheSeaLike::
	.string "Com'è il fondo del mare?\n"
	.string "Vorrei andarci almeno una volta!$"

GiddyText_WhenYouSeeTheSettingSunDoesIt::
	.string "Quando guardi il tramonto, non ti\n"
	.string "viene voglia di tornare a casa?$"

GiddyText_LyingBackInTheGreenGrass::
	.string "Sdraiarsi sull'erba verde…\n"
	.string "Oh, che bello, che bello!$"

GiddyText_SecretBasesAreSoWonderful::
	.string "Adoro le Basi Segrete!\n"
	.string "Non senti l'emozione?$"
