MoveTutor_Text_ThisMoveCanOnlyBeLearnedOnce:
	.string "Questa mossa si può insegnare una\n"
	.string "sola volta. Va bene lo stesso?$"

MoveTutor_Text_SwaggerTeach:
	.string "Eh! Il mio Pokémon è il numero uno!\n"
	.string "È più figo di qualsiasi altro Pokémon!\p"
	.string "Me ne andavo in giro tutto impettito\n"
	.string "a fare il bullo, quando il Presidente\l"
	.string "mi ha fatto una bella ramanzina.\p"
	.string "Mi è passata subito la voglia di fare\n"
	.string "il bullo.\p"
	.string "Se vuoi, posso insegnare la mossa\n"
	.string "Bullo a uno dei tuoi Pokémon.$"

MoveTutor_Text_SwaggerDeclined:
	.string "Come sarebbe, no? Su, un po' di\n"
	.string "grinta, che diamine!$"

MoveTutor_Text_SwaggerWhichMon:
	.string "Bene, quale Pokémon vuole imparare\n"
	.string "a fare il Bullo?$"

MoveTutor_Text_SwaggerTaught:
	.string "D'ora in poi loderò il mio Pokémon\n"
	.string "senza fare il bullo. Promesso.$"

MoveTutor_Text_RolloutTeach:
	.string "Lo sapevi che da qui puoi andare\n"
	.string "lontanissimo da quella parte\l"
	.string "senza mai cambiare direzione?\p"
	.string "Forse potrei perfino arrivarci\n"
	.string "rotolando.\p"
	.string "Secondo te anche i tuoi Pokémon\n"
	.string "hanno voglia di rotolare?\p"
	.string "Se ti va, posso insegnare a uno\n"
	.string "di loro la mossa Rotolamento.$"

MoveTutor_Text_RolloutDeclined:
	.string "Non c'è niente di cui vergognarsi.\n"
	.string "Dai, rotoliamo!$"

MoveTutor_Text_RolloutWhichMon:
	.string "Ehehe, ma certo! Sarebbe bello se\n"
	.string "il Pokémon mi somigliasse un po'.$"

MoveTutor_Text_RolloutTaught:
	.string "Rotolarmi nell'erba mi mette di buon\n"
	.string "umore. Forza, rotoliamo insieme!$"

MoveTutor_Text_FuryCutterTeach:
	.string "C'è una mossa che diventa sempre più\n"
	.string "forte se la usi più volte di fila.\p"
	.string "È di tipo Coleottero, ed è una vera\n"
	.string "bomba.\p"
	.string "Si chiama Tagliofuria.\n"
	.string "Vuoi che la insegni a un Pokémon?$"

MoveTutor_Text_FuryCutterDeclined:
	.string "Non siamo sulla stessa lunghezza\n"
	.string "d'onda.$"

MoveTutor_Text_FuryCutterWhichMon:
	.string "Evvai!\n"
	.string "Mostrami a quale Pokémon insegnarla.$"

MoveTutor_Text_FuryCutterTaught:
	.string "Che brivido vedere se la mossa\n"
	.string "continua a colpire senza sosta!$"

MoveTutor_MimicTeach:
	.string "Ah, giovanotto!\p"
	.string "Anch'io sono giovane, ma imito il modo\n"
	.string "di fare e di parlare degli anziani\l"
	.string "di questo paese.\p"
	.string "Che ne dici, giovanotto?\n"
	.string "Accetteresti, se mi offrissi\l"
	.string "di insegnare la mossa Mimica?$"

MoveTutor_MimicDeclined:
	.string "Uffa! Volevo tanto insegnare Mimica\n"
	.string "ai tuoi Pokémon!$"

MoveTutor_Text_MimicWhichMon:
	.string "Ohohò! E così sia!\n"
	.string "Mostrami il Pokémon a cui\l"
	.string "desideri che la insegni.$"

MoveTutor_Text_MimicTaught:
	.string "Mimica è una mossa di grande\n"
	.string "profondità.\p"
	.string "Saprai eseguirla alla perfezione\n"
	.string "come me…?$"

MoveTutor_Text_MetronomeTeach:
	.string "Vorrei un sacco di cose!\n"
	.string "Ma ho già finito la paghetta…\p"
	.string "Non sarebbe bello se esistesse una\n"
	.string "magia che fa spuntare i soldi\l"
	.string "quando agiti un dito?\p"
	.string "Se vuoi, posso insegnare ai tuoi\n"
	.string "Pokémon la mossa Metronomo.\p"
	.string "I soldi non spunteranno, ma il tuo\n"
	.string "Pokémon agiterà il dito. Va bene?$"

MoveTutor_Text_MetronomeDeclined:
	.string "Va bene. Io resto qui, se cambi\n"
	.string "idea.$"

MoveTutor_Text_MetronomeWhichMon:
	.string "Sì! Te la insegno!\n"
	.string "A quale Pokémon?$"

MoveTutor_Text_MetronomeTaught:
	.string "Quando un Pokémon agita il dito\n"
	.string "come un metronomo, succedono\l"
	.string "tante cose belle.\p"
	.string "Non sarebbe bello poterlo fare\n"
	.string "anche noi? Magari si aprirebbe\l"
	.string "un Varco pieno di dolcetti!$"

MoveTutor_Text_SleepTalkTeach:
	.string "Bah! Mia moglie si affida a\n"
	.string "Introforza per restare sveglia.\p"
	.string "Dovrebbe schiacciare un pisolino\n"
	.string "come me, e usare Sonnolalia.\p"
	.string "Posso insegnare Sonnolalia ai tuoi\n"
	.string "Pokémon, se vuoi. Ti interessa?$"

MoveTutor_Text_SleepTalkDeclined:
	.string "Ah, va bene, va bene. Anche tu vuoi\n"
	.string "restare sveglio con Introforza…$"

MoveTutor_Text_SleepTalkWhichMon:
	.string "Ah, un ragazzo che sa apprezzare!\n"
	.string "A quale Pokémon devo insegnarla?$"

MoveTutor_Text_SleepTalkTaught:
	.string "Non sono mai riuscito a indovinare\n"
	.string "il trucco della moneta di mia moglie.\p"
	.string "Mi basterebbe azzeccarlo una volta,\n"
	.string "anche solo parlando nel sonno…$"

MoveTutor_Text_SubstituteTeach:
	.string "Quando guardo il mondo dall'alto,\n"
	.string "qui sul tetto…\p"
	.string "Penso a quanto sarebbe bello se\n"
	.string "ci fossero tante altre me, magari\l"
	.string "in altri mondi oltre i Varchi,\l"
	.string "per vivere tutte le vite possibili.\p"
	.string "Ovviamente è impossibile.\n"
	.string "Ih ih…\p"
	.string "Ah, ecco! Ti piacerebbe insegnare\n"
	.string "a un Pokémon la mossa Sostituto?$"

MoveTutor_Text_SubstituteDeclined:
	.string "Oh, no?\p"
	.string "Guarda che con quella mossa un\n"
	.string "Pokémon crea una copia di sé stesso.$"

MoveTutor_Text_SubstituteWhichMon:
	.string "Ih ih…\n"
	.string "A quale Pokémon vuoi che\l"
	.string "insegni Sostituto?$"

MoveTutor_Text_SubstituteTaught:
	.string "Noi esseri umani dovremmo goderci\n"
	.string "la vita fino in fondo!\p"
	.string "Spero che ci riuscirai anche tu!$"

MoveTutor_Text_DynamicPunchTeach:
	.string "Non ce la faccio più!\p"
	.string "È tutto inutile!\p"
	.string "Sono un Allenatore di tipo Lotta,\n"
	.string "quindi alla Palestra di Verdeazzupoli\l"
	.string "non vincerò mai, per quanto mi sforzi!\p"
	.string "Argh! Pugno! Pugno! Pugno!\n"
	.string "Pugno! Pugno! Pugno!\p"
	.string "Ehi, non guardarmi così!\n"
	.string "Sto solo prendendo a pugni il suolo!\p"
	.string "O vuoi che insegni Dinamipugno\n"
	.string "ai tuoi Pokémon?$"

MoveTutor_Text_DynamicPunchDeclined:
	.string "Accidenti! Anche tu mi prendi in giro?\n"
	.string "Pugno! Pugno! Pugno!$"

MoveTutor_Text_DynamicPunchWhichMon:
	.string "Cosa? Davvero? Sei un tesoro!\n"
	.string "A quale Pokémon devo insegnarla?$"

MoveTutor_Text_DynamicPunchTaught:
	.string "Vinci alla Palestra di Verdeazzupoli\n"
	.string "a colpi di Dinamipugno, mi raccomando!$"

MoveTutor_Text_DoubleEdgeTeach:
	.string "Sigh…\p"
	.string "Il Capopalestra di Ceneride è così\n"
	.string "adorabile e ammirevole…\p"
	.string "Ma questo vuol dire che ho un sacco\n"
	.string "di rivali in amore.\p"
	.string "Il suo fascino è a doppio taglio,\n"
	.string "proprio come Sdoppiatore.\l"
	.string "Io non riesco nemmeno a farmi notare.\p"
	.string "Ti prego, lascia che insegni ai tuoi\n"
	.string "Pokémon la mossa Sdoppiatore!$"

MoveTutor_Text_DoubleEdgeDeclined:
	.string "Oh…\n"
	.string "Anche tu mi respingi…$"

MoveTutor_Text_DoubleEdgeWhichMon:
	.string "Bene, a quale Pokémon devo\n"
	.string "insegnare Sdoppiatore?$"

MoveTutor_Text_DoubleEdgeTaught:
	.string "Basta vivere per amore!\n"
	.string "Diventerò una tipa tosta!$"

MoveTutor_Text_ExplosionTeach:
	.string "Non ho intenzione di restare per\n"
	.string "sempre in questo buco a far niente.\p"
	.string "Vedrai, me ne andrò in città e farò\n"
	.string "un successo strepitoso.\p"
	.string "Anzi, sul serio: provocherò una vera\n"
	.string "Esplosione di popolarità!\p"
	.string "Visto che hai sentito tutto, insegnerò\n"
	.string "volentieri Esplosione ai tuoi Pokémon!$"

MoveTutor_Text_ExplosionDeclined:
	.string "Bah! Mi dici di no perché vivo\n"
	.string "in un paesino sperduto?$"

MoveTutor_Text_ExplosionWhichMon:
	.string "E va bene! Esplosione sia!\n"
	.string "Quale Pokémon vuole fare il botto?$"

MoveTutor_Text_ExplosionTaught:
	.string "Da anni insegno Esplosione ai\n"
	.string "Pokémon, ma la mia, di Esplosione,\l"
	.string "non è ancora scoppiata…\p"
	.string "Forse perché in fondo in fondo\n"
	.string "preferisco restare qui…$"
