MoveRelearner_Text_WouldLearnNewMoves:
	.string "Ciao! Sono il Ricordamosse.\n"
	.string "Vuoi insegnare nuove mosse ai Pokémon?$"

MoveRelearner_Text_LevelUpMoves:
	.string "Mosse Livello$"

MoveRelearner_Text_EggMoves:
	.string "Mosse Uovo$"

MoveRelearner_Text_TMMoves:
	.string "Mosse MT$"

MoveRelearner_Text_TutormoveMoves:
	.string "Mosse Tutor$"

MoveRelearner_Text_SeeYa:
	.string "A presto!$"

MoveRelearner_Text_AnythingElse:
	.string "Posso fare altro per te?$"

MoveRelearner_Text_ChoosePkmn:
	.string "Scegli un Pokémon, per favore.$"

MoveRelearner_Text_HaveNoPkmn:
	.string "Non hai nessun Pokémon.$"

MoveRelearner_Text_CantTeachMoveToEgg:
	.string "Mi dispiace…\n"
	.string "Ma un Uovo non può imparare mosse.$"

MoveRelearner_Text_CantTeachMoveToPkmn:
	.string "Mi dispiace…\p"
	.string "Non c'è nessuna mossa che io possa\n"
	.string "insegnare a quel Pokémon.$"

MoveRelearner_Text_LevelUpMoveLWR::
	.string "mossa di livello$"

MoveRelearner_Text_EggMoveLWR::
	.string "mossa Uovo$"

MoveRelearner_Text_TMMoveLWR::
	.string "mossa MT$"

MoveRelearner_Text_TutorMoveLWR::
	.string "mossa Tutor$"

MoveRelearner_Text_MoveLWR::
	.string "mossa$"

MoveRelearner_Text_WhichXmoveShouldTeach:
	.string "Quale {STR_VAR_3} devo insegnare?$"

MoveRelearner_Text_ThankYouComeAgain:
	.string "Grazie per essere passato!\n"
	.string "Le mosse non scappano: torna presto!$"
