gText_ObtainedTheItem::
	.string "Hai ottenuto {STR_VAR_2}!$"

gText_TheBagIsFull::
	.string "La Borsa è piena…$"

gText_PutItemInPocket::
	.string "{PLAYER} ripone {STR_VAR_2}\n"
	.string "nella Tasca {STR_VAR_3}.$"

gText_PlayerFoundOneItem::
	.string "{PLAYER} ha trovato {STR_VAR_2}!$"

gText_TooBadBagIsFull::
	.string "Peccato!\n"
	.string "La Borsa è piena…$"

gText_PlayerPutItemInBag::
	.string "{PLAYER} ripone {STR_VAR_2}\n"
	.string "nella Borsa.$"

gText_ObtainedTheDecor::
	.string "Hai ottenuto {STR_VAR_2}!$"

gText_NoRoomLeftForAnother::
	.string "Peccato! Non c'è più posto\n"
	.string "per {STR_VAR_2}…$"

gText_TheDecorWasTransferredToThePC::
	.string "Hai inviato {STR_VAR_2}\n"
	.string "al PC.$"

gText_ObtainedTheItems::
	.string "Hai ottenuto {STR_VAR_1} {STR_VAR_2}!$"

gText_PlayerFoundItems::
	.string "{PLAYER} ha trovato\n"
	.string "{STR_VAR_1} {STR_VAR_2}!$"

gText_PutCoinsAwayInCoinCase::
	.string "{PLAYER} ripone i Gettoni\n"
	.string "nel Salvadanaio.$"

gText_FoundXCoins::
	.string "{PLAYER} ha trovato\n"
	.string "{STR_VAR_1} {STR_VAR_2}!$"

gText_FoundXItems::
	.string "{PLAYER} ha trovato\n"
	.string "{STR_VAR_1} {STR_VAR_2}!$"

gText_CoinCaseIsFull::
	.string "Peccato!\n"
	.string "Il Salvadanaio è pieno…$"

gText_NothingToPutThemIn::
	.string "Peccato!\n"
	.string "Non hai niente in cui metterli…$"
