Text_BootUpPC:
	.string "{PLAYER} ha acceso il PC.$"

gText_WhichPCShouldBeAccessed::
	.string "A quale PC vuoi accedere?$"

gText_AccessedSomeonesPC::
	.string "Accesso al PC di qualcuno.$"

gText_StorageSystemOpened::
	.string "Sistema Memoria Pokémon avviato.$"

gText_AccessedPlayersPC::
	.string "Accesso al PC di {PLAYER}.$"

gText_AccessedLanettesPC::
	.string "Accesso al PC di Lanette.$"

gText_AccessedBillsPC::
	.string "Accesso al PC di Bill.$"
