gText_WouldYouLikeToRestYourPkmn::
	.string "Ciao, e benvenuto al\n"
	.string "Centro Pokémon!\p"
	.string "Qui rimettiamo in forma i Pokémon\n"
	.string "stanchi, da qualunque mondo arrivino.\p"
	.string "Vuoi che curi i tuoi Pokémon?$"

gText_IllTakeYourPkmn::
	.string "D'accordo, allora prendo i tuoi\n"
	.string "Pokémon per qualche secondo.$"

gText_RestoredPkmnToFullHealth::
	.string "Grazie per l'attesa.\p"
	.string "I tuoi Pokémon sono di nuovo\n"
	.string "in perfetta forma.$"

gText_WeHopeToSeeYouAgain::
	.string "Torna a trovarci quando vuoi!$"

gText_WelcomeCutShort::
	.string "Ciao, e benvenuto al\n"
	.string "Centro Pokémon!\p"
	.string "Qui rimettiamo in forma i Pokémon\n"
	.string "stanchi, da qualunque mondo arrivino.\p"
	.string "Vuoi che curi i tuoi…$"

gText_NoticesGoldCard::
	.string "Q-quella scheda…\n"
	.string "Ma è… una Scheda d'oro?!\p"
	.string "Che splendore, quel colore dorato!\n"
	.string "E le quattro stelle scintillano!\p"
	.string "Di Allenatori con la Scheda d'argento\n"
	.string "ne ho visti parecchi, ma tu, {PLAYER},\l"
	.string "sei il primo che vedo con una\l"
	.string "Scheda d'oro!\p"
	.string "Allora, {PLAYER}, concedimi l'onore\n"
	.string "di curare i tuoi Pokémon!$"

gText_YouWantTheUsual::
	.string "Che bello rivederti, {PLAYER}!\n"
	.string "Il solito, vero?$"

gText_IllTakeYourPkmn2::
	.string "D'accordo, allora prendo i tuoi\n"
	.string "Pokémon per qualche secondo.$"

gText_ThankYouForWaiting::
	.string "Grazie per l'attesa.$"

gText_WeHopeToSeeYouAgain2::
	.string "Torna a trovarci quando vuoi!$"
