gBirchDexRatingText_AreYouCurious::
	.string "Prof. Birch: Ah, {PLAYER}{KUN}!\p"
	.string "Sei curioso di sapere a che punto\n"
	.string "è il tuo Pokédex?$"

gBirchDexRatingText_Cancel::
	.string "Mmh? Oh, non hai ancora catturato\n"
	.string "abbastanza Pokémon per valutarlo.$"

gBirchDexRatingText_SoYouveSeenAndCaught::
	.string "Dunque, dunque…\p"
	.string "Hai visto {STR_VAR_1} Pokémon\n"
	.string "e ne hai catturati {STR_VAR_2}…$"

gBirchDexRatingText_LessThan10::
	.string "Esplora di più l'erba alta e cerca\n"
	.string "i Pokémon con più attenzione.$"

gBirchDexRatingText_LessThan20::
	.string "Stai cominciando a prenderci la mano.\n"
	.string "Ma da qui in poi si fa più dura!$"

gBirchDexRatingText_LessThan30::
	.string "Alcuni Pokémon compaiono solo\n"
	.string "in certe zone.\l"
	.string "Devi essere tenace!$"

gBirchDexRatingText_LessThan40::
	.string "Beh, servirebbe un po' più di quantità,\n"
	.string "ma ormai comincia ad assomigliare\l"
	.string "a un vero Pokédex.$"

gBirchDexRatingText_LessThan50::
	.string "Procede piuttosto bene.\n"
	.string "Continua così!$"

gBirchDexRatingText_LessThan60::
	.string "Hai provato a pescare con l'Amo?\n"
	.string "Nel mare vivono tantissimi Pokémon!$"

gBirchDexRatingText_LessThan70::
	.string "Invece di limitarti a catturarli,\n"
	.string "perché non provi anche a farli evolvere?$"

gBirchDexRatingText_LessThan80::
	.string "Sarà un Pokédex fantastico.\n"
	.string "Ho un ottimo presentimento!$"

gBirchDexRatingText_LessThan90::
	.string "Ne hai raccolti così tanti…\n"
	.string "Hai un talento straordinario!$"

gBirchDexRatingText_LessThan100::
	.string "Sei stato alla Zona Safari?\p"
	.string "Dicono che ci siano Pokémon che\n"
	.string "si possono catturare solo lì.$"

gBirchDexRatingText_LessThan110::
	.string "Finalmente hai raggiunto\n"
	.string "quota 100 specie!\p"
	.string "È un Pokédex davvero notevole!$"

gBirchDexRatingText_LessThan120::
	.string "Forse alcuni Pokémon si nascondono\n"
	.string "nelle rocce da rompere con Spaccaroccia.$"

gBirchDexRatingText_LessThan130::
	.string "Prova a ottenere altri Pokémon\n"
	.string "facendo scambi con altre persone.$"

gBirchDexRatingText_LessThan140::
	.string "Ho sentito parlare di Pokémon che si\n"
	.string "evolvono quando si affezionano\l"
	.string "davvero al loro Allenatore.$"

gBirchDexRatingText_LessThan150::
	.string "Non immaginavo che a Hoenn vivessero\n"
	.string "così tante specie di Pokémon.\l"
	.string "Merito anche dei Varchi, forse!$"

gBirchDexRatingText_LessThan160::
	.string "A volte certi Pokémon compaiono\n"
	.string "in massa, tutti nello stesso posto.\p"
	.string "Non lasciarti sfuggire occasioni\n"
	.string "del genere!$"

gBirchDexRatingText_LessThan170::
	.string "Basta sfogliare il tuo Pokédex per\n"
	.string "farsi un'idea precisa dei Pokémon\l"
	.string "che vivono nella regione di Hoenn.$"

gBirchDexRatingText_LessThan180::
	.string "Direi che potresti già fare il\n"
	.string "Professore Pokémon…\l"
	.string "E pure uno bravo!$"

gBirchDexRatingText_LessThan190::
	.string "Con un Pokédex così completo,\n"
	.string "sei un vero professionista!$"

gBirchDexRatingText_LessThan200::
	.string "Ti manca pochissimo per completare\n"
	.string "questo Pokédex.\l"
	.string "Me lo sento fin nelle ossa!$"

gBirchDexRatingText_DexCompleted::
	.string "Straordinario! Congratulazioni!\n"
	.string "Il tuo Pokédex è completo!$"

gBirchDexRatingText_OnANationwideBasis::
	.string "Mmh…\n"
	.string "E contando tutti i mondi…\p"
	.string "Hai visto {STR_VAR_1} Pokémon\n"
	.string "e ne hai catturati {STR_VAR_2}…$"

@ FRLG

PokedexRating_Text_HowIsPokedexComingAlong::
	.string "Prof. Oak: Che piacere vederti!\n"
	.string "Come procede il tuo Pokédex?\p"
	.string "Su, fammi dare un'occhiata.$"

PokedexRating_Text_SeenXOwnedY::
	.string "Ecco a che punto è il tuo\n"
	.string "Pokédex:\p"
	.string "{STR_VAR_1} Pokémon visti e\n"
	.string "{STR_VAR_2} Pokémon catturati.\p"
	.string "{FONT_NORMAL}Valutazione del Prof. Oak:$"

PokedexRating_Text_LessThan10::
	.string "Hai ancora tanta strada da fare.\p"
	.string "Entra in ogni ciuffo d'erba che vedi\n"
	.string "e cerca i Pokémon!$"

PokedexRating_Text_LessThan20::
	.string "Mi sembra che tu sia sulla\n"
	.string "strada giusta!\p"
	.string "Ho dato a uno dei miei Assistenti la\n"
	.string "MN Flash. Vai a prenderla!$"

PokedexRating_Text_LessThan30::
	.string "Il tuo Pokédex ha ancora bisogno\n"
	.string "di un po' di volume!\p"
	.string "Prova a catturare altre specie\n"
	.string "di Pokémon!$"

PokedexRating_Text_LessThan40::
	.string "Bene, si vede che ti stai\n"
	.string "impegnando!\p"
	.string "Ho dato a uno dei miei Assistenti un\n"
	.string "Ricerca Strum. Vai a prenderlo!$"

PokedexRating_Text_LessThan50::
	.string "Il tuo Pokédex procede\n"
	.string "proprio bene!\p"
	.string "Ho dato a uno dei miei Assistenti un\n"
	.string "Monetamuleto. Vai a prenderlo!$"

PokedexRating_Text_LessThan60::
	.string "Ah, finalmente hai superato\n"
	.string "le 50 specie!\p"
	.string "Ho dato a uno dei miei Assistenti un\n"
	.string "Condividi Esp. Vai a prenderlo!$"

PokedexRating_Text_LessThan70::
	.string "Ohoh! Sta diventando un Pokédex\n"
	.string "di tutto rispetto!$"

PokedexRating_Text_LessThan80::
	.string "Molto bene!\p"
	.string "Credo che andando a pesca troverai\n"
	.string "ancora più Pokémon!$"

PokedexRating_Text_LessThan90::
	.string "Magnifico! Fammi indovinare… Ti\n"
	.string "piace collezionare cose, vero?$"

PokedexRating_Text_LessThan100::
	.string "Sono colpito!\n"
	.string "Dev'essere stata una bella impresa!$"

PokedexRating_Text_LessThan110::
	.string "Finalmente sei arrivato a 100 specie!\n"
	.string "Non credo ai miei occhi, che bravura!$"

PokedexRating_Text_LessThan120::
	.string "Hai perfino le forme evolute\n"
	.string "dei Pokémon! Super!$"

PokedexRating_Text_LessThan130::
	.string "Eccellente! Fai scambi con gli amici\n"
	.string "per ottenerne altri!$"

PokedexRating_Text_LessThan140::
	.string "Fenomenale!\n"
	.string "Ormai sei un vero esperto!$"

PokedexRating_Text_LessThan150::
	.string "Non ho più niente da dirti!\n"
	.string "Ora il Professore Pokémon sei tu!$"

PokedexRating_Text_Complete::
	.string "Il tuo Pokédex è completo in tutto e\n"
	.string "per tutto! Congratulazioni!!$"

PokedexRating_Text_NationalDexSeenXOwnedY::
	.string "E il tuo Pokédex Nazionale:\p"
	.string "{STR_VAR_1} Pokémon visti e\n"
	.string "{STR_VAR_2} Pokémon catturati.$"

PokedexRating_Text_LookForwardToFilledNationalDex::
	.string "Non vedo l'ora di vederti completare\n"
	.string "il Pokédex Nazionale!$"

PokedexRating_Text_YouveCompletedDex::
	.string "Finalmente…\p"
	.string "Finalmente hai completato\n"
	.string "il Pokédex!\p"
	.string "È magnifico!\n"
	.string "Un'impresa davvero fantastica!$"

PokedexRating_Text_Wroooaaarrr::
	.string "Uooooooooaaaaaaahhh!$"

PokedexRating_Text_ThankYouMadeDreamReality::
	.string "Grazie, {PLAYER}!\n"
	.string "Grazie di cuore!\l"
	.string "Hai trasformato il mio sogno in realtà!$"

PokedexRating_Text_LoveSeeingYourPokedex::
	.string "Prof. Oak: Ah, benvenuto!\p"
	.string "Dimmi, come procede il tuo\n"
	.string "Pokédex?\p"
	.string "Ahahah!\p"
	.string "A dire il vero lo so già, ma mi\n"
	.string "piace sempre dargli un'occhiata!\p"
	.string "Vediamo…$"
