Questionnaire_Text_FillOut::
	.string "C'è un questionario.\n"
	.string "Vuoi compilarlo?$"

Questionnaire_Text_ThankYou::
	.string "Grazie per aver dedicato un po'\n"
	.string "di tempo al nostro questionario.\p"
	.string "Le tue risposte ci aiuteranno\n"
	.string "a migliorare in futuro.$"

Questionnaire_Text_YouKnowThoseWordsGift::
	.string "Oh, ciao!\n"
	.string "Conosci quelle parole?\p"
	.string "Allora devi sapere tutto\n"
	.string "del Dono Segreto.\p"
	.string "D'ora in poi potrai ricevere\n"
	.string "anche tu i Doni Segreti!$"

Questionnaire_Text_YouCanAccessMysteryGift::
	.string "Dopo aver salvato la partita, potrai\n"
	.string "accedere al Dono Segreto.$"

Questionnaire_Text_YouKnowThoseWordsEvent::
	.string "Oh, ciao!\n"
	.string "Conosci quelle parole?\p"
	.string "Allora devi sapere tutto\n"
	.string "dell'Evento Misterioso.$"

Questionnaire_Text_YouCanAccessMysteryEvent::
	.string "Dopo aver salvato la partita, potrai\n"
	.string "accedere all'Evento Misterioso.$"

MysteryGift_Text_TheresATicketForYou::
	.string "Grazie per aver usato il sistema\n"
	.string "Evento Misterioso.\p"
	.string "Tu devi essere {PLAYER}.\n"
	.string "C'è un biglietto per te.$"

MysteryGift_Text_TryUsingItAtLilycovePort::
	.string "A quanto pare, si usa al porto\n"
	.string "di Porto Alghepoli.\p"
	.string "Perché non vai a provarlo? Chissà\n"
	.string "dove ti porterà!$"
