	.align 2
gText_ConfirmSave::
	.string "Vuoi salvare la partita?$"

gText_AlreadySavedFile::
	.string "Esiste già un file di salvataggio.\n"
	.string "Vuoi sovrascriverlo?$"

gText_SavingDontTurnOff::
	.string "Salvataggio in corso…\n"
	.string "Non spegnere la console!$"

gText_PlayerSavedGame::
	.string "{PLAYER} ha salvato la partita.$"

gText_DifferentSaveFile::
	.string "Attenzione!\p"
	.string "C'è già un file salvato che\n"
	.string "appartiene a un'altra partita.\p"
	.string "Se salvi ora, l'avventura dell'altro\n"
	.string "file, compresi strumenti e Pokémon,\l"
	.string "andrà persa per sempre.\p"
	.string "Vuoi davvero salvare adesso e\n"
	.string "sovrascrivere l'altro salvataggio?$"

gText_SaveError::
	.string "Errore di salvataggio.\p"
	.string "Sostituisci la memoria\n"
	.string "di backup.$"

gText_SavingDontTurnOffPower::
	.string "Salvataggio in corso…\n"
	.string "Non spegnere la console!$"
