SecretBase_Text_Trainer0Intro:
	.string "Hai già creato una Base Segreta?\p"
	.string "Io ho girato in lungo e in largo\n"
	.string "prima di scegliere questo posto.\p"
	.string "Visto che sei qui, che ne dici\n"
	.string "di una bella lotta?$"

SecretBase_Text_Trainer0AcceptBattle:
	.string "Perfetto!\n"
	.string "Arriviamo!$"

SecretBase_Text_Trainer0DeclineBattle:
	.string "Eh?\n"
	.string "Ah, adesso non puoi…$"

SecretBase_Text_Trainer0Defeated::
	.string "Uaaargh! Sei troppo forte!\n"
	.string "Ho perso? Acqua in bocca, eh!$"

SecretBase_Text_Trainer0PostBattle:
	.string "Che ne pensi della mia Base Segreta?\n"
	.string "Torna a trovarmi domani.$"

SecretBase_Text_Trainer0PreChampion:
	.string "Hai già creato una Base Segreta?\p"
	.string "Io ho girato in lungo e in largo\n"
	.string "prima di scegliere questo posto.\p"
	.string "Fai pure come se fossi a casa tua!$"

SecretBase_Text_Trainer5Intro:
	.string "Ci sono un sacco di posti dove\n"
	.string "creare una Base Segreta.\p"
	.string "Ma questo è il mio preferito.\n"
	.string "Carino, non trovi?\p"
	.string "Oh, ti andrebbe di lottare?$"

SecretBase_Text_Trainer5AcceptBattle:
	.string "Bene, si comincia!$"

SecretBase_Text_Trainer5DeclineBattle:
	.string "Oh…\n"
	.string "Adesso non puoi? Va bene.$"

SecretBase_Text_Trainer5Defeated::
	.string "Mmm… Abbiamo perso…\n"
	.string "Ma non dirlo a nessuno!\l"
	.string "È un segreto segretissimo!$"

SecretBase_Text_Trainer5PostBattle:
	.string "Se ripassi da queste parti,\n"
	.string "spero che verrai a trovarmi.$"

SecretBase_Text_Trainer5PreChampion:
	.string "Ci sono un sacco di posti dove\n"
	.string "creare una Base Segreta.\p"
	.string "Ma questo è il mio preferito.\n"
	.string "Carino, non trovi?$"

SecretBase_Text_Trainer1Intro:
	.string "Questo posto è gettonatissimo.\n"
	.string "È sempre occupato.\p"
	.string "Oh! Stavi pensando di prenderlo\n"
	.string "anche tu?\p"
	.string "Facciamo così: se riesci a battermi,\n"
	.string "questo posto è tuo.$"

SecretBase_Text_Trainer1AcceptBattle:
	.string "D'accordo!\n"
	.string "Difenderò la mia Base Segreta!$"

SecretBase_Text_Trainer1DeclineBattle:
	.string "Eh? Davvero?\n"
	.string "Questo posto non ti interessa?$"

SecretBase_Text_Trainer1Defeated::
	.string "Non ce la faccio più!\n"
	.string "Mi arrendo!$"

SecretBase_Text_Trainer1PostBattle:
	.string "Va bene: quando un giorno traslocherò,\n"
	.string "questo posto sarà tuo!$"

SecretBase_Text_Trainer1PreChampion:
	.string "Questo posto è gettonatissimo.\n"
	.string "È sempre occupato.\p"
	.string "Ho aspettato un sacco che si liberasse.\n"
	.string "Finalmente è mio!$"

SecretBase_Text_Trainer6Intro:
	.string "Benvenuto nel mio Laboratorio Pokémon.\p"
	.string "Qui studio le lotte in gran segreto.\n"
	.string "E, quando capita, anche i Varchi!\p"
	.string "Vuoi vedere quanto sono forte?$"

SecretBase_Text_Trainer6AcceptBattle:
	.string "Darò il massimo!$"

SecretBase_Text_Trainer6DeclineBattle:
	.string "Oh.\n"
	.string "Sarà per un'altra volta!$"

SecretBase_Text_Trainer6Defeated::
	.string "Mmm… Ho ancora tanto da imparare.\n"
	.string "Devo studiare di più.$"

SecretBase_Text_Trainer6PostBattle:
	.string "Grazie per aver lottato con me.\n"
	.string "Torna a trovarmi domani.$"

SecretBase_Text_Trainer6PreChampion:
	.string "Benvenuto nel mio Laboratorio Pokémon.\p"
	.string "Qui studio le lotte in gran segreto.\n"
	.string "E, quando capita, anche i Varchi!$"

SecretBase_Text_Trainer2Intro:
	.string "Una villa enorme è bella, ma io\n"
	.string "preferisco un posticino così.\p"
	.string "Mi piace perché viene a trovarmi\n"
	.string "gente di tutti i tipi.\p"
	.string "Allora, ti va una lotta?$"

SecretBase_Text_Trainer2AcceptBattle:
	.string "Così si fa!$"

SecretBase_Text_Trainer2DeclineBattle:
	.string "Quando sei pronto, fammi un fischio!$"

SecretBase_Text_Trainer2Defeated::
	.string "Uffa! Mi hai steso!\n"
	.string "Ma lottare è sempre uno spasso!$"

SecretBase_Text_Trainer2PostBattle:
	.string "Bene, ora devo andare a comprare\n"
	.string "qualche decorazione e dei mobili.\p"
	.string "Voglio che la mia Base Segreta sia\n"
	.string "un posto dove tutti si trovino bene.$"

SecretBase_Text_Trainer2PreChampion:
	.string "Una villa enorme è bella, ma io\n"
	.string "preferisco un posticino così.\p"
	.string "Mi piace perché viene a trovarmi\n"
	.string "gente di tutti i tipi.$"

SecretBase_Text_Trainer7Intro:
	.string "Adoro fare acquisti di decorazioni\n"
	.string "e mobili.\p"
	.string "E adoro allevare Pokémon\n"
	.string "altrettanto.\p"
	.string "Se fossi così gentile, lotteresti\n"
	.string "con i miei Pokémon?$"

SecretBase_Text_Trainer7AcceptBattle:
	.string "Grazie.\n"
	.string "Vogliamo cominciare?$"

SecretBase_Text_Trainer7DeclineBattle:
	.string "Oh.\n"
	.string "Che peccato…$"

SecretBase_Text_Trainer7Defeated::
	.string "Mi inchino…$"

SecretBase_Text_Trainer7PostBattle:
	.string "È stato un piacevolissimo svago!\n"
	.string "Ora vado a godermi un po' di shopping.$"

SecretBase_Text_Trainer7PreChampion:
	.string "Adoro fare acquisti di decorazioni\n"
	.string "e mobili.\p"
	.string "E adoro allevare Pokémon\n"
	.string "altrettanto.$"

SecretBase_Text_Trainer3Intro:
	.string "C'è chi crea la sua Base Segreta in\n"
	.string "posti difficilissimi da trovare.\l"
	.string "Vorrà forse restare nascosto?\p"
	.string "Ma visto che mi hai trovato, che\n"
	.string "ne dici di una lotta?$"

SecretBase_Text_Trainer3AcceptBattle:
	.string "Non mi farò battere facilmente!$"

SecretBase_Text_Trainer3DeclineBattle:
	.string "Oh… Sei stanco per tutta la strada\n"
	.string "che hai fatto per trovarmi?$"

SecretBase_Text_Trainer3Defeated::
	.string "Sono crollato…$"

SecretBase_Text_Trainer3PostBattle:
	.string "Dov'è la tua Base Segreta?\n"
	.string "Verrò a trovarti.$"

SecretBase_Text_Trainer3PreChampion:
	.string "C'è chi crea la sua Base Segreta in\n"
	.string "posti difficilissimi da trovare.\l"
	.string "Vorrà forse restare nascosto?$"

SecretBase_Text_Trainer8Intro:
	.string "Mi hanno detto che le decorazioni\n"
	.string "si possono ottenere in tanti modi.\p"
	.string "Facciamo una gara a chi trova le\n"
	.string "decorazioni e i mobili più belli!\p"
	.string "Nel frattempo, ti va una lotta?$"

SecretBase_Text_Trainer8AcceptBattle:
	.string "Questa è la mia Base Segreta.\n"
	.string "Non posso perdere!$"

SecretBase_Text_Trainer8DeclineBattle:
	.string "Io sono pronta a lottare quando vuoi.$"

SecretBase_Text_Trainer8Defeated::
	.string "Eh?\n"
	.string "Ho appena perso?$"

SecretBase_Text_Trainer8PostBattle:
	.string "Ma a collezionare decorazioni non\n"
	.string "perderò! Torna a trovarmi!$"

SecretBase_Text_Trainer8PreChampion:
	.string "Mi hanno detto che le decorazioni\n"
	.string "si possono ottenere in tanti modi.\p"
	.string "Facciamo una gara a chi trova le\n"
	.string "decorazioni e i mobili più belli!$"

SecretBase_Text_Trainer4Intro:
	.string "Ho trovato un posto che mi piaceva\n"
	.string "e l'ho arredato a modo mio.\p"
	.string "Alleno il mio Pokémon preferito\n"
	.string "e divento forte insieme a lui.\p"
	.string "Ecco cosa faccio.\n"
	.string "Ti va di lottare con me?$"

SecretBase_Text_Trainer4AcceptBattle:
	.string "Fammi vedere di che pasta sei fatto!$"

SecretBase_Text_Trainer4DeclineBattle:
	.string "Capita, a volte, di non averne\n"
	.string "voglia.$"

SecretBase_Text_Trainer4Defeated::
	.string "Adesso so di che pasta sei fatto!$"

SecretBase_Text_Trainer4PostBattle:
	.string "Possiamo diventare più forti tutti\n"
	.string "e due. Diamoci dentro!$"

SecretBase_Text_Trainer4PreChampion:
	.string "Ho trovato un posto che mi piaceva\n"
	.string "e l'ho arredato a modo mio.\p"
	.string "Alleno il mio Pokémon preferito\n"
	.string "e divento forte insieme a lui.\p"
	.string "Ogni giorno è un giorno fantastico.$"

SecretBase_Text_Trainer9Intro:
	.string "Dalle decorazioni che una persona\n"
	.string "sceglie, e da come le dispone,\l"
	.string "si capiscono un sacco di cose sui\l"
	.string "suoi gusti.\p"
	.string "Che ne pensi dei miei gusti?\n"
	.string "Sei rimasto senza parole?\p"
	.string "Vuoi vedere il mio stile in lotta?$"

SecretBase_Text_Trainer9AcceptBattle:
	.string "Non mi tratterrò!$"

SecretBase_Text_Trainer9DeclineBattle:
	.string "Sarò felice di mostrarti il mio stile\n"
	.string "quando vuoi.$"

SecretBase_Text_Trainer9Defeated::
	.string "Hai un talento straordinario!\n"
	.string "La tua forza sembra senza limiti…$"

SecretBase_Text_Trainer9PostBattle:
	.string "Che ne pensi del mio stile?\n"
	.string "Continuerò a perfezionarlo!$"

SecretBase_Text_Trainer9PreChampion:
	.string "Dalle decorazioni che una persona\n"
	.string "sceglie, e da come le dispone,\l"
	.string "si capiscono un sacco di cose sui\l"
	.string "suoi gusti.\p"
	.string "Che ne pensi dei miei gusti?\n"
	.string "Sei rimasto senza parole?$"
