ShoalCave_LowTideEntranceRoom_Text_AreYouPlanningOnGoingInThere:
	.string "Hai intenzione di addentrarti\n"
	.string "là dentro?\p"
	.string "Che ne dici di riportarmi un po' di\n"
	.string "Sale Ondoso e qualche Gusciondoso?\p"
	.string "Se mi porti gli ingredienti, posso\n"
	.string "prepararti qualcosa di speciale.$"

ShoalCave_LowTideEntranceRoom_Text_BringMe4ShoalSaltAndShells:
	.string "Se mi porti quattro Sale Ondoso\n"
	.string "e quattro Gusciondoso, posso\l"
	.string "prepararti una Conchinella…\p"
	.string "Gli ingredienti li trovi là dentro\n"
	.string "tutti i giorni.$"

ShoalCave_LowTideEntranceRoom_Text_WouldYouLikeShellBell:
	.string "Oh, ehi! Sale Ondoso e Gusciondoso!\n"
	.string "E ce ne sono abbastanza!\p"
	.string "Vuoi che ti prepari una\n"
	.string "Conchinella con questi?$"

ShoalCave_LowTideEntranceRoom_Text_MakeShellBellRightAway:
	.string "Benissimo, allora! Ti preparo\n"
	.string "subito una Conchinella.\p"
	.string "… … … … … … … …\n"
	.string "… … … … … … … …\p"
	.string "Ecco qua! Fatto!$"

ShoalCave_LowTideEntranceRoom_Text_ExplainShellBell:
	.string "Falla tenere a un Pokémon.\n"
	.string "Gli piacerà, puoi starne certo.\p"
	.string "Ah, il trillo della Conchinella…\n"
	.string "Non c'è musica più bella!\p"
	.string "Gli ingredienti si trovano ogni giorno,\n"
	.string "quindi posso fartene delle altre.$"

ShoalCave_LowTideEntranceRoom_Text_WantedToMakeShellBell:
	.string "Oh… Ah, è così…\n"
	.string "E io che volevo fare una Conchinella…$"

ShoalCave_LowTideEntranceRoom_Text_NoSpaceInYourBag:
	.string "Se te la preparassi, non avresti\n"
	.string "spazio nella Borsa.\p"
	.string "Fai un po' di posto e torna a\n"
	.string "prenderti la tua Conchinella.$"

ShoalCave_Text_WasShoalSaltNowNothing:
	.string "Qui c'era del Sale Ondoso.\n"
	.string "Ma ora non c'è più niente.$"

ShoalCave_Text_WasShoallShellNowNothing:
	.string "Qui c'era un Gusciondoso.\n"
	.string "Ma ora non c'è più niente.$"
