Route102_Text_CalvinIntro:
	.string "Se hai dei Pokémon con te, allora\n"
	.string "sei un Allenatore a tutti gli effetti!\l"
	.string "Non puoi rifiutare la mia sfida!$"

Route102_Text_CalvinDefeated:
	.string "Aaargh, ho perso…\n"
	.string "Dovevo allenarli di più, i miei Pokémon…$"

Route102_Text_CalvinPostBattle:
	.string "Ehi, tu! Se eri così forte,\n"
	.string "potevi anche avvisarmi prima!$"

Route102_Text_CalvinRegister:
	.string "Dall'ultima volta che ci siamo visti\n"
	.string "mi sono allenato come un matto.\p"
	.string "Voglio la rivincita! Mi registri\n"
	.string "nel tuo PokéNav?$"

Route102_Text_CalvinRegisterShort:
	.string "Voglio la rivincita! Mi registri\n"
	.string "nel tuo PokéNav?$"

Route102_Text_CalvinRematchIntro:
	.string "Da quando mi hai battuto, ho allenato\n"
	.string "i miei Pokémon senza sosta.\l"
	.string "Non puoi rifiutare la mia sfida!$"

Route102_Text_CalvinRematchDefeated:
	.string "Aaargh, ho perso di nuovo…\n"
	.string "Sbaglio qualcosa negli allenamenti?$"

Route102_Text_CalvinRematchPostBattle:
	.string "Se tu diventi più forte,\n"
	.string "allora lo diventerò anch'io!$"

Route102_Text_AllenIntro:
	.string "Sei appena diventato un Allenatore?\n"
	.string "Allora siamo due principianti!$"

Route102_Text_AllenDefeated:
	.string "Ti ho sfidato perché pensavo\n"
	.string "di poterti battere…$"

Route102_Text_AllenPostBattle:
	.string "Non ho ancora vinto neanche una volta…\n"
	.string "Speriamo di farcela presto…$"

Route102_Text_RickIntro:
	.string "Ahah! I nostri sguardi si sono incrociati!\n"
	.string "Ti sfido con i miei Pokémon Coleottero!$"

Route102_Text_RickDefeated:
	.string "Ahia! Steso al tappeto!$"

Route102_Text_RickPostBattle:
	.string "Se incroci lo sguardo di un Allenatore,\n"
	.string "devi sfidarlo! È la regola!$"

Route102_Text_TianaIntro:
	.string "Voglio vincere sempre e diventare\n"
	.string "l'Allenatrice più forte di tutte.\p"
	.string "Aiutami a fare carriera!$"

Route102_Text_TianaDefeated:
	.string "Ho finito per far fare carriera a te…$"

Route102_Text_TianaPostBattle:
	.string "Per continuare a salire, mi sa che\n"
	.string "devo catturare altri Pokémon.$"

Route103_Text_DaisyIntro:
	.string "Hai sentito il richiamo della nostra\n"
	.string "fragranza che rasserena l'anima?$"

Route103_Text_DaisyDefeated:
	.string "Il nostro profumo non ti ha incantato…$"

Route103_Text_DaisyPostBattle:
	.string "L'aromaterapia cura lo spirito\n"
	.string "con il potere delle fragranze.\p"
	.string "Vicino ai Varchi, invece, l'aria sa\n"
	.string "di ozono… Che profumo bizzarro!$"

Route103_Text_AmyIntro:
	.string "Amy: Io sono Amy.\n"
	.string "E questa è la mia sorellina Liv.\l"
	.string "Lottiamo sempre in coppia!$"

Route103_Text_AmyDefeated:
	.string "Amy: Ops, abbiamo perso.$"

Route103_Text_AmyPostBattle:
	.string "Amy: Quando lotti contro due\n"
	.string "Allenatori insieme, devi tenere\l"
	.string "d'occhio un sacco di cose!$"

Route103_Text_AmyNotEnoughPokemon:
	.string "Amy: Ops, hai con te un Pokémon solo.\n"
	.string "Così non puoi lottare contro di noi.$"

Route103_Text_LivIntro:
	.string "Liv: Noi due lottiamo come una\n"
	.string "squadra sola.$"

Route103_Text_LivDefeated:
	.string "Liv: Oh, abbiamo perso, sorellona…$"

Route103_Text_LivPostBattle:
	.string "Liv: Io e la mia sorellona siamo\n"
	.string "una coppia perfetta…\p"
	.string "Eppure abbiamo perso…$"

Route103_Text_AmyLivRegister:
	.string "Liv: Guarda che siamo molto più brave…\n"
	.string "Davvero! La prossima volta vedrai!$"

Route103_Text_LivNotEnoughPokemon:
	.string "Liv: Se vuoi sfidarci, devi avere\n"
	.string "almeno due Pokémon!\l"
	.string "Altrimenti non vale!$"

Route103_Text_AmyRematchIntro:
	.string "Amy: Ciao, sono sempre Amy!\n"
	.string "E questa è la mia sorellina Liv.\l"
	.string "Lottiamo sempre in coppia!$"

Route103_Text_AmyRematchDefeated:
	.string "Amy: Uffa!\n"
	.string "Abbiamo perso di nuovo…$"

Route103_Text_AmyRematchPostBattle:
	.string "Amy: Quando lotti contro due\n"
	.string "Allenatori insieme, devi tenere\l"
	.string "d'occhio un sacco di cose!$"

Route103_Text_AmyRematchNotEnoughPokemon:
	.string "Amy: Ops, hai con te un Pokémon solo.\n"
	.string "Così non puoi lottare contro di noi.$"

Route103_Text_LivRematchIntro:
	.string "Liv: Noi due lottiamo come una\n"
	.string "squadra sola.$"

Route103_Text_LivRematchDefeated:
	.string "Liv: Uffa, abbiamo perso ancora…\n"
	.string "Sorellona…$"

Route103_Text_LivRematchPostBattle:
	.string "Liv: Io e la mia sorellona siamo\n"
	.string "una coppia perfetta…\p"
	.string "Allora perché abbiamo perso ancora?$"

Route103_Text_LivRematchNotEnoughPokemon:
	.string "Liv: Se vuoi sfidarci, devi avere\n"
	.string "almeno due Pokémon!\l"
	.string "Altrimenti non vale!$"

Route103_Text_AndrewIntro:
	.string "Argh! La lenza si è tutta aggrovigliata!\n"
	.string "Sono nervoso e di pessimo umore!\l"
	.string "Basta! Lotta con me!$"

Route103_Text_AndrewDefeated:
	.string "Argh! Ho perso!\n"
	.string "Adesso sono ancora più nervoso!$"

Route103_Text_AndrewPostBattle:
	.string "Argh, sto ancora ribollendo…\n"
	.string "Grrrrr…$"

Route103_Text_MiguelIntro:
	.string "Il mio Pokémon è adorabile da morire!\n"
	.string "Non fare il timido, te lo presento!$"

Route103_Text_MiguelDefeated:
	.string "Oh, santo cielo!\n"
	.string "Il mio tesoruccio!$"

Route103_Text_MiguelPostBattle:
	.string "Il mio Pokémon è un amore\n"
	.string "anche quando è esausto!\p"
	.string "È sbucato da un Varco, sai? Chissà\n"
	.string "da che mondo arriva, quel batuffolo!$"

Route103_Text_MiguelRegister:
	.string "Tornerai a trovarmi, e vedrai quanto\n"
	.string "è adorabile il mio Pokémon!$"

Route103_Text_MiguelRematchIntro:
	.string "Ciao! Il mio adorabile Pokémon\n"
	.string "è diventato ancora più carino!$"

Route103_Text_MiguelRematchDefeated:
	.string "Oh!\n"
	.string "Il mio tesoruccio!$"

Route103_Text_MiguelRematchPostBattle:
	.string "Più tempo passo con lui, più il mio\n"
	.string "Pokémon diventa adorabile.$"

Route103_Text_PeteIntro:
	.string "Per una distanza così corta…\n"
	.string "Potresti benissimo farla a nuoto!$"

Route103_Text_PeteDefeated:
	.string "Oh, che bracciata potente!$"

Route103_Text_PetePostBattle:
	.string "Ah, adesso capisco perché non nuoti.\p"
	.string "Se avessi un Pokémon così affidabile,\n"
	.string "anch'io mi farei portare con Surf!$"

Route103_Text_IsabelleIntro:
	.string "Guarda dove vai!\n"
	.string "Ci scontriamo!$"

Route103_Text_IsabelleDefeated:
	.string "Uff…$"

Route103_Text_IsabellePostBattle:
	.string "Nuoto malissimo, e mi stavo allenando…\n"
	.string "Scusa se per poco non ti venivo addosso.$"

Route103_Text_RhettIntro:
	.string "Ehi!\n"
	.string "Come sei finito in un buco così stretto?$"

Route103_Text_RhettDefeated:
	.string "Ehi!\n"
	.string "Il ragazzino ci sa fare!$"

Route103_Text_RhettPostBattle:
	.string "Ti piacciono i posti angusti\n"
	.string "come questo?$"

Route103_Text_MarcosIntro:
	.string "Ti ha attirato l'urlo della mia chitarra?$"

Route103_Text_MarcosDefeated:
	.string "Il mio concerto da solista è rovinato…$"

Route103_Text_MarcosPostBattle:
	.string "Suonavo la chitarra in un posto dove\n"
	.string "non passa quasi nessuno, eppure\l"
	.string "si è radunato un sacco di gente.\p"
	.string "Eh eh, forse dovrei passare al\n"
	.string "professionismo.$"

Route104_Text_GinaIntro:
	.string "Gina: Forza, lottiamo con i nostri\n"
	.string "Pokémon!$"

Route104_Text_GinaDefeat:
	.string "Gina: Perdere mi fa arrabbiare!$"

Route104_Text_GinaPostBattle:
	.string "Gina: Sei fortissimo!\n"
	.string "Dobbiamo allenarci molto di più!$"

Route104_Text_GinaNotEnoughMons:
	.string "Gina: Eh? Hai un Pokémon solo?\n"
	.string "Allora con te non lottiamo.\p"
	.string "Un Pokémon da solo si sentirebbe\n"
	.string "triste. Non è carino.$"

Route104_Text_MiaIntro:
	.string "Mia: Siamo gemelle, perciò lottiamo\n"
	.string "con i Pokémon sempre insieme.$"

Route104_Text_MiaDefeat:
	.string "Mia: Abbiamo lottato insieme, ma\n"
	.string "abbiamo perso tutte e due…$"

Route104_Text_MiaPostBattle:
	.string "Mia: Alleneremo di più i Pokémon\n"
	.string "e diventeremo forti come te.$"

Route104_Text_MiaNotEnoughMons:
	.string "Mia: Vuoi lottare con noi?\p"
	.string "Niente da fare, se non hai almeno\n"
	.string "due Pokémon con te.\l"
	.string "Siamo troppo forti per te!$"

Route104_Text_IvanIntro:
	.string "Perché tenerlo segreto?\n"
	.string "Sono l'esperto di Pokémon Acqua!\p"
	.string "Eh?\n"
	.string "Non sai chi sono?$"

Route104_Text_IvanDefeat:
	.string "Pensavo di non essere niente male,\n"
	.string "modestamente… E invece… Bleah…$"

Route104_Text_IvanPostBattle:
	.string "Mi sono fatto prendere dalla pesca.\n"
	.string "Ho scordato di allenare i Pokémon…$"

Route104_Text_BillyIntro:
	.string "Lasciare impronte sulla sabbia\n"
	.string "è troppo divertente!$"

Route104_Text_BillyDefeat:
	.string "Uaaah! Ho le scarpe piene di sabbia!\n"
	.string "Scricchiolano tutte!$"

Route104_Text_BillyPostBattle:
	.string "Vorrei lasciare impronte dappertutto,\n"
	.string "ma le onde le cancellano subito…\p"
	.string "Ieri ne ho viste di stranissime.\n"
	.string "Un Pokémon arrivato da un Varco?$"

Route104_Text_HaleyIntro:
	.string "Lo faccio…\n"
	.string "O non lo faccio?\p"
	.string "Va bene, d'accordo, lottiamo!$"

Route104_Text_HaleyDefeat:
	.string "Non avrei dovuto lottare…$"

Route104_Text_HaleyPostBattle:
	.string "Se devi prendere una decisione e\n"
	.string "lasci che qualcun altro scelga per te,\l"
	.string "te ne pentirai, comunque vada\l"
	.string "a finire.$"

Route104_Text_HaleyRegister1:
	.string "Sei forte, ma dovrei registrarti\n"
	.string "nel mio PokéNav?\l"
	.string "Forse è meglio di no…\p"
	.string "Va bene, d'accordo, ti registro!$"

Route104_Text_HaleyRegister2:
	.string "Sei forte, ma dovrei registrarti\n"
	.string "nel mio PokéNav?\l"
	.string "Forse è meglio di no…\p"
	.string "Va bene, d'accordo, ti registro!$"

Route104_Text_HaleyRematchIntro:
	.string "Dai, lotta con me!$"

Route104_Text_HaleyRematchDefeat:
	.string "Ohh…\n"
	.string "Pensavo di poter vincere…$"

Route104_Text_HaleyPostRematch:
	.string "Ho deciso io di lottare, quindi posso\n"
	.string "accettare la sconfitta con dignità.\p"
	.string "Però mi brucia lo stesso!$"

Route104_Text_WinstonIntro:
	.string "Ma certo, accetto la tua sfida.\n"
	.string "Tanto ho un sacco di soldi.$"

Route104_Text_WinstonDefeat:
	.string "Perché non ho vinto?$"

Route104_Text_WinstonPostBattle:
	.string "Ci sono cose che il denaro non compra.\n"
	.string "Tipo i Pokémon…$"

Route104_Text_WinstonRegister1:
	.string "Mh?\n"
	.string "Oh, hai un PokéNav.\p"
	.string "Ti registro volentieri.\n"
	.string "In fondo, di soldi ne ho a palate.$"

Route104_Text_WinstonRegister2:
	.string "Mh?\n"
	.string "Oh, hai un PokéNav.\p"
	.string "Ti registro volentieri.\n"
	.string "In fondo, di soldi ne ho a palate.$"

Route104_Text_WinstonRematchIntro:
	.string "Dopo aver perso con te, ho imparato\n"
	.string "un sacco di cose sui Pokémon.$"

Route104_Text_WinstonRematchDefeat:
	.string "Ho perso ancora?\n"
	.string "Perché non riesco a vincere?$"

Route104_Text_WinstonPostRematch:
	.string "Sono ricchissimo, ma con i Pokémon\n"
	.string "non riesco proprio a vincere…\p"
	.string "Com'è profondo, il mondo dei Pokémon…\n"
	.string "Anzi, i mondi, con tutti questi Varchi!$"

Route104_Text_CindyIntro:
	.string "Il destino voleva che c'incontrassimo.\n"
	.string "Posso chiederti una lotta?$"

Route104_Text_CindyDefeat:
	.string "Oh, cielo!$"

Route104_Text_CindyPostBattle:
	.string "Ogni “buongiorno” è l'inizio di un\n"
	.string "“arrivederci”. Spero di rivederti.$"

Route104_Text_CindyRegister1:
	.string "Buongiorno, ci incontriamo di nuovo.\p"
	.string "Pare che il destino ci unisca. Perché\n"
	.string "non ci registriamo nei PokéNav?$"

Route104_Text_CindyRegister2:
	.string "Dovremmo celebrare il destino che\n"
	.string "continua a farci incontrare.\p"
	.string "Registriamoci a vicenda nei nostri\n"
	.string "PokéNav.$"

Route104_Text_CindyRematchIntro:
	.string "Buongiorno, ci incontriamo di nuovo.\n"
	.string "Posso chiederti una lotta?$"

Route104_Text_CindyRematchDefeat:
	.string "Oh, cielo…\n"
	.string "Ho fatto del mio meglio…$"

Route104_Text_CindyPostRematch:
	.string "Ogni “buongiorno” è l'inizio di un\n"
	.string "“arrivederci”. Spero di rivederti.$"

Route104_Text_DarianIntro:
	.string "Ho pescato un Pokémon dall'aria\n"
	.string "tostissima!\p"
	.string "Ha qualcosa di magico, te lo dico io!\n"
	.string "È tosto, eccome se è tosto!$"

Route104_Text_DarianDefeat:
	.string "Ma che…$"

Route104_Text_DarianPostBattle:
	.string "Ehi, Pokémon mio! Con quell'aria\n"
	.string "magica mi avevi proprio illuso, eh?$"

Route105_Text_FosterIntro:
	.string "Dicono che qui intorno ci sia una\n"
	.string "roccia misteriosa, forse caduta\l"
	.string "da un Varco. Ne sai qualcosa?$"

Route105_Text_FosterDefeated:
	.string "Pensavo troppo a quella roccia, e\n"
	.string "i miei Pokémon sono rimasti deboli…$"

Route105_Text_FosterPostBattle:
	.string "Posso passare ore e ore a fissare\n"
	.string "una bella roccia senza annoiarmi.$"

Route105_Text_LuisIntro:
	.string "Uff! Quando ti ho visto, ho temuto\n"
	.string "che un ragazzino stesse annegando.\p"
	.string "Ma vedo che stai bene, quindi\n"
	.string "che ne dici di una lotta?$"

Route105_Text_LuisDefeated:
	.string "Glu… Glu…$"

Route105_Text_LuisPostBattle:
	.string "Se stai annegando, il segnale è agitare\n"
	.string "un braccio verso la spiaggia.$"

Route105_Text_DominikIntro:
	.string "Nuotare nel mare blu profondo…\n"
	.string "Non c'è niente di meglio!$"

Route105_Text_DominikDefeated:
	.string "Ho perso…\n"
	.string "Ora ho il morale sott'acqua…$"

Route105_Text_DominikPostBattle:
	.string "Perché il mare è blu?\p"
	.string "L'ho studiato al Museo Oceanografico\n"
	.string "di Porto Selcepoli, ma l'ho scordato.$"

Route105_Text_BeverlyIntro:
	.string "In acqua mi sento più leggera.\n"
	.string "Come se fossi dimagrita!$"

Route105_Text_BeverlyDefeated:
	.string "Sto galleggiando…$"

Route105_Text_PostBattle:
	.string "In acqua il peso del corpo si riduce\n"
	.string "a un decimo.\p"
	.string "Quindi io peserei…\n"
	.string "Ops! Il mio peso non te lo dico!$"

Route105_Text_ImaniIntro:
	.string "Il cielo blu, così blu…\n"
	.string "Il mare immenso…\l"
	.string "Che pace…$"

Route105_Text_ImaniDefeated:
	.string "Ho perso mentre mi rilassavo!$"

Route105_Text_ImaniPostBattle:
	.string "Vorrei che dicessero che stare con me\n"
	.string "è rilassante. Ih ih.$"

Route105_Text_AndresIntro:
	.string "Sono convinto che il mare ci nasconda\n"
	.string "qualcosa. Magari un Varco sul fondo!$"

Route105_Text_AndresDefeated:
	.string "Già…\n"
	.string "Lottare non è il mio forte…$"

Route105_Text_AndresPostBattle:
	.string "Nei mari ci sono di sicuro tanti\n"
	.string "segreti ancora da scoprire.\p"
	.string "E io li troverò tutti!$"

Route105_Text_AndresRegister:
	.string "Eh? Sono così scarso, eppure vuoi\n"
	.string "registrarmi nel tuo PokéNav?$"

Route105_Text_AndresRematchIntro:
	.string "Te l'ho detto che sono scarso…\n"
	.string "Sei sicuro di volerlo fare?$"

Route105_Text_AndresRematchDefeated:
	.string "Già…\n"
	.string "Non pensavo di poter vincere.$"

Route105_Text_AndresRematchPostBattle:
	.string "Sarò scarso a lottare, ma nessuno\n"
	.string "batte la mia voglia di esplorare.\p"
	.string "Esplorerò tutti i mari di Hoenn,\n"
	.string "fino all'ultimo scoglio!$"

Route105_Text_JosueIntro:
	.string "Sono sfinito dal nuoto.\n"
	.string "Non ci sono proprio abituato.\p"
	.string "Mi serve una lotta per cambiare aria!$"

Route105_Text_JosueDefeated:
	.string "Ho perso perché ho lottato in mare.$"

Route105_Text_JosuePostBattle:
	.string "Già, io e i miei pennuti siamo fatti\n"
	.string "per il cielo, mica per il mare.$"

Route106_Text_ElliotIntro:
	.string "Tu cosa preferisci: pescare in mare\n"
	.string "o in un torrente?$"

Route106_Text_ElliotDefeated:
	.string "Come nella pesca d'altura, ho perso\n"
	.string "in modo spettacolare!$"

Route106_Text_ElliotPostBattle:
	.string "La pesca è il massimo, che sia in mare\n"
	.string "o in un torrente.\l"
	.string "Sei d'accordo con me, vero?$"

Route106_Text_ElliotRegister:
	.string "Pescare è bello, ma anche lottare.\n"
	.string "Se non ti dispiace, ci rivediamo?$"

Route106_Text_ElliotRematchIntro:
	.string "Ho pescato un sacco di Pokémon.\n"
	.string "Ti farò vedere una lotta coi fiocchi!$"

Route106_Text_ElliotRematchDefeated:
	.string "Ho perso di nuovo, e alla grande!$"

Route106_Text_ElliotRematchPostBattle:
	.string "Che si vinca o si perda, i Pokémon\n"
	.string "sono il massimo! Sei d'accordo, vero?$"

Route106_Text_NedIntro:
	.string "Come si fa quando bisogna andare\n"
	.string "in bagno?\p"
	.string "E se abbocca un pesce grosso mentre\n"
	.string "sono in bagno? Non posso andarci…$"

Route106_Text_NedDefeated:
	.string "Ho perso perché mi sto trattenendo\n"
	.string "dall'andare in bagno…$"

Route106_Text_NedPostBattle:
	.string "Oh, no! Me lo sento: sta per abboccare\n"
	.string "un pesce enorme!$"

Route106_Text_DouglasIntro:
	.string "Ahahah! Sulla terra corro malissimo,\n"
	.string "ma in acqua non mi prendi!$"

Route106_Text_DouglasDefeated:
	.string "Mi arrendo!$"

Route106_Text_DouglasPostBattle:
	.string "In una gara di nuoto non perderei…$"

Route106_Text_KylaIntro:
	.string "Il mare è il mio giardino. Non ci vado\n"
	.string "piano solo perché sei un ragazzino!$"

Route106_Text_KylaDefeated:
	.string "Ci sei andato piano con me,\n"
	.string "per caso?$"

Route106_Text_KylaPostBattle:
	.string "Lasciarsi trasportare dalle onde…\n"
	.string "Che bello! Perché non provi anche tu?$"

Route107_Text_DarrinIntro:
	.string "Uaaah…\p"
	.string "Devo essermi addormentato mentre\n"
	.string "mi lasciavo cullare dalle onde.$"

Route107_Text_DarrinDefeated:
	.string "Ahah, ho perso…\n"
	.string "Credo che mi farò un pisolino…$"

Route107_Text_DarrinPostBattle:
	.string "Galleggiare cullato dalle onde…\n"
	.string "È come dormire in un letto morbido\l"
	.string "e comodissimo.$"

Route107_Text_TonyIntro:
	.string "Il mare è il giardino di casa mia.\n"
	.string "Lottiamo!$"

Route107_Text_TonyDefeated:
	.string "Ho perso in casa mia…\n"
	.string "Sono sotto shock!$"

Route107_Text_TonyPostBattle:
	.string "Nuoto per i mari con il cuore pieno\n"
	.string "di sogni…\p"
	.string "È una canzone! Comunque, vado\n"
	.string "a nuotare ancora un po'.$"

Route107_Text_TonyRegister:
	.string "Mi hai sconvolto fino al midollo!\n"
	.string "Beh, così non ti scorderai di me…$"

Route107_Text_TonyRematchIntro:
	.string "Nuotando in mare aperto, il mio\n"
	.string "Pokémon è diventato più forte!$"

Route107_Text_TonyRematchDefeated:
	.string "Che shock!\p"
	.string "Il mio Pokémon si è fatto più forte,\n"
	.string "ma io come Allenatore no!$"

Route107_Text_TonyRematchPostBattle:
	.string "Ciò che impari lottando ti rende\n"
	.string "un Allenatore più forte.\l"
	.string "Me l'hanno insegnato le onde.$"

Route107_Text_DeniseIntro:
	.string "Conosci un paesino che si chiama\n"
	.string "Bluruvia?$"

Route107_Text_DeniseDefeated:
	.string "Che rabbia!$"

Route107_Text_DenisePostBattle:
	.string "Al Salone di Bluruvia va di moda\n"
	.string "un modo di dire stranissimo.$"

Route107_Text_BethIntro:
	.string "Volevi lottare con me?\n"
	.string "Certo, ci sto!$"

Route107_Text_BethDefeated:
	.string "Non sono stata all'altezza.$"

Route107_Text_BethPostBattle:
	.string "Secondo me continuerai a migliorare.\n"
	.string "Ce la metterò tutta anch'io!$"

Route107_Text_LisaIntro:
	.string "Lisa: Ti sfidiamo da sorella\n"
	.string "e fratello!$"

Route107_Text_LisaDefeated:
	.string "Lisa: Fantastico.\n"
	.string "Sei di un altro livello.$"

Route107_Text_LisaPostBattle:
	.string "Lisa: Hai degli amici che verrebbero\n"
	.string "al mare con te?$"

Route107_Text_LisaNotEnoughPokemon:
	.string "Lisa: Se vuoi lottare con noi,\n"
	.string "porta più Pokémon.$"

Route107_Text_RayIntro:
	.string "Ray: Io e mia sorella lottiamo sempre\n"
	.string "con i Pokémon.\p"
	.string "Io perdo sempre, ma in due contro due\n"
	.string "ti battiamo!$"

Route107_Text_RayDefeated:
	.string "Ray: Wow, sei molto più forte\n"
	.string "di noi due!$"

Route107_Text_RayPostBattle:
	.string "Ray: Il mio Pokémon me l'ha regalato\n"
	.string "mia sorella. L'ho cresciuto io, e ora\l"
	.string "è il mio compagno più prezioso!$"

Route107_Text_RayNotEnoughPokemon:
	.string "Ray: Se vuoi sfidarci,\n"
	.string "vai a prendere altri Pokémon!$"

Route107_Text_CamronIntro:
	.string "Sono a metà di un triathlon,\n"
	.string "ma non sono per niente stanco!$"

Route107_Text_CamronDefeated:
	.string "Che fatica…$"

Route107_Text_CamronPostBattle:
	.string "Dopo questo mi restano ancora il nuoto\n"
	.string "e la corsa.\p"
	.string "Ce la farò?$"

Route108_Text_JeromeIntro:
	.string "Il mio sogno è nuotare nei sette mari…\n"
	.string "anzi, nei mari di tutti i mondi!$"

Route108_Text_JeromeDefeated:
	.string "Di questo passo, i sette mari\n"
	.string "non li attraverserò mai…$"

Route108_Text_JeromePostBattle:
	.string "Nuotare insieme ai Pokémon marini\n"
	.string "è uno dei piaceri più grandi!$"

Route108_Text_MatthewIntro:
	.string "Ehilà! Anche tu sei diretto\n"
	.string "alla Vecchia Nave?$"

Route108_Text_MatthewDefeated:
	.string "Affondo!\n"
	.string "Glub… Glub…$"

Route108_Text_MatthewPostBattle:
	.string "C'è chi si spinge persino dentro\n"
	.string "la Vecchia Nave.\l"
	.string "Dicono che là sotto qualcosa ronzi\l"
	.string "ancora… Brrr!$"

Route108_Text_TaraIntro:
	.string "Quel bugiardo del mio ragazzo dice\n"
	.string "che in bikini sto benissimo…$"

Route108_Text_TaraDefeated:
	.string "Uffa!$"

Route108_Text_TaraPostBattle:
	.string "Anche se è una bugia, mi piace\n"
	.string "sentirmelo dire…\l"
	.string "Noi ragazze siamo complicate…$"

Route108_Text_MissyIntro:
	.string "Adoro il mare!\n"
	.string "Quando nuoto, scordo ogni pensiero!$"

Route108_Text_MissyDefeated:
	.string "Quando perdo una lotta, mi sale\n"
	.string "uno stress tremendo!$"

Route108_Text_MissyPostBattle:
	.string "Lo stress si scioglie nuotando!\n"
	.string "Fa benissimo alla salute!$"

Route108_Text_CoryIntro:
	.string "Adoro i Pokémon di tipo Acqua.\n"
	.string "Ma adoro anche tutti gli altri!$"

Route108_Text_CoryDefeated:
	.string "Uaaah! Ho perso!\n"
	.string "Uaaah! Uaaah!$"

Route108_Text_CoryPostBattle:
	.string "Urlare mi fa bene!\n"
	.string "Mi tira su il morale!$"

Route108_Text_CoryRegister:
	.string "Adoro anche gli Allenatori forti!\n"
	.string "Registrami nel tuo PokéNav!$"

Route108_Text_CoryRematchIntro:
	.string "Vinco o perdo, lottare in mare\n"
	.string "è sempre una gioia!$"

Route108_Text_CoryRematchDefeated:
	.string "Uaaah! Ho perso di nuovo!\n"
	.string "Uaaah! Uaaah!$"

Route108_Text_CoryRematchPostBattle:
	.string "Se hai un problema da affrontare,\n"
	.string "prova a urlarlo al mare!$"

Route108_Text_CarolinaIntro:
	.string "Vado fierissima dei miei Pokémon.\n"
	.string "Ti mostreremo una lotta lampo!$"

Route108_Text_CarolinaDefeated:
	.string "Questo non è stato per niente carino.$"

Route108_Text_CarolinaPostBattle:
	.string "Già che sono al mare, non mi\n"
	.string "dispiacerebbe un costumino rosa a balze…$"

Route109_Text_DavidIntro:
	.string "Hiyah! Guarda che addominali!\n"
	.string "Questa sì che è una “tartaruga”!$"

Route109_Text_DavidDefeated:
	.string "Aiyah!\n"
	.string "Affondato!$"

Route109_Text_DavidPostBattle:
	.string "Hiyah!\p"
	.string "I miei addominali scolpiti non c'entrano\n"
	.string "niente con le lotte Pokémon!$"

Route109_Text_AliceIntro:
	.string "Ti sei protetto bene\n"
	.string "dal sole?$"

Route109_Text_AliceDefeated:
	.string "Ahi, ahi, ahi!$"

Route109_Text_AlicePostBattle:
	.string "Le guance sono le prime a scottarsi!$"

Route109_Text_HueyIntro:
	.string "Ho gettato l'ancora in ogni porto di\n"
	.string "Hoenn, ma Porto Selcepoli è il top.$"

Route109_Text_HueyDefeated:
	.string "Sei il migliore!$"

Route109_Text_HueyPostBattle:
	.string "Nel porto migliore, l'Allenatore\n"
	.string "migliore…$"

Route109_Text_EdmondIntro:
	.string "Uuurgh…\n"
	.string "Una lotta? Con me?$"

Route109_Text_EdmondDefeated:
	.string "Urp… Oooooohhhhh…\n"
	.string "Uuuurgh…$"

Route109_Text_EdmondPostBattle:
	.string "Di solito sono più forte di così!\n"
	.string "È che ho un mal di mare tremendo!\p"
	.string "E pensare che faccio il marinaio…$"

Route109_Text_RickyIntro:
	.string "Che sete… Mi berrei una Gassosa\n"
	.string "alla Casa sul Mare…$"

Route109_Text_RickyDefeated:
	.string "Uff…$"

Route109_Text_RickyPostBattle:
	.string "Ho una fame… Il mio salvagente\n"
	.string "sembra una ciambella gigante…$"

Route109_Text_RickyRegister:
	.string "Mi rifai una lotta quando non\n"
	.string "sarò più così assetato?$"

Route109_Text_RickyRematchIntro:
	.string "Ho fame, ma di energia per una\n"
	.string "lotta ne ho ancora!$"

Route109_Text_RickyRematchDefeated:
	.string "Ho perso…\n"
	.string "È tutta colpa della fame…$"

Route109_Text_RickyRematchPostBattle:
	.string "Se mangi in spiaggia, tutto sembra\n"
	.string "un pochino più buono.$"

Route109_Text_LolaIntro:
	.string "Un ombrellone da spiaggia non ti\n"
	.string "sembra un fiore gigante?$"

Route109_Text_LolaDefeated:
	.string "Mammaaa!$"

Route109_Text_LolaPostBattle:
	.string "Se guardi la spiaggia dal cielo,\n"
	.string "sembra un grande giardino fiorito!$"

Route109_Text_LolaRegister:
	.string "Io?\n"
	.string "Sono qui tutti i giorni!$"

Route109_Text_LolaRematchIntro:
	.string "Stavolta non perdo!\n"
	.string "Per questo ho il mio salvagente!$"

Route109_Text_LolaRematchDefeated:
	.string "Mammaaa!$"

Route109_Text_LolaRematchPostBattle:
	.string "Col salvagente, io e i miei Pokémon\n"
	.string "siamo carini il doppio!$"

Route109_Text_AustinaIntro:
	.string "Senza salvagente non so nuotare,\n"
	.string "ma con i Pokémon non perdo!$"

Route109_Text_AustinaDefeated:
	.string "Ho perso perché ho\n"
	.string "il salvagente?$"

Route109_Text_AustinaPostBattle:
	.string "Il mio salvagente è un accessorio\n"
	.string "di moda. Senza, non esco di casa.$"

Route109_Text_GwenIntro:
	.string "Ciao, Allenatore grande.\n"
	.string "Lotti con me?$"

Route109_Text_GwenDefeated:
	.string "Oh, sei forte.$"

Route109_Text_GwenPostBattle:
	.string "Come hai fatto a diventare così forte?$"

Route109_Text_CarterIntro:
	.string "Uahahah! Oggi il sottoscritto\n"
	.string "tira su un pesce grosso!$"

Route109_Text_CarterDefeated:
	.string "Il sottoscritto se l'è fatto\n"
	.string "scappare…$"

Route109_Text_CarterPostBattle:
	.string "Per il sottoscritto, tu sei un pesce\n"
	.string "grosso. Anzi, lo diventerai!$"

Route109_Text_PaulIntro:
	.string "Paul: Ecco, l'atmosfera è rovinata.\p"
	.string "Potresti evitare di disturbare\n"
	.string "il nostro prezioso tempo insieme?$"

Route109_Text_PaulDefeated:
	.string "Paul: Va bene, mi arrendo.$"

Route109_Text_PaulPostBattle:
	.string "Paul: Ehm, non dire a nessuno che\n"
	.string "siamo qui.\l"
	.string "Altro che multiverso: questo è il\l"
	.string "nostro mondo a due!$"

Route109_Text_PaulNotEnoughPokemon:
	.string "Paul: Siamo innamorati persi.\n"
	.string "Per questo i nostri Pokémon\l"
	.string "lottano sempre in coppia.$"

Route109_Text_MelIntro:
	.string "Mel: Tipo, siamo innamoratissimi.\n"
	.string "Il nostro amore scalda tutta Hoenn!$"

Route109_Text_MelDefeated:
	.string "Mel: Abbiamo perso, ed è colpa mia!\n"
	.string "Paul mi odierà!$"

Route109_Text_MelPostBattle:
	.string "Mel: Ehm, Paul, sei arrabbiato?\n"
	.string "Ti prego, non arrabbiarti.$"

Route109_Text_MelNotEnoughPokemon:
	.string "Mel: Tipo, siamo innamoratissimi.\n"
	.string "Per questo i nostri Pokémon\l"
	.string "lottano sempre insieme.$"

Route109_Text_ChandlerIntro:
	.string "Tadaaan! Visto?\n"
	.string "Il mio salvagente è rotondo!$"

Route109_Text_ChandlerDefeated:
	.string "Oh, oh!\n"
	.string "Che peccato!$"

Route109_Text_ChandlerPostBattle:
	.string "E dire che ti ho pure mostrato\n"
	.string "il mio salvagente rotondo…$"

Route109_Text_HaileyIntro:
	.string "Non so nuotare, quindi faccio\n"
	.string "finta di nuotare.$"

Route109_Text_HaileyDefeated:
	.string "Lo sapevo!\n"
	.string "Sapevo che non potevamo vincere.$"

Route109_Text_HaileyPostBattle:
	.string "Quando imparerò a nuotare, anche i\n"
	.string "miei Pokémon diventeranno più forti.$"

Route109_Text_ElijahIntro:
	.string "Per un duro come me, i Pokémon\n"
	.string "uccello sono la scelta perfetta!$"

Route109_Text_ElijahDefeated:
	.string "Resto un figo anche se perdo, eh?$"

Route109_Text_ElijahPostBattle:
	.string "Per un duro come me, un porto è\n"
	.string "lo scenario perfetto!\p"
	.string "Credo proprio che farò rotta\n"
	.string "verso Porto Selcepoli.$"

Route110_Text_JacobIntro:
	.string "Ehi! Attento!\n"
	.string "Non sei abituato alle corse in Bici?$"

Route110_Text_JacobDefeated:
	.string "Uoah!\n"
	.string "Mi sono saltati i freni!$"

Route110_Text_JacobPostBattle:
	.string "Gomme a terra e freni rotti possono\n"
	.string "farti cadere molto male!\l"
	.string "Controlla sempre la tua Bici!$"

Route110_Text_AnthonyIntro:
	.string "Ehi, tu!\n"
	.string "Riesci a stare al mio passo?$"

Route110_Text_AnthonyDefeated:
	.string "Schianto totale!$"

Route110_Text_AnthonyPostBattle:
	.string "Con la sola velocità non si vince una\n"
	.string "lotta Pokémon. Devo ripensarci…$"

Route110_Text_BenjaminIntro:
	.string "Niente panico se la Bici va forte!$"

Route110_Text_BenjaminDefeated:
	.string "Non dovrei andare nel panico\n"
	.string "durante le lotte…$"

Route110_Text_BenjaminPostBattle:
	.string "Niente panico, niente stress.\n"
	.string "Con calma. C'è tutto il tempo.$"

Route110_Text_BenjaminRegister:
	.string "Io continuo a pedalare senza stress.\n"
	.string "Fammi un fischio, se ti va.$"

Route110_Text_BenjaminRematchIntro:
	.string "Non stai andando un po' troppo forte?\n"
	.string "Con calma: facciamo una lotta.$"

Route110_Text_BenjaminRematchDefeated:
	.string "Niente panico, eppure ho perso…$"

Route110_Text_BenjaminRematchPostBattle:
	.string "Niente panico, niente stress.\n"
	.string "Con calma. C'è tutto il tempo.$"

Route110_Text_AbigailIntro:
	.string "Il triathlon è una fatica estrema.\p"
	.string "Bisogna completare tre prove:\n"
	.string "nuoto, ciclismo e corsa.$"

Route110_Text_AbigailDefeated:
	.string "Anche le lotte Pokémon sono dure!$"

Route110_Text_AbigailPostBattle:
	.string "Sono sfinita, mi serve una pausa.\n"
	.string "Riposare bene è fondamentale.$"

Route110_Text_AbigailRegister:
	.string "Sai, mi sei simpatico! Rivincita\n"
	.string "sulla Pista Ciclabile?$"

Route110_Text_AbigailRematchIntro:
	.string "Non è fantastico lottare\n"
	.string "mentre si pedala?$"

Route110_Text_AbigailRematchDefeated:
	.string "Wow…\n"
	.string "Come fai a essere così forte?$"

Route110_Text_AbigailRematchPostBattle:
	.string "Stavi cercando di battere un record?\p"
	.string "Scusa se ti ho fatto rallentare!$"

Route110_Text_JasmineIntro:
	.string "Pedalo senza sosta da ore.\n"
	.string "Ho le cosce di pietra!$"

Route110_Text_JasmineDefeated:
	.string "Speriamo di non avere i crampi…$"

Route110_Text_JasminePostBattle:
	.string "Oh, hai delle Medaglie?\n"
	.string "Ecco perché sei così forte!$"

Route110_Text_EdwardIntro:
	.string "Ho previsto le tue intenzioni!\n"
	.string "Non posso assolutamente perdere!$"

Route110_Text_EdwardDefeated:
	.string "La mia sconfitta non l'avevo prevista!$"

Route110_Text_EdwardPostBattle:
	.string "Vedo il tuo futuro…\p"
	.string "Mmh…\n"
	.string "Vedo una luce splendente…\l"
	.string "come uno strappo nel cielo…$"

Route110_Text_JaclynIntro:
	.string "Ahahahah!\n"
	.string "Ti abbaglierò con i miei prodigi!$"

Route110_Text_JaclynDefeated:
	.string "Ho perso… prodigiosamente!$"

Route110_Text_JaclynPostBattle:
	.string "Hai vinto solo perché è successo un\n"
	.string "prodigio! Sì, un prodigio!\l"
	.string "Non credere di vincere sempre!$"

Route110_Text_EdwinIntro:
	.string "Posso vedere i tuoi Pokémon?\n"
	.string "Solo un'occhiata, ti prego!$"

Route110_Text_EdwinDefeated:
	.string "Volevo completare\n"
	.string "la mia collezione…$"

Route110_Text_EdwinPostBattle:
	.string "Quando vedo un Pokémon sconosciuto,\n"
	.string "il mio cuore da collezionista arde!\p"
	.string "E con i Varchi, ne arrivano di\n"
	.string "nuovi ogni giorno!$"

Route110_Text_EdwinRegister:
	.string "Colleziono anche le registrazioni\n"
	.string "del Match Call…$"

Route110_Text_EdwinRematchIntro:
	.string "Ciao! Hai catturato nuovi Pokémon?\p"
	.string "Posso vedere i tuoi Pokémon?\n"
	.string "Solo un'occhiata, ti prego!$"

Route110_Text_EdwinRematchDefeated:
	.string "I tuoi Pokémon…\n"
	.string "Che invidia.$"

Route110_Text_EdwinRematchPostBattle:
	.string "Ah, quanto vorrei che tutti i Pokémon\n"
	.string "rari fossero miei!$"

Route110_Text_DaleIntro:
	.string "Ehi!\n"
	.string "Non arrivarmi alle spalle così!$"

Route110_Text_DaleDefeated:
	.string "Ho perso!\n"
	.string "Accidenti!$"

Route110_Text_DalePostBattle:
	.string "La pesca è tutta concentrazione.\n"
	.string "Non perdere mai di vista il galleggiante.$"

Route110_Text_IsabelIntro:
	.string "Ahahah! Andrei ovunque pur di far\n"
	.string "ammirare i miei deliziosi Pokémon.$"

Route110_Text_IsabelDefeated:
	.string "Oh, povera me, così non va.$"

Route110_Text_IsabelPostBattle:
	.string "Più che lottare, forse dovrei mostrare\n"
	.string "i miei Pokémon al Fan Club.$"

Route110_Text_IsabelRegister:
	.string "Non hai visto nemmeno la metà di\n"
	.string "quanto sono belli i miei Pokémon.\p"
	.string "Sarai il mio pubblico fisso,\n"
	.string "il più spesso possibile!$"

Route110_Text_IsabelRematchIntro:
	.string "Ahahahah! Ti mostrerò i miei Pokémon\n"
	.string "tutte le volte che vuoi!$"

Route110_Text_IsabelRematchDefeated:
	.string "Oh, povera me, così non va.$"

Route110_Text_IsabelRematchPostBattle:
	.string "Credo che non smetterò mai di\n"
	.string "vantarmi dei miei Pokémon.\p"
	.string "Ma anche lottare mi piace!$"

Route110_Text_TimmyIntro:
	.string "Ho trovato dei Pokémon fighissimi\n"
	.string "nell'erba qui intorno! Roba da Varco!$"

Route110_Text_TimmyDefeated:
	.string "Essere fighi non basta per vincere…$"

Route110_Text_TimmyPostBattle:
	.string "È difficile lottare con Pokémon\n"
	.string "appena catturati.$"

Route110_Text_AlyssaIntro:
	.string "Sono caduta dalla Pista Ciclabile…\p"
	.string "Per smaltire l'imbarazzo,\n"
	.string "lotterò con te!$"

Route110_Text_AlyssaDefeated:
	.string "Oops!\n"
	.string "Alla fine ho perso!$"

Route110_Text_AlyssaPostBattle:
	.string "Cadere… Perdere…\n"
	.string "Che figuraccia!$"

Route110_Text_JosephIntro:
	.string "Okay! Si va a tutto volume! Chi non\n"
	.string "tiene il ritmo, resta indietro!$"

Route110_Text_JosephDefeated:
	.string "Il ritmo ce l'hai, eccome…$"

Route110_Text_JosephPostBattle:
	.string "Non mi butto giù per così poco!\n"
	.string "Perdere mi ha reso un uomo migliore!$"

Route110_Text_KalebIntro:
	.string "Pokémon carini che si aiutano a vicenda…\n"
	.string "Non c'è niente di più tenero!$"

Route110_Text_KalebDefeated:
	.string "Non hai un briciolo di pietà?$"

Route110_Text_KalebPostBattle:
	.string "Su, su, avete fatto del vostro\n"
	.string "meglio, tesorini miei.$"

Route111_Text_DrewIntro:
	.string "Oh, ehi! Quegli Occhialoni ti stanno\n"
	.string "bene. Ma a me stanno meglio.\p"
	.string "Decidiamo con una lotta a chi\n"
	.string "stanno meglio!$"

Route111_Text_DrewDefeat:
	.string "Con gli Occhialoni non vedevo\n"
	.string "cosa succedeva ai lati.$"

Route111_Text_DrewPostBattle:
	.string "Con gli Occhialoni si attraversano\n"
	.string "le tempeste di sabbia.\l"
	.string "Che soddisfazione!$"

Route111_Text_HeidiIntro:
	.string "Sto facendo un picnic nel deserto.\p"
	.string "Qui si trova sempre un Allenatore,\n"
	.string "quindi posso anche lottare!$"

Route111_Text_HeidiDefeat:
	.string "Ohhh! Sei cattivo!$"

Route111_Text_HeidiPostBattle:
	.string "Se lotti in una tempesta di sabbia,\n"
	.string "controlla i PS dei tuoi Pokémon.\p"
	.string "Se non li tieni d'occhio,\n"
	.string "rischiano di finire esausti!$"

Route111_Text_BeauIntro:
	.string "Con questi Occhialoni mi sento\n"
	.string "un supereroe.\l"
	.string "Adesso nessuno può battermi!$"

Route111_Text_BeauDefeat:
	.string "Lo spirito da solo non basta…$"

Route111_Text_BeauPostBattle:
	.string "Un giorno diventerò un vero eroe.\n"
	.string "Mi allenerò ancora di più per rendere\l"
	.string "più forti me e i miei Pokémon.$"

Route111_Text_BeckyIntro:
	.string "Ho sentito che nel deserto ci sono\n"
	.string "dei fossili. Dove saranno?$"

Route111_Text_BeckyDefeat:
	.string "Non ce l'ho fatta…$"

Route111_Text_BeckyPostBattle:
	.string "Se nel deserto ci sono fossili,\n"
	.string "un tempo qui c'era il mare.\l"
	.string "O forse sono caduti da un Varco?$"

Route111_Text_DustyIntro:
	.string "Da trent'anni cerco rovine\n"
	.string "antiche!\l"
	.string "E qualcuno osa sfidarmi?$"

Route111_Text_DustyDefeat:
	.string "Ho cercato rovine, sì,\n"
	.string "ma non Pokémon forti.$"

Route111_Text_DustyPostBattle:
	.string "Da trent'anni cerco rovine\n"
	.string "antiche!\p"
	.string "Anzi, aspetta, erano quaranta?\n"
	.string "Quanti erano, insomma?$"

Route111_Text_DustyRegister:
	.string "Non ho mai cercato Pokémon\n"
	.string "forti.\p"
	.string "Però, chissà perché, i PokéNav\n"
	.string "mi piacciono un sacco.$"

Route111_Text_DustyRematchIntro:
	.string "Da trent'anni cerco rovine\n"
	.string "antiche!\p"
	.string "Anzi, aspetta, erano quaranta?\n"
	.string "Comunque, mi stai sfidando?$"

Route111_Text_DustyRematchDefeat:
	.string "Niente rovine, e nemmeno\n"
	.string "Pokémon forti…$"

Route111_Text_DustyPostRematch:
	.string "Da trent'anni cerco rovine\n"
	.string "antiche!\p"
	.string "Anzi, aspetta, erano quarant'anni\n"
	.string "di ricerche?\p"
	.string "Mmh… Potrebbero essere cinquanta…\n"
	.string "Da quanto tempo sono qui?$"

Route111_Text_TravisIntro:
	.string "Sono pieno di grinta!\n"
	.string "E il mio Pokémon è grintoso uguale!$"

Route111_Text_TravisDefeat:
	.string "Il mio Pokémon ha perso la grinta…$"

Route111_Text_TravisPostBattle:
	.string "Quando vedo un Allenatore grintoso,\n"
	.string "non posso fare a meno di guardarlo.$"

Route111_Text_IreneIntro:
	.string "Non so dove sei diretto,\n"
	.string "ma ti va una lotta?$"

Route111_Text_IreneDefeat:
	.string "Oh, sei bravo da far rabbia!$"

Route111_Text_IrenePostBattle:
	.string "Pensavo di andare al Monte Camino,\n"
	.string "ma anche qui intorno il panorama\l"
	.string "è bellissimo.$"

Route111_Text_DaisukeIntro:
	.string "Per allenarmi, sfido chiunque\n"
	.string "incontri!$"

Route111_Text_DaisukeDefeat:
	.string "Basta! Mi arrendo!$"

Route111_Text_DaisukePostBattle:
	.string "Non mi resta che allenarmi finché\n"
	.string "non batterò Allenatori forti\l"
	.string "come te.$"

Route111_Text_WiltonIntro:
	.string "Mostrami quanto hai rafforzato\n"
	.string "i tuoi Pokémon.$"

Route111_Text_WiltonDefeat:
	.string "Vedo che li hai rafforzati\n"
	.string "parecchio.$"

Route111_Text_WiltonPostBattle:
	.string "Pokémon e Allenatori imparano\n"
	.string "molto lottando.\p"
	.string "L'importante è non arrendersi mai,\n"
	.string "anche quando si perde.$"

Route111_Text_WiltonRegister:
	.string "C'è molto da imparare dal tuo\n"
	.string "modo di allenarti.\p"
	.string "Ti chiedo una rivincita, se\n"
	.string "ti aggrada.$"

Route111_Text_WiltonRematchIntro:
	.string "Ci alleniamo qui per portare la\n"
	.string "nostra tecnica al livello successivo.\l"
	.string "Resta ad allenarti con noi!$"

Route111_Text_WiltonRematchDefeat:
	.string "Ooh, niente male!$"

Route111_Text_WiltonPostRematch:
	.string "Con la tua forza, dovresti puntare\n"
	.string "alla Lega Pokémon.$"

Route111_Text_BrookeIntro:
	.string "Oh, i tuoi Pokémon sembrano attori\n"
	.string "professionisti.\l"
	.string "Devo proprio scritturarli.$"

Route111_Text_BrookeDefeat:
	.string "Non sembravano solo forti:\n"
	.string "lo sono davvero!$"

Route111_Text_BrookePostBattle:
	.string "Credevo di allenare i miei Pokémon\n"
	.string "con impegno, ma, ahimè, c'è ancora\l"
	.string "molto da fare.$"

Route111_Text_BrookeRegister:
	.string "Vorrei fare amicizia con altre\n"
	.string "persone forti come te!$"

Route111_Text_BrookeRematchIntro:
	.string "Le mosse che insegni possono rendere\n"
	.string "i Pokémon più forti o più deboli.\p"
	.string "Che mosse conoscono i tuoi\n"
	.string "Pokémon?$"

Route111_Text_BrookeRematchDefeat:
	.string "Hai insegnato loro mosse ottime!$"

Route111_Text_BrookePostRematch:
	.string "Forse dovevo impedire ai miei\n"
	.string "Pokémon di evolversi finché non\l"
	.string "avessero imparato mosse migliori…$"

Route111_Text_CeliaIntro:
	.string "Non dovevo venire a fare un picnic\n"
	.string "in un posto del genere!$"

Route111_Text_CeliaDefeat:
	.string "Uffa!\n"
	.string "Non dovevo proprio venire!$"

Route111_Text_CeliaPostBattle:
	.string "Con questa tempesta di sabbia non\n"
	.string "riesco ad apparecchiare il picnic,\l"
	.string "nemmeno con gli Occhialoni…$"

Route111_Text_BryanIntro:
	.string "Quanto sei forte?\n"
	.string "Sveleremo questo segreto!$"

Route111_Text_BryanDefeat:
	.string "Oh! La tua forza!\n"
	.string "È avvolta nel mistero!$"

Route111_Text_BryanPostBattle:
	.string "Questo deserto nasconde misteri\n"
	.string "sotto le sue dune. Come quella torre\l"
	.string "che appare e scompare…$"

Route111_Text_BrandenIntro:
	.string "Ti do un pezzo del mio panino\n"
	.string "se perdi.$"

Route111_Text_BrandenDefeat:
	.string "Tsk! Credevo che un panino bastasse\n"
	.string "a corromperti…$"

Route111_Text_BrandenPostBattle:
	.string "Il mio Sandshrew adora mangiare\n"
	.string "i miei panini.$"

Route111_Text_TyronIntro:
	.string "Ecco il mio tipo di Pokémon preferito!\n"
	.string "Guardalo bene, perché brucia in fretta!$"

Route111_Text_TyronDefeat:
	.string "Aspetta!\n"
	.string "L'hai visto bene, il mio Pokémon?$"

Route111_Text_TyronPostBattle:
	.string "Quando lotto, il bello per me è\n"
	.string "mettere in mostra i miei Pokémon.\p"
	.string "Scommetto che vale per tutti,\n"
	.string "quando scendono in campo!$"

Route111_Text_CelinaIntro:
	.string "La mia vita profuma di fiori, ma è\n"
	.string "troppo tranquilla. Dammi un brivido!$"

Route111_Text_CelinaDefeat:
	.string "Oh… Mamma mia…\n"
	.string "Fin troppi brividi, per oggi.$"

Route111_Text_CelinaPostBattle:
	.string "Il cuore mi batte ancora a mille.\n"
	.string "Sei un Allenatore favoloso!$"

Route111_Text_HaydenIntro:
	.string "Quando hai la fame che ho io,\n"
	.string "non c'è spazio per la pietà!$"

Route111_Text_HaydenDefeat:
	.string "Uuugh…$"

Route111_Text_HaydenPostBattle:
	.string "Il mio stomaco brontola!\n"
	.string "Quasi quasi arrostisco qualche Bacca…$"

Route111_Text_BiancaIntro:
	.string "Arrivi da Ciclamipoli?\n"
	.string "Allora sarai carico di energia!$"

Route111_Text_BiancaDefeat:
	.string "Uh là là!\n"
	.string "Che scarica!$"

Route111_Text_BiancaPostBattle:
	.string "Questa strada…\n"
	.string "Hai ancora un bel pezzo da fare.$"

Route112_Text_BriceIntro:
	.string "Ahahahah!\n"
	.string "Che ne dici di una bella lotta?\l"
	.string "Io e te!\l"
	.string "Ahahahah!$"

Route112_Text_BriceDefeat:
	.string "Ho perso!\n"
	.string "Ahahahah!$"

Route112_Text_BricePostBattle:
	.string "Ahahahah! Mi è entrato qualcosa\n"
	.string "nel naso! Ahahah… ah… ETCIÙ!$"

Route112_Text_TrentIntro:
	.string "Ho le gambe d'acciaio, a forza di\n"
	.string "salire e scendere dalle montagne.\p"
	.string "Non cederanno tanto facilmente,\n"
	.string "amico mio!$"

Route112_Text_TrentDefeat:
	.string "Ahia! Mi è venuto un crampo!$"

Route112_Text_TrentPostBattle:
	.string "Prova a camminare, ma sul serio,\n"
	.string "su questi sentieri di montagna\l"
	.string "con uno zaino che pesa\l"
	.string "decine di chili.\p"
	.string "Quello sì, amico mio, che ti rimette\n"
	.string "in forma per davvero!$"

Route112_Text_TrentRegister:
	.string "Ahi, che crampi alle gambe…\n"
	.string "Mi passi le bende che ho\l"
	.string "nello zaino?\p"
	.string "No, quello è il mio PokéNav!\n"
	.string "Va be', già che ci sei, ti registro.$"

Route112_Text_TrentRematchIntro:
	.string "Mi tengo in forma con le escursioni.\n"
	.string "Di forza ne ho da vendere!$"

Route112_Text_TrentRematchDefeat:
	.string "Battuto proprio sulla forza?$"

Route112_Text_TrentRematchPostBattle:
	.string "Dicono che in cima al Monte Camino\n"
	.string "ci siano Allenatori tostissimi.\p"
	.string "Ho intenzione di arrivare lassù\n"
	.string "e sfidarli tutti!$"

Route112_Text_LarryIntro:
	.string "Io sono forte.\n"
	.string "Se perdo, non piango.$"

Route112_Text_LarryDefeat:
	.string "Uaaaaah!$"

Route112_Text_LarryPostBattle:
	.string "Non piango perché mi manca la mamma!\n"
	.string "Sniff…$"

Route112_Text_CarolIntro:
	.string "Quando sei in gita, beh, non puoi\n"
	.string "fare a meno di cantare!\l"
	.string "Dai, canta con me!$"

Route112_Text_CarolDefeat:
	.string "Oh, ma quanto sei forte!$"

Route112_Text_CarolPostBattle:
	.string "Non importa se sei bravo o scarso\n"
	.string "a cantare o con i Pokémon.\p"
	.string "Chi si diverte di più, vince!$"

Route112_Text_BryantIntro:
	.string "Ho preso Pokémon bollenti nel\n"
	.string "Cammino Ardente! Guarda qua!$"

Route112_Text_BryantDefeat:
	.string "Che lotta piena di scossoni!$"

Route112_Text_BryantPostBattle:
	.string "Mi piace il tuo modo di lottare.\n"
	.string "Ha un certo stile, sai?$"

Route112_Text_ShaylaIntro:
	.string "Oh, ma che Allenatore adorabile!\n"
	.string "Concedimi una lotta romantica,\l"
	.string "ti prego! Me la cavo abbastanza!$"

Route112_Text_ShaylaDefeat:
	.string "Oh, quanto sei forte!\n"
	.string "Mi hai proprio sconvolta!$"

Route112_Text_ShaylaPostBattle:
	.string "Hai da fare in questo momento?\n"
	.string "Pensavo che magari potremmo fare\l"
	.string "subito una rivincita…\l"
	.string "Ma se sei impegnato, non importa.$"

Route113_Text_JaylenIntro:
	.string "Indovina un po' perché qui intorno\n"
	.string "fa così fresco?$"

Route113_Text_JaylenDefeat:
	.string "Puah!\n"
	.string "Che puzza!$"

Route113_Text_JaylenPostBattle:
	.string "La cenere del vulcano copre il sole,\n"
	.string "così qui non fa mai troppo caldo.\p"
	.string "Per me è perfetto: il caldo non lo\n"
	.string "sopporto proprio!$"

Route113_Text_DillonIntro:
	.string "L'eruzione del vulcano è la prova\n"
	.string "che la terra è viva… e pure nervosa!$"

Route113_Text_DillonDefeat:
	.string "Sei forte sul serio!$"

Route113_Text_DillonPostBattle:
	.string "Ahi! Uhi! Non ci vedo più!\n"
	.string "Ho la cenere fin dentro gli occhi!\p"
	.string "Sono diventato… Cenerentolo!\n"
	.string "Capita? Cenere… Cenerentolo?\p"
	.string "Ok, era pessima, scusa…$"

Route113_Text_MadelineIntro:
	.string "Uso questo parasole per riparare\n"
	.string "i miei cari Pokémon da quella\l"
	.string "sudicia, orrenda cenere vulcanica.$"

Route113_Text_MadelineDefeat:
	.string "Uff, uff…\n"
	.string "Sono esausta…$"

Route113_Text_MadelinePostBattle:
	.string "Sei davvero bravo.\n"
	.string "Devo ammettere che mi hai colpita!$"

Route113_Text_MadelineRegister:
	.string "Su, vieni sotto il mio parasole.\n"
	.string "Ti registro nel mio PokéNav.$"

Route113_Text_MadelineRematchIntro:
	.string "Oh, salve! Quanto tempo, vero?\n"
	.string "Posso invitarti a una lotta?$"

Route113_Text_MadelineRematchDefeat:
	.string "Oh, che meraviglia!$"

Route113_Text_MadelinePostRematch:
	.string "Sei rimasto bravissimo.\n"
	.string "Devo ammettere che mi hai colpita!$"

Route113_Text_LaoIntro:
	.string "Dalle ceneri io balzo! Hiyah!\n"
	.string "Ti sfido, o viandante!$"

Route113_Text_LaoDefeat:
	.string "Con onore ammetto la sconfitta!$"

Route113_Text_LaoPostBattle:
	.string "Devo affinare l'arte di celarmi.\n"
	.string "Ti porgo il mio commiato.$"

Route113_Text_LaoRegister:
	.string "Yiiyaah! Ammira l'antica tecnica\n"
	.string "ninja della registrazione PokéNav!$"

Route113_Text_LaoRematchIntro:
	.string "Dalle ceneri io balzo! Hiyah!\n"
	.string "Ti sfido, o viandante!$"

Route113_Text_LaoRematchDefeat:
	.string "Con onore ammetto la sconfitta!$"

Route113_Text_LaoPostRematch:
	.string "Il mio mimetismo era perfetto,\n"
	.string "ma la mia arte di lotta è acerba…\p"
	.string "Ti porgo il mio commiato.$"

Route113_Text_LungIntro:
	.string "Grazie per avermi trovato!\n"
	.string "Ma adesso dobbiamo lottare!$"

Route113_Text_LungDefeat:
	.string "Ora userò il mio ninjutsu…\n"
	.string "“Mantello Turbine di Cenere”!\p"
	.string "…Eh?\n"
	.string "È già finita?$"

Route113_Text_LungPostBattle:
	.string "Sai qual è il brutto del nascondersi?\n"
	.string "Che se non passa nessuno, sei solo.$"

Route113_Text_ToriIntro:
	.string "Tori: Noi due raccogliamo la cenere.\n"
	.string "E lottiamo anche con i Pokémon.$"

Route113_Text_ToriDefeat:
	.string "Tori: Abbiamo perso… Che noia,\n"
	.string "vado a raccogliere altra cenere.$"

Route113_Text_ToriPostBattle:
	.string "Tori: Quanta cenere abbiamo?\n"
	.string "Spero basti per un Flauto Bianco.$"

Route113_Text_ToriNotEnoughMons:
	.string "Tori: Vogliamo lottare due contro due.\n"
	.string "Sennò perderemmo!$"

Route113_Text_TiaIntro:
	.string "Tia: Noi due raccogliamo la cenere.\n"
	.string "E lottiamo anche con i Pokémon.$"

Route113_Text_TiaDefeat:
	.string "Tia: Non abbiamo vinto… Che noia,\n"
	.string "vado a prendere altra cenere.$"

Route113_Text_TiaPostBattle:
	.string "Tia: Abbiamo un sacco di cenere!\n"
	.string "Basterà per un Flauto Bianco!$"

Route113_Text_TiaNotEnoughMons:
	.string "Tia: Vogliamo lottare due contro due.\n"
	.string "Altrimenti non vinciamo!$"

Route113_Text_CobyIntro:
	.string "Pfui, con queste ali ti spazzo via\n"
	.string "in un battito!$"

Route113_Text_CobyDefeat:
	.string "Ma… Cosa?$"

Route113_Text_CobyPostBattle:
	.string "Non so proprio cosa dire, quando\n"
	.string "mi battono così facilmente…$"

Route113_Text_SophieIntro:
	.string "Questo tepore mi fa venire sonno.\n"
	.string "Lotta con me, così resto sveglia.$"

Route113_Text_SophieDefeat:
	.string "È un sogno.\n"
	.string "Ne sono sicura…$"

Route113_Text_SophiePostBattle:
	.string "Perdere mi fa ribollire…\n"
	.string "Mi metto a dormire qui e basta!\l"
	.string "Zzz!$"

Route113_Text_LawrenceIntro:
	.string "Per caso stavi raccogliendo\n"
	.string "un po' di cenere vulcanica?$"

Route113_Text_LawrenceDefeat:
	.string "Eheh.\n"
	.string "Ci hai battuti senza storie.$"

Route113_Text_LawrencePostBattle:
	.string "Quasi quasi mi nascondo anch'io\n"
	.string "sotto la cenere.$"

Route113_Text_WyattIntro:
	.string "V-vuoi lottare con me?\n"
	.string "Ma ho appena preso il mio Pokémon!$"

Route113_Text_WyattDefeat:
	.string "T-tutto contento di aver vinto?\n"
	.string "Anche se era solo contro di me?$"

Route113_Text_WyattPostBattle:
	.string "Ah, adesso vuoi pure fare due\n"
	.string "chiacchiere con chi ha perso?\p"
	.string "Ti senti proprio il più figo, eh?\n"
	.string "Hmpf!$"

Route114_Text_LennyIntro:
	.string "Iodelaiii-hiuuu!\p"
	.string "… …\p"
	.string "Qui non c'è l'eco, quindi devi\n"
	.string "gridare tu “Iodelaiii-hiuuu”!$"

Route114_Text_LennyDefeat:
	.string "Iodelaiii-hiuuu!$"

Route114_Text_LennyPostBattle:
	.string "Da piccolo credevo che ci fosse\n"
	.string "qualcuno che mi imitava e mi\l"
	.string "rispondeva: “Iodelaiii-hiuuu”.\p"
	.string "Coi Varchi di oggi, chissà… magari\n"
	.string "era qualcuno di un altro mondo!$"

Route114_Text_LucasIntro:
	.string "Se non sei preparato, in montagna\n"
	.string "non ci devi proprio salire!$"

Route114_Text_LucasDefeat:
	.string "La montagna non perdona…$"

Route114_Text_LucasPostBattle:
	.string "D'inverno, tra bufere e valanghe,\n"
	.string "le montagne diventano letali.$"

Route114_Text_ShaneIntro:
	.string "Il campeggio è fantastico! Pesca,\n"
	.string "marshmallow e storie di fantasmi!\p"
	.string "Ma la cosa più bella di tutte\n"
	.string "sono le lotte Pokémon!$"

Route114_Text_ShaneDefeat:
	.string "Troppo forte!$"

Route114_Text_ShanePostBattle:
	.string "Che bello poter andare in campeggio\n"
	.string "insieme ai miei Pokémon.$"

Route114_Text_NancyIntro:
	.string "Dopo mangiato devo fare un po' di\n"
	.string "moto. Facciamo una lotta!$"

Route114_Text_NancyDefeat:
	.string "Oh, no!$"

Route114_Text_NancyPostBattle:
	.string "Ho appena fatto un pranzo squisito.\n"
	.string "Mi sta venendo sonno…$"

Route114_Text_SteveIntro:
	.string "Ufufufufufu…\n"
	.string "Vuoi lottare contro i miei Pokémon?$"

Route114_Text_SteveDefeat:
	.string "I-i miei Pokémon…$"

Route114_Text_StevePostBattle:
	.string "Un corpo enorme, duro e bitorzoluto,\n"
	.string "corna gigantesche, zanne feroci…\p"
	.string "Ufufufufu…\n"
	.string "Vorrei tanto un Pokémon così…\l"
	.string "Magari un giorno uscirà da un Varco…$"

Route114_Text_SteveRegister:
	.string "Non dimenticare cosa mi hai fatto!\n"
	.string "Farò in modo che tu non lo scordi!$"

Route114_Text_SteveRematchIntro:
	.string "Ufufufufufu…\n"
	.string "Dai, lotta contro i miei Pokémon…$"

Route114_Text_SteveRematchDefeat:
	.string "Che fortuna poter ammirare\n"
	.string "i tuoi Pokémon…$"

Route114_Text_StevePostRematch:
	.string "Ufufufufufu…\p"
	.string "Quando vedo i Pokémon lottare,\n"
	.string "mi vengono i brividi dappertutto…$"

Route114_Text_BernieIntro:
	.string "Se accendi un falò, tieni sempre\n"
	.string "l'acqua a portata di mano.$"

Route114_Text_BernieDefeat:
	.string "Grazie per aver spento il mio fuoco!$"

Route114_Text_BerniePostBattle:
	.string "Con il fuoco nei boschi bisogna\n"
	.string "stare davvero attenti.\p"
	.string "Mai sottovalutare la potenza\n"
	.string "delle fiamme.$"

Route114_Text_BernieRegister:
	.string "Mi hai acceso lo spirito!\n"
	.string "Registriamoci a vicenda!$"

Route114_Text_BernieRematchIntro:
	.string "Hai imparato a tenere l'acqua\n"
	.string "a portata di mano per i falò?$"

Route114_Text_BernieRematchDefeat:
	.string "Mi hai spento prima che potessi\n"
	.string "divampare, a quanto pare.$"

Route114_Text_BerniePostRematch:
	.string "Con il fuoco nei boschi bisogna\n"
	.string "stare davvero attenti.\p"
	.string "Mai sottovalutare la potenza\n"
	.string "delle fiamme.$"

Route114_Text_ClaudeIntro:
	.string "Se fosse una gara di pesca, contro\n"
	.string "di me non avresti scampo.\l"
	.string "Quindi, fuori i tuoi Pokémon!$"

Route114_Text_ClaudeDefeat:
	.string "Se fosse stata una gara di pesca,\n"
	.string "avrei vinto io…$"

Route114_Text_ClaudePostBattle:
	.string "Proverò a tirar su un pesce enorme\n"
	.string "alle Cascate Meteora.\p"
	.string "Con tutto quello che esce dai Varchi,\n"
	.string "laggiù dev'esserci qualcosa. Lo sento!$"

Route114_Text_NolanIntro:
	.string "Mi piace pescare. Ma mi piace anche\n"
	.string "lottare!\p"
	.string "Se qualcuno mi sfida, io ci sto,\n"
	.string "anche mentre pesco.$"

Route114_Text_NolanDefeat:
	.string "Mi piace lottare, ma non vuol dire\n"
	.string "che io sia bravo…$"

Route114_Text_NolanPostBattle:
	.string "Stavolta ce la faccio!\p"
	.string "Lo penso sempre, per questo non smetto\n"
	.string "né di pescare né di lottare.$"

Route114_Text_TyraIntro:
	.string "Tyra: Ma certo.\n"
	.string "Ne ho proprio voglia.\l"
	.string "Ti insegno due cose sui Pokémon.$"

Route114_Text_TyraDefeat:
	.string "Tyra: Che stile di lotta incredibile!$"

Route114_Text_TyraPostBattle:
	.string "Tyra: Stavo insegnando i segreti\n"
	.string "dei Pokémon alla mia allieva Ivy.$"

Route114_Text_TyraNotEnoughMons:
	.string "Tyra: Ihihih…\n"
	.string "Se vuoi lottare con noi, un Pokémon\l"
	.string "solo non basta!$"

Route114_Text_IvyIntro:
	.string "Ivy: Chi ti ha insegnato a lottare?$"

Route114_Text_IvyDefeat:
	.string "Ivy: Che stile di lotta incredibile!$"

Route114_Text_IvyPostBattle:
	.string "Ivy: Ho iniziato ad allenare Pokémon\n"
	.string "perché me l'ha insegnato Tyra,\l"
	.string "la mia tutor!$"

Route114_Text_IvyNotEnoughMons:
	.string "Ivy: Hai un solo Pokémon?\n"
	.string "Poverino, si sentirà tanto solo.$"

Route114_Text_KaiIntro:
	.string "Ho preso un pesce grosso!\n"
	.string "Enorme, ti dico!$"

Route114_Text_KaiDefeat:
	.string "Ma come?\n"
	.string "Il mio era più piccolo?$"

Route114_Text_KaiPostBattle:
	.string "Va bene!\n"
	.string "Allora ne pescherò uno ancora più grosso!$"

Route114_Text_CharlotteIntro:
	.string "Io!\n"
	.string "Non sono solo un bel faccino!$"

Route114_Text_CharlotteDefeat:
	.string "Non è stato carino per niente!$"

Route114_Text_CharlottePostBattle:
	.string "Non voglio un Pokémon che sia\n"
	.string "soltanto carino.\p"
	.string "Adoro quelli carini che hanno\n"
	.string "anche qualche stranezza!$"

Route114_Text_AngelinaIntro:
	.string "Hai fatto evolvere tanti dei\n"
	.string "tuoi Pokémon?$"

Route114_Text_AngelinaDefeat:
	.string "Oh, capisco.\n"
	.string "Buono a sapersi.$"

Route114_Text_AngelinaPostBattle:
	.string "Certi Pokémon, quando si evolvono,\n"
	.string "cambiano così tanto che è incredibile!$"

Route115_Text_TimothyIntro:
	.string "Mm…\n"
	.string "Sembri piuttosto capace…\l"
	.string "Permettimi di farti compagnia!$"

Route115_Text_TimothyDefeat:
	.string "Sei molto più forte di quanto\n"
	.string "immaginassi!$"

Route115_Text_TimothyPostBattle:
	.string "Il genio innato non esiste.\n"
	.string "Tutto dipende dall'impegno!\l"
	.string "Questo è ciò in cui credo…$"

Route115_Text_TimothyRegister:
	.string "Mm… Una sconfitta così netta non\n"
	.string "mi capitava da tempo immemore.\p"
	.string "Se me lo permetti, vorrei un'altra\n"
	.string "occasione di lottare con te.$"

Route115_Text_TimothyRematchIntro:
	.string "Mm… Come sempre, la tua agilità\n"
	.string "parla da sé.\l"
	.string "Vieni, fammi compagnia!$"

Route115_Text_TimothyRematchDefeat:
	.string "Forte come sempre!$"

Route115_Text_TimothyPostRematch:
	.string "Basta l'impegno!\p"
	.string "Ho perso perché non mi sono\n"
	.string "impegnato abbastanza!$"

Route115_Text_KoichiIntro:
	.string "Tu!\p"
	.string "I miei Pokémon!\p"
	.string "Esigono una lotta!$"

Route115_Text_KoichiDefeat:
	.string "Ahi, ahi, ahi!$"

Route115_Text_KoichiPostBattle:
	.string "La mia squadra di lottatori!\p"
	.string "Finché loro cercheranno la forza,\n"
	.string "io diventerò forte insieme a loro!$"

Route115_Text_NobIntro:
	.string "La mia tecnica migliore? Spaccare\n"
	.string "mattoni a colpi di fronte!$"

Route115_Text_NobDefeat:
	.string "Uuuaaargh!\n"
	.string "La mia povera testa!$"

Route115_Text_NobPostBattle:
	.string "Insegno il karate ai miei Pokémon.\p"
	.string "Pare che diventeranno molto più\n"
	.string "bravi di me. Non vedo l'ora!$"

Route115_Text_NobRegister:
	.string "Mi hai impressionato! Dammi la\n"
	.string "rivincita quando mi sarò riallenato!$"

Route115_Text_NobRematchIntro:
	.string "Dopo la sconfitta ci siamo allenati\n"
	.string "duramente per migliorare.\l"
	.string "Forza, dacci la rivincita!$"

Route115_Text_NobRematchDefeat:
	.string "Uuuaaargh!\n"
	.string "Abbiamo perso di nuovo!$"

Route115_Text_NobPostRematch:
	.string "I miei Pokémon diventeranno più forti!\n"
	.string "Raddoppierò gli allenamenti!$"

Route115_Text_CyndyIntro:
	.string "Questa spiaggia è la mia palestra\n"
	.string "segreta! Non venire a disturbare!$"

Route115_Text_CyndyDefeat:
	.string "Non mi sono allenata abbastanza!$"

Route115_Text_CyndyPostBattle:
	.string "La sabbia attutisce i colpi\n"
	.string "e previene gli infortuni.\l"
	.string "È il posto perfetto per allenarsi.$"

Route115_Text_CyndyRegister:
	.string "Va bene, d'accordo, puoi venire qui.\n"
	.string "In cambio, voglio un'altra lotta!$"

Route115_Text_CyndyRematchIntro:
	.string "Ok, diamo inizio a questa lotta!$"

Route115_Text_CyndyRematchDefeat:
	.string "Io so lottare, ma i miei Pokémon…$"

Route115_Text_CyndyPostRematch:
	.string "Anche quando perdo, mi diverto\n"
	.string "lo stesso.\l"
	.string "Dev'essere perché adoro i Pokémon.$"

Route115_Text_HectorIntro:
	.string "Ho un Pokémon rarissimo!\n"
	.string "Vuoi che te lo faccia vedere?$"

Route115_Text_HectorDefeat:
	.string "Tu…\n"
	.string "Tu vuoi il mio Pokémon, vero?$"

Route115_Text_HectorPostBattle:
	.string "Ho questo Pokémon raro, arrivato\n"
	.string "da un Varco. Mi basta e avanza.$"

Route115_Text_KyraIntro:
	.string "Lotto mentre corro!\n"
	.string "Vediamo se riesci a starmi dietro!$"

Route115_Text_KyraDefeat:
	.string "Ansf, ansf…$"

Route115_Text_KyraPostBattle:
	.string "Che errore, lottare mentre corro!\p"
	.string "Farò una corsetta per calmarmi…$"

Route115_Text_JaidenIntro:
	.string "Beccati questo!\n"
	.string "Ultra attacco Pokémon ninja!$"

Route115_Text_JaidenDefeat:
	.string "Uaaah!\n"
	.string "La nostra strategia è fallita!$"

Route115_Text_JaidenPostBattle:
	.string "Però i miei Pokémon erano ultra,\n"
	.string "non trovi?$"

Route115_Text_HeleneIntro:
	.string "I miei Pokémon hanno una forza\n"
	.string "da cintura nera!$"

Route115_Text_HeleneDefeat:
	.string "Che umiliazione!$"

Route115_Text_HelenePostBattle:
	.string "Raramente incontro qualcuno più\n"
	.string "bravo di me…\p"
	.string "Ho capito!\n"
	.string "Tu sei un Capopalestra, vero?$"

Route115_Text_AlixIntro:
	.string "I nostri sguardi si sono incrociati!\n"
	.string "Ora non puoi più scappare!$"

Route115_Text_AlixDefeat:
	.string "Accidenti!\n"
	.string "Niente male!$"

Route115_Text_AlixPostBattle:
	.string "Pazienza.\n"
	.string "Torno a casa con Teletrasporto.$"

Route115_Text_MarleneIntro:
	.string "Hai disturbato la mia meditazione…\n"
	.string "Per questo verrai punito.$"

Route115_Text_MarleneDefeat:
	.string "Hai spezzato la mia concentrazione!$"

Route115_Text_MarlenePostBattle:
	.string "Meditavo con i miei Pokémon, ma\n"
	.string "oggi sono tutti stranamente agitati…\p"
	.string "Che ci sia un Varco qui vicino?$"

Route116_Text_ClarkIntro:
	.string "Se il tunnel non passa, allora\n"
	.string "passerò sopra la montagna.$"

Route116_Text_ClarkDefeat:
	.string "Ansf… Ansf…\n"
	.string "Perdere mi ha stancato…$"

Route116_Text_ClarkPostBattle:
	.string "Se il tunnel non c'è, pazienza.\n"
	.string "Per un Montanaro, i monti sono strade!$"

Route116_Text_JoeyIntro:
	.string "I miei Pokémon sono fortissimi!\n"
	.string "Guarda un po'!$"

Route116_Text_JoeyDefeat:
	.string "Ahia! Mi sono sbucciato!\n"
	.string "Mi serve subito un cerotto!$"

Route116_Text_JoeyPostBattle:
	.string "I cerotti sono il segno dei duri!\n"
	.string "E guarda qui: ne ho un altro!$"

Route116_Text_JoseIntro:
	.string "I miei Pokémon Coleottero sono tosti!\n"
	.string "Forza, lottiamo!$"

Route116_Text_JoseDefeat:
	.string "Ho perso!\n"
	.string "Credevo di averti in pugno!$"

Route116_Text_JosePostBattle:
	.string "I Pokémon Coleottero si evolvono\n"
	.string "presto, e presto diventano forti!$"

Route116_Text_JaniceIntro:
	.string "Ti faccio vedere quanto è forte\n"
	.string "il mio adorabile Pokémon!$"

Route116_Text_JaniceDefeat:
	.string "Sei una spanna sopra di me…$"

Route116_Text_JanicePostBattle:
	.string "Un Pokémon carino e potente insieme:\n"
	.string "secondo me, quello è l'ideale!$"

Route116_Text_JerryIntro:
	.string "Alla Scuola Allenatori impariamo\n"
	.string "un sacco di cose.\p"
	.string "Voglio metterle alla prova sul serio!$"

Route116_Text_JerryDefeat:
	.string "A scuola ho fatto lo scansafatiche…\n"
	.string "Ecco perché ho perso.$"

Route116_Text_JerryPostBattle:
	.string "Dovrò ripetere qualche lezione alla\n"
	.string "Scuola Allenatori, o Petra mi farà\l"
	.string "ripassare tutto da capo!$"

Route116_Text_JerryRegister1:
	.string "Alla Scuola Allenatori ho imparato\n"
	.string "che il PokéNav registra gli Allenatori.\p"
	.string "Non ho ben capito cosa vuol dire…\n"
	.string "Posso fare una prova con te?$"

Route116_Text_JerryRegister2:
	.string "Alla Scuola Allenatori ho imparato\n"
	.string "che il PokéNav registra gli Allenatori.\p"
	.string "Non ho ben capito cosa vuol dire…\n"
	.string "Posso fare una prova con te?$"

Route116_Text_JerryRematchIntro:
	.string "Ho studiato sul serio alla Scuola\n"
	.string "Allenatori. Stavolta non perderò\l"
	.string "come l'altra volta!$"

Route116_Text_JerryRematchDefeat:
	.string "Eh?!\n"
	.string "Eppure avevo studiato tanto…$"

Route116_Text_JerryPostRematch:
	.string "Dovrò ripetere qualche lezione alla\n"
	.string "Scuola Allenatori, o Petra mi farà\l"
	.string "ripassare tutto da capo!$"

Route116_Text_KarenIntro:
	.string "Studio a scuola, e studio pure\n"
	.string "mentre torno a casa!$"

Route116_Text_KarenDefeat:
	.string "Sono sconvolta… Ho perso?!$"

Route116_Text_KarenPostBattle:
	.string "Uffa! Di questo passo non diventerò\n"
	.string "mai elegante come Petra!$"

Route116_Text_KarenRegister1:
	.string "Ehi! Ma quello è un PokéNav?\n"
	.string "Ce l'ho anch'io! Registrami, dai!$"

Route116_Text_KarenRegister2:
	.string "Ehi! Ma quello è un PokéNav?\n"
	.string "Ce l'ho anch'io! Registrami, dai!$"

Route116_Text_KarenRematchIntro:
	.string "Da quando ci siamo visti ho studiato\n"
	.string "tantissimo. Guarda che progressi!$"

Route116_Text_KarenRematchDefeat:
	.string "Sono sconvolta.\n"
	.string "Ho perso di nuovo?$"

Route116_Text_KarenPostRematch:
	.string "Hai battuto Petra?\n"
	.string "Allora non posso batterti. Non ancora!$"

Route116_Text_SarahIntro:
	.string "Ti avverto: in vita mia non ho mai\n"
	.string "perso contro nessuno, in niente.$"

Route116_Text_SarahDefeat:
	.string "Oh, santo cielo.\n"
	.string "Per me è un'esperienza nuova.$"

Route116_Text_SarahPostBattle:
	.string "Una vita nel lusso mi concede tutto\n"
	.string "ciò che potrei mai desiderare.\p"
	.string "Ma quando si parla di Pokémon,\n"
	.string "la mia ricchezza non conta nulla.$"

Route116_Text_DawsonIntro:
	.string "Quando vedrai lo splendido pelo dei\n"
	.string "miei Pokémon, la loro bellezza ti\l"
	.string "lascerà senza difese!$"

Route116_Text_DawsonDefeat:
	.string "Oh, no, ditemi che non è vero!$"

Route116_Text_DawsonPostBattle:
	.string "Oh, no, no, no!\n"
	.string "Hai arruffato il pelo dei miei Pokémon!\l"
	.string "E mi hai rovinato anche la piega!\l"
	.string "Devo chiamare subito il parrucchiere!$"

Route116_Text_DevanIntro:
	.string "Ti travolgeremo come una frana!$"

Route116_Text_DevanDefeat:
	.string "Ahiahiai!\n"
	.string "Non c'è stata partita!$"

Route116_Text_DevanPostBattle:
	.string "Dovrei provare Pokémon di altri tipi…\n"
	.string "Magari uno sbucato da un Varco!$"

Route116_Text_JohnsonIntro:
	.string "Quassù la strada non porta da\n"
	.string "nessuna parte. Mi annoio: lottiamo?$"

Route116_Text_JohnsonDefeat:
	.string "Ho perso, ma mi sono divertito!$"

Route116_Text_JohnsonPostBattle:
	.string "Ti va di restare qui a farmi\n"
	.string "un po' di compagnia?$"

Route117_Text_IsaacIntro:
	.string "Senti, ti andrebbe di lottare contro\n"
	.string "i Pokémon che sto allevando?$"

Route117_Text_IsaacDefeat:
	.string "Hai allevato i tuoi in modo superbo…$"

Route117_Text_IsaacPostBattle:
	.string "Con i Pokémon non conta solo la forza.\p"
	.string "Far brillare il carattere unico di\n"
	.string "ognuno è un altro modo per godersi\l"
	.string "i Pokémon.$"

Route117_Text_IsaacRegister:
	.string "Raddoppierò gli allenamenti.\n"
	.string "Passeresti a vedere come andiamo?$"

Route117_Text_IsaacRematchIntro:
	.string "I Pokémon che allevo sono in forma\n"
	.string "smagliante, proprio come l'altra volta.$"

Route117_Text_IsaacRematchDefeat:
	.string "Sai proprio come allevarli. Potresti\n"
	.string "lavorare alla Pensione Pokémon…$"

Route117_Text_IsaacPostRematch:
	.string "I tuoi Pokémon crescono benissimo!\n"
	.string "Dovresti portarli alle Gare Pokémon!$"

Route117_Text_LydiaIntro:
	.string "Permettimi di valutare se hai allevato\n"
	.string "i tuoi Pokémon come si deve.$"

Route117_Text_LydiaDefeat:
	.string "Sì, stanno crescendo come si deve.$"

Route117_Text_LydiaPostBattle:
	.string "Prova ad allevare i Pokémon facendo\n"
	.string "più attenzione al loro carattere.$"

Route117_Text_LydiaRegister:
	.string "Che piacere aver trovato in te un\n"
	.string "Allenatore così bravo.\l"
	.string "Spero di rivederti presto.$"

Route117_Text_LydiaRematchIntro:
	.string "Permettimi di valutare di nuovo come\n"
	.string "hai allevato i tuoi Pokémon.$"

Route117_Text_LydiaRematchDefeat:
	.string "Stanno crescendo in modo ammirevole.$"

Route117_Text_LydiaPostRematch:
	.string "Ogni Pokémon preferisce Pokémelle\n"
	.string "diverse, a seconda della sua natura.$"

Route117_Text_DylanIntro:
	.string "Sono nel bel mezzo di un triathlon,\n"
	.string "ma chi se ne importa: lottiamo!$"

Route117_Text_DylanDefeat:
	.string "Ho finito le energie!$"

Route117_Text_DylanPostBattle:
	.string "Forse ho combinato un pasticcio…\p"
	.string "Con questa lotta potrei essere\n"
	.string "scivolato all'ultimo posto…$"

Route117_Text_DylanRegister:
	.string "Anche i Pokémon devono essere forti?\n"
	.string "Allora allenami tu!$"

Route117_Text_DylanRematchIntro:
	.string "Sono in pieno triathlon, ma ho un\n"
	.string "bel vantaggio sugli altri.\l"
	.string "Facciamo una lotta lampo!$"

Route117_Text_DylanRematchDefeat:
	.string "Ho finito di nuovo le energie!$"

Route117_Text_DylanPostRematch:
	.string "Nel nuoto e in bici sono il migliore,\n"
	.string "ma con i Pokémon non mi sento ancora\l"
	.string "così sicuro.$"

Route117_Text_MariaIntro:
	.string "Mi alleno per il triathlon con i miei\n"
	.string "Pokémon: in velocità non ho rivali!$"

Route117_Text_MariaDefeat:
	.string "Devo allenarmi ancora di più,\n"
	.string "a quanto pare.$"

Route117_Text_MariaPostBattle:
	.string "L'allenamento serve solo se è\n"
	.string "costante.\p"
	.string "Bene! Riprendo ad allenarmi!\n"
	.string "Da domani!$"

Route117_Text_MariaRegister:
	.string "Vedo che ti alleni come si deve…\n"
	.string "Se ti va, lottiamo ancora più avanti!$"

Route117_Text_MariaRematchIntro:
	.string "Ti stai allenando con costanza?\n"
	.string "Io sì, eccome!\l"
	.string "Te ne darò la prova!$"

Route117_Text_MariaRematchDefeat:
	.string "Devo allenarmi ancora di più,\n"
	.string "a quanto pare.$"

Route117_Text_MariaPostRematch:
	.string "Riprendo ad allenarmi domani.\n"
	.string "Rifacciamo una lotta, prima o poi!$"

Route117_Text_DerekIntro:
	.string "Un tempo Pigliamosche!\n"
	.string "E ora Insettomane!\p"
	.string "Ma il mio amore per i Pokémon\n"
	.string "non è cambiato di una virgola!$"

Route117_Text_DerekDefeat:
	.string "Anche la mia incapacità non è\n"
	.string "cambiata di una virgola…$"

Route117_Text_DerekPostBattle:
	.string "Ho solo seguito il mio cuore, e ora\n"
	.string "tutti mi chiamano Insettomane…\p"
	.string "Be', sono un esperto di Pokémon\n"
	.string "Coleottero, quindi è normale che mi\l"
	.string "chiamino Insettomane.$"

Route117_Text_AnnaIntro:
	.string "Anna: Sono in coppia con la mia\n"
	.string "piccola allieva. Devo farmi onore!$"

Route117_Text_AnnaDefeat:
	.string "Anna: Proprio davanti alla mia\n"
	.string "allieva… Che figuraccia!$"

Route117_Text_AnnaPostBattle:
	.string "Anna: I tuoi Pokémon fanno delle\n"
	.string "belle combinazioni.\p"
	.string "Direi che sei secondo solo a noi!$"

Route117_Text_AnnaAndMegRegister:
	.string "Anna: Non possiamo finire così!\n"
	.string "Tornerai a sfidarci, vero?$"

Route117_Text_AnnaNotEnoughMons:
	.string "Anna: Se vuoi sfidarci,\n"
	.string "porta con te due Pokémon.$"

Route117_Text_MegIntro:
	.string "Meg: Io e la mia super compagna\n"
	.string "più grande ti batteremo!$"

Route117_Text_MegDefeat:
	.string "Meg: Oh, no!\n"
	.string "Scusa, Anna! Ti ho delusa…$"

Route117_Text_MegPostBattle:
	.string "Meg: Ho fatto perdere Anna…\n"
	.string "Senza di me, lei avrebbe vinto!$"

Route117_Text_MegNotEnoughMons:
	.string "Meg: Hai un Pokémon solo?\n"
	.string "Allora non possiamo lottare.\p"
	.string "Noi vogliamo una lotta due contro due.$"

Route117_Text_AnnaRematchIntro:
	.string "Anna: Non posso continuare a perdere\n"
	.string "davanti alla mia allieva, no?$"

Route117_Text_AnnaRematchDefeat:
	.string "Anna: Non sono riuscita a carburare.$"

Route117_Text_AnnaPostRematch:
	.string "Anna: I tuoi Pokémon fanno delle\n"
	.string "belle combinazioni.\p"
	.string "Direi che sei secondo solo a noi!$"

Route117_Text_AnnaRematchNotEnoughMons:
	.string "Anna: Se vuoi sfidarci,\n"
	.string "porta con te due Pokémon.$"

Route117_Text_MegRematchIntro:
	.string "Meg: Faccio squadra con la mia\n"
	.string "compagna grande. Stavolta vinciamo!$"

Route117_Text_MegRematchDefeat:
	.string "Meg: Troppo forte!$"

Route117_Text_MegPostRematch:
	.string "Meg: Abbiamo lottato insieme, io e\n"
	.string "la mia compagna, ma abbiamo perso…\p"
	.string "Che delusione…$"

Route117_Text_MegRematchNotEnoughMons:
	.string "Meg: Hai un Pokémon solo?\n"
	.string "Allora non possiamo lottare.\p"
	.string "Noi vogliamo una lotta due contro due.$"

Route117_Text_MelinaIntro:
	.string "Non è meraviglioso lottare\n"
	.string "in mezzo a tutti questi fiori?$"

Route117_Text_MelinaDefeat:
	.string "Oh, davvero notevole!$"

Route117_Text_MelinaPostBattle:
	.string "È stupendo correre con tutti\n"
	.string "questi fiori intorno.$"

Route117_Text_BrandiIntro:
	.string "Lascia che ti mostri il potere\n"
	.string "nascosto in un Pokémon Psico!$"

Route117_Text_BrandiDefeat:
	.string "Sbalorditivo!$"

Route117_Text_BrandiPostBattle:
	.string "I Pokémon Psico sono complessi…\n"
	.string "e sentono i Varchi prima di tutti.\p"
	.string "Dovresti provare a catturarne qualcuno.$"

Route117_Text_AishaIntro:
	.string "Concentrarsi solo sulla vittoria.\n"
	.string "Ecco come lotto io!$"

Route117_Text_AishaDefeat:
	.string "Non perdo tempo ad arrabbiarmi per\n"
	.string "una sconfitta: preferisco allenarmi.$"

Route117_Text_AishaPostBattle:
	.string "Secondo me, se hai paura di perdere,\n"
	.string "finisci per perdere davvero.$"

Route118_Text_RoseIntro:
	.string "Il profumo dei fiori ha un potere\n"
	.string "magico. Purifica il corpo e l'anima.$"

Route118_Text_RoseDefeat:
	.string "Oh, povera me.\n"
	.string "Pare proprio che abbia perso.$"

Route118_Text_RosePostBattle:
	.string "I fiori, i Pokémon…\n"
	.string "Adoro tutto ciò che profuma.\p"
	.string "Le cose puzzolenti…\n"
	.string "No, grazie.$"

Route118_Text_RoseRegister:
	.string "Sniff… Questo odore… è un PokéNav!\n"
	.string "Dobbiamo registrarci a vicenda!$"

Route118_Text_RoseRematchIntro:
	.string "Sei arrivato fin qui seguendo\n"
	.string "questo dolce profumo?$"

Route118_Text_RoseRematchDefeat:
	.string "Il potere del profumo…\n"
	.string "Non è servito granché.$"

Route118_Text_RosePostRematch:
	.string "Se sai usare bene un dolce profumo,\n"
	.string "i Pokémon ne saranno attratti.$"

Route118_Text_PerryIntro:
	.string "I Pokémon uccello che solcano il cielo\n"
	.string "con eleganza… Sono i migliori!$"

Route118_Text_PerryDefeat:
	.string "Urgh…\n"
	.string "Sono precipitato…$"

Route118_Text_PerryPostBattle:
	.string "Hai dei Pokémon eccezionali.\n"
	.string "Dovrò allenare meglio i miei.$"

Route118_Text_ChesterIntro:
	.string "Spiccate il volo,\n"
	.string "miei Pokémon uccello!$"

Route118_Text_ChesterDefeat:
	.string "Hanno preso il volo… per scappare!$"

Route118_Text_ChesterPostBattle:
	.string "Se diventassero più forti, potrebbero\n"
	.string "volare più liberi…$"

Route118_Text_BarnyIntro:
	.string "Sono un pescatore, ma anche un\n"
	.string "Allenatore: alleno i Pokémon che pesco!$"

Route118_Text_BarnyDefeat:
	.string "Credevo che l'allenamento stesse\n"
	.string "andando bene…$"

Route118_Text_BarnyPostBattle:
	.string "Allenare i Pokémon mentre pesco\n"
	.string "non è bastato per vincere…\p"
	.string "Facevo le cose a metà?$"

Route118_Text_WadeIntro:
	.string "Per un pescatore, l'attrezzatura\n"
	.string "è tutto.\p"
	.string "Ma per un Allenatore, gli ingredienti\n"
	.string "giusti sono Pokémon e cuore!$"

Route118_Text_WadeDefeat:
	.string "Battuto… proprio nel cuore?$"

Route118_Text_WadePostBattle:
	.string "A pensarci bene, anche la pesca è una\n"
	.string "lotta tra pescatore e Pokémon.$"

Route118_Text_DaltonIntro:
	.string "La mia melodia ti scuoterà l'anima!$"

Route118_Text_DaltonDefeat:
	.string "La-lalalà…$"

Route118_Text_DaltonPostBattle:
	.string "Una chitarra elettrica non deve per\n"
	.string "forza fare baccano…\p"
	.string "Si può pizzicare piano, per tirarne\n"
	.string "fuori una melodia che tocca il cuore…$"

Route118_Text_DaltonRegister:
	.string "Quando comporrò melodie migliori,\n"
	.string "dovrai venire ad ascoltarle, intesi?$"

Route118_Text_DaltonRematchIntro:
	.string "Una melodia dei miei Pokémon e mia…\n"
	.string "Lascia che arrivi alla tua anima.$"

Route118_Text_DaltonRematchDefeat:
	.string "La-lalalà…$"

Route118_Text_DaltonPostRematch:
	.string "Quando suono, le mie emozioni\n"
	.string "dovrebbero arrivarti attraverso\l"
	.string "la mia chitarra elettrica…$"

Route118_Text_DeandreIntro:
	.string "Via, via, via!\n"
	.string "Pokémon 1, 2 e 3!$"

Route118_Text_DeandreDefeat:
	.string "Pokémon, rispondete! State bene?\n"
	.string "Pokémon 1, 2 e 3?!$"

Route118_Text_DeandrePostBattle:
	.string "Forte, eh, avere una vera squadra\n"
	.string "da lotta di Pokémon?\p"
	.string "Puoi copiarmi, non mi offendo!$"

Route119_Text_BrentIntro:
	.string "Siamo il Circolo Mimica!\n"
	.string "Imitiamo tutto quello che fai!$"

Route119_Text_BrentDefeat:
	.string "Ops!\n"
	.string "Ho perso!$"

Route119_Text_BrentPostBattle:
	.string "Cosa ci sarà mai di bello\n"
	.string "nell'imitare?\p"
	.string "Ihihih…\n"
	.string "Non lo capirai mai…$"

Route119_Text_DonaldIntro:
	.string "E così, finalmente ci incontriamo!\n"
	.string "I miei Pokémon Coleottero ti terranno\l"
	.string "compagnia!$"

Route119_Text_DonaldDefeat:
	.string "Avrei preferito non incontrarti mai…$"

Route119_Text_DonaldPostBattle:
	.string "Voglio imitarti ancora un po'.\n"
	.string "Ti decidi a muoverti?$"

Route119_Text_TaylorIntro:
	.string "Se fai un passo avanti, lo facciamo\n"
	.string "anche noi.\p"
	.string "Se giri a destra, giriamo anche noi…$"

Route119_Text_TaylorDefeat:
	.string "Ma se vinci tu, io perdo…$"

Route119_Text_TaylorPostBattle:
	.string "Non riesco a imitare la tua vittoria.\n"
	.string "È semplicemente impossibile…\l"
	.string "E la cosa mi brucia da morire…$"

Route119_Text_DougIntro:
	.string "Eh sì, alla fine mi hai beccato!\n"
	.string "O stavi cercando di evitarmi?$"

Route119_Text_DougDefeat:
	.string "Wow, che bella lotta!$"

Route119_Text_DougPostBattle:
	.string "Siamo il Circolo Mimica!\n"
	.string "Spero ti sia piaciuto lo spettacolo.$"

Route119_Text_GregIntro:
	.string "Non sai chi sono, vero?\p"
	.string "Be', nemmeno io so chi sei tu.\n"
	.string "Quindi, lottiamo!$"

Route119_Text_GregDefeat:
	.string "Sei proprio forte!$"

Route119_Text_GregPostBattle:
	.string "Finché non te ne andrai, continueremo\n"
	.string "a imitare ogni tua mossa.$"

Route119_Text_KentIntro:
	.string "Il Circolo Mimica è nato da gente\n"
	.string "a cui piace imitare.\p"
	.string "La lotta inizia nell'istante in cui\n"
	.string "ci incontriamo!$"

Route119_Text_KentDefeat:
	.string "Mi arrendo!$"

Route119_Text_KentPostBattle:
	.string "Perché non entri nel Circolo Mimica?$"

Route119_Text_JacksonIntro:
	.string "Chi ha le conoscenze e le tecniche\n"
	.string "per sopravvivere nella natura?\p"
	.string "I Ranger Pokémon, ecco chi!$"

Route119_Text_JacksonDefeat:
	.string "Non ne sapevo abbastanza\n"
	.string "sui Pokémon…$"

Route119_Text_JacksonPostBattle:
	.string "Staccarsi dalla civiltà e risvegliare\n"
	.string "lo spirito selvaggio che è in noi!\p"
	.string "Questa è la nostra filosofia.$"

Route119_Text_JacksonRegister:
	.string "Spero mi concederai una rivincita,\n"
	.string "senza ridere delle mie lacune.$"

Route119_Text_JacksonRematchIntro:
	.string "Ritroverò il mio spirito selvaggio\n"
	.string "stando insieme ai Pokémon.$"

Route119_Text_JacksonRematchDefeat:
	.string "Sei rimasto forte!$"

Route119_Text_JacksonPostRematch:
	.string "Credi nei tuoi Pokémon.\n"
	.string "Credi in te stesso.\p"
	.string "La strada si rivelerà da sola.$"

Route119_Text_CatherineIntro:
	.string "Oh? Ma guardati.\p"
	.string "Per essere in viaggio sotto questa\n"
	.string "pioggia, hai un bagaglio leggerissimo.$"

Route119_Text_CatherineDefeat:
	.string "Gli incidenti capitano quando\n"
	.string "non si è preparati!$"

Route119_Text_CatherinePostBattle:
	.string "Viaggi leggero, ma hai tutto quello\n"
	.string "che ti serve.\p"
	.string "E sei in gran forma, sia di testa\n"
	.string "che di fisico.$"

Route119_Text_CatherineRegister:
	.string "Hai un PokéNav?\n"
	.string "Per un Allenatore è indispensabile.\p"
	.string "Oh, ce l'hai davvero!\n"
	.string "Allora registriamoci a vicenda!$"

Route119_Text_CatherineRematchIntro:
	.string "Come procede il tuo viaggio\n"
	.string "con i Pokémon?$"

Route119_Text_CatherineRematchDefeat:
	.string "Mi manca ancora qualcosa…$"

Route119_Text_CatherinePostRematch:
	.string "Come tu, da Allenatore, conti sui tuoi\n"
	.string "Pokémon, anche i tuoi Pokémon\l"
	.string "contano su di te.$"

Route119_Text_HughIntro:
	.string "Il cielo sconfinato è pieno di promesse!\p"
	.string "Niente batte l'ebbrezza del volo…\n"
	.string "nemmeno questa pioggia infinita!$"

Route119_Text_HughDefeat:
	.string "Abbattuto in volo!$"

Route119_Text_HughPostBattle:
	.string "I miei Pokémon uccello hanno\n"
	.string "realizzato il mio sogno di volare!$"

Route119_Text_PhilIntro:
	.string "Ti mostrerò il vero potenziale mio\n"
	.string "e dei miei Pokémon uccello!$"

Route119_Text_PhilDefeat:
	.string "Ci mancava il potenziale…$"

Route119_Text_PhilPostBattle:
	.string "Fin da piccolo ho sempre ammirato\n"
	.string "i Pokémon uccello…$"

Route119_Text_YasuIntro:
	.string "Celarmi nell'ombra, vivere\n"
	.string "nell'oscurità… È il mio destino.\p"
	.string "Emergo per sfidarti!$"

Route119_Text_YasuDefeat:
	.string "Ammetto la sconfitta!$"

Route119_Text_YasuPostBattle:
	.string "Chi viene sconfitto in lotta torna\n"
	.string "in silenzio nell'ombra.\l"
	.string "Anche questo è destino…$"

Route119_Text_TakashiIntro:
	.string "Se abbassi la guardia,\n"
	.string "saranno guai!$"

Route119_Text_TakashiDefeat:
	.string "Sei più bravo del previsto!$"

Route119_Text_TakashiPostBattle:
	.string "Il mio attacco a sorpresa è\n"
	.string "fallito…$"

Route119_Text_HideoIntro:
	.string "Un albero si nasconde nella foresta!$"

Route119_Text_HideoDefeat:
	.string "Mi inchino alla tua superiorità.$"

Route119_Text_HideoPostBattle:
	.string "Un albero si nasconde nella foresta!\n"
	.string "Un Pokémon si nasconde tra i Pokémon!\p"
	.string "Non c'è nessun significato nascosto\n"
	.string "dietro, eh.$"

Route119_Text_ChrisIntro:
	.string "Mi hai rivolto la parola…\n"
	.string "Allora vuoi sfidarmi!\p"
	.string "D'accordo! Proverò i Pokémon che\n"
	.string "ho pescato mentre facevo Surf!$"

Route119_Text_ChrisDefeat:
	.string "Non ho la minima idea di cosa\n"
	.string "serva per vincere.$"

Route119_Text_ChrisPostBattle:
	.string "Fare Surf sul mio Pokémon…\p"
	.string "Poi pescare dalla sua groppa…\p"
	.string "È un piacere che non si può descrivere!$"

Route119_Text_FabianIntro:
	.string "Dammi un accordo potente, sì!\n"
	.string "La vittoria è mia, finisce qui!\l"
	.string "È l'ora di brillare, oh, yeah!$"

Route119_Text_FabianDefeat:
	.string "Il capo sei tu, l'hai dimostrato!\n"
	.string "Mi tocca perdere, che peccato, oh, no!$"

Route119_Text_FabianPostBattle:
	.string "Un altro accordo, fallo vibrare!\n"
	.string "Lasciami solo, non mi parlare!\l"
	.string "Questa vittoria la devi scontare!$"

Route119_Text_DaytonIntro:
	.string "Ohohoh!\n"
	.string "Adoro gli Allenatori giovani!\l"
	.string "Facciamo una lotta infuocata!$"

Route119_Text_DaytonDefeat:
	.string "Sei una vera fiammata!\n"
	.string "Ohohoh!$"

Route119_Text_DaytonPostBattle:
	.string "Ohohoh!\n"
	.string "Vorrei avere anch'io il fuoco che\l"
	.string "avete voi giovani Allenatori!$"

Route119_Text_RachelIntro:
	.string "Pioggia o sole, ovunque io vada,\n"
	.string "il mio parasole non mi lascia mai.$"

Route119_Text_RachelDefeat:
	.string "Oh, ma…\n"
	.string "Non è giusto!$"

Route119_Text_RachelPostBattle:
	.string "Mi chiedi se il parasole è pesante?\n"
	.string "Nella tua Borsa c'è molta più roba\l"
	.string "di quanta ne porti in giro io!$"

Route120_Text_ColinIntro:
	.string "Hai qualche mossa capace di colpire\n"
	.string "un Pokémon in volo?$"

Route120_Text_ColinDefeat:
	.string "Mi hai superato in quota!$"

Route120_Text_ColinPostBattle:
	.string "La mossa Volo è comodissima,\n"
	.string "non trovi?\p"
	.string "Finché il Pokémon è in aria, quasi\n"
	.string "nessuna mossa riesce a colpirlo.$"

Route120_Text_RobertIntro:
	.string "Il mio Pokémon è forte!\n"
	.string "E il tuo, invece?$"

Route120_Text_RobertDefeat:
	.string "I tuoi Pokémon erano più forti…$"

Route120_Text_RobertPostBattle:
	.string "Un Pokémon che cresce con costanza\n"
	.string "è un Pokémon su cui puoi contare.$"

Route120_Text_RobertRegister:
	.string "Anche tu sei uno che migliora sempre.\n"
	.string "Voglio registrarti nel mio PokéNav!$"

Route120_Text_RobertRematchIntro:
	.string "I miei Pokémon sono cresciuti con\n"
	.string "costanza. Ora puoi contare su di loro!$"

Route120_Text_RobertRematchDefeat:
	.string "I tuoi Pokémon sono fortissimi.$"

Route120_Text_RobertPostRematch:
	.string "I miei Pokémon diventano più forti.\n"
	.string "Devo crescere anch'io, insieme a loro.$"

Route120_Text_LorenzoIntro:
	.string "Vediamo se i tuoi Pokémon sono\n"
	.string "pronti per la vita all'aria aperta.$"

Route120_Text_LorenzoDefeat:
	.string "Con Pokémon così forti, nessuno\n"
	.string "dovrà mai venire a soccorrerti!$"

Route120_Text_LorenzoPostBattle:
	.string "Andare ovunque ti porti il cuore,\n"
	.string "insieme ai tuoi Pokémon…\l"
	.string "È questa la gioia di un Allenatore.$"

Route120_Text_JennaIntro:
	.string "Come sei messo a forma fisica?\n"
	.string "Se non sei allenato, nei momenti\l"
	.string "critici potresti trovarti nei guai.$"

Route120_Text_JennaDefeat:
	.string "Sono in formissima, eppure…$"

Route120_Text_JennaPostBattle:
	.string "Mi alleno ogni giorno, senza eccezioni.\n"
	.string "E corro sempre insieme ai miei Pokémon.$"

Route120_Text_JeffreyIntro:
	.string "… … … … … …\n"
	.string "… … … … … …\l"
	.string "Vuoi lottare?$"

Route120_Text_JeffreyDefeat:
	.string "Perso…$"

Route120_Text_JeffreyPostBattle:
	.string "… … … … … …\n"
	.string "… … … … … …\l"
	.string "Mi impegnerò di più…$"

Route120_Text_JeffreyRegister:
	.string "… … … … … …\n"
	.string "… … … … … …\l"
	.string "Hai un PokéNav…?$"

Route120_Text_JeffreyRematchIntro:
	.string "… … … … … …\n"
	.string "… … … … … …\l"
	.string "Lottiamo ancora…?$"

Route120_Text_JeffreyRematchDefeat:
	.string "… … … … … …\n"
	.string "Ho perso di nuovo…$"

Route120_Text_JeffreyPostRematch:
	.string "… … … … … …\n"
	.string "… … … … … …\l"
	.string "Mi impegnerò di più…\l"
	.string "Per i miei adorati Pokémon Coleottero…$"

Route120_Text_JenniferIntro:
	.string "I Pokémon hanno tante Abilità speciali.\n"
	.string "Se vuoi diventare un Allenatore di\l"
	.string "prim'ordine, devi conoscerle bene.$"

Route120_Text_JenniferDefeat:
	.string "Si vede che usi la testa.$"

Route120_Text_JenniferPostBattle:
	.string "Le Abilità dei Pokémon possono\n"
	.string "cambiare del tutto lo stile di lotta.$"

Route120_Text_ChipIntro:
	.string "E tu chi saresti?\p"
	.string "Stai forse cercando anche tu le antiche\n"
	.string "rovine che, secondo la leggenda,\l"
	.string "potrebbero trovarsi da queste parti?$"

Route120_Text_ChipDefeat:
	.string "Che battuta d'arresto vergognosa…$"

Route120_Text_ChipPostBattle:
	.string "Quel masso gigantesco… Voglio credere\n"
	.string "che nasconda davvero antiche rovine.\l"
	.string "Ma non vedo nessun ingresso.\p"
	.string "Si dice che un popolo antico vi abbia\n"
	.string "inciso qualcosa, quando il cielo\l"
	.string "si squarciò…$"

Route120_Text_ClarissaIntro:
	.string "Perché porto con me questo parasole?\p"
	.string "Te lo dirò se riuscirai a battermi.$"

Route120_Text_ClarissaDefeat:
	.string "Un parasole non ripara dagli\n"
	.string "attacchi dei Pokémon…$"

Route120_Text_ClarissaPostBattle:
	.string "Credo che il sole troppo forte non\n"
	.string "faccia bene ai miei Pokémon.\l"
	.string "Così li riparo col mio parasole.$"

Route120_Text_AngelicaIntro:
	.string "Io, i miei Pokémon e il mio parasole…\p"
	.string "Se anche uno solo di noi mancasse,\n"
	.string "il quadro della bellezza svanirebbe.$"

Route120_Text_AngelicaDefeat:
	.string "Hai rovinato la mia bellezza…$"

Route120_Text_AngelicaPostBattle:
	.string "A te un parasole non starebbe\n"
	.string "per niente bene.\p"
	.string "Anzi, una cosa del genere ti sarebbe\n"
	.string "soltanto d'intralcio.$"

Route120_Text_KeigoIntro:
	.string "Imiterò i movimenti dei Pokémon\n"
	.string "per creare nuove tecniche ninja!$"

Route120_Text_KeigoDefeat:
	.string "Creare nuove tecniche ninja\n"
	.string "è solo un sogno lontano…$"

Route120_Text_KeigoPostBattle:
	.string "Forse dovrei diventare l'allievo\n"
	.string "di un vero maestro ninja.$"

Route120_Text_RileyIntro:
	.string "Noi ninja ci nascondiamo sotto\n"
	.string "i nostri mantelli mimetici.\l"
	.string "Scommetto che non mi avevi visto!$"

Route120_Text_RileyDefeat:
	.string "Ho perso!\n"
	.string "Devo mimetizzare la vergogna!$"

Route120_Text_RileyPostBattle:
	.string "I nostri mantelli mimetici sono\n"
	.string "tutti fatti a mano.\p"
	.string "Però, a mimetizzarsi, certi Pokémon\n"
	.string "invisibili sono più bravi di noi…$"

Route120_Text_CallieIntro:
	.string "Se non stai attento,\n"
	.string "rischi di farti male!$"

Route120_Text_CallieDefeat:
	.string "Ahi!\n"
	.string "Quella che si è fatta male sono io.$"

Route120_Text_CalliePostBattle:
	.string "Chissà… Dovrei far evolvere i miei\n"
	.string "Pokémon? Sono così carini come sono…$"

Route120_Text_LeonelIntro:
	.string "I Pokémon della tua squadra…\n"
	.string "Sono di tipi diversi?$"

Route120_Text_LeonelDefeat:
	.string "Ho visto la tua strategia all'opera!$"

Route120_Text_LeonelPostBattle:
	.string "Trovo fantastico che tu sia così forte\n"
	.string "lottando coi tuoi Pokémon preferiti.$"

Route121_Text_VanessaIntro:
	.string "Vuoi giocare con i miei Pokémon,\n"
	.string "che sono deliziosamente carini?$"

Route121_Text_VanessaDefeat:
	.string "Non era questo che intendevo!$"

Route121_Text_VanessaPostBattle:
	.string "Sto andando alle Gare Pokémon\n"
	.string "di Porto Alghepoli.\p"
	.string "I miei Pokémon stravinceranno di\n"
	.string "sicuro anche al livello Master.$"

Route121_Text_WalterIntro:
	.string "Con i miei Pokémon ho viaggiato\n"
	.string "in ogni angolo di Hoenn.\p"
	.string "Diciamo che ho una certa fiducia\n"
	.string "nelle mie capacità.$"

Route121_Text_WalterDefeat:
	.string "Ah, ben giocato.$"

Route121_Text_WalterPostBattle:
	.string "Vorrei rifare il giro di Hoenn\n"
	.string "ancora una volta, coi miei Pokémon.\p"
	.string "E se un giorno si aprisse un Varco,\n"
	.string "magari spingermi anche oltre…$"

Route121_Text_WalterRegister:
	.string "La tua bravura coi Pokémon è notevole.\n"
	.string "Permettimi di registrarti, per ricordo.$"

Route121_Text_WalterRematchIntro:
	.string "Con i miei Pokémon ho viaggiato\n"
	.string "in ogni angolo di Hoenn.\p"
	.string "E nelle mie capacità ho ancora\n"
	.string "parecchia fiducia, sai?$"

Route121_Text_WalterRematchDefeat:
	.string "Ah, ben giocato. Di nuovo.$"

Route121_Text_WalterPostRematch:
	.string "Tu e i tuoi Pokémon…\p"
	.string "Insieme sareste considerati forti\n"
	.string "persino in un altro mondo.$"

Route121_Text_TammyIntro:
	.string "Esistono poteri che vanno oltre\n"
	.string "la nostra comprensione…$"

Route121_Text_TammyDefeat:
	.string "Ho perso…$"

Route121_Text_TammyPostBattle:
	.string "Il Monte Pira…\n"
	.string "Lassù è all'opera un potere\l"
	.string "misterioso…\p"
	.string "Dicono che persino gli spiriti\n"
	.string "sentano quando si apre un Varco…$"

Route121_Text_KateIntro:
	.string "Kate: Insieme non temiamo nessuno!\n"
	.string "Ti faremo vedere quanto siamo toste!$"

Route121_Text_KateDefeat:
	.string "Kate: Che figuraccia davanti alla\n"
	.string "mia compagna di scuola più piccola…$"

Route121_Text_KatePostBattle:
	.string "Kate: Quando qualcuno conta su di me,\n"
	.string "mi viene una gran voglia di fare\l"
	.string "bella figura…$"

Route121_Text_KateNotEnoughMons:
	.string "Kate: Se hai un solo Pokémon,\n"
	.string "non possiamo lottare con te.\p"
	.string "Due contro uno? Sarebbe da prepotenti.$"

Route121_Text_JoyIntro:
	.string "Joy: Insieme non temiamo nessuno!\n"
	.string "Ti faremo vedere quanto siamo toste!$"

Route121_Text_JoyDefeat:
	.string "Joy: Perdonami, Kate!$"

Route121_Text_JoyPostBattle:
	.string "Joy: Ehehe, dovrò allenarmi ancora\n"
	.string "con Kate, la mia compagna più grande.$"

Route121_Text_JoyNotEnoughMons:
	.string "Joy: Ti servono almeno due Pokémon\n"
	.string "se vuoi sfidarci!$"

Route121_Text_JessicaIntro:
	.string "Fermo lì! Ammira bene i miei preziosi\n"
	.string "Pokémon!$"

Route121_Text_JessicaDefeat:
	.string "Oh, ma come ti permetti!\n"
	.string "Non prenderla così sul serio!$"

Route121_Text_JessicaPostBattle:
	.string "Forse andrò a catturare altri Pokémon\n"
	.string "alla Zona Safari.$"

Route121_Text_JessicaRegister:
	.string "Stavolta ci sono andata piano!\n"
	.string "La prossima volta non sarà così!$"

Route121_Text_JessicaRematchIntro:
	.string "I miei preziosi Pokémon sono cresciuti!\n"
	.string "Ammirali bene!$"

Route121_Text_JessicaRematchDefeat:
	.string "Oh, ma come ti permetti!\n"
	.string "Ancora non ci vai piano!$"

Route121_Text_JessicaPostRematch:
	.string "Forse andrò a catturare altri Pokémon\n"
	.string "alla Zona Safari. Dicono che lì ne\l"
	.string "siano arrivati alcuni dai Varchi!$"

Route121_Text_CristinIntro:
	.string "Ho una routine: battere cinque\n"
	.string "Allenatori al giorno.\l"
	.string "Indovina un po'? Tu sei il quinto!$"

Route121_Text_CristinDefeat:
	.string "No!\n"
	.string "Sei tremendo!$"

Route121_Text_CristinPostBattle:
	.string "Non pensavo di perdere così in fretta…\n"
	.string "La prossima volta vinco io!$"

Route121_Text_CristinRegister:
	.string "È stata un'umiliazione totale!\n"
	.string "Non ti dimenticherò…\l"
	.string "Dammi il tuo PokéNav!$"

Route121_Text_CristinRematchIntro:
	.string "Ho una nuova routine: battere dieci\n"
	.string "Allenatori al giorno.\l"
	.string "Indovina un po'? Tu sei il decimo!$"

Route121_Text_CristinRematchDefeat:
	.string "Aspetta! Così non vale!\n"
	.string "Pretendo la rivincita!$"

Route121_Text_CristinPostRematch:
	.string "Un avversario che non riesco a battere…\n"
	.string "Sniff…\l"
	.string "Non posso crederci…$"

Route121_Text_CaleIntro:
	.string "Non vedi che ho le mani piene\n"
	.string "di roba?\p"
	.string "E nonostante questo, vuoi lottare\n"
	.string "lo stesso?$"

Route121_Text_CaleDefeat:
	.string "Per forza ho perso!\n"
	.string "Ho tutte e due le mani occupate!$"

Route121_Text_CalePostBattle:
	.string "Ho comprato troppa roba al Centro\n"
	.string "Commerciale di Porto Alghepoli.\p"
	.string "È più avanti, lungo questa strada.\n"
	.string "Vorrei avere una Borsa come la tua.$"

Route121_Text_MylesIntro:
	.string "Non c'è niente che mi piaccia di più\n"
	.string "che sbirciare i Pokémon degli altri!$"

Route121_Text_MylesDefeat:
	.string "Fantastici!$"

Route121_Text_MylesPostBattle:
	.string "Sono bravissimi, i tuoi Pokémon!\n"
	.string "Come li cresci?$"

Route121_Text_PatIntro:
	.string "Voglio che tutti vedano i Pokémon\n"
	.string "che ho cresciuto!$"

Route121_Text_PatDefeat:
	.string "Wow!\n"
	.string "Spettacolare!$"

Route121_Text_PatPostBattle:
	.string "Cresco ogni Pokémon con lo stesso\n"
	.string "amore, che venga da Hoenn o da un\l"
	.string "Varco. Non faccio preferenze!$"

Route121_Text_MarcelIntro:
	.string "I miei Pokémon non hanno mai perso!\n"
	.string "Alla prossima vittoria li iscrivo\l"
	.string "alle Gare Pokémon.$"

Route121_Text_MarcelDefeat:
	.string "Ehi, ma cos'è successo?$"

Route121_Text_MarcelPostBattle:
	.string "Forse devo allenare ancora un po'\n"
	.string "la mia squadra prima delle Gare.$"

Route123_Text_WendyIntro:
	.string "Vuoi sapere quanto sei forte?\n"
	.string "L'esame te lo faccio io!$"

Route123_Text_WendyDefeat:
	.string "Promosso a pieni voti!$"

Route123_Text_WendyPostBattle:
	.string "Battere perfino me…\n"
	.string "La tua forza è straordinaria!$"

Route123_Text_BraxtonIntro:
	.string "Mi sembra che tu abbia una bella\n"
	.string "collezione di Medaglie.\p"
	.string "Vediamo se te le meriti davvero!$"

Route123_Text_BraxtonDefeat:
	.string "Oh, te le meriti eccome!$"

Route123_Text_BraxtonPostBattle:
	.string "Hai fatto onore alle tue Medaglie\n"
	.string "in questa lotta!$"

Route123_Text_VioletIntro:
	.string "Si dice che i bei momenti siano\n"
	.string "pieni di buoni profumi.$"

Route123_Text_VioletDefeat:
	.string "Oh…\n"
	.string "Sento l'odore amaro della sconfitta…$"

Route123_Text_VioletPostBattle:
	.string "Il giardino del maestro delle Bacche\n"
	.string "è pieno di profumi che mettono allegria.$"

Route123_Text_CameronIntro:
	.string "Essere un Sensitivo è questione\n"
	.string "di forza di volontà.\p"
	.string "Ho deciso che non perderò con\n"
	.string "nessuno. Per questo sono forte!$"

Route123_Text_CameronDefeat:
	.string "Che tristezza…$"

Route123_Text_CameronPostBattle:
	.string "Essere un Sensitivo è questione di\n"
	.string "volontà. Credevo di non perdere…$"

Route123_Text_CameronRegister:
	.string "Lo sento!\n"
	.string "Tu e io lotteremo di nuovo!\l"
	.string "Ma non so dire se vincerò…\p"
	.string "Fammi vedere il tuo PokéNav.$"

Route123_Text_CameronRematchIntro:
	.string "Mi sono convinto che non perderò\n"
	.string "più. Per questo sono forte!$"

Route123_Text_CameronRematchDefeat:
	.string "Che tristezza…$"

Route123_Text_CameronPostRematch:
	.string "Dovrei allenarmi sul Monte Pira…\n"
	.string "Così non ti batterò mai…$"

Route123_Text_JackiIntro:
	.string "Non esultare se i tuoi Pokémon\n"
	.string "sviluppano poteri psichici.\p"
	.string "Devi affinarli, se vuoi che siano\n"
	.string "davvero utili.$"

Route123_Text_JackiDefeat:
	.string "Travolta!$"

Route123_Text_JackiPostBattle:
	.string "Tutti abbiamo poteri psichici.\n"
	.string "Abbiamo solo scordato come usarli.$"

Route123_Text_JackiRegister:
	.string "Vorrei sfidarti di nuovo.\n"
	.string "Per te va bene?$"

Route123_Text_JackiRematchIntro:
	.string "Hai risvegliato i poteri psichici\n"
	.string "che sono dentro di te?$"

Route123_Text_JackiRematchDefeat:
	.string "Sbalorditivo!$"

Route123_Text_JackiPostRematch:
	.string "Il tuo legame con i Pokémon…\n"
	.string "Anche quello è un potere psichico.$"

Route123_Text_MiuIntro:
	.string "Miu: Ciao, Allenatore. Spero che i tuoi\n"
	.string "Pokémon non piangano quando perdono.$"

Route123_Text_MiuDefeat:
	.string "Miu: Oh-oh, abbiamo perso.$"

Route123_Text_MiuPostBattle:
	.string "Miu: Allenatore, i tuoi Pokémon sono\n"
	.string "forti perché siete amici.$"

Route123_Text_MiuNotEnoughMons:
	.string "Miu: Non è divertente lottare se\n"
	.string "non hai due Pokémon.$"

Route123_Text_YukiIntro:
	.string "Yuki: Pronte!\n"
	.string "Battiamo i Pokémon dell'Allenatore!$"

Route123_Text_YukiDefeat:
	.string "Yuki: Oh-oh, abbiamo perso.$"

Route123_Text_YukiPostBattle:
	.string "Yuki: Perché sei così forte?\n"
	.string "Noi non avevamo mai perso.$"

Route123_Text_YukiNotEnoughMons:
	.string "Yuki: Non è divertente lottare se\n"
	.string "non hai due Pokémon.$"

Route123_Text_KindraIntro:
	.string "Il Monte Pira…\n"
	.string "Dove riposano gli spiriti dei Pokémon…\l"
	.string "Anche i tuoi Pokémon vorranno dormire?$"

Route123_Text_KindraDefeat:
	.string "Traboccano di vitalità…$"

Route123_Text_KindraPostBattle:
	.string "Il Monte Pira…\n"
	.string "Dove riposano gli spiriti dei Pokémon…\p"
	.string "Lassù deve scorrere un potere\n"
	.string "immenso, che placa gli spiriti…$"

Route123_Text_FernandoIntro:
	.string "Ti stendo mentre suono questo\n"
	.string "pezzo a tutto volume!$"

Route123_Text_FernandoDefeat:
	.string "Ehi, aspetta!\n"
	.string "Stavo ancora suonando l'intro!$"

Route123_Text_FernandoPostBattle:
	.string "Sei solido come il rock.\n"
	.string "Vorrei scrivere una canzone su di te.$"

Route123_Text_FernandoRegister:
	.string "La prossima volta ascolta il pezzo\n"
	.string "fino in fondo, d'accordo?$"

Route123_Text_FernandoRematchIntro:
	.string "Oggi è il giorno giusto!\n"
	.string "Ti stendo prima di finire\l"
	.string "la mia canzone!$"

Route123_Text_FernandoRematchDefeat:
	.string "Ehi, aspetta!\n"
	.string "Non sono ancora arrivato al ritornello!$"

Route123_Text_FernandoPostRematch:
	.string "Pensavo che la mia musica ti avrebbe\n"
	.string "rapito al punto da farti perdere.$"

Route123_Text_DavisIntro:
	.string "Ecco il mio fantastico Pokémon\n"
	.string "Coleottero! Me l'ha preso mio fratello.$"

Route123_Text_DavisDefeat:
	.string "Uaaah!\n"
	.string "Cattivo!$"

Route123_Text_DavisPostBattle:
	.string "Non dire a mio fratello che ho perso.\n"
	.string "Deve restare un segreto!$"

Route123_Text_JazmynIntro:
	.string "Battere qualcuno che sembra forte\n"
	.string "mi darà un bel po' di fiducia!$"

Route123_Text_JazmynDefeat:
	.string "Addio fiducia…$"

Route123_Text_JazmynPostBattle:
	.string "Si dice che l'abito non faccia il monaco.\p"
	.string "Ma spesso l'apparenza non inganna…$"

Route123_Text_FrederickIntro:
	.string "Salve, ragazzo!\n"
	.string "Hai un po' di tempo per me?$"

Route123_Text_FrederickDefeat:
	.string "Ah, che ragazzo in gamba!\n"
	.string "Contribuirò alla tua paghetta.$"

Route123_Text_FrederickPostBattle:
	.string "La paghetta, dici?\n"
	.string "Non ti è bastato il premio in denaro?$"

Route123_Text_AlbertoIntro:
	.string "Te lo devo dire: i Pokémon uccello\n"
	.string "sono la mia ossessione!\p"
	.string "Gli uccelli sono fantastici!\n"
	.string "Sono i migliori!$"

Route123_Text_AlbertoDefeat:
	.string "Anche quando perdono, i Pokémon\n"
	.string "uccello sono fantastici!$"

Route123_Text_AlbertoPostBattle:
	.string "Raccolgo le piume che i Pokémon\n"
	.string "uccello perdono durante le lotte.\p"
	.string "Ci farò un cappello di piume\n"
	.string "di Pokémon uccello!$"

Route123_Text_EdIntro:
	.string "Quando non ci sono Allenatori in giro,\n"
	.string "faccio lottare i miei Pokémon tra loro.\l"
	.string "E li osservo.$"

Route123_Text_EdDefeat:
	.string "I tuoi Pokémon mi piacciono parecchio.$"

Route123_Text_EdPostBattle:
	.string "Ehehe, ti rubo qualche idea di lotta!\n"
	.string "Credo che mi renderà più bravo.$"

Route123_Text_JonasIntro:
	.string "Ti ho teso un agguato, e un Allenatore\n"
	.string "è caduto nella mia trappola!$"

Route123_Text_JonasDefeat:
	.string "Se non perdi tu, come faccio a\n"
	.string "divertirmi a giocare al ninja?$"

Route123_Text_JonasPostBattle:
	.string "La prossima volta tendo un agguato\n"
	.string "a un Allenatore dall'aria più debole.$"

Route123_Text_KayleyIntro:
	.string "Ho appena comprato questo parasole.\n"
	.string "La mia grazia è salita di un terzo!$"

Route123_Text_KayleyDefeat:
	.string "Sei più bravo di me di circa\n"
	.string "cinque volte!$"

Route123_Text_KayleyPostBattle:
	.string "Saper usare gli accessori è il segreto\n"
	.string "per avere stile.$"

Route124_Text_SpencerIntro:
	.string "Ehi, ti sei perso in mare?\p"
	.string "Se batti i miei Pokémon,\n"
	.string "posso farti da guida.$"

Route124_Text_SpencerDefeat:
	.string "Ho perso la bussola in lotta!$"

Route124_Text_SpencerPostBattle:
	.string "In mare in tanti perdono l'orientamento.\p"
	.string "Se sei uno di loro, consulta la\n"
	.string "Mappa del tuo PokéNav.\p"
	.string "E se la bussola gira all'impazzata,\n"
	.string "occhio: c'è un Varco nei paraggi!$"

Route124_Text_RolandIntro:
	.string "Hm! Tu cavalchi un Pokémon invece\n"
	.string "di nuotare con le tue forze…\p"
	.string "Che invidia!$"

Route124_Text_RolandDefeat:
	.string "Oh!\n"
	.string "Non ce la faccio…$"

Route124_Text_RolandPostBattle:
	.string "Comincio ad avere freddo…\n"
	.string "Sono in acqua da troppo tempo…\p"
	.string "Vorrei cavalcare un Pokémon come te…$"

Route124_Text_JennyIntro:
	.string "Se galleggi in mare così,\n"
	.string "i Pokémon vengono a giocare.$"

Route124_Text_JennyDefeat:
	.string "Oh, accidenti.\n"
	.string "Ho perso.$"

Route124_Text_JennyPostBattle:
	.string "Nuotando ho notato che certi Pokémon\n"
	.string "attaccano e altri stanno a guardare.\p"
	.string "Credo che anche i Pokémon abbiano\n"
	.string "un carattere tutto loro.$"

Route124_Text_JennyRegister:
	.string "È solo un capriccio, ma forse ti farò\n"
	.string "registrare il mio numero nel PokéNav.$"

Route124_Text_JennyRematchIntro:
	.string "Se galleggi in mare così,\n"
	.string "gli Allenatori ti sfidano!$"

Route124_Text_JennyRematchDefeat:
	.string "Che strano…\n"
	.string "Ho perso di nuovo…$"

Route124_Text_JennyPostRematch:
	.string "Non c'entra niente, ma forse andrò\n"
	.string "a visitare la Casa dei Trucchi.$"

Route124_Text_GraceIntro:
	.string "Nuotare comincia ad annoiarmi…\n"
	.string "Che ne dici di una lotta?$"

Route124_Text_GraceDefeat:
	.string "Non immaginavo fossi così forte!\n"
	.string "Mi hai lasciata senza fiato!$"

Route124_Text_GracePostBattle:
	.string "Tutto l'impegno che ci hai messo\n"
	.string "ti ha reso così forte, vero?$"

Route124_Text_ChadIntro:
	.string "Ehehehe… Mi immergo negli abissi\n"
	.string "per passare inosservato.\l"
	.string "Nel profondo sono imbattibile!$"

Route124_Text_ChadDefeat:
	.string "Glu, glu, glu…\n"
	.string "Sto affondando…$"

Route124_Text_ChadPostBattle:
	.string "Ho saputo da fonte sicura che qui\n"
	.string "vicino c'è un punto dove usare Sub.\p"
	.string "Mi è tornata la voglia di scendere\n"
	.string "giù in profondità…$"

Route124_Text_LilaIntro:
	.string "Lila: Uff…\p"
	.string "Sono in mezzo al mare, e con chi?\n"
	.string "Con il mio fratellino!\p"
	.string "Lottiamo, così almeno smetto\n"
	.string "di pensarci!$"

Route124_Text_LilaDefeat:
	.string "Lila: Roy! Abbiamo perso per colpa tua!\n"
	.string "Dopo facciamo i conti!$"

Route124_Text_LilaPostBattle:
	.string "Lila: Uff…\p"
	.string "Se solo accanto a me ci fosse un bel\n"
	.string "fidanzato, invece del mio fratellino…$"

Route124_Text_LilaNotEnoughMons:
	.string "Lila: Vuoi lottare contro di noi?\n"
	.string "Senza due Pokémon non se ne parla.$"

Route124_Text_RoyIntro:
	.string "Roy: Mia sorella è un asso coi Pokémon!\p"
	.string "Non metterti a piangere quando perdi!$"

Route124_Text_RoyDefeat:
	.string "Roy: Oh-oh…\n"
	.string "Mia sorella mi farà una ramanzina…$"

Route124_Text_RoyPostBattle:
	.string "Roy: Mia sorella fa paura quando\n"
	.string "si arrabbia.\p"
	.string "È per questo che non trova\n"
	.string "un fidanzato.$"

Route124_Text_LilaRoyRegister:
	.string "Roy: Lotterai ancora con noi?\n"
	.string "Però la prossima volta vacci piano, eh?$"

Route124_Text_RoyNotEnoughMons:
	.string "Roy: Volevi sfidarci?\n"
	.string "Allora porta due Pokémon.$"

Route124_Text_LilaRematchIntro:
	.string "Lila: Uff…\p"
	.string "Sono in mezzo al mare, e con chi?\n"
	.string "Con il mio fratellino!\p"
	.string "Oh, ciao! Quanto tempo! Lottiamo,\n"
	.string "così smetto di rimuginare!$"

Route124_Text_LilaRematchDefeat:
	.string "Lila: Roy!\n"
	.string "Abbiamo riperso per colpa tua!\p"
	.string "Dopo ti aspetta un bell'allenamento!$"

Route124_Text_LilaPostRematch:
	.string "Lila: Uff…\p"
	.string "Con un bel fidanzato, faremmo combo\n"
	.string "stupende e batteremmo chiunque…$"

Route124_Text_LilaRematchNotEnoughMons:
	.string "Lila: Vuoi lottare contro di noi?\n"
	.string "Senza due Pokémon non se ne parla.$"

Route124_Text_RoyRematchIntro:
	.string "Roy: Se perdiamo, sono guai per me.\n"
	.string "Stavolta do il massimo!$"

Route124_Text_RoyRematchDefeat:
	.string "Roy: Oh-oh…\n"
	.string "Mia sorella mi sgriderà di nuovo.$"

Route124_Text_RoyPostRematch:
	.string "Roy: Mia sorella fa paura quando\n"
	.string "si arrabbia.\p"
	.string "Dopo mi farà allenare un sacco\n"
	.string "con i Pokémon…$"

Route124_Text_RoyRematchNotEnoughMons:
	.string "Roy: Volevi sfidarci?\n"
	.string "Allora porta due Pokémon.$"

Route124_Text_DeclanIntro:
	.string "Eccomi qui, a nuotare tutto solo\n"
	.string "in questo mare vasto e bellissimo.\p"
	.string "Non ci sono altre parole per dirlo.\n"
	.string "È patetico!$"

Route124_Text_DeclanDefeat:
	.string "Che tristezza…\n"
	.string "Profonda come l'oceano…$"

Route124_Text_DeclanPostBattle:
	.string "Dovrei attaccare bottone con qualche\n"
	.string "Nuotatrice e invitarla a nuotare con me.$"

Route124_Text_IsabellaIntro:
	.string "Io nuoto con le mie braccia! Non perdo\n"
	.string "contro chi si fa scarrozzare in Surf!$"

Route124_Text_IsabellaDefeat:
	.string "È solo sudore negli occhi!\n"
	.string "Non sto piangendo!$"

Route124_Text_IsabellaPostBattle:
	.string "Da queste parti si trovano dei\n"
	.string "cocci colorati bellissimi.\p"
	.string "Chissà, magari li ha sputati fuori\n"
	.string "qualche Varco…$"

Route125_Text_NolenIntro:
	.string "Ti ho sentito arrivare, così sono\n"
	.string "rimasto qui ad aspettarti!$"

Route125_Text_NolenDefeat:
	.string "Mi arrendo!$"

Route125_Text_NolenPostBattle:
	.string "In acqua il suono viaggia più veloce\n"
	.string "che nell'aria. Lo sapevi?$"

Route125_Text_StanIntro:
	.string "Ehilà!\n"
	.string "Guarda che Pokémon favolosi ho!$"

Route125_Text_StanDefeat:
	.string "Che naufragio…$"

Route125_Text_StanPostBattle:
	.string "Sono rimasto stregato dal fascino di\n"
	.string "Horsea, così mi sono messo a nuotare.$"

Route125_Text_TanyaIntro:
	.string "Sono stanca di nuotare.\n"
	.string "Ti va di lottare con me?$"

Route125_Text_TanyaDefeat:
	.string "Sei troppo forte!$"

Route125_Text_TanyaPostBattle:
	.string "Uff…\n"
	.string "Da che parte è Verdeazzupoli?$"

Route125_Text_SharonIntro:
	.string "Ti va di affrontare i Pokémon\n"
	.string "di tipo Acqua che ho cresciuto io?$"

Route125_Text_SharonDefeat:
	.string "Ho perso la presa…$"

Route125_Text_SharonPostBattle:
	.string "Che potenza… Tu fai sul serio.\n"
	.string "Sono senza parole!$"

Route125_Text_ErnestIntro:
	.string "Ohè! Sono un Marinaio tutto muscoli!\n"
	.string "Ho sfidato tutti i mari di Hoenn!$"

Route125_Text_ErnestDefeat:
	.string "Grrrooaaar!\n"
	.string "Non ce l'ho fatta!$"

Route125_Text_ErnestPostBattle:
	.string "Dentro la Grotta Ondosa la marea\n"
	.string "sale e scende.\p"
	.string "A proposito, tra alta e bassa marea\n"
	.string "passano circa sei ore. Lo sapevi?$"

Route125_Text_ErnestRegister:
	.string "Registrami nel tuo PokéNav e ti\n"
	.string "racconterò una cosa utile.$"

Route125_Text_ErnestRematchIntro:
	.string "È ora che mi prenda la rivincita\n"
	.string "su di te! Forza, si lotta!$"

Route125_Text_ErnestRematchDefeat:
	.string "Non ce l'ho fatta!\n"
	.string "Proprio non ce l'ho fatta!$"

Route125_Text_ErnestRematchPostBattle:
	.string "La Grotta Ondosa…\p"
	.string "Ci sono punti che puoi raggiungere\n"
	.string "oppure no, a seconda dell'alta\l"
	.string "o della bassa marea.\p"
	.string "A proposito, tra alta e bassa marea\n"
	.string "passano circa sei ore. Non scordarlo!$"

Route125_Text_KimIntro:
	.string "Kim: Mi hanno detto che nella Grotta\n"
	.string "Ondosa vive un vecchietto buffo.\l"
	.string "Anche tu vai a trovarlo?$"

Route125_Text_KimDefeat:
	.string "Kim: Pensavo che avremmo vinto.$"

Route125_Text_KimPostBattle:
	.string "Kim: Nella Grotta Ondosa vive un\n"
	.string "vecchietto buffo, vero?\p"
	.string "Andiamo a trovarlo, Iris!$"

Route125_Text_KimNotEnoughMons:
	.string "Kim: No, no, no! Servono due Pokémon,\n"
	.string "altrimenti non se ne fa niente!$"

Route125_Text_IrisIntro:
	.string "Iris: Kim, mi dici cosa stiamo\n"
	.string "cercando qui in mezzo al mare?$"

Route125_Text_IrisDefeat:
	.string "Iris: Oh, ci siamo andate vicine.$"

Route125_Text_IrisPostBattle:
	.string "Iris: Kim, entriamo davvero nella\n"
	.string "Grotta Ondosa?\l"
	.string "Ci bagneremo tutte!$"

Route125_Text_IrisNotEnoughMons:
	.string "Iris: Oh, noi non potremmo mai fare\n"
	.string "una lotta due contro uno.$"

Route125_Text_PresleyIntro:
	.string "Perché mai un Ornitologo come me\n"
	.string "verrebbe fin qui in mezzo al mare?$"

Route125_Text_PresleyDefeat:
	.string "Va bene.\n"
	.string "Ti dico perché sono qui.$"

Route125_Text_PresleyPostBattle:
	.string "Ho chiuso un messaggio in bottiglia\n"
	.string "e l'ho affidato alle onde.\p"
	.string "Sono sicuro che lo troverà\n"
	.string "una bella Nuotatrice!$"

Route125_Text_AuronIntro:
	.string "Ehi! Sei stato tu a buttare\n"
	.string "rifiuti in mare?$"

Route125_Text_AuronDefeat:
	.string "Ah, allora non eri tu a sporcare\n"
	.string "il mare. Chiedo scusa.$"

Route125_Text_AuronPostBattle:
	.string "Poco fa ho visto una brutta bottiglia\n"
	.string "che galleggiava tra le onde.\p"
	.string "Mi fa infuriare che qualcuno\n"
	.string "inquini il mare!$"

Route126_Text_BarryIntro:
	.string "Il nuoto allena tutto il corpo!\n"
	.string "Ti rimetterai in forma!$"

Route126_Text_BarryDefeat:
	.string "Lo ammetto!\n"
	.string "Hai vinto tu!$"

Route126_Text_BarryPostBattle:
	.string "Grazie alle mie nuotate quotidiane…\n"
	.string "Guarda! Ammira questo fisico!$"

Route126_Text_DeanIntro:
	.string "Quell'enorme montagna di roccia\n"
	.string "bianca è Ceneride.$"

Route126_Text_DeanDefeat:
	.string "Sono stato battuto?!$"

Route126_Text_DeanPostBattle:
	.string "Non riesco a trovare l'ingresso di\n"
	.string "Ceneride. Dove sarà?$"

Route126_Text_NikkiIntro:
	.string "Ufufufufu!\n"
	.string "Sono una sirena!$"

Route126_Text_NikkiDefeat:
	.string "Il mio sogno è scoppiato come una bolla!\n"
	.string "Blub, blub, blub…$"

Route126_Text_NikkiPostBattle:
	.string "Mi hai stracciata… Vorrei sparire\n"
	.string "in un'onda di disperazione…$"

Route126_Text_BrendaIntro:
	.string "Ciao, piccolino!\n"
	.string "Ti va una lotta con me?$"

Route126_Text_BrendaDefeat:
	.string "Oh, nooooo!$"

Route126_Text_BrendaPostBattle:
	.string "Adoro sguazzare in mare così,\n"
	.string "insieme ai miei Pokémon!$"

Route126_Text_PabloIntro:
	.string "Guarda che fisico scolpito!\n"
	.string "Sono più definito di un Cinturanera!$"

Route126_Text_PabloDefeat:
	.string "Ops! Troppo forte!\n"
	.string "Niente male! Davvero niente male!$"

Route126_Text_PabloPostBattle:
	.string "Perdere con te mi ha dato la carica!\n"
	.string "Allenerò me e i Pokémon ancora di più!$"

Route126_Text_PabloRegister:
	.string "Sì, sei davvero niente male!\n"
	.string "Vorrei conoscerti meglio!$"

Route126_Text_PabloRematchIntro:
	.string "Guarda che corpo stupendo!\n"
	.string "Ho più linea di un Nuotatore!$"

Route126_Text_PabloRematchDefeat:
	.string "Ops! Davvero troppo forte!\n"
	.string "Niente male! Davvero niente male!$"

Route126_Text_PabloPostRematch:
	.string "Mi allenerò ancora di più!\n"
	.string "Sei una motivazione fantastica!\l"
	.string "Devi tornare a trovarmi!$"

Route126_Text_LeonardoIntro:
	.string "L'anno scorso non sapevo nemmeno\n"
	.string "nuotare, ora sono un buon Nuotatore.\p"
	.string "Mi sento capace di tutto!$"

Route126_Text_LeonardoDefeat:
	.string "Accidenti, mi sono montato la testa\n"
	.string "e non è servito a niente.$"

Route126_Text_LeonardoPostBattle:
	.string "Se ti eserciti in qualcosa,\n"
	.string "prima o poi diventi bravo.\p"
	.string "Sei giovane: non aver paura di\n"
	.string "provare un po' di tutto!$"

Route126_Text_IsobelIntro:
	.string "Quando l'acqua di mare ti entra nel\n"
	.string "naso, non è una sensazione orribile?$"

Route126_Text_IsobelDefeat:
	.string "Ack! Ma tu…\n"
	.string "Glub!$"

Route126_Text_IsobelPostBattle:
	.string "Uh, ho bevuto un sorso d'acqua!\n"
	.string "È amara! È salata!!$"

Route126_Text_SiennaIntro:
	.string "Ci sto mettendo tutto\n"
	.string "il cuore!$"

Route126_Text_SiennaDefeat:
	.string "Tu ci hai messo più cuore!$"

Route126_Text_SiennaPostBattle:
	.string "Ora devo rinfrescarmi…\n"
	.string "Credo che farò un tuffo.$"

Route127_Text_CamdenIntro:
	.string "Te lo leggo in faccia.\n"
	.string "Vuoi sfidarmi.$"

Route127_Text_CamdenDefeat:
	.string "Uauauauaua…$"

Route127_Text_CamdenPostBattle:
	.string "Una lotta ben giocata mi lascia\n"
	.string "rigenerato e sereno.$"

Route127_Text_DonnyIntro:
	.string "Hai un rivale contro cui proprio\n"
	.string "odi perdere?$"

Route127_Text_DonnyDefeat:
	.string "Arrrgh!\n"
	.string "Odio perdere!$"

Route127_Text_DonnyPostBattle:
	.string "Se hai un rivale, non senti il\n"
	.string "bisogno di migliorare\l"
	.string "sempre di più?$"

Route127_Text_JonahIntro:
	.string "Con la pesca ho raggiunto uno stato\n"
	.string "di quiete assoluta…\p"
	.string "Permettimi di dimostrartelo…$"

Route127_Text_JonahDefeat:
	.string "Anche se ho perso, il mio cuore\n"
	.string "resta calmo…$"

Route127_Text_JonahPostBattle:
	.string "Non importa se non prendo nulla.\n"
	.string "La lenza resta in acqua…$"

Route127_Text_HenryIntro:
	.string "Ops! Non dirmi che ho agganciato\n"
	.string "un Pokémon che usa Surf?$"

Route127_Text_HenryDefeat:
	.string "Non riesco a starti dietro!$"

Route127_Text_HenryPostBattle:
	.string "Sarebbero guai se abboccasse\n"
	.string "un Pokémon forte come il tuo!$"

Route127_Text_RogerIntro:
	.string "Ehilà! Ecco una sfida tra un fan dei\n"
	.string "Pokémon e un patito della pesca!$"

Route127_Text_RogerDefeat:
	.string "No! La mia lenza è tutta aggrovigliata!\n"
	.string "La festa è finita!$"

Route127_Text_RogerPostBattle:
	.string "La mia lenza si è messa a ballare!\n"
	.string "Il tango del groviglio! Ahahah, che nodo!$"

Route127_Text_AidanIntro:
	.string "I Pokémon uccello hanno una vista\n"
	.string "eccezionale. Vedono le prede dall'alto.$"

Route127_Text_AidanDefeat:
	.string "Uff… Mi arrendo.$"

Route127_Text_AidanPostBattle:
	.string "Nel mare qui intorno ci sono tanti\n"
	.string "punti dove usare Sub.\p"
	.string "Dal cielo si vedono facilmente,\n"
	.string "perché l'acqua è più scura.$"

Route127_Text_KojiIntro:
	.string "Corri a piedi nudi.\n"
	.string "Così si rinforzano le piante dei piedi!$"

Route127_Text_KojiDefeat:
	.string "Ahia!\n"
	.string "Ho un sassolino sotto l'unghia!$"

Route127_Text_KojiPostBattle:
	.string "Andare scalzi è fantastico.\n"
	.string "Però le tue Scarpe da Corsa spaccano!$"

Route127_Text_KojiRegister:
	.string "Ecco cosa faccio con chi mi batte!\n"
	.string "Spero di rifarlo presto.$"

Route127_Text_KojiRematchIntro:
	.string "Corro ancora scalzo tutti i giorni.\n"
	.string "Ho le piante dei piedi d'acciaio!$"

Route127_Text_KojiRematchDefeat:
	.string "Ahia!\n"
	.string "Mi si sono piantati i sassi nei piedi!$"

Route127_Text_KojiPostRematch:
	.string "Vuoi provare a stare scalzo un po'?\n"
	.string "Così mi provo le tue Scarpe da Corsa!$"

Route127_Text_AthenaIntro:
	.string "Facciamo una lotta lenta\n"
	.string "e metodica.$"

Route127_Text_AthenaDefeat:
	.string "Non mi hai dato il tempo di\n"
	.string "elaborare una strategia.$"

Route127_Text_AthenaPostBattle:
	.string "Circondata dal blu del mare e del\n"
	.string "cielo, sembra che il tempo rallenti.$"

Route128_Text_IsaiahIntro:
	.string "Iridopoli è ancora\n"
	.string "lontanissima…$"

Route128_Text_IsaiahDefeat:
	.string "Anche la mia prima vittoria sembra\n"
	.string "lontanissima…$"

Route128_Text_IsaiahPostBattle:
	.string "Ho passato la vita a perdere,\n"
	.string "ma non mi arrenderò mai!$"

Route128_Text_IsaiahRegister:
	.string "So di non essere bravo adesso, ma\n"
	.string "credo che prima o poi vincerò.\p"
	.string "Registrami nel tuo PokéNav, per favore.$"

Route128_Text_IsaiahRematchIntro:
	.string "Mi sento ancora in forma. Continuerò\n"
	.string "a nuotare fino a Iridopoli.$"

Route128_Text_IsaiahRematchDefeat:
	.string "La mia prima vittoria non arriva mai…$"

Route128_Text_IsaiahPostRematch:
	.string "Prima o poi arriverò a Iridopoli,\n"
	.string "e lì, prima o poi, vincerò…$"

Route128_Text_KatelynIntro:
	.string "In un triathlon devi nuotare, andare\n"
	.string "in bici e poi correre una maratona.\p"
	.string "È una gara massacrante fatta\n"
	.string "di tre prove.$"

Route128_Text_KatelynDefeat:
	.string "Anche le lotte Pokémon sono dure…$"

Route128_Text_KatelynPostBattle:
	.string "Ora tocca alla Bici, ma…\n"
	.string "sto per gettare la spugna…$"

Route128_Text_KatelynRegister:
	.string "Beh, tanto vale prenderla bene.\n"
	.string "Prima o poi voglio la rivincita.$"

Route128_Text_KatelynRematchIntro:
	.string "Il triathlon è lungo. Ma anche la\n"
	.string "strada per diventare Campione\l"
	.string "è lunga e massacrante.$"

Route128_Text_KatelynRematchDefeat:
	.string "Le lotte Pokémon sono davvero dure\n"
	.string "e spietate…$"

Route128_Text_KatelynPostRematch:
	.string "Dovresti prepararti bene per le\n"
	.string "sfide della Via Vittoria.$"

Route128_Text_AlexaIntro:
	.string "Abbiamo lavorato tanto per sfidare\n"
	.string "la Lega Pokémon…\p"
	.string "Non possiamo permetterci di perdere!$"

Route128_Text_AlexaDefeat:
	.string "Oh!\n"
	.string "Com'è potuto succedere?!$"

Route128_Text_AlexaPostBattle:
	.string "Dopo tutta la fatica per arrivare qui,\n"
	.string "non mi arrendo per una sconfitta.$"

Route128_Text_RubenIntro:
	.string "Non esiste Allenatore più forte di me!$"

Route128_Text_RubenDefeat:
	.string "Non può essere!$"

Route128_Text_RubenPostBattle:
	.string "Forse non esiste Allenatore più forte\n"
	.string "di te!$"

Route128_Text_WayneIntro:
	.string "Voglio andare a Iridopoli, così ho\n"
	.string "catturato un Pokémon che conosce\l"
	.string "Cascata, per risalire le cascate.$"

Route128_Text_WayneDefeat:
	.string "Che delusione a cascata!$"

Route128_Text_WaynePostBattle:
	.string "Uffa, che sfortuna!\p"
	.string "Il mio Pokémon conosce Cascata, ma\n"
	.string "non ho la Medaglia di Ceneride!$"

Route128_Text_HarrisonIntro:
	.string "Sembri proprio un osso duro.\n"
	.string "Chissà se riuscirò a vincere?$"

Route128_Text_HarrisonDefeat:
	.string "Ahi!\n"
	.string "Vincere era impossibile, temo.$"

Route128_Text_HarrisonPostBattle:
	.string "Intorno a Iridopoli ci sono un sacco\n"
	.string "di Allenatori fortissimi.\p"
	.string "Pensi che io non sia\n"
	.string "alla loro altezza?$"

Route128_Text_CarleeIntro:
	.string "Il sole picchia più forte\n"
	.string "da queste parti.$"

Route128_Text_CarleeDefeat:
	.string "Non vedevo bene per colpa del\n"
	.string "riverbero del sole.$"

Route128_Text_CarleePostBattle:
	.string "Dovrei tornare presto.\n"
	.string "Devo rimettermi la crema solare.$"

Route129_Text_ChaseIntro:
	.string "È il mio primo triathlon.\n"
	.string "Sono tesissimo e nervoso!$"

Route129_Text_ChaseDefeat:
	.string "Uaaaaargh!\n"
	.string "Non sono riuscito a vincere!$"

Route129_Text_ChasePostBattle:
	.string "Se sono così teso, non riuscirò\n"
	.string "a dare il massimo.$"

Route129_Text_AllisonIntro:
	.string "Sono nel bel mezzo di un triathlon,\n"
	.string "ma certo, perché non lottare?$"

Route129_Text_AllisonDefeat:
	.string "Ero sicura di vincere!$"

Route129_Text_AllisonPostBattle:
	.string "Sai qual è la cosa più bella\n"
	.string "dei triathlon?\p"
	.string "Mettere alla prova i limiti della\n"
	.string "propria forza e resistenza contro\l"
	.string "Madre Natura!$"

Route129_Text_ReedIntro:
	.string "Ehi, ehi, ehi!\n"
	.string "Diamoci una mossa!$"

Route129_Text_ReedDefeat:
	.string "Battuto, sono battuto.\n"
	.string "Fine, basta!$"

Route129_Text_ReedPostBattle:
	.string "Per chi perde non c'è niente.\n"
	.string "Meglio che me ne torni a casa.$"

Route129_Text_TishaIntro:
	.string "Che fretta c'è?\n"
	.string "Prendiamocela con calma.$"

Route129_Text_TishaDefeat:
	.string "Oh, cielo.\n"
	.string "Volevo rilassarmi ancora un po'…$"

Route129_Text_TishaPostBattle:
	.string "Non odi fare errori quando\n"
	.string "vai di fretta?\p"
	.string "Per questo cerco di fare tutto\n"
	.string "con calma.$"

Route129_Text_ClarenceIntro:
	.string "Il surf non è facile come sembra,\n"
	.string "non è vero?$"

Route129_Text_ClarenceDefeat:
	.string "Vincere non è affatto facile.$"

Route129_Text_ClarencePostBattle:
	.string "Punti alla Lega Pokémon?\n"
	.string "Non mollare!$"

Route130_Text_RodneyIntro:
	.string "Che sorpresa! Non pensavo di trovare\n"
	.string "un Allenatore in mezzo al mare.\p"
	.string "Direi che dobbiamo lottare!$"

Route130_Text_RodneyDefeat:
	.string "Questo ragazzo è fortissimo…$"

Route130_Text_RodneyPostBattle:
	.string "Hai lo sguardo di chi ha affrontato\n"
	.string "sfide durissime e le ha vinte.\l"
	.string "Ti si addice!$"

Route130_Text_KatieIntro:
	.string "Nel profondo mare blu,\n"
	.string "il mio cuore infranto trova\l"
	.string "conforto tra le onde.$"

Route130_Text_KatieDefeat:
	.string "Come il vasto mare blu,\n"
	.string "i mondi dei Pokémon hanno\l"
	.string "abissi senza fine.$"

Route130_Text_KatiePostBattle:
	.string "I bambini di tutto il mondo\n"
	.string "sognano di diventare un giorno\l"
	.string "Campioni della Lega Pokémon.$"

Route130_Text_SantiagoIntro:
	.string "Galleggiare in mare aperto così…\n"
	.string "Che pace.$"

Route130_Text_SantiagoDefeat:
	.string "Dovevo essere un po' meno pacifico!$"

Route130_Text_SantiagoPostBattle:
	.string "Nuotare e lottare così…\n"
	.string "Sono proprio un tipo felice…$"

Route131_Text_RichardIntro:
	.string "Il mare brulica di Pokémon.\n"
	.string "Nuotare non è facile, te lo dico io.$"

Route131_Text_RichardDefeat:
	.string "I Pokémon cresciuti dagli Allenatori\n"
	.string "sono davvero tosti…$"

Route131_Text_RichardPostBattle:
	.string "Uff… Uff…\n"
	.string "Sono a pezzi…\p"
	.string "Andare è facile. La parte difficile\n"
	.string "è tornare indietro.\p"
	.string "Mi resterà abbastanza fiato per\n"
	.string "il viaggio di ritorno?$"

Route131_Text_HermanIntro:
	.string "Il mare… Il mare… Il mare…\n"
	.string "Mare a perdita d'occhio!\l"
	.string "Sono stufo marcio del mare!$"

Route131_Text_HermanDefeat:
	.string "Puah!$"

Route131_Text_HermanPostBattle:
	.string "Stufo del mare sono, ma nuotar devo.\p"
	.string "Sono nato per nuotare!\n"
	.string "Ce l'ho nel sangue.$"

Route131_Text_SusieIntro:
	.string "Ehi, tesoro, aspetta!\n"
	.string "Io e te dobbiamo proprio lottare!$"

Route131_Text_SusieDefeat:
	.string "Sei più tosto di quanto sembri!$"

Route131_Text_SusiePostBattle:
	.string "Hai visto quel tizio laggiù che si\n"
	.string "lamenta di essere stufo del mare?\p"
	.string "Sono tutte chiacchiere.\n"
	.string "È perdutamente innamorato del mare!$"

Route131_Text_KaraIntro:
	.string "Perché ai ragazzi piacciono tanto\n"
	.string "i costumi da bagno?\p"
	.string "Mi fissano tutti!$"

Route131_Text_KaraDefeat:
	.string "Aiuto, non tocco più!$"

Route131_Text_KaraPostBattle:
	.string "Forse non è il costume ad attirare\n"
	.string "gli sguardi. Sarà la mia bellezza!$"

Route131_Text_ReliIntro:
	.string "Reli: Io e mio fratello lotteremo\n"
	.string "insieme contro di te!$"

Route131_Text_ReliDefeat:
	.string "Reli: Neanche lottando insieme\n"
	.string "siamo riusciti a vincere…$"

Route131_Text_ReliPostBattle:
	.string "Reli: Noi di Orocea cresciamo con\n"
	.string "il mare e con i Pokémon fin da\l"
	.string "quando nasciamo.\p"
	.string "E adesso anche con quelli arrivati\n"
	.string "dai Varchi. Più siamo, meglio è!$"

Route131_Text_ReliNotEnoughMons:
	.string "Reli: Non hai due Pokémon?\n"
	.string "Allora non ci divertiremmo a lottare.$"

Route131_Text_IanIntro:
	.string "Ian: Ce la metto tutta insieme\n"
	.string "alla mia sorellona!$"

Route131_Text_IanDefeat:
	.string "Ian: Ce l'ho messa tutta con lei,\n"
	.string "ma non abbiamo vinto lo stesso…$"

Route131_Text_IanPostBattle:
	.string "Ian: Lo sai che Orocea è\n"
	.string "una città galleggiante?\p"
	.string "Quindi, ovunque ci sia il mare,\n"
	.string "lì c'è un pezzetto di Orocea!$"

Route131_Text_IanNotEnoughMons:
	.string "Ian: Se hai due Pokémon,\n"
	.string "ti sfidiamo!$"

Route131_Text_TaliaIntro:
	.string "Se riesci a battermi, ti darò\n"
	.string "un'informazione preziosa!$"

Route131_Text_TaliaDefeat:
	.string "Eh?\n"
	.string "Ho perso?$"

Route131_Text_TaliaPostBattle:
	.string "Qui vicino c'è un posto strano:\n"
	.string "una torre altissima in mezzo al mare.\p"
	.string "Di notte, sopra la cima, brilla una\n"
	.string "luce sottile, come un'aurora.\l"
	.string "Perché non vai a dare un'occhiata?$"

Route131_Text_KevinIntro:
	.string "Noi di Orocea siamo gente\n"
	.string "tranquilla.\p"
	.string "Non ci arrabbiamo mai.\n"
	.string "Io per primo.$"

Route131_Text_KevinDefeat:
	.string "Ops!$"

Route131_Text_KevinPostBattle:
	.string "Tsk! …Ah, no, aspetta.\n"
	.string "Non sono arrabbiato. Davvero!\p"
	.string "Però, accidenti, sei forte!\n"
	.string "Ahahah!$"

Route132_Text_GilbertIntro:
	.string "Da piccolo mi prendevo sempre il\n"
	.string "raffreddore, ma da quando nuoto\l"
	.string "sono in formissima.$"

Route132_Text_GilbertDefeat:
	.string "Mi serve più energia…$"

Route132_Text_GilbertPostBattle:
	.string "Gli Allenatori girano per prati e\n"
	.string "montagne: devono essere in forma!$"

Route132_Text_DanaIntro:
	.string "Cerco di non nuotare dove le\n"
	.string "correnti sono troppo forti.$"

Route132_Text_DanaDefeat:
	.string "Oh, no, ti prego!$"

Route132_Text_DanaPostBattle:
	.string "Se la corrente mi trascina via,\n"
	.string "perdo del tutto l'orientamento…$"

Route132_Text_RonaldIntro:
	.string "Vincere o perdere? Non lo sai\n"
	.string "finché non getti l'amo!$"

Route132_Text_RonaldDefeat:
	.string "Uaaah!\n"
	.string "Sono colato a picco!$"

Route132_Text_RonaldPostBattle:
	.string "Non lotto mai quando so di vincere.\n"
	.string "Mi piacciono le sfide in bilico, tese\l"
	.string "come una lenza con un pesce grosso!$"

Route132_Text_KiyoIntro:
	.string "Medito sui Pokémon 24 ore al giorno.\n"
	.string "Come potresti mai battermi?$"

Route132_Text_KiyoDefeat:
	.string "Ho perso.\n"
	.string "Accetto la sconfitta.$"

Route132_Text_KiyoPostBattle:
	.string "Ugh…\n"
	.string "Sei un fanatico dei Pokémon, vero?\p"
	.string "Anche tu ci mediti sopra 24 ore\n"
	.string "al giorno, non è così?$"

Route132_Text_MakaylaIntro:
	.string "Sto sempre con mio marito,\n"
	.string "ma so vincere anche senza di lui.$"

Route132_Text_MakaylaDefeat:
	.string "Oh, non sono stata all'altezza.$"

Route132_Text_MakaylaPostBattle:
	.string "Quel ragazzo laggiù è identico a\n"
	.string "mio marito da giovane.\p"
	.string "Mi fa arrossire!$"

Route132_Text_JonathanIntro:
	.string "Qualcuno mi sta fissando da un po'.\n"
	.string "Eri tu?$"

Route132_Text_JonathanDefeat:
	.string "Wow!\n"
	.string "Che forza, niente da dire!$"

Route132_Text_JonathanPostBattle:
	.string "Non riesco a togliermi di dosso\n"
	.string "la sensazione di essere osservato.\p"
	.string "Non riesco a concentrarmi!$"

Route132_Text_PaxtonIntro:
	.string "Dove sarà finita mia moglie?\n"
	.string "Siamo sempre insieme.\l"
	.string "Chissà se so vincere da solo.$"

Route132_Text_PaxtonDefeat:
	.string "Ah, a quanto pare da solo non ce\n"
	.string "l'ho fatta, dopotutto.$"

Route132_Text_PaxtonPostBattle:
	.string "Mia moglie mi starà cercando.\n"
	.string "Meglio che vada subito da lei.$"

Route132_Text_DarcyIntro:
	.string "Mi piaceva allenarmi qui da sola.\n"
	.string "Che seccatura, tutta questa gente!$"

Route132_Text_DarcyDefeat:
	.string "E va bene! Non mi lamenterò più\n"
	.string "della gente che viene qui.$"

Route132_Text_DarcyPostBattle:
	.string "Magari posso fare coppia con quel\n"
	.string "signore e sfidare l'altra squadra.$"

Route133_Text_FranklinIntro:
	.string "Anche tu portato qui dalle correnti?\n"
	.string "Dev'essere il destino.\l"
	.string "Lottiamo!$"

Route133_Text_FranklinDefeat:
	.string "Forte!\n"
	.string "Troppo forte!$"

Route133_Text_FranklinPostBattle:
	.string "Proprio a me doveva capitare un\n"
	.string "Allenatore così forte alla deriva…\l"
	.string "Sarò stregato…$"

Route133_Text_DebraIntro:
	.string "Ho avuto una vita di sventure…\n"
	.string "Sono naufragata, e la corrente\l"
	.string "mi ha portata fin qui…$"

Route133_Text_DebraDefeat:
	.string "Un'altra sconfitta…$"

Route133_Text_DebraPostBattle:
	.string "Una vita alla deriva…\n"
	.string "Non ne posso più!$"

Route133_Text_LindaIntro:
	.string "Benvenuto!\n"
	.string "Ti stavo aspettando!$"

Route133_Text_LindaDefeat:
	.string "No! Ti prego!$"

Route133_Text_LindaPostBattle:
	.string "Un Allenatore così giovane e forte…\n"
	.string "Che nervi!$"

Route133_Text_WarrenIntro:
	.string "Voglio vincere come tutti, ma non\n"
	.string "allenerò i Pokémon come tutti.$"

Route133_Text_WarrenDefeat:
	.string "Accidenti!\n"
	.string "Il mio metodo è ancora troppo molle!$"

Route133_Text_WarrenPostBattle:
	.string "È molto più divertente fare a modo\n"
	.string "mio che essere come tutti gli altri.\l"
	.string "Mi sembra ovvio, no?$"

Route133_Text_BeckIntro:
	.string "Sono arrivato fin qui in volo con\n"
	.string "i miei Pokémon uccello.$"

Route133_Text_BeckDefeat:
	.string "Tu…\n"
	.string "Sei incredibilmente in gamba!$"

Route133_Text_BeckPostBattle:
	.string "Vorrei tornare a Forestopoli, ma\n"
	.string "mi sono affezionato a questo posto.$"

Route133_Text_MollieIntro:
	.string "Avrò lottato migliaia di volte.\n"
	.string "Ho perso il conto.$"

Route133_Text_MollieDefeat:
	.string "Avrò anche perso migliaia di volte,\n"
	.string "ma una sconfitta brucia sempre.$"

Route133_Text_MolliePostBattle:
	.string "Non mollare, giovanotto. Così un\n"
	.string "giorno sarai come me e mio marito.$"

Route133_Text_ConorIntro:
	.string "I giovani si lasciano trascinare\n"
	.string "dalla corrente. Sono senza rotta.$"

Route133_Text_ConorDefeat:
	.string "Tu hai una rotta ben precisa.$"

Route133_Text_ConorPostBattle:
	.string "Non lasciarti portare fuori strada.\n"
	.string "Non perdere la rotta crescendo.$"

Route134_Text_JackIntro:
	.string "Anche i Pokémon che sanno nuotare\n"
	.string "vengono trascinati dalle correnti.$"

Route134_Text_JackDefeat:
	.string "Aaaaaaah!$"

Route134_Text_JackPostBattle:
	.string "Secondo me ai Pokémon piacciono le\n"
	.string "correnti impetuose di queste parti.$"

Route134_Text_LaurelIntro:
	.string "I miei Luvdisc cercano una lotta\n"
	.string "divertente. Ti unisci a noi?$"

Route134_Text_LaurelDefeat:
	.string "Oh-oh!$"

Route134_Text_LaurelPostBattle:
	.string "C'è un collezionista che va matto\n"
	.string "per le Squame Cuore dei Luvdisc.$"

Route134_Text_AlexIntro:
	.string "Bene, bene! Basta riposo, ragazzi!\n"
	.string "È ora di lottare!$"

Route134_Text_AlexDefeat:
	.string "Spennato di nuovo…$"

Route134_Text_AlexPostBattle:
	.string "I miei Pokémon uccello si stancano\n"
	.string "presto dopo un lungo volo…$"

Route134_Text_HitoshiIntro:
	.string "Sei un Allenatore di Pokémon.\n"
	.string "Niente parole. Lottiamo.$"

Route134_Text_HitoshiDefeat:
	.string "… … … … … …\n"
	.string "… … … … … …$"

Route134_Text_HitoshiPostBattle:
	.string "Sono stato io a sfidarti, eppure\n"
	.string "ho perso. Che vergogna…$"

Route134_Text_AaronIntro:
	.string "Le maree selvagge di queste acque\n"
	.string "ci rendono più forti che mai.$"

Route134_Text_AaronDefeat:
	.string "Accetto la sconfitta di buon grado.$"

Route134_Text_AaronPostBattle:
	.string "Torneremo ad allenarci alle\n"
	.string "Cascate Meteora.\p"
	.string "Dicono che lì, tremila anni fa,\n"
	.string "sia piovuto un pezzo di cielo.\p"
	.string "Se vuoi, vacci anche tu.\n"
	.string "Ti temprerà di sicuro!$"

Route134_Text_KelvinIntro:
	.string "L-la nostra barca!\n"
	.string "La marea se l'è portata via!$"

Route134_Text_KelvinDefeat:
	.string "Aaaaah!\n"
	.string "Basta, ti prego! Basta!$"

Route134_Text_KelvinPostBattle:
	.string "Se non possiamo usare Surf, come\n"
	.string "facciamo a tornare a casa?\p"
	.string "Lo so, anche un Pokémon esausto può\n"
	.string "usare Surf, ma mi sembra crudele.$"

Route134_Text_MarleyIntro:
	.string "I tuoi Pokémon sapranno schivare\n"
	.string "i nostri attacchi fulminei?$"

Route134_Text_MarleyDefeat:
	.string "Non conoscevo questa tecnica!\n"
	.string "Ci hai battuti su tutta la linea.$"

Route134_Text_MarleyPostBattle:
	.string "La mia passione per la velocità è\n"
	.string "intatta. Mi impegnerò di più.$"

Route134_Text_ReynaIntro:
	.string "I miei Pokémon non si lasciano\n"
	.string "abbattere facilmente!$"

Route134_Text_ReynaDefeat:
	.string "Stai scherzando?!\n"
	.string "Spiegami come ho fatto a perdere!$"

Route134_Text_ReynaPostBattle:
	.string "Ahah!\n"
	.string "Hai vinto, poco da dire!\p"
	.string "Risalirò la china sfidando tutti gli\n"
	.string "Allenatori che incontro!$"

Route134_Text_HudsonIntro:
	.string "Ehi, hai visto un altro marinaio\n"
	.string "da queste parti?$"

Route134_Text_HudsonDefeat:
	.string "Questa sì che è bella!$"

Route134_Text_HudsonPostBattle:
	.string "La nostra barca è andata alla deriva.\p"
	.string "Il mio compare è un tipo timoroso,\n"
	.string "sono preoccupato per lui.$"

VSSeeker_Text_BatteryNotChargedNeedXSteps::
	.string "La batteria non è abbastanza carica.\p"
	.string "Passi necessari per ricaricarla\n"
	.string "del tutto: {STR_VAR_1}{PAUSE_UNTIL_PRESS}$"

VSSeeker_Text_NoTrainersWithinRange::
	.string "Non ci sono Allenatori nei paraggi\n"
	.string "pronti a lottare…\p"
	.string "Il Cercasfide si è spento.{PAUSE_UNTIL_PRESS}$"

VSSeeker_Text_TrainersNotReady::
	.string "Gli altri Allenatori non sembrano\n"
	.string "ancora pronti a lottare.\p"
	.string "Meglio aspettare un po'.{PAUSE_UNTIL_PRESS}$"
