LilycoveCity_ContestLobby_Text_InterviewRequest:
	.string "Oh, ciao! Hai appena partecipato\n"
	.string "a una Gara Pokémon, vero?\l"
	.string "Si capisce subito dai tuoi Pokémon!\p"
	.string "Lavoro per la TV: sto preparando\n"
	.string "un servizio sulle Gare Pokémon.\p"
	.string "Ti andrebbe di rispondere a qualche\n"
	.string "domanda?$"

LilycoveCity_ContestLobby_Text_DescribeContest:
	.string "Davvero? Che gentile!\n"
	.string "Grazie mille.\p"
	.string "In poche parole, come descriveresti\n"
	.string "la Gara a cui hai appena partecipato?$"

LilycoveCity_ContestLobby_Text_WhatImageWhenYouHearX:
	.string "Capisco!\n"
	.string "Un commento davvero illuminante.\p"
	.string "Rende benissimo l'atmosfera\n"
	.string "della Gara.\p"
	.string "Ora l'ultima domanda.\p"
	.string "Quando senti la parola “{STR_VAR_2}”,\n"
	.string "qual è la prima immagine che ti viene?$"

LilycoveCity_ContestLobby_Text_ThatsAllForInterview:
	.string "Ah, ecco!\p"
	.string "Quindi è così che immagini\n"
	.string "il concetto di “{STR_VAR_2}”.\p"
	.string "Grazie!\n"
	.string "Mi hai dato un sacco di idee.\p"
	.string "Ora posso scrivere un bel pezzo\n"
	.string "sulle Gare Pokémon.\p"
	.string "E chissà, forse il servizio finirà\n"
	.string "addirittura in televisione.\l"
	.string "Resta sintonizzato!$"

LilycoveCity_ContestLobby_Text_PleaseDoShareStoryWithMe:
	.string "Oh, che peccato…\p"
	.string "Beh, se ti capita una bella storia,\n"
	.string "raccontamela, mi raccomando!$"

LilycoveCity_ContestLobby_Text_LookingForwardToNextContest:
	.string "Non vedo l'ora di vederti alla tua\n"
	.string "prossima Gara Pokémon!$"

gTVBravoTrainerText00::
	.string "Evviva!\n"
	.string "È l'ora di Bravo, Allenatore!\p"
	.string "Oggi vi presentiamo un Pokémon\n"
	.string "di {STR_VAR_1}.\p"
	.string "Ha conquistato il grado {STR_VAR_3}\n"
	.string "nella categoria {STR_VAR_2}!$"

gTVBravoTrainerText01::
	.string "Signore e signori, ecco {STR_VAR_2},\n"
	.string "uno splendido {STR_VAR_1}!\p"
	.string "Il soprannome {STR_VAR_2}…\p"
	.string "Già il nome trasmette un'aria che\n"
	.string "grida: “{STR_VAR_3}”!$"

gTVBravoTrainerText02::
	.string "Quando {STR_VAR_1} ha iscritto\n"
	.string "questo Pokémon a una Gara,\l"
	.string "abbiamo raccolto qualche parola\l"
	.string "appassionata sul fedele compagno.$"

gTVBravoTrainerText03::
	.string "Dopo la Gara, {STR_VAR_1} ci ha\n"
	.string "risposto con un sorriso enorme:\l"
	.string "“{STR_VAR_2}!”\p"
	.string "Beh, certo: il Pokémon di {STR_VAR_1}\n"
	.string "è arrivato {STR_VAR_3}º nella Gara!\p"
	.string "Direi che quella frase calza\n"
	.string "a pennello a {STR_VAR_1}, oggi!$"

gTVBravoTrainerText04::
	.string "Dopo la Gara, {STR_VAR_1} ci ha\n"
	.string "risposto con un filo d'amarezza:\l"
	.string "“{STR_VAR_2}.”\p"
	.string "Beh, certo: il Pokémon di {STR_VAR_1}\n"
	.string "è arrivato solo {STR_VAR_3}º nella Gara.\p"
	.string "La delusione di {STR_VAR_1} si sente\n"
	.string "forte e chiara, direi!$"

gTVBravoTrainerText05::
	.string "Non vorreste sapere anche cosa\n"
	.string "immagina {STR_VAR_1} quando\l"
	.string "sente la parola {STR_VAR_2}?\p"
	.string "Noi sì!\n"
	.string "E infatti gliel'abbiamo chiesto!\p"
	.string "La risposta, in una sola parola:\n"
	.string "“{STR_VAR_3}!”\p"
	.string "Ecco cosa rappresenta {STR_VAR_2}\n"
	.string "per {STR_VAR_1}!$"

gTVBravoTrainerText06::
	.string "E l'ultima mossa di {STR_VAR_1},\n"
	.string "{STR_VAR_2}, è stata pura\l"
	.string "“{STR_VAR_3}”!$"

gTVBravoTrainerText07::
	.string "Bravo, {STR_VAR_1}!\n"
	.string "Bravo, {STR_VAR_2}!\p"
	.string "Speriamo di vedere {STR_VAR_1}\n"
	.string "salire ancora più in alto!\p"
	.string "Il nostro tempo è scaduto!\n"
	.string "Alla prossima puntata, ciao a tutti!$"

gTVBravoTrainerText08::
	.string "Signore e signori, ecco {STR_VAR_1}!$"

BattleFrontier_BattleTowerLobby_Text_InterviewRequest::
	.string "Ciao! Sei l'Allenatore che ha appena\n"
	.string "finito di lottare, vero?\p"
	.string "Raccolgo interviste ad Allenatori\n"
	.string "di ogni parte… e di ogni mondo!\p"
	.string "Mi diresti due parole sulle tue\n"
	.string "impressioni di lotta?$"

BattleFrontier_BattleTowerLobby_Text_HowDidBattleTowerTurnOut::
	.string "Davvero? Sul serio?\n"
	.string "Grazie!\l"
	.string "Allora, ehm…\p"
	.string "Com'è andata oggi\n"
	.string "alla Torre Lotta?\p"
	.string "Sei soddisfatto della lotta?\n"
	.string "O sei rimasto deluso?$"

BattleFrontier_BattleTowerLobby_Text_SorryWeDisturbedYou::
	.string "Oh…\n"
	.string "Scusa il disturbo.\p"
	.string "Concedici un'intervista la prossima\n"
	.string "volta che passi dalla Torre Lotta!$"

BattleFrontier_BattleTowerLobby_Text_ObviousYouHadGreatBattle::
	.string "Ma certo!\p"
	.string "Quell'aria soddisfatta\n"
	.string "stampata in faccia…\p"
	.string "Si vede lontano un miglio che hai\n"
	.string "fatto una lotta grandiosa.$"

BattleFrontier_BattleTowerLobby_Text_DifficultToMakeBattleTurnOutAsPlanned::
	.string "Oh, capisco…\p"
	.string "Eh, non è mai facile che una lotta\n"
	.string "vada esattamente come previsto.$"

BattleFrontier_BattleTowerLobby_Text_DescribeYourBattle::
	.string "Oh, oh, posso farti un'ultima domanda?\p"
	.string "Se dovessi descrivere le tue\n"
	.string "impressioni su questa lotta\l"
	.string "con una frase, quale sarebbe?$"

BattleFrontier_BattleTowerLobby_Text_ThatsGreatLine::
	.string "Oh, ma è fantastica!\p"
	.string "Che frase da campione!\n"
	.string "In bocca al lupo per la prossima!\p"
	.string "Spero di rivederti presto!$"

BattleFrontier_BattleTowerLobby_Text_SilentType::
	.string "Oh, capisco…\p"
	.string "Del resto, anche il tipo silenzioso\n"
	.string "ha il suo fascino, no?\p"
	.string "Spero che la prossima volta vorrai\n"
	.string "condividere i tuoi pensieri!$"

BattleFrontier_BattleTowerLobby_Text_LookingForwardToNextBattle::
	.string "Non vedo l'ora di assistere\n"
	.string "alla tua prossima lotta!$"

BravoTrainerBattleTower_Text_Intro::
	.string "Evviva!\n"
	.string "È l'ora di Bravo, Allenatore!\p"
	.string "Oggi vi presentiamo {STR_VAR_1},\n"
	.string "che ha sfidato la Torre Lotta!\p"
	.string "Per la sfida, {STR_VAR_1} ha schierato\n"
	.string "{STR_VAR_2}, un Pokémon da paura!$"

BravoTrainerBattleTower_Text_NewRecord::
	.string "La coppia ha stabilito un nuovo\n"
	.string "record: {STR_VAR_2} vittorie di fila\l"
	.string "nella categoria {STR_VAR_1}!\l"
	.string "Bravo, Allenatore!$"

BravoTrainerBattleTower_Text_Lost::
	.string "Alla fine, la coppia si è arresa\n"
	.string "a {STR_VAR_1} all'incontro {STR_VAR_2}.\l"
	.string "Bel tentativo, Allenatore!\p"
	.string "Ma che sfortuna, incrociare\n"
	.string "{STR_VAR_1} così presto nella sfida!\p"
	.string "Abbiamo chiesto all'Allenatore cosa\n"
	.string "ne pensa della lotta con {STR_VAR_1}.$"

BravoTrainerBattleTower_Text_Won::
	.string "La coppia ha vinto tutto, travolgendo\n"
	.string "{STR_VAR_2}, il Pokémon di {STR_VAR_1}.\l"
	.string "Bravo, Allenatore!\p"
	.string "Battere perfino {STR_VAR_1}…\n"
	.string "Incredibile! Semplicemente strepitoso!\p"
	.string "Abbiamo chiesto all'Allenatore cosa\n"
	.string "si prova nel momento della gloria.$"

BravoTrainerBattleTower_Text_LostFinal::
	.string "Dopo una serie di vittorie, la coppia\n"
	.string "si è arresa a {STR_VAR_2} di {STR_VAR_1},\l"
	.string "l'ultimo ostacolo.\p"
	.string "Bel tentativo, Allenatore!\p"
	.string "Ma bisogna riconoscerlo:\n"
	.string "non capita spesso di vedere un duo\l"
	.string "famoso come {STR_VAR_1} e {STR_VAR_2}.\p"
	.string "Abbiamo chiesto all'Allenatore cosa\n"
	.string "si prova ad affrontare quella coppia.$"

BravoTrainerBattleTower_Text_Satisfied::
	.string "Ecco le parole dell'Allenatore:\n"
	.string "“Sono soddisfatto!”\p"
	.string "Che risposta rinfrescante, eh?\n"
	.string "Bravo, Allenatore!\p"
	.string "Non è fantastico poter lottare fino\n"
	.string "a sentirsi pienamente soddisfatti?\p"
	.string "E ho capito quanto fosse soddisfatto\n"
	.string "quando gli ho sentito dire questo:$"

BravoTrainerBattleTower_Text_Unsatisfied::
	.string "Ecco le parole dell'Allenatore:\n"
	.string "“Non sono soddisfatto…”\p"
	.string "Il nostro Allenatore era chiaramente\n"
	.string "un po' giù mentre lo diceva.\p"
	.string "Del resto, non è facile lottare\n"
	.string "e restare del tutto soddisfatti, no?\p"
	.string "Comunque, ho capito quanto fosse\n"
	.string "deluso quando gli ho sentito dire:$"

BravoTrainerBattleTower_Text_None1::
	.string "Nessuno$"

BravoTrainerBattleTower_Text_None2::
	.string "Nessuno$"

BravoTrainerBattleTower_Text_None3::
	.string "Nessuno$"

BravoTrainerBattleTower_Text_None4::
	.string "Nessuno$"

BravoTrainerBattleTower_Text_Response::
	.string "“{STR_VAR_1}.”$"

BravoTrainerBattleTower_Text_ResponseSatisfied::
	.string "“{STR_VAR_1}.”\n"
	.string "Non è magnifico?\p"
	.string "Esprime alla perfezione la gioia\n"
	.string "di {STR_VAR_2}, direi.\p"
	.string "Quella lotta finale con {STR_VAR_3}…\n"
	.string "È stata davvero quel che si dice\l"
	.string "“{STR_VAR_1}”!$"

BravoTrainerBattleTower_Text_ResponseUnsatisfied::
	.string "“{STR_VAR_1}.”\n"
	.string "Calzante, non trovate?\p"
	.string "Quella lotta finale con {STR_VAR_3}…\n"
	.string "Non si può descrivere in altro modo\l"
	.string "che “{STR_VAR_1}”!\p"
	.string "La delusione di {STR_VAR_2} si sente\n"
	.string "forte e chiara, direi!$"

BravoTrainerBattleTower_Text_Outro::
	.string "Bravo, {STR_VAR_1}!\n"
	.string "Bravo, {STR_VAR_2}!\p"
	.string "Speriamo di vedere {STR_VAR_1}\n"
	.string "salire ancora più in alto!\p"
	.string "Il nostro tempo è scaduto!\n"
	.string "Alla prossima puntata, ciao a tutti!$"

SlateportCity_PokemonFanClub_Text_InterviewRequestHasName:
	.string "Wow!\p"
	.string "Si vede lontano un miglio quanto\n"
	.string "vuoi bene al tuo {STR_VAR_1}.\p"
	.string "Ah, si chiama {STR_VAR_2}!\p"
	.string "Posso chiederti un favore?\p"
	.string "Lavoro per la TV e sto facendo\n"
	.string "un sondaggio sui Pokémon.\p"
	.string "Ti andrebbe di rispondere a qualche\n"
	.string "semplice domanda?$"

SlateportCity_PokemonFanClub_Text_HereGoesQuickAnswers:
	.string "Fantastico! Grazie!\p"
	.string "Allora, cominciamo.\n"
	.string "Rispondi di getto, d'accordo?$"

SlateportCity_PokemonFanClub_Text_DescribeFeelingsFirstMetMon:
	.string "Quando hai incontrato {STR_VAR_1}\n"
	.string "la prima volta, cosa hai provato?\p"
	.string "Come descriveresti le emozioni\n"
	.string "di quel momento?$"

SlateportCity_PokemonFanClub_Text_LikenMonToSomethingYouLike:
	.string "Il tuo {STR_VAR_1} è proprio coccolato.\p"
	.string "Se dovessi paragonarlo a qualcosa\n"
	.string "che ti piace, cosa sceglieresti?$"

SlateportCity_PokemonFanClub_Text_WhatAttractedYouAboutMon:
	.string "Anche questa domanda riguarda\n"
	.string "il tuo adorato {STR_VAR_1}.\p"
	.string "Che cosa ti ha conquistato\n"
	.string "di {STR_VAR_1}?$"

SlateportCity_PokemonFanClub_Text_WhatDoPokemonMeanToYou:
	.string "Ok, ha senso.\p"
	.string "La prossima domanda potrebbe essere\n"
	.string "un tantino più difficile.\p"
	.string "Eccola…\p"
	.string "Che cosa sono i Pokémon per te?$"

SlateportCity_PokemonFanClub_Text_ThatsAllForInterview:
	.string "Capisco!\p"
	.string "Mmh mmh…\p"
	.string "Perfetto!\n"
	.string "Grazie per l'aiuto.\p"
	.string "È stato divertente e istruttivo\n"
	.string "chiacchierare con te.\p"
	.string "Può darsi che l'intervista finisca\n"
	.string "in TV. Resta sintonizzato!\p"
	.string "Bene, è tutto.\n"
	.string "Ciao ciao!$"

SlateportCity_PokemonFanClub_Text_HereIfYouGetUrgeToTellMe:
	.string "Oh, va bene…\p"
	.string "Se ti viene voglia di parlarmi dei tuoi\n"
	.string "Pokémon, io sono qui!$"

SlateportCity_PokemonFanClub_Text_EnjoyDoingInterviews:
	.string "Adoro questo lavoro! Con le interviste\n"
	.string "scopro sempre qualcosa sui Pokémon…\l"
	.string "e con tutti quelli arrivati dai Varchi,\l"
	.string "non mi annoio mai!$"

SlateportCity_PokemonFanClub_Text_InterviewRequest:
	.string "Ciao! Sembri molto legato\n"
	.string "al tuo {STR_VAR_1}.\p"
	.string "Sai una cosa?\n"
	.string "Lavoro per la TV.\p"
	.string "Giro la regione intervistando\n"
	.string "la gente sui Pokémon.\p"
	.string "Ti andrebbe di raccontarmi qualcosa\n"
	.string "sul tuo {STR_VAR_1}?$"

SlateportCity_PokemonFanClub_Text_TellMeAnythingAboutYourMon:
	.string "Wow, grazie!\p"
	.string "Allora, raccontami tutto quello che\n"
	.string "vuoi sul tuo {STR_VAR_1}.$"

SlateportCity_PokemonFanClub_Text_ThatsAllForInterview2:
	.string "Wow…\n"
	.string "Che racconto interessante.\p"
	.string "Tu e {STR_VAR_1} siete proprio\n"
	.string "inseparabili, eh?\p"
	.string "Ho la sensazione che la tua storia\n"
	.string "diventerà un gran servizio TV.\p"
	.string "Prometto che ne farò\n"
	.string "una trasmissione divertente.\l"
	.string "Tieni gli occhi aperti!\p"
	.string "Bene, è tutto.\n"
	.string "Ciao ciao!$"

gTVFanClubOpinionsText00::
	.string "Noi siamo… il Pokémon Fan Club!\p"
	.string "Siamo in onda!\p"
	.string "Qui raccogliamo le vostre opinioni\n"
	.string "e io le urlo al posto vostro!\l"
	.string "Non è un'idea geniale?\p"
	.string "Oggi vi proponiamo il servizio del\n"
	.string "nostro inviato, che abbiamo spedito\l"
	.string "al Pokémon Fan Club.\p"
	.string "Allora, chi è il fan dei Pokémon\n"
	.string "protagonista di oggi?\p"
	.string "… … … … … … … …\p"
	.string "{STR_VAR_1}!\p"
	.string "Sentiamo cosa dice {STR_VAR_1}\n"
	.string "di {STR_VAR_3}, il suo {STR_VAR_2}.\p"
	.string "E io urlerò quelle parole d'amore\n"
	.string "a squarciagola in TV!\p"
	.string "Uh-uh!\p"
	.string "Urliamo!$"

gTVFanClubOpinionsText01::
	.string "Abbiamo chiesto a {STR_VAR_1}: “Cosa\n"
	.string "hai pensato la prima volta che hai\l"
	.string "visto il tuo {STR_VAR_2}?”\p"
	.string "“{STR_VAR_3}!”\p"
	.string "Evvai! Che urlo coi fiocchi!\p"
	.string "Non vi fa tornare in mente\n"
	.string "i bei tempi andati?$"

gTVFanClubOpinionsText02::
	.string "Abbiamo chiesto a {STR_VAR_1}: “Se\n"
	.string "dovessi paragonare il tuo {STR_VAR_2}\l"
	.string "a qualcosa, sarebbe…”\p"
	.string "… … … … … … … …\p"
	.string "“{STR_VAR_3}!”\p"
	.string "Uoh-oh, questa sì che è originale!\p"
	.string "Si sente tutta l'intensità\n"
	.string "dell'affetto dell'Allenatore\l"
	.string "per {STR_VAR_2}.$"

gTVFanClubOpinionsText03::
	.string "E vediamo un po'…\n"
	.string "Cos'ha fatto innamorare {STR_VAR_1}\l"
	.string "del suo {STR_VAR_2}?\p"
	.string "… … … … … … … …\p"
	.string "“{STR_VAR_3}!”\p"
	.string "Wow! Che dichiarazione spettacolare!\p"
	.string "L'amore dell'Allenatore per\n"
	.string "{STR_VAR_2} arriva forte e chiaro!$"

gTVFanClubOpinionsText04::
	.string "Mh? Oh, c'è dell'altro.\n"
	.string "Diamo un'occhiata!\p"
	.string "Vediamo un po'…\p"
	.string "Abbiamo chiesto a {STR_VAR_1}: “Che\n"
	.string "cosa sono per te i Pokémon?”\p"
	.string "… … … … … …\p"
	.string "“{STR_VAR_3}!”\p"
	.string "Bravo!\p"
	.string "È l'urlo migliore di tutta la giornata!\p"
	.string "“{STR_VAR_3}!”\p"
	.string "Viene voglia di urlarlo ancora\n"
	.string "e ancora!\p"
	.string "Dopo un urlo così, è ora di salutarci\n"
	.string "fino alla prossima puntata!\p"
	.string "Allora, un ultimo urlo tutti insieme!\n"
	.string "Pronti…\p"
	.string "“{STR_VAR_3}!”$"

gTVFanClubText00::
	.string "Noi siamo… il Pokémon Fan Club!\p"
	.string "Siamo in onda!\p"
	.string "Oggi si parte alla grande con\n"
	.string "l'Angolo delle Lettere Pokémon!\p"
	.string "Fra tutte le storie di Pokémon e\n"
	.string "Allenatori che arrivano da ogni\l"
	.string "angolo di Hoenn, quale ci stupirà oggi?\p"
	.string "Vediamo…\p"
	.string "Questa!\p"
	.string "Cominciamo con questa lettera!\p"
	.string "È una lettera di {STR_VAR_1} sul suo\n"
	.string "amato {STR_VAR_2}.\p"
	.string "Vediamo con quanta passione sa\n"
	.string "dichiarare amore a {STR_VAR_2}!\l"
	.string "Mmh mmh…$"

gTVFanClubText01::
	.string "Uaoh!\n"
	.string "Che lettera meravigliosa!$"

gTVFanClubText02::
	.string "Mi è piaciuta tanto che ve la rileggo!$"

gTVFanClubText03::
	.string "Una bella lettera merita di essere\n"
	.string "letta e riletta!$"

gTVFanClubText04::
	.string "Quel “{STR_VAR_3}”… accentua\n"
	.string "davvero l'impatto emotivo!\p"
	.string "È una lettera piena di sentimento\n"
	.string "sincero e profondo!$"

gTVFanClubText05::
	.string "Soprattutto quel “{STR_VAR_3}”!\p"
	.string "Adoro come è usato “{STR_VAR_3}”!$"

gTVFanClubText06::
	.string "Comunque, non che sia importante,\n"
	.string "ma “{STR_VAR_3}” suona benissimo.\p"
	.string "Ultimamente dico “{STR_VAR_3}”\n"
	.string "di continuo, quando chiacchiero.$"

gTVFanClubText07::
	.string "Se dovessi dare un voto a questa\n"
	.string "lettera, le darei {STR_VAR_3} punti.\p"
	.string "La prossima volta mi aspetto una\n"
	.string "lettera ancora più bella, {STR_VAR_1}!\p"
	.string "Ops, ma guardate che ore sono!\n"
	.string "È ora di salutarci, alla prossima!$"

SlateportCity_OceanicMuseum_1F_Text_InterviewRequest:
	.string "Oh?\n"
	.string "Per caso ti piacciono i Pokémon?\p"
	.string "Sono qui per conto di una rete TV.\p"
	.string "Raccolgo storie recenti su Pokémon\n"
	.string "e Allenatori. Con tutti questi Varchi,\l"
	.string "di cose strane ne succedono!\p"
	.string "Se non ti dispiace, mi racconteresti\n"
	.string "qualcosa di te?$"

SlateportCity_OceanicMuseum_1F_Text_InterviewRequestShort:
	.string "Raccolgo storie recenti su Pokémon\n"
	.string "e Allenatori.\p"
	.string "Se non ti dispiace, mi racconteresti\n"
	.string "qualcosa di te?$"

SlateportCity_OceanicMuseum_1F_Text_TellMeExperienceInvolvingPokemon:
	.string "Oh, davvero?\n"
	.string "Grazie!\p"
	.string "Allora raccontami qualcosa\n"
	.string "di interessante che ti è successo\l"
	.string "di recente con i Pokémon.$"

SlateportCity_OceanicMuseum_1F_Text_LetMeKnowIfYouHaveStory:
	.string "Oh, capisco…\p"
	.string "Beh, se hai una storia interessante\n"
	.string "da raccontare, fammelo sapere.$"

SlateportCity_OceanicMuseum_1F_Text_ThatsAllForInterview:
	.string "Oh, che storia emozionante!\p"
	.string "Farò in modo che venga raccontata\n"
	.string "in televisione.\p"
	.string "Prima o poi dovrebbe andare in onda,\n"
	.string "quindi resta sintonizzato!$"

SlateportCity_OceanicMuseum_1F_Text_BetterWriteUpStory:
	.string "Mmmh…\n"
	.string "Ho una bella storia per la TV.\p"
	.string "Meglio scriverla in fretta!$"
gTVRecentHappeningsText00::
	.string "Salve a tutti! È l'ora di Accadde\n"
	.string "a Hoenn!\p"
	.string "Per gli Allenatori, tra un Varco e\n"
	.string "l'altro, ogni giorno è un romanzo.\p"
	.string "Noi vogliamo raccontarvi qualcuna\n"
	.string "di queste storie di Pokémon.\p"
	.string "Oggi vi presentiamo la storia\n"
	.string "dell'Allenatore {STR_VAR_1}.\p"
	.string "Che cosa avrà vissuto di recente\n"
	.string "{STR_VAR_1}? Scopriamolo insieme.\p"
	.string "Vediamo un po'…$"

gTVRecentHappeningsText01::
	.string "Non è stato illuminante?\p"
	.string "Il racconto ci fa capire bene\n"
	.string "che cosa ha vissuto {STR_VAR_1}.\l"
	.string "È come se fossimo stati lì anche noi!$"

gTVRecentHappeningsText02::
	.string "“{STR_VAR_3}.” Che parola!\n"
	.string "Dà al racconto spessore e profondità.$"

gTVRecentHappeningsText03::
	.string "“{STR_VAR_3}.”\n"
	.string "Ecco che il racconto prende forma:\l"
	.string "sembra di vedere il luogo dei fatti.$"

gTVRecentHappeningsText04::
	.string "Il passaggio “{STR_VAR_3}”\n"
	.string "è davvero molto espressivo.$"

gTVRecentHappeningsText05::
	.string "{STR_VAR_1} ci ha raccontato una\n"
	.string "splendida storia di Pokémon.\p"
	.string "E ora il racconto di {STR_VAR_1}\n"
	.string "vi resterà impresso nel cuore.\p"
	.string "Per oggi è tutto.\n"
	.string "Restate sintonizzati!$"

gTVMassOutbreakText00::
	.string "Buongiorno a tutti!\n"
	.string "È l'ora del TG Pokémon.\p"
	.string "Ci è appena giunta notizia di un\n"
	.string "evento davvero raro.\p"
	.string "Ci segnalano una vera invasione\n"
	.string "di {STR_VAR_2}!\l"
	.string "Zona interessata: {STR_VAR_1}.\p"
	.string "Come forse saprete, {STR_VAR_2}\n"
	.string "è un Pokémon raro e difficile\l"
	.string "da trovare.\p"
	.string "C'è chi sospetta un Varco minore,\n"
	.string "ma intanto è un'occasione unica per\l"
	.string "vedere {STR_VAR_2} allo stato brado.\p"
	.string "Dal TG Pokémon è tutto.$"

gTV3CheersForPokeblocksText00::
	.string "Presentatore: Allegria a volontà,\n"
	.string "“Tre Urrà per le Pokémelle” è qua!\p"
	.string "Oggi esaminiamo la Pokémella\n"
	.string "preparata da {STR_VAR_1} e soci.\p"
	.string "Senza indugi, la faccio assaggiare\n"
	.string "al mio Gulpin buongustaio.\p"
	.string "… … … … … …\n"
	.string "… … … … … …$"

gTV3CheersForPokeblocksText01::
	.string "Gulpin: Gubi! Gubii!\p"
	.string "Presentatore: Il verdetto? Gusto\n"
	.string "{STR_VAR_1} al punto giusto!\p"
	.string "Secondo Gulpin, il sapore è:\n"
	.string "“{STR_VAR_2}!”\p"
	.string "Grazie mille, {STR_VAR_3}!$"

gTV3CheersForPokeblocksText02::
	.string "Al Frullabacche, {STR_VAR_1}\n"
	.string "ha lasciato un po' a desiderare.\p"
	.string "Con un tocco più preciso, questa\n"
	.string "Pokémella sarebbe molto più gustosa.$"

gTV3CheersForPokeblocksText03::
	.string "Gulpin: Gubi! Gubii!\p"
	.string "Presentatore: Mmh… Troppo {STR_VAR_1}.\n"
	.string "Secondo Gulpin, il sapore è:\l"
	.string "“{STR_VAR_2}!”\p"
	.string "Pare che gli errori di {STR_VAR_3}\n"
	.string "abbiano rovinato la miscela…$"

gTV3CheersForPokeblocksText04::
	.string "Peccato: l'impegno di {STR_VAR_1}\n"
	.string "stavolta non è bastato.\p"
	.string "Speriamo che {STR_VAR_2} e soci\n"
	.string "facciano meglio la prossima volta!$"

gTV3CheersForPokeblocksText05::
	.string "Alla prossima! E ricordate il motto:\n"
	.string "“Tre Urrà per le Pokémelle!”$"

LilycoveCity_PokemonTrainerFanClub_Text_WhatsYourOpinionOfTrainer::
	.string "Ciao!\p"
	.string "Sono un grande fan di {STR_VAR_1}.\n"
	.string "Tu che ne pensi di {STR_VAR_1}?$"

LilycoveCity_PokemonTrainerFanClub_Text_ThatsWhatYouThink::
	.string "Capisco, capisco! Allora è questo\n"
	.string "che pensi del nostro idolo.$"

LilycoveCity_PokemonTrainerFanClub_Text_HaveYouForgottenTrainer::
	.string "Ti sei proprio dimenticato\n"
	.string "di {STR_VAR_1}?$"

LilycoveCity_PokemonTrainerFanClub_Text_WhatsYourOpinionOfTrainer2::
	.string "Sono un grande fan di {STR_VAR_1}.\n"
	.string "Tu che ne pensi di {STR_VAR_1}?$"

LilycoveCity_PokemonTrainerFanClub_Text_HowStrongRateTrainer::
	.string "Da 0 a 100, quanto diresti\n"
	.string "che è forte {STR_VAR_1}?$"

LilycoveCity_PokemonTrainerFanClub_Text_HaveYouForgottenTrainer2::
	.string "Ti sei proprio dimenticato\n"
	.string "di {STR_VAR_1}?$"

LilycoveCity_PokemonTrainerFanClub_Text_YouShouldMeetTrainer::
	.string "Ah, capisco!\n"
	.string "Prima o poi devi conoscere {STR_VAR_1}.\l"
	.string "Diventerai un fan anche tu, vedrai!$"

LilycoveCity_PokemonTrainerFanClub_Text_ThankYouIllShareThisInfo::
	.string "Capisco, capisco.\p"
	.string "Grazie mille!\n"
	.string "È un'informazione preziosissima.\p"
	.string "La condividerò con gli altri fan di\n"
	.string "{STR_VAR_1} e ne discuteremo.$"

LilycoveCity_PokemonTrainerFanClub_HopeYouCatchTVSpecial::
	.string "Presto andrà in onda uno speciale\n"
	.string "TV dedicato a {STR_VAR_1}.\p"
	.string "Spero che tu non te lo perda!$"

gTVTrainerFanClubSpecialText00::
	.string "Fan Club Allenatori:\n"
	.string "Speciale {STR_VAR_1}!\p"
	.string "Una puntata speciale per tutti i fan\n"
	.string "di {STR_VAR_1} sparsi per Hoenn!\p"
	.string "Oggi ci chiediamo: “Che cosa pensa\n"
	.string "la gente di {STR_VAR_1}?”\p"
	.string "Lo abbiamo chiesto a {STR_VAR_2},\n"
	.string "in rappresentanza degli Allenatori.\p"
	.string "La domanda: “Con una sola parola,\n"
	.string "come descriveresti {STR_VAR_1}?”\p"
	.string "La risposta: “{STR_VAR_3}.”\p"
	.string "Complimenti a {STR_VAR_2}!\n"
	.string "Che osservazione acuta!\p"
	.string "“{STR_VAR_1} {STR_VAR_3}.”\n"
	.string "Suona proprio bene!\p"
	.string "{STR_VAR_2} ha anche dato un voto\n"
	.string "da 0 a 100 alla forza di {STR_VAR_1}.$"

gTVTrainerFanClubSpecialText01::
	.string "Il voto è {STR_VAR_3} punti!\n"
	.string "Un punteggio altissimo!\p"
	.string "Evidentemente {STR_VAR_2} ha\n"
	.string "grande stima di {STR_VAR_1}.$"

gTVTrainerFanClubSpecialText02::
	.string "Il voto è {STR_VAR_3} punti!\n"
	.string "Un punteggio niente male.\p"
	.string "Pare che {STR_VAR_2} consideri\n"
	.string "{STR_VAR_1} un degno rivale.$"

gTVTrainerFanClubSpecialText03::
	.string "Il voto è {STR_VAR_3} punti!\n"
	.string "Un punteggio piuttosto basso.\p"
	.string "Pare che {STR_VAR_2} consideri\n"
	.string "{STR_VAR_1} una semplice spalla.$"

gTVTrainerFanClubSpecialText04::
	.string "Il voto è {STR_VAR_3} punti!\n"
	.string "Un punteggio disastroso.\p"
	.string "Pare che {STR_VAR_2} consideri\n"
	.string "{STR_VAR_1} un semplice gregario.$"

gTVTrainerFanClubSpecialText05::
	.string "Ecco fatto, amici!\p"
	.string "Oggi abbiamo scoperto qualcosa di\n"
	.string "nuovo su {STR_VAR_1}.\p"
	.string "Per chiudere, vi lascio con le parole\n"
	.string "di {STR_VAR_2}.\p"
	.string "{STR_VAR_1} {STR_VAR_3}!$"

gTVNameRaterText00::
	.string "E adesso è il momento di…\n"
	.string "Lo Show del Giudice dei Nomi!\p"
	.string "Leggo il destino dei vostri Pokémon\n"
	.string "nel soprannome che avete scelto.\p"
	.string "Il mio compito è dare consigli,\n"
	.string "e i miei consigli sono preziosi.\p"
	.string "Oggi leggerò il soprannome\n"
	.string "{STR_VAR_3}, scelto da {STR_VAR_1}\l"
	.string "per il suo {STR_VAR_2}.\p"
	.string "Mmh mmh…\p"
	.string "Mmh…\n"
	.string "Questo soprannome è…$"

gTVNameRaterText01::
	.string "Un soprannome che rivela talento\n"
	.string "in tanti campi diversi.\p"
	.string "Esorto questo Allenatore a farsi\n"
	.string "coraggio e ad affrontare mille sfide.$"

gTVNameRaterText02::
	.string "Un soprannome in perfetta armonia\n"
	.string "con il nome dell'Allenatore, {STR_VAR_1}.\p"
	.string "Annuncia un'ottima intesa,\n"
	.string "con un tempismo impeccabile.$"

gTVNameRaterText03::
	.string "Un soprannome degno di un Pokémon\n"
	.string "unico in tutto il Multiverso!\p"
	.string "Se cresciuto con cura, la sua unicità\n"
	.string "sboccerà oltre ogni misura!$"

gTVNameRaterText04::
	.string "Un soprannome che coltiva il lato più\n"
	.string "premuroso e gentile dei Pokémon.\p"
	.string "Se cresciuto con cura, questo Pokémon\n"
	.string "mostrerà un calore sincero!$"

gTVNameRaterText05::
	.string "Un soprannome splendido, che lascia\n"
	.string "presagire un futuro di grandezza.\p"
	.string "Sono curioso di scoprire che cosa\n"
	.string "riserverà il futuro a questo Pokémon.$"

gTVNameRaterText06::
	.string "Un buon soprannome, che renderà il\n"
	.string "Pokémon sano e robusto!\p"
	.string "Questo Pokémon resterà in forma\n"
	.string "e in salute per tanto, tanto tempo.$"

gTVNameRaterText07::
	.string "Un buon soprannome, che renderà il\n"
	.string "Pokémon pieno di energia!\p"
	.string "Direi proprio che questo Pokémon\n"
	.string "darà spettacolo nelle lotte.$"

gTVNameRaterText08::
	.string "Un soprannome affascinante, che\n"
	.string "renderà il Pokémon irresistibile!\p"
	.string "Non ho dubbi: questo Pokémon farà\n"
	.string "strage di cuori nelle Gare Pokémon.$"

gTVNameRaterText09::
	.string "Il soprannome {STR_VAR_1} poggia\n"
	.string "sulla lettera “{STR_VAR_3}”.\p"
	.string "A sostenerla c'è l'iniziale “{STR_VAR_2}”,\n"
	.string "che dà al nome una presenza solida.$"

gTVNameRaterText10::
	.string "Il soprannome {STR_VAR_1} ha una\n"
	.string "forma armoniosa e piacevole.\p"
	.string "E le lettere “{STR_VAR_2}” e “{STR_VAR_3}”…\n"
	.string "sono davvero notevoli!$"

gTVNameRaterText11::
	.string "Il soprannome {STR_VAR_1}… ha un che\n"
	.string "di sublime, di fluido.\p"
	.string "Il passaggio dall'iniziale “{STR_VAR_2}”\n"
	.string "a “{STR_VAR_3}” è davvero splendido.$"

gTVNameRaterText12::
	.string "Vediamo ora altri esempi di ottimi\n"
	.string "soprannomi, che ne dite?$"

gTVNameRaterText13::
	.string "Ecco un esempio: prendete una parte\n"
	.string "del nome dell'Allenatore, {STR_VAR_1},\l"
	.string "e otterrete l'ottimo soprannome\l"
	.string "{STR_VAR_2}{STR_VAR_3}.$"

gTVNameRaterText14::
	.string "Anche il soprannome {STR_VAR_2}{STR_VAR_3}\n"
	.string "funzionerebbe piuttosto bene.$"

gTVNameRaterText15::
	.string "Anche il nome della specie, {STR_VAR_2},\n"
	.string "può servire da base per creare\l"
	.string "il soprannome {STR_VAR_1}{STR_VAR_3}.$"

gTVNameRaterText16::
	.string "Anche {STR_VAR_1}{STR_VAR_3} sarebbe un\n"
	.string "soprannome efficace.$"

gTVNameRaterText17::
	.string "Una cosa va sempre evitata: usare il\n"
	.string "nome di un'altra specie di Pokémon.\p"
	.string "Per esempio, non prendete il nome\n"
	.string "{STR_VAR_2} per creare {STR_VAR_1}{STR_VAR_3}.\l"
	.string "Sarebbe inaccettabile.$"

gTVNameRaterText18::
	.string "Devo dire che {STR_VAR_1} è davvero\n"
	.string "un ottimo soprannome.\p"
	.string "Spero che l'Allenatore continui\n"
	.string "a trattare {STR_VAR_1} con amore.\p"
	.string "Per oggi lo show è finito.\n"
	.string "Arrivederci alla prossima!$"

gTVPokemonAnglerText00::
	.string "A Pesca di {STR_VAR_2}\p"
	.string "Conduttore: Salve! Oggi vi diamo\n"
	.string "qualche dritta per pescare {STR_VAR_2}.\p"
	.string "Guru, che consiglio darebbe a chi\n"
	.string "vuole pescare {STR_VAR_2}?\p"
	.string "Guru: Mh? Pescare {STR_VAR_2}?\n"
	.string "Ve lo dico io: pazienza e attesa.\l"
	.string "È tutto qui il segreto.\p"
	.string "Vede {STR_VAR_1}, laggiù?\n"
	.string "È un ottimo esempio.\p"
	.string "Ha già visto scappare ben\n"
	.string "{STR_VAR_3} Pokémon.\p"
	.string "Eppure {STR_VAR_1} aspetta. Non molla.\n"
	.string "È la regola d'oro per {STR_VAR_2}.\p"
	.string "Conduttore: Capisco…\p"
	.string "Oh! Finalmente {STR_VAR_1} ha preso\n"
	.string "l'inafferrabile {STR_VAR_2}!\p"
	.string "Sembra sul punto di piangere\n"
	.string "dalla gioia!\p"
	.string "Vedendo quella faccia felice, viene\n"
	.string "voglia di andare a pescare anche a me!\p"
	.string "Telespettatori, perché non provate\n"
	.string "anche voi a pescare {STR_VAR_2}?\p"
	.string "Alla prossima puntata, un saluto\n"
	.string "e buona pesca a tutti!$"

gTVPokemonAnglerText01::
	.string "A Pesca di {STR_VAR_2}\p"
	.string "Conduttore: Salve! Oggi vi diamo\n"
	.string "qualche dritta per pescare {STR_VAR_2}.\p"
	.string "Guru, che consiglio darebbe a chi\n"
	.string "vuole pescare {STR_VAR_2}?\p"
	.string "Guru: Mh? Pescare {STR_VAR_2}?\n"
	.string "Ve lo dico io: maneggiate l'Amo\l"
	.string "con grinta!\p"
	.string "Vede {STR_VAR_1}, laggiù?\n"
	.string "Guardi come maneggia l'Amo!\p"
	.string "Ha già preso {STR_VAR_3} Pokémon\n"
	.string "uno dopo l'altro.\p"
	.string "Conduttore: Incredibile!\n"
	.string "Sembra una tempesta…\p"
	.string "Con una tecnica di quel livello,\n"
	.string "viene voglia di pescare anche a me.\p"
	.string "Telespettatori, perché non provate\n"
	.string "anche voi a pescare {STR_VAR_2}?\p"
	.string "Alla prossima puntata, un saluto\n"
	.string "e buona pesca a tutti!$"

gTVPokemonTodayFailedText00::
	.string "Salve!\p"
	.string "È l'ora di Pokémon Oggi!\p"
	.string "Sorellona: Ciao! Siete tutti belli\n"
	.string "carichi e pimpanti oggi?\p"
	.string "Oggi conosceremo {STR_VAR_2},\n"
	.string "il Pokémon di {STR_VAR_1}!\p"
	.string "Fratellone: Sì! È proprio quello\n"
	.string "che faremo!$"

gTVPokemonTodayFailedText01::
	.string "Oh!\n"
	.string "A proposito di {STR_VAR_1}…\p"
	.string "Sorellona, io quell'Allenatore l'ho\n"
	.string "visto con i miei occhi!\p"
	.string "Sorellona: Ah sì? E che cosa hai visto?\p"
	.string "Fratellone: Beh, ero in giro per\n"
	.string "lavoro, zona {STR_VAR_2}.\p"
	.string "Ed è lì che ho incrociato {STR_VAR_1},\n"
	.string "che cercava di catturare il Pokémon\l"
	.string "{STR_VAR_3}, ma…$"

gTVPokemonTodayFailedText02::
	.string "Il Pokémon è riuscito a scappare!\p"
	.string "Poké Ball sprecate in tutto:\n"
	.string "{STR_VAR_2}!\p"
	.string "Avreste dovuto vedere la faccia\n"
	.string "delusa di {STR_VAR_1} quando\l"
	.string "il Pokémon se l'è data a gambe!$"

gTVPokemonTodayFailedText03::
	.string "Ma {STR_VAR_1} ha fatto un pasticcio\n"
	.string "e ha mandato KO il Pokémon!\p"
	.string "Poké Ball sprecate in tutto:\n"
	.string "{STR_VAR_2}!\p"
	.string "Avreste dovuto vedere lo sgomento\n"
	.string "sulla faccia di {STR_VAR_1}\l"
	.string "quando il Pokémon è andato KO!$"

gTVPokemonTodayFailedText04::
	.string "Sorellona: Ehi, ehi!\n"
	.string "Così non è carino!\p"
	.string "Non si ride delle disgrazie\n"
	.string "degli altri!\p"
	.string "Oh, {STR_VAR_1}…\n"
	.string "Che peccato!\p"
	.string "Fratellone: Hai ragione!\n"
	.string "Scusate se ho riso.$"

gTVPokemonTodayFailedText05::
	.string "Sorellona: Bufufu…\p"
	.string "Fratellone: Ehi!\n"
	.string "Hai appena riso anche tu!\p"
	.string "Sorellona: Eh?!\p"
	.string "Io non ho riso!\n"
	.string "Giuro, non ho riso!\p"
	.string "Oh, {STR_VAR_1}…\n"
	.string "Che peccato!\p"
	.string "Fratellone: …$"

gTVPokemonTodayFailedText06::
	.string "Sorellona: Basta con le sciocchezze!\n"
	.string "Vediamo il Pokémon di oggi…\p"
	.string "Eh?\n"
	.string "Il tempo è già finito?\p"
	.string "Uffa!\n"
	.string "Oggi niente scheda del Pokémon!\p"
	.string "Fratellone: Alla prossima puntata!\p"
	.string "Sorellona: Ehi, non chiudere la\n"
	.string "puntata senza di me!$"

gTVPokemonTodaySuccessfulText00::
	.string "Salve!\p"
	.string "È l'ora di Pokémon Oggi!\p"
	.string "Sorellona: Ciao! Siete tutti belli\n"
	.string "carichi e pimpanti oggi?\p"
	.string "Oggi conosceremo {STR_VAR_2},\n"
	.string "il Pokémon di {STR_VAR_1}!\p"
	.string "Fratellone: Sì! È proprio quello\n"
	.string "che faremo!$"

gTVPokemonTodaySuccessfulText01::
	.string "Sorellona: {STR_VAR_1} ha chiamato\n"
	.string "{STR_VAR_3} il suo {STR_VAR_2}!\p"
	.string "Si vede che {STR_VAR_3} riceve\n"
	.string "tante cure e tanto affetto!$"

gTVPokemonTodaySuccessfulText02::
	.string "Fratellone: Poké Ball lanciate per\n"
	.string "catturarlo: {STR_VAR_3}!\p"
	.string "E alla fine è stata una {STR_VAR_2}\n"
	.string "a fare centro!$"

gTVPokemonTodaySuccessfulText03::
	.string "Sorellona: Se è stato così facile,\n"
	.string "dev'essere stato il destino (o un\l"
	.string "Varco!) a far incontrare {STR_VAR_1}\l"
	.string "e {STR_VAR_2}!$"

gTVPokemonTodaySuccessfulText04::
	.string "Sorellona: Wow! Che bello!\p"
	.string "Ma si sa: un Pokémon che costa tanta\n"
	.string "fatica per essere catturato si\l"
	.string "guadagna l'amore del suo Allenatore!$"

gTVPokemonTodaySuccessfulText05::
	.string "Sorellona: Questo {STR_VAR_2} è\n"
	.string "speciale per {STR_VAR_1}: per prenderlo\l"
	.string "ci è voluta una preziosa Master Ball!\p"
	.string "Fratellone: Wow! È mega-fantastico!\p"
	.string "Sorellona: {STR_VAR_1} doveva volere\n"
	.string "{STR_VAR_2} a tutti i costi!$"

gTVPokemonTodaySuccessfulText06::
	.string "Fratellone: E poi chiamare {STR_VAR_3}\n"
	.string "il suo {STR_VAR_2}…\p"
	.string "Si capisce subito che {STR_VAR_1}\n"
	.string "ha un vero fiuto da Allenatore.\p"
	.string "Sorellona: Sottoscrivo!$"

gTVPokemonTodaySuccessfulText07::
	.string "Se fosse per me, quel soprannome lo\n"
	.string "darei a un Pokémon come {STR_VAR_3}!\p"
	.string "Fratellone: Wow! Potrebbe nascere\n"
	.string "una nuova moda!$"

gTVPokemonTodaySuccessfulText08::
	.string "{STR_VAR_1} di nome {STR_VAR_2}?\n"
	.string "Non suona perfetto?\p"
	.string "Le lettere, tutto quanto… si adattano\n"
	.string "alla perfezione al Pokémon\l"
	.string "{STR_VAR_1}!\p"
	.string "Fratellone: Già, verissimo!$"

gTVPokemonTodaySuccessfulText09::
	.string "Che io sappia, nessun Allenatore ha\n"
	.string "mai chiamato {STR_VAR_2} il suo\l"
	.string "{STR_VAR_1}!\p"
	.string "Fratellone: Questo dimostra che\n"
	.string "l'Allenatore ha un gran gusto\l"
	.string "per i soprannomi!$"

gTVPokemonTodaySuccessfulText10::
	.string "Il prossimo Pokémon che catturo\n"
	.string "lo chiamerò {STR_VAR_2}.\p"
	.string "Fratellone: Eh? Anch'io!\n"
	.string "Anch'io lo chiamerò {STR_VAR_2}!$"

gTVPokemonTodaySuccessfulText11::
	.string "Sorellona: Oh, no!\n"
	.string "Guarda che ore sono!\p"
	.string "Bene, ragazzi, per oggi è tutto.\n"
	.string "Alla prossima puntata!\p"
	.string "Fratellone: Ricordate: la prossima\n"
	.string "volta potrebbe toccare al vostro\l"
	.string "Pokémon… anche se viene da un Varco!$"

SmartShopper_Text_Intro::
	.string "Salve!\p"
	.string "È l'ora di Acquisti Furbi!\p"
	.string "Giornalista: Come state, cari\n"
	.string "telespettatori?\p"
	.string "Oggi siamo in visita a un negozio\n"
	.string "di {STR_VAR_2}.\p"
	.string "Scopriamo quali sono stati gli\n"
	.string "articoli più venduti di recente.$"

SmartShopper_Text_ClerkNormal::
	.string "Facciamo due chiacchiere col commesso\n"
	.string "per avere qualche dritta.\p"
	.string "Salve! Come vanno gli affari?\p"
	.string "Commesso: Oh, a gonfie vele!\p"
	.string "Ultimamente {STR_VAR_2} va\n"
	.string "letteralmente a ruba.\p"
	.string "Proprio l'altro giorno un Allenatore\n"
	.string "di nome {STR_VAR_1} ne ha fatto\l"
	.string "scorta: {STR_VAR_3} pezzi!$"

SmartShopper_Text_RandomComment1::
	.string "Giornalista: Ben {STR_VAR_3} pezzi di\n"
	.string "{STR_VAR_2}? Che scorta!\p"
	.string "Se posso dire la mia, {STR_VAR_1} si\n"
	.string "starà preparando per un lungo viaggio\l"
	.string "verso posti lontani.\p"
	.string "Magari persino oltre un Varco!\p"
	.string "In viaggio, {STR_VAR_2} è davvero\n"
	.string "indispensabile!$"

SmartShopper_Text_RandomComment2::
	.string "Giornalista: A proposito di\n"
	.string "{STR_VAR_2}, anch'io ne ho appena\l"
	.string "fatto scorta: {STR_VAR_3} pezzi!\p"
	.string "Del resto, {STR_VAR_2} è un acquisto\n"
	.string "fantastico!$"

SmartShopper_Text_RandomComment3::
	.string "Giornalista: {STR_VAR_2}?!\n"
	.string "Ma addirittura {STR_VAR_3} pezzi?!\p"
	.string "Non credevo che qualcuno potesse\n"
	.string "comprarne così tanti.\p"
	.string "Santo cielo, io me ne posso\n"
	.string "permettere uno o due alla volta…$"

SmartShopper_Text_RandomComment4::
	.string "Giornalista: Una volta ho comprato\n"
	.string "una montagna di {STR_VAR_2}.\p"
	.string "Ma avevo esagerato, e alla fine\n"
	.string "ho avuto un sacco di rimpianti…\p"
	.string "Da allora compro soltanto lo stretto\n"
	.string "indispensabile…\p"
	.string "Ops!\p"
	.string "Ma che c'entro io, adesso?!$"

SmartShopper_Text_SecondItem::
	.string "Commesso: {STR_VAR_1} ha preso anche\n"
	.string "{STR_VAR_2}. Quantità: {STR_VAR_3}.\p"
	.string "Giornalista: Scelta saggia!\n"
	.string "Anche {STR_VAR_2} è un ottimo acquisto.$"

SmartShopper_Text_ThirdItem::
	.string "Commesso: E dallo scontrino risulta\n"
	.string "pure {STR_VAR_2}. Quantità: {STR_VAR_3}.$"

SmartShopper_Text_DuringSale::
	.string "Commesso: E per giunta durante i saldi!\n"
	.string "Questo sì che è saper fare la spesa.$"

SmartShopper_Text_OutroNormal::
	.string "Giornalista: Mmh… {STR_VAR_1} sembra\n"
	.string "proprio un cacciatore di affari!\p"
	.string "In totale, la spesa di {STR_VAR_1}\n"
	.string "ammonta a…\p"
	.string "¥{STR_VAR_2}?!\n"
	.string "Una cifra da capogiro!\p"
	.string "Ops! Il tempo a disposizione è finito!\n"
	.string "Alla prossima puntata!$"

SmartShopper_Text_IsVIP::
	.string "Commesso: {STR_VAR_1} è un cliente VIP,\n"
	.string "non ci sono dubbi.$"

SmartShopper_Text_ClerkMax::
	.string "Facciamo due chiacchiere col commesso\n"
	.string "per avere qualche dritta.\p"
	.string "Salve! Come vanno gli affari?\p"
	.string "Commesso: Oh, alla grande! Anzi,\n"
	.string "quasi non riusciamo a starci dietro!\p"
	.string "Di recente {STR_VAR_1}, un Allenatore,\n"
	.string "ha fatto incetta di {STR_VAR_2}.\p"
	.string "Ci ha quasi svuotato il magazzino:\n"
	.string "di {STR_VAR_2} non resta quasi nulla!\p"
	.string "Mai visto un cliente comprare una\n"
	.string "scorta simile di {STR_VAR_2}.\l"
	.string "Roba da non credere!\p"
	.string "Giornalista: Quindi parliamo di 100\n"
	.string "o 200 pezzi venduti?\p"
	.string "Commesso: Oh, no, molti di più!\p"
	.string "Giornalista: Santo cielo!\n"
	.string "{STR_VAR_1} è un cliente coi fiocchi!\p"
	.string "Commesso: {STR_VAR_1} è un cliente VIP,\n"
	.string "non ci sono dubbi.$"

SmartShopper_Text_OutroMax::
	.string "Giornalista: Mmh…\n"
	.string "È davvero incredibile.\p"
	.string "Ma a cosa servirà all'Allenatore\n"
	.string "tutta quella roba?\p"
	.string "Una spedizione dentro un Varco?\n"
	.string "Una festa per cento Pokémon?\p"
	.string "… …\p"
	.string "Il mistero si infittisce, ma il nostro\n"
	.string "tempo per oggi è finito.\l"
	.string "Alla prossima puntata!\p"
	.string "{STR_VAR_1} resta proprio un enigma…$"

gTVWorldOfMastersText00::
	.string "Il Mondo dei Maestri\p"
	.string "Buongiorno, cari telespettatori.\p"
	.string "Forse conoscete già un Allenatore\n"
	.string "di nome {STR_VAR_1}.\p"
	.string "{STR_VAR_1} è famoso come vero maestro\n"
	.string "nella cattura dei Pokémon.\p"
	.string "La sua caccia ai Pokémon si basa\n"
	.string "tutta su lunghe ricerche a piedi.\p"
	.string "In una giornata memorabile, ha\n"
	.string "percorso ben {STR_VAR_2} passi.\p"
	.string "Quel giorno, i Pokémon catturati\n"
	.string "hanno raggiunto quota {STR_VAR_3}!$"

gTVWorldOfMastersText01::
	.string "Un'impresa simile è stata possibile\n"
	.string "grazie alla fiducia tra l'Allenatore\l"
	.string "e il suo {STR_VAR_1}.$"

gTVWorldOfMastersText02::
	.string "Quel giorno, l'ultima cattura del\n"
	.string "maestro è stata {STR_VAR_3},\l"
	.string "vicino a {STR_VAR_2}.\p"
	.string "Pare che quel Pokémon ora goda di\n"
	.string "uno status speciale da primatista.\p"
	.string "Invitiamo gli Allenatori più abili\n"
	.string "a sfidare questo splendido record.\p"
	.string "Per oggi è tutto.\n"
	.string "Restate sintonizzati!$"

gTVTodaysRivalTrainerText00::
	.string "Il Rivale del Giorno!\p"
	.string "Salve, amici Allenatori di Pokémon!\n"
	.string "Come ve la passate oggi?\p"
	.string "Oggi, come ogni giorno, metteremo\n"
	.string "sotto la lente uno dei nostri rivali!$"

gTVTodaysRivalTrainerText07::
	.string "Il rivale di oggi è {STR_VAR_1},\n"
	.string "che ora si trova in zona {STR_VAR_3}.\p"
	.string "Finora {STR_VAR_1} ha registrato\n"
	.string "{STR_VAR_2} Pokémon nel Pokédex.$"

gTVTodaysRivalTrainerText08::
	.string "Il rivale di oggi è {STR_VAR_1},\n"
	.string "che ora si trova in una Base Segreta.\p"
	.string "Finora {STR_VAR_1} ha registrato\n"
	.string "{STR_VAR_2} Pokémon nel Pokédex.$"

gTVTodaysRivalTrainerText09::
	.string "Il rivale di oggi è {STR_VAR_1}.\p"
	.string "Finora {STR_VAR_1} ha registrato\n"
	.string "{STR_VAR_2} Pokémon nel Pokédex.$"

gTVTodaysRivalTrainerText10::
	.string "Il rivale di oggi è {STR_VAR_1},\n"
	.string "che ora viaggia su un traghetto.\p"
	.string "Finora {STR_VAR_1} ha registrato\n"
	.string "{STR_VAR_2} Pokémon nel Pokédex.$"

	.string "$"

gTVTodaysRivalTrainerText01::
	.string "E quante Medaglie ha il nostro rivale?\n"
	.string "Per la precisione… {STR_VAR_1}!$"

gTVTodaysRivalTrainerText02::
	.string "Ma il nostro rivale non ha ancora\n"
	.string "nemmeno una Medaglia!$"

gTVTodaysRivalTrainerText03::
	.string "Il nostro rivale non ha ancora nemmeno\n"
	.string "un Simbolo del Parco Lotta.$"

gTVTodaysRivalTrainerText04::
	.string "Vediamo quanti Simboli del Parco Lotta\n"
	.string "ha conquistato il nostro rivale.\p"
	.string "Simboli d'Oro: {STR_VAR_1}!\n"
	.string "Simboli d'Argento: {STR_VAR_2}!$"

gTVTodaysRivalTrainerText05::
	.string "Il nostro rivale ha accumulato\n"
	.string "{STR_VAR_1} Punti Lotta al Parco Lotta.$"

gTVTodaysRivalTrainerText06::
	.string "Allora, come ve la cavate voi in\n"
	.string "confronto a {STR_VAR_1}?\p"
	.string "L'avventura continua!\p"
	.string "Amici Allenatori!\p"
	.string "Andiamo avanti a testa alta e\n"
	.string "lasciamoci i rivali alle spalle!$"

TrendWatcher_Text_Intro::
	.string "Radar Tendenze di Bluruvia!\p"
	.string "Conduttore: Ehilà, gente!\n"
	.string "Oggi vi diamo le dritte più fresche\l"
	.string "su cosa fa tendenza a Bluruvia.\p"
	.string "Il nostro ospite è un vecchio leone,\n"
	.string "la massima autorità su tutto ciò\l"
	.string "che succede a Bluruvia.\p"
	.string "Anziano: Lieto di essere qui.\p"
	.string "Conduttore: Andiamo dritti al sodo.\p"
	.string "Cos'è che sta facendo impazzire\n"
	.string "la brava gente di Bluruvia?\p"
	.string "Anziano: {STR_VAR_1} {STR_VAR_2}.\p"
	.string "Conduttore: {STR_VAR_1} {STR_VAR_2},\n"
	.string "dici?\p"
	.string "Anziano: No.\p"
	.string "{STR_VAR_1} {STR_VAR_2} non è\n"
	.string "mai diventato di moda.\p"
	.string "Vuoi che ti racconti com'è andata?\p"
	.string "Conduttore: Ehm, no. A noi interessa\n"
	.string "sapere cosa va forte adesso…$"

@ Identical to below, may have been different in other languages
TrendWatcher_Text_MaleTaughtMePhrase::
	.string "Anziano: {STR_VAR_1} {STR_VAR_2}…\n"
	.string "Me l'ha insegnato {STR_VAR_3} di\l"
	.string "Albanova, diceva che era di moda…$"

TrendWatcher_Text_FemaleTaughtMePhrase::
	.string "Anziano: {STR_VAR_1} {STR_VAR_2}…\n"
	.string "Me l'ha insegnato {STR_VAR_3} di\l"
	.string "Albanova, diceva che era di moda…$"

TrendWatcher_Text_PhraseWasHopeless::
	.string "Ma è stato un fiasco totale.\p"
	.string "Festival di {STR_VAR_1} {STR_VAR_2}!\p"
	.string "Gara di {STR_VAR_1} {STR_VAR_2}!\p"
	.string "Ho provato a insegnarlo a tutti\n"
	.string "come meglio potevo, ma…\p"
	.string "Forse era la parte “{STR_VAR_1}”\n"
	.string "a non funzionare…\p"
	.string "Conduttore: Ehm, scusa, nonno, a me\n"
	.string "serve sapere cosa va forte adesso…$"

@ Identical to below, may have been different in other languages
TrendWatcher_Text_MaleTellMeBigger::
	.string "Anziano: {STR_VAR_3}!\n"
	.string "Ti prego, insegnami qualcosa di più\l"
	.string "forte di {STR_VAR_1} {STR_VAR_2}!$"

TrendWatcher_Text_FemaleTellMeBigger::
	.string "Anziano: {STR_VAR_3}!\n"
	.string "Ti prego, insegnami qualcosa di più\l"
	.string "forte di {STR_VAR_1} {STR_VAR_2}!$"

TrendWatcher_Text_Outro::
	.string "Conduttore: …Ehm… Ecco qua, gente\n"
	.string "alla moda di tutta Hoenn!\p"
	.string "{STR_VAR_1} {STR_VAR_2}… ehm…\n"
	.string "A Bluruvia non ha fatto tendenza!\p"
	.string "Il tempo è scaduto. Alla prossima!\p"
	.string "Anziano: {STR_VAR_1} {STR_VAR_2}!$"

gTVHoennTreasureInvestigatorsText00::
	.string "Cacciatori di Tesori di Hoenn!\p"
	.string "Ciao a tutti!\n"
	.string "Trovato qualche tesoro nascosto?\p"
	.string "Come sempre, esaminiamo le vostre\n"
	.string "segnalazioni di segreti da ogni\l"
	.string "angolo di Hoenn… Varchi compresi!\p"
	.string "Partiamo con una lettera.\n"
	.string "Dice: “Trovato {STR_VAR_1}!”$"

gTVHoennTreasureInvestigatorsText01::
	.string "Wow, questa lettera promette bene!\n"
	.string "Ve la leggo subito.\p"
	.string "…Cari Cacciatori di Tesori,\n"
	.string "spero che stiate bene.\p"
	.string "Di recente ho visto {STR_VAR_2}\n"
	.string "nei dintorni di {STR_VAR_3}.\p"
	.string "Ha trovato lo strumento\n"
	.string "{STR_VAR_1}. Che invidia!\p"
	.string "…Ottimo lavoro, {STR_VAR_2}!\p"
	.string "Telespettatori, prendete esempio:\n"
	.string "accendete il Ricerca Strum. e\l"
	.string "mettetevi a cercare!\p"
	.string "Aspetto notizie entusiasmanti\n"
	.string "da tutti voi!$"

gTVHoennTreasureInvestigatorsText02::
	.string "Wow, questa lettera promette bene!\n"
	.string "Ve la leggo subito.\p"
	.string "…Cari Cacciatori di Tesori,\n"
	.string "spero che stiate bene.\p"
	.string "Di recente ho visto {STR_VAR_2}\n"
	.string "a bordo di un traghetto.\p"
	.string "Ha trovato lo strumento\n"
	.string "{STR_VAR_1}. Che invidia!\p"
	.string "…Ottimo lavoro, {STR_VAR_2}!\p"
	.string "Telespettatori, prendete esempio:\n"
	.string "accendete il Ricerca Strum. e\l"
	.string "mettetevi a cercare!\p"
	.string "Aspetto notizie entusiasmanti\n"
	.string "da tutti voi!$"

gTVFindThatGamerText00::
	.string "Caccia al Giocatore!\p"
	.string "Ehi, giocatori!\n"
	.string "Come gira la vostra {STR_VAR_2}?\p"
	.string "Come sempre, puntiamo i riflettori\n"
	.string "su un Allenatore fuori dal comune\l"
	.string "che ha fatto visita al Casinò!\p"
	.string "Il giocatore numero uno di oggi è…\n"
	.string "{STR_VAR_1}!$"

gTVFindThatGamerText01::
	.string "{STR_VAR_1} ha giocato alla {STR_VAR_2}\n"
	.string "e ha vinto ben {STR_VAR_3} Gettoni.\p"
	.string "“Quando arriva {STR_VAR_1}, meglio\n"
	.string "avere Gettoni a sufficienza.”\p"
	.string "Così borbottano i dipendenti del\n"
	.string "Casinò quando il nostro asso gioca!\p"
	.string "Telespettatori, se andate al Casinò\n"
	.string "a giocare alla {STR_VAR_2}, gestite\l"
	.string "i Gettoni come {STR_VAR_1}!\p"
	.string "In diretta dal Casinò, dove\n"
	.string "l'emozione si sente nell'aria!\p"
	.string "Per oggi è tutto!$"

gTVFindThatGamerText02::
	.string "{STR_VAR_1} ha giocato alla {STR_VAR_2}\n"
	.string "e ha perso {STR_VAR_3} Gettoni.\p"
	.string "“Quando arriva {STR_VAR_1}, le vendite\n"
	.string "di Gettoni volano alle stelle.”\p"
	.string "Così dicono i dipendenti del Casinò\n"
	.string "quando il nostro giocatore è in pista!$"

gTVFindThatGamerText03::
	.string "Telespettatori, se andate al Casinò\n"
	.string "a giocare alla {STR_VAR_2}, gestite\l"
	.string "i Gettoni meglio di {STR_VAR_1}!\p"
	.string "In diretta dal Casinò, dove\n"
	.string "l'emozione si sente nell'aria!\p"
	.string "Per oggi è tutto!$"

gTVBreakingNewsText00::
	.string "Edizione Straordinaria!$"

gTVBreakingNewsText01::
	.string "{STR_VAR_1} cattura un raro\n"
	.string "{STR_VAR_2}!\p"
	.string "Siamo in diretta dai dintorni di\n"
	.string "{STR_VAR_3}!\p"
	.string "Proprio qui, poco fa, {STR_VAR_1}\n"
	.string "ha catturato un raro {STR_VAR_2}!$"

gTVBreakingNewsText02::
	.string "Davanti al raro {STR_VAR_2},\n"
	.string "{STR_VAR_1} ha mandato in campo\l"
	.string "il suo {STR_VAR_3}.$"

gTVBreakingNewsText03::
	.string "Durante la lotta, l'Allenatore ha\n"
	.string "lanciato {STR_VAR_1} Poké Ball in tutto.\p"
	.string "Alla fine il Pokémon raro è stato\n"
	.string "catturato con l'ultima {STR_VAR_2}.$"

gTVBreakingNewsText04::
	.string "In quell'istante, {STR_VAR_2}\n"
	.string "ha risuonato delle grida di trionfo\l"
	.string "di {STR_VAR_1}.\p"
	.string "Lo ammetto, invidio un po'\n"
	.string "{STR_VAR_1}. Vorrei urlare anch'io!\p"
	.string "…E con questa scena di gioia\n"
	.string "si chiude il nostro collegamento!$"

gTVBreakingNewsText05::
	.string "{STR_VAR_1} si lascia sfuggire\n"
	.string "un raro {STR_VAR_2}!\p"
	.string "Siamo in diretta dai dintorni di\n"
	.string "{STR_VAR_3}!\p"
	.string "Proprio qui, {STR_VAR_1} ha fallito\n"
	.string "la cattura di un raro {STR_VAR_2}!$"

gTVBreakingNewsText06::
	.string "Davanti al raro {STR_VAR_2},\n"
	.string "{STR_VAR_1} ha mandato in campo\l"
	.string "il suo {STR_VAR_3}.$"

gTVBreakingNewsText07::
	.string "L'Allenatore ha ordinato a {STR_VAR_2}\n"
	.string "di usare la mossa {STR_VAR_1}.\p"
	.string "Così, senza volerlo, ha mandato KO\n"
	.string "il Pokémon raro…$"

gTVBreakingNewsText12::
	.string "Ma alla vista del raro {STR_VAR_2},\n"
	.string "{STR_VAR_1} è andato nel panico.\p"
	.string "In preda alla confusione, ha ordinato\n"
	.string "a {STR_VAR_3} di attaccare.\p"
	.string "Così, senza volerlo, ha mandato KO\n"
	.string "il Pokémon raro.$"

gTVBreakingNewsText08::
	.string "In quell'istante, {STR_VAR_2}\n"
	.string "ha risuonato delle grida di\l"
	.string "frustrazione di {STR_VAR_1}…$"

gTVBreakingNewsText09::
	.string "Ma a quanto pare, {STR_VAR_1} era\n"
	.string "rimasto senza Poké Ball.\p"
	.string "L'Allenatore ha dovuto abbandonare\n"
	.string "la lotta con il raro {STR_VAR_2}.\p"
	.string "In quell'istante, {STR_VAR_3}\n"
	.string "ha risuonato delle grida di\l"
	.string "frustrazione di {STR_VAR_1}…$"

gTVBreakingNewsText10::
	.string "Ma {STR_VAR_2} se l'è svignata\n"
	.string "all'improvviso. Sarà sparito\l"
	.string "in un Varco?\p"
	.string "In quell'istante, {STR_VAR_3}\n"
	.string "ha risuonato delle grida di\l"
	.string "frustrazione di {STR_VAR_1}…$"

gTVBreakingNewsText11::
	.string "Lo ammetto, mi dispiace per\n"
	.string "{STR_VAR_1}. Viene voglia di urlare\l"
	.string "anche a me.\p"
	.string "…E con questa scena malinconica\n"
	.string "si chiude il nostro collegamento!$"

gTVSecretBaseVisitText00::
	.string "Salve, gente!\n"
	.string "Torna l'appuntamento con\l"
	.string "“Visita alla Base Segreta”!\p"
	.string "Oggi entriamo nella Base Segreta\n"
	.string "di {STR_VAR_1}.\p"
	.string "Come l'avrà personalizzata\n"
	.string "{STR_VAR_1}, la sua Base Segreta?\p"
	.string "Scopriamolo!\n"
	.string "… … … … … …$"

gTVSecretBaseVisitText01::
	.string "Oh!\n"
	.string "Ma che meraviglia!\p"
	.string "Ecco qui: {STR_VAR_2}…\n"
	.string "Davvero inaspettato, in un posto\l"
	.string "come questo!$"

gTVSecretBaseVisitText02::
	.string "Oh!\n"
	.string "Ma che cosa straordinaria!\p"
	.string "Non c'è un solo mobile, né un\n"
	.string "singolo oggetto d'arredo!\p"
	.string "I comuni mortali non potrebbero mai\n"
	.string "imitare una scelta così audace!\p"
	.string "È semplice, eppure trabocca, sì,\n"
	.string "trabocca di spirito selvaggio!\p"
	.string "Giù il cappello, {STR_VAR_1}.\n"
	.string "Solo tu potevi farlo!$"

gTVSecretBaseVisitText03::
	.string "Oh! Ho capito!\n"
	.string "Ora vedo tutto con chiarezza!\p"
	.string "La presenza di {STR_VAR_2} qui…\n"
	.string "Lancia un messaggio potentissimo!$"

gTVSecretBaseVisitText04::
	.string "Oh! Ho capito!\n"
	.string "Ora vedo tutto con chiarezza!\p"
	.string "Questo spazio è stato lasciato\n"
	.string "vuoto di proposito!\p"
	.string "Lancia un messaggio potentissimo!$"

gTVSecretBaseVisitText05::
	.string "Uaaauh!\p"
	.string "L'accoppiata tra {STR_VAR_2}\n"
	.string "e {STR_VAR_3}!\p"
	.string "Una combinazione da sogno,\n"
	.string "non c'è che dire!$"

gTVSecretBaseVisitText06::
	.string "Uaaauh!\p"
	.string "Aver messo {STR_VAR_2}\n"
	.string "proprio qui…\p"
	.string "Ha una presenza che riempie\n"
	.string "l'intera Base Segreta!$"

gTVSecretBaseVisitText07::
	.string "Uaaauh!\p"
	.string "Qui non c'è proprio niente.\p"
	.string "Questo spazio vuoto dà carattere\n"
	.string "all'intera Base Segreta.$"

gTVSecretBaseVisitText08::
	.string "Oh!\n"
	.string "Ecco che arriva {STR_VAR_1}!\l"
	.string "Sfidiamolo a una lotta!\p"
	.string "… … … … … …\n"
	.string "… … … … … …$"

gTVSecretBaseVisitText09::
	.string "Uff…\n"
	.string "Tanto di cappello a {STR_VAR_1}.\p"
	.string "I suoi Pokémon erano davvero\n"
	.string "degni del titolo di Campione.\p"
	.string "Hanno dimostrato tutta la forza\n"
	.string "di {STR_VAR_1} come Allenatore.\p"
	.string "Il fatto che {STR_VAR_2} conoscesse\n"
	.string "la mossa {STR_VAR_3}…\p"
	.string "La dice lunga sul tipo di Allenatore\n"
	.string "che è {STR_VAR_1}.\p"
	.string "Che lezione, non c'è che dire!$"

gTVSecretBaseVisitText10::
	.string "Aiaaah!\n"
	.string "Devo proprio inchinarmi a {STR_VAR_1}.\p"
	.string "I suoi Pokémon erano\n"
	.string "mostruosamente forti!\p"
	.string "Hanno dimostrato tutta la tenacia\n"
	.string "di {STR_VAR_1} come Allenatore.\p"
	.string "Il fatto che {STR_VAR_2} conoscesse\n"
	.string "la mossa {STR_VAR_3}…\p"
	.string "La dice lunga sul tipo di Allenatore\n"
	.string "che è {STR_VAR_1}.\p"
	.string "Che lezione, non c'è che dire!$"
gTVSecretBaseVisitText11::
	.string "Uaaah!\n"
	.string "Tanto di cappello a {STR_VAR_1}!\p"
	.string "I Pokémon di questo Allenatore sono\n"
	.string "cresciuti in modo davvero equilibrato.\p"
	.string "Sono la prova di quanta cura\n"
	.string "{STR_VAR_1} metta in ogni lotta.\p"
	.string "E poi, il fatto che {STR_VAR_2}\n"
	.string "conoscesse la mossa {STR_VAR_3}…\p"
	.string "Dice tutto su che tipo di Allenatore\n"
	.string "sia {STR_VAR_1}.\p"
	.string "Che lezione, signori miei!$"

gTVSecretBaseVisitText12::
	.string "Bene, bene!\n"
	.string "Tanto di cappello a {STR_VAR_1}!\p"
	.string "I Pokémon di questo Allenatore hanno\n"
	.string "un futuro davvero promettente.\p"
	.string "In loro brillano i sogni e le\n"
	.string "speranze di {STR_VAR_1}.\p"
	.string "E poi, il fatto che {STR_VAR_2}\n"
	.string "conoscesse la mossa {STR_VAR_3}…\p"
	.string "Dice tutto su che tipo di Allenatore\n"
	.string "sia {STR_VAR_1}.\p"
	.string "Una vera lezione di stile!$"

gTVSecretBaseVisitText13::
	.string "Devo proprio dirlo: che Base Segreta\n"
	.string "straordinaria!\p"
	.string "Telespettatori, se ne avete l'occasione,\n"
	.string "visitate la Base di {STR_VAR_1}!\p"
	.string "Alla prossima, vi saluto con un inchino!$"

gTVPokemonLotteryWinnerFlashReportText00::
	.string "Che emozione!\n"
	.string "Che suspense!\p"
	.string "È il Flash Speciale sui Vincitori\n"
	.string "della Lotteria Pokémon!\p"
	.string "Salve! Siamo in diretta dall'Angolo\n"
	.string "Lotteria Pokémon, al piano terra\l"
	.string "del Centro Commerciale di\l"
	.string "Porto Alghepoli!\p"
	.string "Come sempre, anche oggi la fortuna\n"
	.string "ha baciato un Allenatore!\p"
	.string "Il suo nome è…\n"
	.string "{STR_VAR_1}!\p"
	.string "{STR_VAR_1} ha vinto il {STR_VAR_2}\n"
	.string "premio: {STR_VAR_3}!\p"
	.string "{STR_VAR_1}!\n"
	.string "Congratulazioni!\p"
	.string "Telespettatori, non limitatevi a\n"
	.string "guardare: tentate anche voi la sorte!\p"
	.string "Tutto lo staff del Centro Commerciale\n"
	.string "di Porto Alghepoli vi aspetta!\p"
	.string "Era una diretta dal Centro\n"
	.string "Commerciale di Porto Alghepoli,\l"
	.string "con l'assortimento più vasto di\l"
	.string "Hoenn… e forse del Multiverso!$"

gTVThePokemonBattleSeminarText00::
	.string "Il Seminario di Lotta Pokémon!\p"
	.string "Analizziamo le lotte degli altri\n"
	.string "per imparare qualcosa anche noi.\p"
	.string "Il caso di oggi riguarda la lotta\n"
	.string "di {STR_VAR_1}.\p"
	.string "{STR_VAR_2} di {STR_VAR_1}\n"
	.string "stava lottando contro {STR_VAR_3}…$"

gTVThePokemonBattleSeminarText01::
	.string "E ha usato la mossa {STR_VAR_3}\n"
	.string "contro {STR_VAR_2}…\p"
	.string "Mmh… {STR_VAR_1}!\n"
	.string "Questa è proprio la mossa sbagliata!$"

gTVThePokemonBattleSeminarText02::
	.string "Oltre a quella mossa sciagurata,\n"
	.string "{STR_VAR_1} conosceva anche$"

gTVThePokemonBattleSeminarText03::
	.string "le mosse {STR_VAR_1}, {STR_VAR_2}\n"
	.string "e {STR_VAR_3}.$"

gTVThePokemonBattleSeminarText04::
	.string "le mosse {STR_VAR_1} e\n"
	.string "{STR_VAR_2}.$"

gTVThePokemonBattleSeminarText05::
	.string "la mossa {STR_VAR_2}.$"

gTVThePokemonBattleSeminarText06::
	.string "Dunque, in questa situazione, quale\n"
	.string "mossa sarebbe stata la scelta giusta?\p"
	.string "… … … … … …\n"
	.string "La mossa {STR_VAR_1}!\p"
	.string "{STR_VAR_1} sarebbe stata di gran\n"
	.string "lunga migliore di {STR_VAR_2}.\p"
	.string "Telespettatori, fate tesoro di questo\n"
	.string "caso e lottate con intelligenza!\p"
	.string "Alla prossima lezione, arrivederci!$"

gTVTrainerFanClubText00::
	.string "Tutti insieme, adesso!\n"
	.string "Il Fan Club dell'Allenatore!\p"
	.string "Conduttore: Come va, gente?\n"
	.string "Oggi abbiamo radunato i fan del\l"
	.string "popolarissimo Allenatore {STR_VAR_1}!\p"
	.string "Fan: Uooooooaaaaah!\p"
	.string "Fan: {STR_VAR_1}!\p"
	.string "Conduttore: Allora, gente!\n"
	.string "Che ne pensate di {STR_VAR_1}?!\p"
	.string "Fan: Adoriamo {STR_VAR_1}!\p"
	.string "Conduttore: E cosa adorate di\n"
	.string "{STR_VAR_1}?!$"

gTVTrainerFanClubText01::
	.string "Fan: Lo stile pazzesco con cui lancia\n"
	.string "le Poké Ball!$"

gTVTrainerFanClubText02::
	.string "Fan: Il modo adorabile in cui corre!$"

gTVTrainerFanClubText03::
	.string "Fan: Quando il gioco si fa duro,\n"
	.string "inizia a giocare sul serio!$"

gTVTrainerFanClubText04::
	.string "Fan: Tutto quello che sa\n"
	.string "sui Pokémon!$"

gTVTrainerFanClubText05::
	.string "Fan: La gentilezza con cui tratta tutti\n"
	.string "i Pokémon, anche quelli dei Varchi!$"

gTVTrainerFanClubText06::
	.string "Fan: Le acrobazie incredibili\n"
	.string "che fa in sella alla Bici!$"

gTVTrainerFanClubText07::
	.string "Fan: Lo stile impeccabile con cui\n"
	.string "fa acquisti al Pokémon Market!$"

gTVTrainerFanClubText08::
	.string "Fan: I soprannomi tenerissimi\n"
	.string "che dà ai suoi Pokémon!$"

gTVTrainerFanClubText09::
	.string "Fan: Il gusto con cui arreda\n"
	.string "la sua Base Segreta!$"

gTVTrainerFanClubText10::
	.string "Fan: Il coraggio con cui usa\n"
	.string "le MT!$"

gTVTrainerFanClubText11::
	.string "Conduttore: Visto? {STR_VAR_1}\n"
	.string "è rovente! Roba da scottarsi, uh!\p"
	.string "Tra i fan di {STR_VAR_1}\n"
	.string "gira uno slogan speciale!\p"
	.string "Conduttore: Quando dico {STR_VAR_1},\n"
	.string "voi dite…\p"
	.string "Fan: {STR_VAR_2}!\p"
	.string "Fan: {STR_VAR_3}!\p"
	.string "Fan: {STR_VAR_2}!\p"
	.string "Fan: {STR_VAR_3}!\p"
	.string "Conduttore: Esatto! Quando qualcuno\n"
	.string "dice “{STR_VAR_1}”…\p"
	.string "Voi rispondete: “{STR_VAR_2}\n"
	.string "{STR_VAR_3}!”\p"
	.string "Ha davvero un suono unico!\n"
	.string "Capisco perché tutti diventano fan\l"
	.string "di {STR_VAR_1}!\p"
	.string "E ora tocca a te, lì davanti alla TV!\n"
	.string "Tutti insieme!\p"
	.string "Conduttore: Quando dico {STR_VAR_1},\n"
	.string "voi dite…\p"
	.string "Fan: {STR_VAR_2}!\p"
	.string "Fan: {STR_VAR_3}!\p"
	.string "Fan: {STR_VAR_2}!\p"
	.string "Fan: {STR_VAR_3}!\p"
	.string "Conduttore: Grazie a tutti voi, fan\n"
	.string "scatenati di {STR_VAR_1}!\l"
	.string "Lo show finisce qui! Alla prossima!\p"
	.string "Conduttore: Quando dico {STR_VAR_1},\n"
	.string "voi dite…\p"
	.string "Fan: {STR_VAR_2}!\p"
	.string "Fan: {STR_VAR_3}!$"

TVSpotTheCuties_Text_Intro::
	.string "Che Carini!\n"
	.string "Pokémon coi Fiocchi!\p"
	.string "Salve, miei dolcissimi telespettatori!\p"
	.string "Sarete d'accordo con me: un Pokémon\n"
	.string "che sfoggia dei Fiocchi è divino!\p"
	.string "Oggi voglio presentarvi un Pokémon\n"
	.string "delizioso che ho notato durante\l"
	.string "una passeggiata in città.\p"
	.string "Il Pokémon carino del giorno è\n"
	.string "{STR_VAR_2} di {STR_VAR_1}.$"

TVSpotTheCuties_Text_RibbonsLow::
	.string "Il numero di Fiocchi che porta\n"
	.string "{STR_VAR_2} è {STR_VAR_3}.\p"
	.string "Questo dice molto su quanto\n"
	.string "{STR_VAR_1} adori il suo Pokémon.$"

TVSpotTheCuties_Text_RibbonsMid::
	.string "{STR_VAR_2} sfoggia ben\n"
	.string "{STR_VAR_3} Fiocchi!\p"
	.string "Ecco tutta la dedizione di\n"
	.string "{STR_VAR_1} per il suo Pokémon!$"

TVSpotTheCuties_Text_RibbonsHigh::
	.string "{STR_VAR_2} sfoggia l'incredibile\n"
	.string "cifra di {STR_VAR_3} Fiocchi!\p"
	.string "Che passione da vero collezionista\n"
	.string "da parte di {STR_VAR_1}!$"

TVSpotTheCuties_Text_RibbonIntro::
	.string "Diamo un'occhiata più da vicino ai\n"
	.string "tanti Fiocchi di {STR_VAR_2}.$"

TVSpotTheCuties_Text_RibbonChampion::
	.string "Il Fiocco Campione è particolarmente\n"
	.string "incantevole.\p"
	.string "{STR_VAR_2} l'ha ricevuto entrando\n"
	.string "nella Sala d'Onore.\p"
	.string "Esalta davvero il coraggio\n"
	.string "di {STR_VAR_2}.\p"
	.string "{STR_VAR_2} e il Fiocco Campione!\n"
	.string "Un abbinamento superefficace!$"

TVSpotTheCuties_Text_RibbonCool::
	.string "Il Fiocco Classe è particolarmente\n"
	.string "elegante.\p"
	.string "{STR_VAR_2} l'ha ricevuto vincendo\n"
	.string "una Gara Classe.\p"
	.string "Esalta davvero la classe\n"
	.string "di {STR_VAR_2}.\p"
	.string "{STR_VAR_2} e il Fiocco Classe!\n"
	.string "Un abbinamento superefficace!$"

TVSpotTheCuties_Text_RibbonBeauty::
	.string "Il Fiocco Bellezza è particolarmente\n"
	.string "incantevole.\p"
	.string "{STR_VAR_2} l'ha ricevuto vincendo\n"
	.string "una Gara Bellezza.\p"
	.string "Esalta davvero la bellezza\n"
	.string "di {STR_VAR_2}.\p"
	.string "{STR_VAR_2} e il Fiocco Bellezza!\n"
	.string "Un abbinamento superefficace!$"

TVSpotTheCuties_Text_RibbonCute::
	.string "Il Fiocco Grazia è particolarmente\n"
	.string "adorabile.\p"
	.string "{STR_VAR_2} l'ha ricevuto vincendo\n"
	.string "una Gara Grazia.\p"
	.string "Esalta davvero la grazia\n"
	.string "di {STR_VAR_2}.\p"
	.string "{STR_VAR_2} e il Fiocco Grazia!\n"
	.string "Un abbinamento superefficace!$"

TVSpotTheCuties_Text_RibbonSmart::
	.string "Il Fiocco Acume è particolarmente\n"
	.string "raffinato.\p"
	.string "{STR_VAR_2} l'ha ricevuto vincendo\n"
	.string "una Gara Acume.\p"
	.string "Esalta davvero l'acume\n"
	.string "di {STR_VAR_2}.\p"
	.string "{STR_VAR_2} e il Fiocco Acume!\n"
	.string "Un abbinamento superefficace!$"

TVSpotTheCuties_Text_RibbonTough::
	.string "Il Fiocco Grinta è particolarmente\n"
	.string "affascinante.\p"
	.string "{STR_VAR_2} l'ha ricevuto vincendo\n"
	.string "una Gara Grinta.\p"
	.string "Esalta davvero la grinta\n"
	.string "di {STR_VAR_2}.\p"
	.string "{STR_VAR_2} e il Fiocco Grinta!\n"
	.string "Un abbinamento superefficace!$"

TVSpotTheCuties_Text_RibbonWinning::
	.string "Il Fiocco Vittoria è particolarmente\n"
	.string "affascinante.\p"
	.string "{STR_VAR_2} l'ha ricevuto per le sue\n"
	.string "imprese alla Torre Lotta.\p"
	.string "Esalta davvero la potenza\n"
	.string "di {STR_VAR_2}.\p"
	.string "{STR_VAR_2} e il Fiocco Vittoria!\n"
	.string "Un abbinamento superefficace!$"

TVSpotTheCuties_Text_RibbonVictory::
	.string "Il Fiocco Trionfo è particolarmente\n"
	.string "splendido.\p"
	.string "{STR_VAR_2} l'ha ricevuto per le sue\n"
	.string "imprese alla Torre Lotta.\p"
	.string "Esalta davvero l'incredibile\n"
	.string "potenza di {STR_VAR_2}.\p"
	.string "{STR_VAR_2} e il Fiocco Trionfo!\n"
	.string "Un abbinamento superefficace!$"

TVSpotTheCuties_Text_RibbonArtist::
	.string "Il Fiocco Artista è particolarmente\n"
	.string "incantevole.\p"
	.string "{STR_VAR_2} l'ha ricevuto per aver\n"
	.string "posato come modello per un artista.\p"
	.string "Esalta davvero il fascino da star\n"
	.string "di {STR_VAR_2}.\p"
	.string "{STR_VAR_2} e il Fiocco Artista!\n"
	.string "Un abbinamento superefficace!$"

TVSpotTheCuties_Text_RibbonEffort::
	.string "Il Fiocco Impegno è particolarmente\n"
	.string "commovente.\p"
	.string "{STR_VAR_2} l'ha ricevuto per il suo\n"
	.string "impegno davvero instancabile.\p"
	.string "Esalta davvero la determinazione\n"
	.string "di {STR_VAR_2}.\p"
	.string "{STR_VAR_2} e il Fiocco Impegno!\n"
	.string "Un abbinamento superefficace!$"

TVSpotTheCuties_Text_Outro::
	.string "…Sospiro…\p"
	.string "Fiocchi e Pokémon…\n"
	.string "Stanno così bene insieme!\p"
	.string "Prima di svenire dall'emozione,\n"
	.string "vi saluto tutti! Ciao ciao!$"

gTVPokemonNewsBattleFrontierText00::
	.string "Buongiorno a tutti!\n"
	.string "È l'ora del TG Pokémon.\p"
	.string "Abbiamo notizie entusiasmanti\n"
	.string "dal Parco Lotta.$"

gTVPokemonNewsBattleFrontierText01::
	.string "L'Allenatore {STR_VAR_1} ha fissato\n"
	.string "un nuovo record: {STR_VAR_2} vittorie\l"
	.string "di fila nella Sala Lotta Singola\l"
	.string "della Torre Lotta.\p"
	.string "Evviva {STR_VAR_1}!$"

gTVPokemonNewsBattleFrontierText02::
	.string "L'Allenatore {STR_VAR_1} ha fissato\n"
	.string "un nuovo record: {STR_VAR_2} vittorie\l"
	.string "di fila nella Sala Lotta Doppia\l"
	.string "della Torre Lotta.\p"
	.string "Evviva {STR_VAR_1}!$"

gTVPokemonNewsBattleFrontierText03::
	.string "L'Allenatore {STR_VAR_1} ha fissato\n"
	.string "un nuovo record: {STR_VAR_2} vittorie\l"
	.string "di fila nella Sala Lotta Multipla\l"
	.string "della Torre Lotta.\p"
	.string "Evviva {STR_VAR_1}!$"

gTVPokemonNewsBattleFrontierText04::
	.string "L'Allenatore {STR_VAR_1} ha fissato\n"
	.string "un nuovo record: {STR_VAR_2} vittorie\l"
	.string "di fila nella Sala Lotta Multipla\l"
	.string "in Link della Torre Lotta.\p"
	.string "Evviva {STR_VAR_1}!$"

gTVPokemonNewsBattleFrontierText05::
	.string "L'Allenatore {STR_VAR_1} ha fissato\n"
	.string "un nuovo record: {STR_VAR_2} tornei\l"
	.string "vinti di fila nei Tornei in Singolo\l"
	.string "della Cupola Lotta.\p"
	.string "Un applauso a {STR_VAR_1}!$"

gTVPokemonNewsBattleFrontierText06::
	.string "L'Allenatore {STR_VAR_1} ha fissato\n"
	.string "un nuovo record: {STR_VAR_2} tornei\l"
	.string "vinti di fila nei Tornei in Doppio\l"
	.string "della Cupola Lotta.\p"
	.string "Un applauso a {STR_VAR_1}!$"

gTVPokemonNewsBattleFrontierText07::
	.string "L'Allenatore {STR_VAR_1} ha fissato\n"
	.string "un nuovo record: {STR_VAR_2} vittorie\l"
	.string "di fila nello Scambio Lotta in\l"
	.string "Singolo della Azienda Lotta.\p"
	.string "Onore a {STR_VAR_1}!$"

gTVPokemonNewsBattleFrontierText08::
	.string "L'Allenatore {STR_VAR_1} ha fissato\n"
	.string "un nuovo record: {STR_VAR_2} vittorie\l"
	.string "di fila nello Scambio Lotta in\l"
	.string "Doppio della Azienda Lotta.\p"
	.string "Onore a {STR_VAR_1}!$"

gTVPokemonNewsBattleFrontierText09::
	.string "L'Allenatore {STR_VAR_1} ha fissato\n"
	.string "un nuovo record: {STR_VAR_2} stanze\l"
	.string "superate nella sfida Scelta Lotta\l"
	.string "della Serpe Lotta.\p"
	.string "Onore a {STR_VAR_1}!$"

gTVPokemonNewsBattleFrontierText10::
	.string "L'Allenatore {STR_VAR_1} ha fissato\n"
	.string "un nuovo record: {STR_VAR_2} vittorie\l"
	.string "di fila nei Tornei KO\l"
	.string "del Dojo Lotta.\p"
	.string "Un applauso a {STR_VAR_1}!$"

gTVPokemonNewsBattleFrontierText11::
	.string "L'Allenatore {STR_VAR_1} ha fissato\n"
	.string "un nuovo record: {STR_VAR_2} vittorie\l"
	.string "di fila nella Sala Lotta Singola\l"
	.string "del Palazzo Lotta.\p"
	.string "Evviva {STR_VAR_1}!$"

gTVPokemonNewsBattleFrontierText12::
	.string "L'Allenatore {STR_VAR_1} ha fissato\n"
	.string "un nuovo record: {STR_VAR_2} vittorie\l"
	.string "di fila nella Sala Lotta Doppia\l"
	.string "del Palazzo Lotta.\p"
	.string "Evviva {STR_VAR_1}!$"

gTVPokemonNewsBattleFrontierText13::
	.string "L'Allenatore {STR_VAR_1} ha fissato\n"
	.string "un nuovo record: {STR_VAR_2} piani\l"
	.string "superati nella Piramide Lotta.\p"
	.string "Onore a {STR_VAR_1}!$"

gTVPokemonNewsBattleFrontierText14::
	.string "E ai tre Pokémon {STR_VAR_1},\n"
	.string "{STR_VAR_2} e {STR_VAR_3}!\p"
	.string "Complimenti per questa prestazione\n"
	.string "da record!$"

gTVPokemonNewsBattleFrontierText15::
	.string "E ai due Pokémon {STR_VAR_1}\n"
	.string "e {STR_VAR_2}!\p"
	.string "Complimenti per questa prestazione\n"
	.string "da record!$"

gTVPokemonNewsBattleFrontierText16::
	.string "E ai quattro Pokémon: {STR_VAR_1}!\p"
	.string "{STR_VAR_2}!\p"
	.string "{STR_VAR_3}!$"

gTVPokemonNewsBattleFrontierText17::
	.string "E {STR_VAR_1}!\p"
	.string "Complimenti per questa prestazione\n"
	.string "da record!$"

gTVPokemonNewsBattleFrontierText18::
	.string "Speriamo di vedere altre imprese\n"
	.string "da record da {STR_VAR_1} e dai suoi\l"
	.string "fedeli Pokémon!\p"
	.string "Per oggi è tutto dal TG Pokémon!$"

gTVWhatsNo1InHoennTodayText00::
	.string "Chi è il Numero Uno di Hoenn oggi?\n"
	.string "Sì, è di nuovo quel momento!\p"
	.string "Salve, telespettatori! State dando\n"
	.string "il massimo in tutto ciò che fate?\p"
	.string "Vediamo chi è l'Allenatore che oggi\n"
	.string "ha dato il meglio di sé!\p"
	.string "Il numero uno di oggi è nientemeno\n"
	.string "che {STR_VAR_1}!$"

gTVWhatsNo1InHoennTodayText01::
	.string "In un solo giorno, {STR_VAR_1} ha\n"
	.string "giocato alle slot machine del Casinò\l"
	.string "ben {STR_VAR_2} volte.\p"
	.string "Mentre giocava, {STR_VAR_1}\n"
	.string "mormorava: “Per me i rulli non\l"
	.string "si muovono nemmeno…”\l"
	.string "Curioso, non trovate?$"

gTVWhatsNo1InHoennTodayText02::
	.string "In un solo giorno, {STR_VAR_1} ha\n"
	.string "giocato alla roulette del Casinò\l"
	.string "ben {STR_VAR_2} volte.\p"
	.string "Mentre giocava, {STR_VAR_1} gridava:\n"
	.string "“Che decidano le palline!”\p"
	.string "Sguardo fisso e volto concentrato:\n"
	.string "che professionalità!$"

gTVWhatsNo1InHoennTodayText03::
	.string "In un solo giorno, {STR_VAR_1} ha\n"
	.string "affrontato Pokémon selvatici\l"
	.string "ben {STR_VAR_2} volte!\p"
	.string "Pare che i Pokémon di {STR_VAR_1}\n"
	.string "siano diventati fortissimi.\p"
	.string "Sembrano pronti a lottare ovunque,\n"
	.string "comunque e in qualunque momento!$"

gTVWhatsNo1InHoennTodayText04::
	.string "In un solo giorno, {STR_VAR_1} ha\n"
	.string "fatto girare il Frullabacche\l"
	.string "ben {STR_VAR_2} volte!\p"
	.string "Alla fine, perfino {STR_VAR_1}\n"
	.string "sembrava avere le vertigini.\p"
	.string "Barcollava di qua e di là,\n"
	.string "proprio come uno Spinda!$"

gTVWhatsNo1InHoennTodayText05::
	.string "In un solo giorno, {STR_VAR_1} ha\n"
	.string "piantato {STR_VAR_2} Bacche!\p"
	.string "Risultato: i vestiti di {STR_VAR_1}\n"
	.string "sono tutti sporchi di terra.\p"
	.string "Ma dove ha piantato, sono sbocciati\n"
	.string "fiori a non finire.\p"
	.string "Si dice che quei fiori sappiano\n"
	.string "rasserenare l'animo delle persone.$"

gTVWhatsNo1InHoennTodayText06::
	.string "In un solo giorno, {STR_VAR_1} ha\n"
	.string "raccolto {STR_VAR_2} Bacche!\p"
	.string "La Borsa di {STR_VAR_1} era così\n"
	.string "piena di Bacche che camminare\l"
	.string "è diventato un'impresa!$"

gTVWhatsNo1InHoennTodayText07::
	.string "In un solo giorno, {STR_VAR_1} ha\n"
	.string "guadagnato {STR_VAR_2} Punti Lotta!\p"
	.string "Poi, per {STR_VAR_1}, il dilemma:\n"
	.string "scambiarli con uno strumento super\l"
	.string "o con un mobile chic per la casa?\p"
	.string "Dicono che, mentre ci pensava,\n"
	.string "sorridesse da un orecchio all'altro!$"

gTVWhatsNo1InHoennTodayText08::
	.string "Ma che notizia, gente!\p"
	.string "{STR_VAR_1}!\n"
	.string "Oggi il numero 1 di Hoenn sei tu!\p"
	.string "Spettatori, prendete esempio\n"
	.string "da {STR_VAR_1}!\p"
	.string "Anche voi potete essere il numero 1,\n"
	.string "ogni santo giorno!$"

TVSecretBaseSecrets_Text_Intro::
	.string "Basi Segrete, Segreti Svelati!\p"
	.string "Cosa fanno gli Allenatori al riparo\n"
	.string "delle loro Basi Segrete?\p"
	.string "Oggi entriamo nella Base Segreta\n"
	.string "di {STR_VAR_1}.\p"
	.string "Oh? Guardate, abbiamo una visita:\n"
	.string "è {STR_VAR_2}!\p"
	.string "Diamo una sbirciatina!\p"
	.string "Cosa farà {STR_VAR_2}?$"

TVSecretBaseSecrets_Text_WhatWillPlayerDoNext1::
	.string "E ora, che cosa farà {STR_VAR_2}?$"

TVSecretBaseSecrets_Text_WhatWillPlayerDoNext2::
	.string "E adesso, {STR_VAR_2} cosa combinerà?$"

TVSecretBaseSecrets_Text_TookXStepsBeforeLeaving::
	.string "Alla fine, {STR_VAR_2} ha fatto\n"
	.string "{STR_VAR_3} passi nella Base Segreta\l"
	.string "di {STR_VAR_1} prima di andarsene.$"

TVSecretBaseSecrets_Text_BaseFailedToInterestPlayer::
	.string "Mmh…\p"
	.string "Sembra che la Base Segreta\n"
	.string "di {STR_VAR_1} non abbia colpito\l"
	.string "{STR_VAR_2}…$"

TVSecretBaseSecrets_Text_PlayerEnjoyedBase::
	.string "A {STR_VAR_2} la Base Segreta\n"
	.string "di {STR_VAR_1} è piaciuta un sacco!$"

TVSecretBaseSecrets_Text_PlayerHugeFanOfBase::
	.string "Per {STR_VAR_2} è amore a prima\n"
	.string "vista! Adora la Base Segreta\l"
	.string "di {STR_VAR_1}!$"

TVSecretBaseSecrets_Text_Outro::
	.string "Spettatori, fate un salto anche voi\n"
	.string "alla Base Segreta di {STR_VAR_1}!\p"
	.string "Alla prossima puntata, con un'altra\n"
	.string "Base Segreta! Grazie per la visione!$"

TVSecretBaseSecrets_Text_StoppedMoving1::
	.string "L'ospite non fa più un passo!\p"
	.string "Resta lì, immobile!\p"
	.string "Possibile che la Base Segreta\n"
	.string "di {STR_VAR_1} sia così noiosa?$"

TVSecretBaseSecrets_Text_StoppedMoving2::
	.string "L'ospite non fa più un passo!\p"
	.string "Non si muove di un millimetro!\p"
	.string "Che sia la stanchezza?\n"
	.string "Avrà bisogno di un pisolino?$"

TVSecretBaseSecrets_Text_UsedChair::
	.string "L'ospite prende posto su una sedia!\n"
	.string "Si accomoda!\p"
	.string "Guardate che espressione beata!\p"
	.string "Dev'essere una sedia davvero comoda,\n"
	.string "per fare quest'effetto!$"

TVSecretBaseSecrets_Text_UsedBalloon::
	.string "L'ospite si lancia contro\n"
	.string "un palloncino!\p"
	.string "BUM!\n"
	.string "Oh, cielo, è scoppiato!\p"
	.string "L'ospite fa un salto per lo\n"
	.string "spavento!$"

TVSecretBaseSecrets_Text_UsedTent::
	.string "L'ospite si infila in una tenda!\p"
	.string "E ora corre su e giù!\p"
	.string "Oh, che spettacolo, salta di gioia!\p"
	.string "Che stupore sul volto dell'ospite:\n"
	.string "è più grande dentro che fuori!\p"
	.string "Che ci sia un Varco là dentro?$"

TVSecretBaseSecrets_Text_UsedPlant::
	.string "L'ospite sta osservando\n"
	.string "una pianta in vaso!\p"
	.string "Che gusti raffinati!\n"
	.string "Chi l'avrebbe mai detto?$"

TVSecretBaseSecrets_Text_UsedGoldShield::
	.string "L'ospite sta esaminando\n"
	.string "uno Scudo d'Oro!\p"
	.string "Ha gli occhi che brillano\n"
	.string "di meraviglia!$"

TVSecretBaseSecrets_Text_UsedSilverShield::
	.string "L'ospite sta esaminando\n"
	.string "uno Scudo d'Argento!\p"
	.string "Guardate che occhi sgranati!$"

TVSecretBaseSecrets_Text_UsedGlassOrnament::
	.string "L'ospite sta esaminando\n"
	.string "un Ornamento di Vetro!\p"
	.string "Oh, no!\p"
	.string "Lo sta toccando!\p"
	.string "Si sta riempiendo di\n"
	.string "ditate…$"

TVSecretBaseSecrets_Text_UsedTV::
	.string "L'ospite accende la TV e si gode\n"
	.string "lo spettacolo!\p"
	.string "Chissà, magari sta guardando\n"
	.string "proprio noi!$"

TVSecretBaseSecrets_Text_UsedMudBall::
	.string "L'ospite pesta una Palla di Fango!\p"
	.string "Che faccia soddisfatta!$"

TVSecretBaseSecrets_Text_UsedBag::
	.string "…Oh?\p"
	.string "L'ospite si mette a frugare\n"
	.string "nella propria Borsa!\p"
	.string "Ed ecco che ne estrae:\n"
	.string "{STR_VAR_2}!\p"
	.string "Guardate che sorriso, con\n"
	.string "{STR_VAR_2} in mano!\p"
	.string "Sembra uno spot pubblicitario!$"

TVSecretBaseSecrets_Text_UsedCushion::
	.string "L'ospite afferra un cuscino e…$"

TVSecretBaseSecrets_Text_HitCushion::
	.string "…comincia a prenderlo a pugni!\p"
	.string "Quanto stress avrà accumulato?$"

TVSecretBaseSecrets_Text_HuggedCushion::
	.string "…lo stringe forte forte!\p"
	.string "Che sia successo qualcosa\n"
	.string "di bello?$"

TVSecretBaseSecrets_Text_BattledWon::
	.string "L'ospite sta chiacchierando\n"
	.string "con {STR_VAR_1}!\p"
	.string "Sembra proprio che stia per\n"
	.string "cominciare una lotta!\p"
	.string "E…\p"
	.string "Vince l'ospite!\n"
	.string "Una vittoria in trasferta!\p"
	.string "E ora si lancia in una\n"
	.string "danza della vittoria!$"

TVSecretBaseSecrets_Text_BattledLost::
	.string "L'ospite sta chiacchierando\n"
	.string "con {STR_VAR_1}!\p"
	.string "Sembra proprio che stia per\n"
	.string "cominciare una lotta!\p"
	.string "E…\p"
	.string "Vince {STR_VAR_1}!\n"
	.string "L'ospite ha perso!\p"
	.string "Ha l'aria proprio abbattuta!$"

TVSecretBaseSecrets_Text_DeclinedBattle::
	.string "L'ospite sta chiacchierando\n"
	.string "con {STR_VAR_1}!\p"
	.string "Sembra proprio che stia per\n"
	.string "cominciare una lotta!\p"
	.string "E…\p"
	.string "No! L'ospite ha rifiutato!\p"
	.string "Niente lotta, alla fine!\p"
	.string "Che {STR_VAR_1} non abbia fatto\n"
	.string "una buona impressione?$"

TVSecretBaseSecrets_Text_UsedPoster::
	.string "L'ospite fissa intensamente\n"
	.string "un poster!\p"
	.string "Sarà di suo gradimento?\p"
	.string "…Però… c'è qualcosa di inquietante\n"
	.string "in quello sguardo.$"

TVSecretBaseSecrets_Text_UsedNoteMat::
	.string "L'ospite pesta un tappeto musicale!\p"
	.string "…Mmh…\n"
	.string "Ne è uscita una melodia buffissima!$"

TVSecretBaseSecrets_Text_BattledDraw::
	.string "L'ospite sta chiacchierando\n"
	.string "con {STR_VAR_1}!\p"
	.string "Sembra proprio che stia per\n"
	.string "cominciare una lotta!\p"
	.string "E…\p"
	.string "È un pareggio!\n"
	.string "Nessun vincitore!\p"
	.string "Entrambi gli Allenatori sembrano\n"
	.string "molto delusi!$"

TVSecretBaseSecrets_Text_UsedSpinMat::
	.string "L'ospite pesta\n"
	.string "un Tappeto Rotante!\p"
	.string "Che giramento di testa!\p"
	.string "L'ospite barcolla qua e là!\n"
	.string "Attenzione!$"

TVSecretBaseSecrets_Text_UsedSandOrnament::
	.string "L'ospite allunga la mano verso\n"
	.string "un Ornamento di Sabbia!\p"
	.string "Oh!\p"
	.string "Si è sbriciolato!\n"
	.string "È andato in pezzi!\p"
	.string "L'ospite ha un'aria imbarazzata\n"
	.string "e colpevole!$"

TVSecretBaseSecrets_Text_UsedDesk::
	.string "L'ospite passa un dito\n"
	.string "sulla scrivania!\p"
	.string "A quanto pare, la polvere\n"
	.string "non è gradita!\p"
	.string "Una sorprendente passione per\n"
	.string "l'ordine e la pulizia!$"

TVSecretBaseSecrets_Text_UsedBrick::
	.string "L'ospite fissa un mattone!\p"
	.string "Forse sta pensando all'oggetto\n"
	.string "che ci sta sopra.$"

TVSecretBaseSecrets_Text_UsedSolidBoard::
	.string "L'ospite attraversa\n"
	.string "l'Asse Solida.\p"
	.string "Continua a guardare giù.\p"
	.string "Una sorprendente dose di timidezza\n"
	.string "e prudenza!$"

TVSecretBaseSecrets_Text_UsedFence::
	.string "L'ospite osserva attentamente\n"
	.string "un recinto!\p"
	.string "Che stia progettando una nuova\n"
	.string "trappola?$"

TVSecretBaseSecrets_Text_UsedGlitterMat::
	.string "L'ospite pesta\n"
	.string "un Tappeto Brillante!\p"
	.string "E si mette a fare pose\n"
	.string "di ogni tipo!\p"
	.string "Sembra sognare a occhi aperti\n"
	.string "di diventare una star!$"

TVSecretBaseSecrets_Text_UsedTire::
	.string "L'ospite fissa intensamente\n"
	.string "uno Pneumatico!\p"
	.string "Starà immaginando su che auto\n"
	.string "andrebbe montato?$"

TVSecretBaseSecrets_Text_UsedStand::
	.string "L'ospite sale su una Pedana!\p"
	.string "Da lassù domina tutta la Base\n"
	.string "di {STR_VAR_1}!\p"
	.string "E…\p"
	.string "Lancia un ruggito!\n"
	.string "L'ospite sta ruggendo!$"

TVSecretBaseSecrets_Text_BrokeDoor::
	.string "L'ospite si scaglia a testa bassa\n"
	.string "contro una Porta Fragile!\p"
	.string "E ride a crepapelle!$"

TVSecretBaseSecrets_Text_UsedDoll::
	.string "L'ospite parla con un peluche!\p"
	.string "…Un po' inquietante…$"

TVSecretBaseSecrets_Text_UsedSlide::
	.string "L'ospite sale la scaletta\n"
	.string "dello Scivolo!\p"
	.string "E…\p"
	.string "Giù a tutta velocità!\p"
	.string "Si sta divertendo\n"
	.string "un mondo!$"

TVSecretBaseSecrets_Text_UsedSlideButDidntGoDown::
	.string "L'ospite sale la scaletta\n"
	.string "dello Scivolo!\p"
	.string "E…\p"
	.string "Torna giù dalla\n"
	.string "scaletta!\p"
	.string "Un improvviso attacco di fifa?$"

TVSecretBaseSecrets_Text_UsedJumpMat::
	.string "L'ospite pesta\n"
	.string "un Tappeto Salto!\p"
	.string "Un salto!\p"
	.string "Due salti!\p"
	.string "E un atterraggio perfetto!\p"
	.string "L'ospite si fa un applauso!\n"
	.string "Che esibizione in solitaria!$"

gTVSafariFanClubText00::
	.string "Fan Club della Zona Safari!\p"
	.string "Inviato: Ehilà, amici!\n"
	.string "Tutti a lanciare Safari Ball, eh?\p"
	.string "Eccomi in diretta dalla Zona Safari,\n"
	.string "stracolma di Pokémon pazzeschi!\p"
	.string "C'è chi giura che certi esemplari\n"
	.string "siano sbucati da un Varco!\p"
	.string "Ma bando alle chiacchiere: parliamo\n"
	.string "con questa simpatica Guida Safari!\p"
	.string "Allora, amico, come se la cavano\n"
	.string "gli Allenatori in visita?$"

gTVSafariFanClubText01::
	.string "Guida: Tutti ci stanno dando\n"
	.string "dentro di brutto.\p"
	.string "{STR_VAR_1} se la cava benissimo!\p"
	.string "L'ultima volta ha catturato ben\n"
	.string "{STR_VAR_2} Pokémon.$"

gTVSafariFanClubText02::
	.string "E con le {POKEBLOCK} ci sa fare:\n"
	.string "ne ha usate {STR_VAR_2}, mi pare.$"

gTVSafariFanClubText03::
	.string "Non ha usato nemmeno una\n"
	.string "{POKEBLOCK}! Neanche una!\p"
	.string "Roba da veri esperti, credimi.$"

gTVSafariFanClubText04::
	.string "Inviato: Ma davvero?\p"
	.string "Allora {STR_VAR_1} è un vero\n"
	.string "asso del Safari!\p"
	.string "Guida: Spero che torni presto\n"
	.string "a mostrarci quella tecnica!$"

gTVSafariFanClubText05::
	.string "Guida: Pare che nessuno se la stia\n"
	.string "cavando granché.\p"
	.string "A {STR_VAR_1} è andata proprio male.\p"
	.string "L'ultima volta ha catturato\n"
	.string "appena {STR_VAR_2} Pokémon.$"

gTVSafariFanClubText06::
	.string "Guida: Pare che nessuno se la stia\n"
	.string "cavando granché.\p"
	.string "A {STR_VAR_1} è andata proprio male.\p"
	.string "L'ultima volta non ha catturato\n"
	.string "neanche un Pokémon. Nemmeno uno!$"

gTVSafariFanClubText07::
	.string "Le {POKEBLOCK} le usa, eh:\n"
	.string "ne ha usate {STR_VAR_2}, mi pare.\p"
	.string "Ma, accidenti, dovrebbe proprio\n"
	.string "fare un po' di pratica.$"

gTVSafariFanClubText08::
	.string "Secondo me avrebbe più fortuna\n"
	.string "con qualche {POKEBLOCK}: l'ultima\l"
	.string "volta non ne ha usata neanche una.$"

gTVSafariFanClubText09::
	.string "Inviato: Ma davvero?\p"
	.string "Allora a {STR_VAR_1} manca ancora\n"
	.string "un po' di esperienza da Safari!\p"
	.string "Guida: Spero che torni ancora e\n"
	.string "ancora, finché non ci prende la mano.$"

gTVSafariFanClubText10::
	.string "Inviato: Giustissimo!\n"
	.string "Le sfide vanno affrontate!\p"
	.string "Spettatori, venite anche voi alla\n"
	.string "Zona Safari a mettervi alla prova!\p"
	.string "Alla prossima, e buone catture!$"

ContestLiveUpdates_Text_Intro::
	.string "“Gare Pokémon in Diretta!”\p"
	.string "Presentatore: Grazie di essere con noi!\p"
	.string "Siamo in diretta dalla sala della\n"
	.string "{STR_VAR_1}, appena conclusa.\p"
	.string "Il pubblico è ancora qui: nessuno\n"
	.string "ha voglia di andarsene!\p"
	.string "Spettatore: {STR_VAR_2}!\p"
	.string "Spettatore: {STR_VAR_3}!\p"
	.string "Presentatore: Come avete sentito,\n"
	.string "la Gara è stata vinta da {STR_VAR_2},\l"
	.string "il Pokémon di {STR_VAR_3}.\p"
	.string "Spettatore: {STR_VAR_2}!\n"
	.string "Sei il migliore!\p"
	.string "Spettatore: {STR_VAR_3}!\n"
	.string "Sei un mito!\p"
	.string "Presentatore: Sentiamo cosa ne\n"
	.string "pensano i fan di questa Gara!$"

ContestLiveUpdates_Text_WonBothRounds::
	.string "Spettatore: {STR_VAR_2} è stato il\n"
	.string "migliore in entrambe le fasi!\p"
	.string "{STR_VAR_2} non lo ferma nessuno!$"

ContestLiveUpdates_Text_BetterRound2::
	.string "Spettatore: {STR_VAR_2} è partito\n"
	.string "male nella prima fase, ma nella\l"
	.string "seconda ha fatto piazza pulita!\p"
	.string "Che rimonta miracolosa per\n"
	.string "{STR_VAR_2}! Evviva!$"

ContestLiveUpdates_Text_EqualRounds::
	.string "Spettatore: {STR_VAR_2} è stato\n"
	.string "costante in tutte e due le fasi.\p"
	.string "{STR_VAR_3} e {STR_VAR_2}…\n"
	.string "che coppia straordinaria!$"

ContestLiveUpdates_Text_BetterRound1::
	.string "Spettatore: In fatto di {STR_VAR_1},\n"
	.string "{STR_VAR_2} è stato eccezionale.\p"
	.string "Però la prossima volta spero\n"
	.string "che faccia esibizioni migliori.$"

ContestLiveUpdates_Text_GotNervous::
	.string "Spettatore: Quando {STR_VAR_2} si è\n"
	.string "agitato, non ho resistito: ho urlato\l"
	.string "per fargli coraggio!\p"
	.string "Ora voglio dirgli solo una cosa:\n"
	.string "“Congratulazioni, {STR_VAR_2}!”$"

ContestLiveUpdates_Text_StartledFoes::
	.string "Spettatore: L'esibizione di\n"
	.string "{STR_VAR_2} ha fatto sobbalzare\l"
	.string "perfino me!\p"
	.string "{STR_VAR_2}, sei stato grandioso!$"

ContestLiveUpdates_Text_UsedCombo::
	.string "Spettatore: La combinazione di\n"
	.string "{STR_VAR_2} è stata strepitosa!\p"
	.string "Mi ha scosso fin nel profondo!$"

ContestLiveUpdates_Text_ExcitingAppeal::
	.string "Spettatore: {STR_VAR_2} ha vinto con\n"
	.string "un'esibizione da batticuore!$"

ContestLiveUpdates_Text_WasCool::
	.string "{STR_VAR_2}!\n"
	.string "Che classe!$"

ContestLiveUpdates_Text_WasBeautiful::
	.string "{STR_VAR_2}!\n"
	.string "Che splendore!$"

ContestLiveUpdates_Text_WasCute::
	.string "{STR_VAR_2}!\n"
	.string "Che tenerezza!$"

ContestLiveUpdates_Text_WasSmart::
	.string "{STR_VAR_2}!\n"
	.string "Che intelligenza!$"

ContestLiveUpdates_Text_WasTough::
	.string "{STR_VAR_2}!\n"
	.string "Che grinta!$"

ContestLiveUpdates_Text_VeryExcitingAppeal::
	.string "Spettatore: {STR_VAR_2} ha vinto e il\n"
	.string "mio cuore batte ancora a mille!$"

ContestLiveUpdates_Text_VeryCool::
	.string "{STR_VAR_2}!\n"
	.string "Sei la classe in persona!$"

ContestLiveUpdates_Text_VeryBeautiful::
	.string "{STR_VAR_2}!\n"
	.string "Sei uno splendore assoluto!$"

ContestLiveUpdates_Text_VeryCute::
	.string "{STR_VAR_2}!\n"
	.string "Sei la cosa più tenera del mondo!$"

ContestLiveUpdates_Text_VerySmart::
	.string "{STR_VAR_2}!\n"
	.string "Sei il più geniale dei geni!$"

ContestLiveUpdates_Text_VeryTough::
	.string "{STR_VAR_2}!\n"
	.string "Sei il più tosto dei tosti!$"

ContestLiveUpdates_Text_TookBreak::
	.string "Spettatore: Anche quando {STR_VAR_2}\n"
	.string "saltava un turno, non riuscivo\l"
	.string "a staccargli gli occhi di dosso.\p"
	.string "{STR_VAR_2} mi ha stregato!$"

ContestLiveUpdates_Text_GotStartled::
	.string "Spettatore: Quando {STR_VAR_2} si è\n"
	.string "spaventato per l'esibizione di un\l"
	.string "altro Pokémon, quasi piangevo.\p"
	.string "{STR_VAR_2}, hai tenuto duro!\n"
	.string "Grande!$"

ContestLiveUpdates_Text_MoveWonderful::
	.string "Spettatore: Oh…\n"
	.string "{STR_VAR_3} di {STR_VAR_2}!\l"
	.string "{STR_VAR_3} di {STR_VAR_2}!\l"
	.string "{STR_VAR_3} di {STR_VAR_2}!\l"
	.string "Come può una mossa essere così bella?$"

ContestLiveUpdates_Text_TalkAboutAnotherMon::
	.string "Presentatore: Ecco, l'avete sentito!\n"
	.string "Qui è pieno di fan di {STR_VAR_1}!\p"
	.string "Devo dire che anche un altro Pokémon,\n"
	.string "{STR_VAR_3} di {STR_VAR_2},\l"
	.string "mi ha colpito.\p"
	.string "{STR_VAR_3} di {STR_VAR_2}…$"

ContestLiveUpdates_Text_FailedToAppeal::
	.string "Per il nervosismo, nella seconda fase\n"
	.string "non ha fatto neanche un'esibizione.\p"
	.string "La prossima volta vorrei vedere\n"
	.string "{STR_VAR_1} esibirsi almeno una volta.$"

ContestLiveUpdates_Text_LastInBothRounds::
	.string "È arrivato ultimo sia nella prima\n"
	.string "sia nella seconda fase.\p"
	.string "Spero che {STR_VAR_1} alleni di nuovo\n"
	.string "{STR_VAR_2} e cancelli l'onta di\l"
	.string "quest'ultimo posto indiscusso.$"

ContestLiveUpdates_Text_NotExcitingEnough::
	.string "Non ha saputo sfruttare l'entusiasmo\n"
	.string "del pubblico con un'esibizione\l"
	.string "all'altezza.\p"
	.string "Speriamo che {STR_VAR_1} impari a\n"
	.string "leggere il pubblico e a mandarlo\l"
	.string "in visibilio, la prossima volta.$"

ContestLiveUpdates_Text_LostAfterWinningRound1::
	.string "Dopo aver vinto la prima fase, nella\n"
	.string "seconda ha fatto cilecca.\p"
	.string "Si è fatto rimontare: una sconfitta\n"
	.string "davvero umiliante.\p"
	.string "Di certo {STR_VAR_1} sta già\n"
	.string "studiando esibizioni più efficaci.$"

ContestLiveUpdates_Text_NeverExciting::
	.string "Nella seconda fase, le sue esibizioni\n"
	.string "non hanno mai scaldato il pubblico.\p"
	.string "Speriamo che smetta di badare\n"
	.string "agli altri Pokémon e impari\l"
	.string "a esibirsi per il pubblico.$"

ContestLiveUpdates_Text_LostBySmallMargin::
	.string "Ha perso contro {STR_VAR_2} di\n"
	.string "{STR_VAR_1} per un soffio.\p"
	.string "Dev'essere straziante arrivare così\n"
	.string "vicino alla vittoria e poi fallire.\p"
	.string "Non mi stupirei se {STR_VAR_3}\n"
	.string "stesse piangendo per com'è andata.$"
ContestLiveUpdates_Text_RepeatedAppeals::
	.string "Ha deluso il Giudice ripetendo\n"
	.string "sempre la stessa esibizione.\p"
	.string "Nelle Gare è un errore imperdonabile,\n"
	.string "e a pagarne il prezzo è il Pokémon.\p"
	.string "{STR_VAR_1} dovrebbe sentirsi in colpa\n"
	.string "per questa pessima figura.$"

ContestLiveUpdates_Text_ValiantEffortButLost::
	.string "{STR_VAR_1} ce l'ha messa tutta,\n"
	.string "ma…\p"
	.string "…non è servito a nulla: ultimo posto.\p"
	.string "{STR_VAR_1} dovrebbe imparare da questa\n"
	.string "sconfitta e farne tesoro.$"

ContestLiveUpdates_Text_Outro::
	.string "Chiudiamo la puntata con il nostro\n"
	.string "solito saluto ai vincitori.\p"
	.string "Questa volta tocca a {STR_VAR_1}\n"
	.string "e a {STR_VAR_2}!\p"
	.string "Presentatore: Siete pronti?\n"
	.string "Tutti insieme!\p"
	.string "Pubblico: {STR_VAR_1}! {STR_VAR_2}!\n"
	.string "Congratulazioni!\l"
	.string "Avete vinto la Gara!$"

gTVPokemonBattleUpdateText00::
	.string "“Lotte Pokémon: Ultim'Ora!”\p"
	.string "I risultati delle Lotte Pokémon in\n"
	.string "tempo reale, da ogni angolo di Hoenn!$"

gTVPokemonBattleUpdateText01::
	.string "Gli Allenatori {STR_VAR_1} e\n"
	.string "{STR_VAR_2} si sono sfidati\l"
	.string "in una Lotta {STR_VAR_3}.\p"
	.string "L'incontro si è concluso con la\n"
	.string "vittoria di {STR_VAR_1}!$"

gTVPokemonBattleUpdateText02::
	.string "In campo, {STR_VAR_2} di {STR_VAR_1}\n"
	.string "ha fatto faville usando\l"
	.string "{STR_VAR_3}!$"

gTVPokemonBattleUpdateText03::
	.string "{STR_VAR_2} di {STR_VAR_1}, invece,\n"
	.string "ha deluso parecchio. Che peccato!$"

gTVPokemonBattleUpdateText04::
	.string "Complimenti per la vittoria,\n"
	.string "{STR_VAR_1}!\p"
	.string "E a {STR_VAR_2}, che ha perso,\n"
	.string "auguriamo più fortuna alla prossima!\p"
	.string "Si chiude qui questa puntata di\n"
	.string "“Lotte Pokémon: Ultim'Ora!”$"

gTVPokemonBattleUpdateText05::
	.string "Le squadre di {STR_VAR_1} e {STR_VAR_2}\n"
	.string "si sono sfidate in una Lotta Multipla.\p"
	.string "L'incontro si è concluso con la\n"
	.string "vittoria della squadra di {STR_VAR_1}.$"

gTVPokemonBattleUpdateText06::
	.string "Nella squadra di {STR_VAR_1},\n"
	.string "{STR_VAR_2} ha dominato il campo\l"
	.string "con {STR_VAR_3}.$"

gTVPokemonBattleUpdateText07::
	.string "Nella squadra di {STR_VAR_2}, invece,\n"
	.string "{STR_VAR_3} ha deluso parecchio.\p"
	.string "Complimenti alla tua squadra per la\n"
	.string "vittoria, {STR_VAR_1}!\p"
	.string "Alla squadra sconfitta di {STR_VAR_2}\n"
	.string "auguriamo più fortuna alla prossima!\p"
	.string "Si chiude qui questa puntata di\n"
	.string "“Lotte Pokémon: Ultim'Ora!”$"

GabbyAndTy_Text_GabbyPreFirstBattle:
	.string "Gabby: Oh! Guarda che Allenatore tosto\n"
	.string "abbiamo trovato, proprio qui!\p"
	.string "Bene, motore, si gira!\n"
	.string "Facciamogli un'intervista!$"

GabbyAndTy_Text_GabbyIntro:
	.string "Gabby: Oh! Ma sei {PLAYER}! Ciao!\n"
	.string "Ti ricordi di noi dall'ultima volta?\p"
	.string "Ci fai vedere quanto sei diventato\n"
	.string "forte? Bene, via con l'intervista!$"

GabbyAndTy_Text_GabbyDefeatFirstTime:
	.string "Gabby: I miei occhi non sbagliano!\n"
	.string "Ho scoperto un Allenatore pazzesco!$"

GabbyAndTy_Text_WhoAreYouInterview:
	.string "Gabby: Incredibile! Incredibile!\n"
	.string "Ma chi sei?!\p"
	.string "Lo sapevo che avevamo fiutato qualcosa\n"
	.string "di grosso appena ti abbiamo visto!\p"
	.string "Oh, scusa, mi spiego. Noi giriamo\n"
	.string "tutta Hoenn, Varchi permettendo, per\l"
	.string "intervistare Allenatori di ogni tipo.\p"
	.string "Allora, ci concedi un po' del tuo tempo\n"
	.string "per un'intervista?$"

GabbyAndTy_Text_QuoteFromLastInterview:
	.string "Gabby: “{STR_VAR_1}!”\p"
	.string "Ti ricordi? È la frase a effetto che\n"
	.string "ci hai regalato l'ultima volta.\p"
	.string "Io queste cose non le dimentico mai!$"

GabbyAndTy_Text_YouStompedUsInterviewAgain:
	.string "L'ultima volta ci hai travolti prima\n"
	.string "ancora che potessimo prepararci…\p"
	.string "Comunque, che ne dici?\n"
	.string "Ti va di farti intervistare di nuovo?$"

GabbyAndTy_Text_YouThrewABallAtUsInterviewAgain:
	.string "L'ultima volta che abbiamo lottato,\n"
	.string "non ci avevi lanciato una Poké Ball?\p"
	.string "Che shock! Così l'abbiamo raccontato\n"
	.string "a tutti, ma proprio a tutti!\p"
	.string "Comunque, che ne dici?\n"
	.string "Ti va di farti intervistare di nuovo?$"

GabbyAndTy_Text_CleverItemSkillsInterviewAgain:
	.string "L'ultima volta ci hai messi al tappeto\n"
	.string "usando gli strumenti con astuzia.\p"
	.string "Comunque, che ne dici?\n"
	.string "Ti va di farti intervistare di nuovo?$"

GabbyAndTy_Text_WeLookedRespectableInterviewAgain:
	.string "L'ultima volta che abbiamo lottato,\n"
	.string "abbiamo fatto almeno una bella figura.\p"
	.string "Comunque, che ne dici?\n"
	.string "Ti va di farti intervistare di nuovo?$"

GabbyAndTy_Text_InterviewAgain:
	.string "Comunque, che ne dici?\n"
	.string "Ti va di farti intervistare di nuovo?$"

GabbyAndTy_Text_DescribeYourFeelings:
	.string "Davvero?\n"
	.string "Grazie mille!\p"
	.string "Allora, descrivimi cosa hai provato\n"
	.string "durante la nostra lotta, ma in modo\l"
	.string "breve e incisivo. Vai!$"

GabbyAndTy_Text_PerfectWellBeSeeingYou:
	.string "Gabby: Mmm, sì!\n"
	.string "È la frase a effetto perfetta!\p"
	.string "Sento che ne verrà fuori un servizio\n"
	.string "televisivo fantastico.\p"
	.string "Potrebbero mandarlo in onda presto,\n"
	.string "quindi tieni d'occhio la TV!\p"
	.string "Bene!\n"
	.string "Alla prossima!$"

GabbyAndTy_Text_DontGiveUpKeepingEyeOut:
	.string "Gabby: Oh…\p"
	.string "Va bene, ma non mollare!\n"
	.string "Noi continueremo a tenerti d'occhio!$"

GabbyAndTy_Text_KeepingAnEyeOutForYou:
	.string "Gabby: Continueremo a tenerti\n"
	.string "d'occhio!$"

GabbyAndTy_Text_GabbyNotEnoughMons:
	.string "Gabby: Non c'è un Allenatore forte\n"
	.string "in giro con un bel po' di Pokémon?$"

GabbyAndTy_Text_GiveUsAnInterviewThisTime:
	.string "Gabby: Wow, sei proprio un fenomeno!\p"
	.string "Sei diventato più forte, molto più\n"
	.string "forte, dalla nostra ultima lotta.\p"
	.string "Avevamo visto giusto: sei proprio\n"
	.string "un Allenatore da prima pagina!\p"
	.string "Allora, che ne dici?\n"
	.string "Stavolta ci concedi\l"
	.string "un'intervista?$"

GabbyAndTy_Text_GabbyDefeat:
	.string "Gabby: Che lotta intensa!\n"
	.string "Ty, hai ripreso tutto?$"

GabbyAndTy_Text_TyPreFirstBattle:
	.string "Ty: Ehi, guarda qua! Un Allenatore\n"
	.string "tosto, proprio in questo posto!\l"
	.string "La telecamera è accesa!$"

GabbyAndTy_Text_TyIntro:
	.string "Ty: Ehi, guarda qua!\n"
	.string "Io ti conosco!\p"
	.string "Riprenderò tutta la lotta con questa\n"
	.string "telecamera!$"

GabbyAndTy_Text_TyPostBattle:
	.string "Ty: Sei un talento naturale!\n"
	.string "Ho girato delle riprese da urlo!$"

GabbyAndTy_Text_TyNotEnoughMons:
	.string "Ty: Hai un Pokémon solo\n"
	.string "e basta?\p"
	.string "Con più Pokémon le riprese verrebbero\n"
	.string "molto meglio, ma…$"

GabbyAndTy_Text_TyDefeatFirstTime:
	.string "Ty: Sì, abbiamo beccato un vero asso.\n"
	.string "Altro che Varchi: questo è lo scoop!$"

GabbyAndTy_Text_TyDefeat:
	.string "Ty: Sì, ho ripreso tutto.\n"
	.string "L'intera lotta è in video.$"

gTVInSearchOfTrainersText00::
	.string "A caccia di Allenatori…\p"
	.string "Gabby: Ciao a tutti! Oggi sono nei\n"
	.string "pressi di {STR_VAR_1}.\p"
	.string "Tra un Varco e l'altro, siamo in cerca\n"
	.string "di nuovi talenti emergenti.\p"
	.string "Oggi abbiamo puntato l'obiettivo\n"
	.string "sull'Allenatore {PLAYER}.\p"
	.string "C'è qualcosa in questo Allenatore\n"
	.string "che ha catturato la nostra attenzione.$"

gTVInSearchOfTrainersText01::
	.string "Avevamo già lottato contro {PLAYER},\n"
	.string "e possiamo garantire che è\l"
	.string "decisamente migliorato da allora.\p"
	.string "Lo sapevo che era un tipo speciale,\n"
	.string "fin da quando l'abbiamo notato!$"

gTVInSearchOfTrainersText02::
	.string "Il modo migliore per capire quanto è\n"
	.string "forte un Allenatore…\p"
	.string "Beh, il più rapido è lottarci contro.\n"
	.string "E così è iniziata la nostra indagine!\p"
	.string "… …\p"
	.string "Ed è così che ci siamo ritrovati\n"
	.string "a lottare contro {PLAYER}.\p"
	.string "Con una prova schiacciante, ci ha\n"
	.string "stesi, arrotolati e buttati via!\p"
	.string "{PLAYER} è spietatamente forte…\p"
	.string "Ecco le nostre impressioni dopo aver\n"
	.string "lottato contro il nostro protagonista.$"

gTVInSearchOfTrainersText03::
	.string "L'intesa tra {STR_VAR_1} e\n"
	.string "{STR_VAR_3} era divina!\p"
	.string "Vederli, {STR_VAR_1} e\n"
	.string "{STR_VAR_3}, sostenersi a vicenda\l"
	.string "nel pieno della lotta…\p"
	.string "È stato uno spettacolo meraviglioso!\p"
	.string "{STR_VAR_2} è stata l'ultima mossa\n"
	.string "usata dall'Allenatore in lotta.\p"
	.string "La mossa {STR_VAR_2} è il simbolo\n"
	.string "dell'amicizia tra {STR_VAR_1}\l"
	.string "e {STR_VAR_3}!$"

gTVInSearchOfTrainersText04::
	.string "…Dopo quell'incontro ho perso tutta\n"
	.string "la fiducia in me stessa.\p"
	.string "Ci ha battuti prima ancora che\n"
	.string "potessimo sferrare un solo attacco.\l"
	.string "Uuuh… Sob…\p"
	.string "Nonostante ciò, le lotte di {PLAYER}\n"
	.string "meritano di essere viste.\p"
	.string "Consiglio agli Allenatori più sicuri\n"
	.string "di sé di sfidare {PLAYER}.$"

gTVInSearchOfTrainersText05::
	.string "C'è solo una cosa da dire.\n"
	.string "Non osate lanciare una Poké Ball\l"
	.string "durante una lotta tra Allenatori!\p"
	.string "{PLAYER} è forte, non c'è dubbio, ma\n"
	.string "non conosce le regole di base.\p"
	.string "Ai telespettatori chiedo un favore.\p"
	.string "Se incontrate {PLAYER}, per favore,\n"
	.string "fategli una bella ramanzina!$"

gTVInSearchOfTrainersText06::
	.string "{PLAYER} sa leggere alla perfezione\n"
	.string "le mosse dell'avversario.\p"
	.string "Ha usato gli strumenti al momento\n"
	.string "giusto, con un'efficacia incredibile!$"

gTVInSearchOfTrainersText07::
	.string "Sinceramente, pensavo di essere\n"
	.string "piuttosto brava anch'io.\p"
	.string "Alla fine abbiamo perso, ma è stata\n"
	.string "una lotta davvero combattuta.\p"
	.string "Però, se fai fatica contro di me,\n"
	.string "ti resta tanta strada da fare, {PLAYER}!$"

gTVInSearchOfTrainersText08::
	.string "Dopo la lotta, abbiamo chiesto a\n"
	.string "{PLAYER} un breve commento.\p"
	.string "L'Allenatore ha risposto: “{STR_VAR_1}.”\p"
	.string "I Pokémon di {PLAYER}, {STR_VAR_2} e\n"
	.string "{STR_VAR_3}…\l"
	.string "E poi “{STR_VAR_1}”…\p"
	.string "Mmm! Che profondità! Dietro quelle\n"
	.string "parole c'è un significato enorme!\p"
	.string "Non c'è da stupirsi: un bravo Allenatore\n"
	.string "sa sempre cosa dire.\p"
	.string "Per oggi è tutto!\n"
	.string "Alla prossima puntata!$"

ContestLadyShow_Text_Intro::
	.string "“Gare Pokémon in Diretta!”\p"
	.string "Presentatore: Scusate l'interruzione\n"
	.string "e grazie per essere con noi!\p"
	.string "Vi trasmettiamo in diretta dal luogo\n"
	.string "dove si è appena conclusa\l"
	.string "la {STR_VAR_1}!\p"
	.string "Spettatori: ?!!!!\p"
	.string "Presentatore: Oh! Sembra che i\n"
	.string "concorrenti stiano venendo qui!\p"
	.string "Proverò a strappare un'intervista\n"
	.string "al volo per voi a casa!\p"
	.string "Spettatori: ?!!!!\n"
	.string "?!!!!$"

ContestLadyShow_Text_Won::
	.string "Presentatore: Mi scusi!\n"
	.string "Grazie per essere in diretta con noi!\p"
	.string "Posso farle i complimenti per la\n"
	.string "vittoria?\p"
	.string "Qual è stata la chiave di questo\n"
	.string "trionfo strepitoso?\p"
	.string "Bellezza: Oggi abbiamo dato il massimo,\n"
	.string "io e il mio {STR_VAR_2}!\p"
	.string "Ma di sicuro non ce l'avremmo fatta\n"
	.string "senza tutto l'aiuto che abbiamo\l"
	.string "ricevuto prima della Gara!\p"
	.string "Presentatore: C'è una persona speciale\n"
	.string "con cui vuole condividere la sua gioia?\l"
	.string "Coraggio, siamo in diretta!\p"
	.string "Bellezza: Ehi, ciao!\p"
	.string "{STR_VAR_3}! Mi stai guardando?\n"
	.string "Ce l'abbiamo fatta!\l"
	.string "Grazie di cuore!$"

ContestLadyShow_Text_Lost::
	.string "Presentatore: Mi scusi!\n"
	.string "Grazie per essere in diretta con noi!\p"
	.string "Immagino sia delusa da com'è andata.\n"
	.string "Vuole dire qualcosa?\p"
	.string "Bellezza: È straziante… Io e il mio\n"
	.string "{STR_VAR_2} abbiamo dato tutto…\p"
	.string "Ma sento di aver deluso tutti quelli\n"
	.string "che ci hanno sostenuto fin qui.\p"
	.string "Presentatore: Mi spiace dirlo, ma il\n"
	.string "Pokémon non era tirato a lucido.\p"
	.string "Bellezza: {STR_VAR_3}, scusami tanto…\n"
	.string "La prossima volta farò meglio, giuro…\l"
	.string "…Sniff… Uaaaaah!\p"
	.string "Spettatori: Avete visto?\n"
	.string "Poverina!\p"
	.string "Presentatore: Ehm… Oh, oh…\p"
	.string "Ehm… Il nostro tempo è finito!\n"
	.string "Grazie per averci seguito!$"

ContestLadyShow_Text_LostBadly::
	.string "Presentatore: Mi scusi!\n"
	.string "Grazie per essere in diretta con noi!\p"
	.string "Com'è andata la sua esibizione?\p"
	.string "Bellezza: È andato tutto storto…\n"
	.string "Non so perché, ma il mio {STR_VAR_2}\l"
	.string "non ha conquistato nessuno.\p"
	.string "Presentatore: Mi spiace dirlo, ma il\n"
	.string "Pokémon non era tirato a lucido.\p"
	.string "Bellezza: … … … … … …\n"
	.string "…Sniff… Uaaaaah!\p"
	.string "Spettatori: Avete visto?\n"
	.string "Poverina!\p"
	.string "Presentatore: Ehm… Oh, oh…\p"
	.string "Ehm… Il nostro tempo è finito!\n"
	.string "Grazie per averci seguito!$"
