FortreeCity_House3_MapScripts::
	.byte 0

FortreeCity_House3_EventScript_Maniac::
	msgbox FortreeCity_House3_Text_MetStevenHadAmazingPokemon, MSGBOX_NPC
	end

FortreeCity_House3_EventScript_SchoolKidM::
	msgbox FortreeCity_House3_Text_OhYouHavePokedex, MSGBOX_NPC
	end

FortreeCity_House3_Text_MetStevenHadAmazingPokemon:
	.string "A proposito di Pokédex, mi è tornata\n"
	.string "in mente una cosa.\p"
	.string "Ho conosciuto un Allenatore, Rocco,\n"
	.string "mentre cercavo pietre rare.\p"
	.string "Accidenti, aveva con sé dei Pokémon\n"
	.string "incredibili!\p"
	.string "Non erano solo rari: erano allenati\n"
	.string "fino a livelli spaventosi!\p"
	.string "Diceva che le pietre che cercava erano\n"
	.string "cadute da altri mondi… Che tipo!\p"
	.string "Forse è persino più forte della\n"
	.string "Capopalestra di questa città…$"

FortreeCity_House3_Text_OhYouHavePokedex:
	.string "Cos'è quell'aggeggio che hai lì?\p"
	.string "… … … … … …\p"
	.string "Oh, si chiama Pokédex?\n"
	.string "È fortissimo!$"

