PetalburgCity_House2_MapScripts::
	.byte 0

PetalburgCity_House2_EventScript_Woman::
	msgbox PetalburgCity_House2_Text_NormanBecameGymLeader, MSGBOX_NPC
	end

PetalburgCity_House2_EventScript_SchoolKid::
	msgbox PetalburgCity_House2_Text_BattledNormanOnce, MSGBOX_NPC
	end

PetalburgCity_House2_Text_NormanBecameGymLeader:
	.string "Norman è il nuovo Capopalestra\n"
	.string "della nostra città.\p"
	.string "La sua famiglia è venuta fin qui da\n"
	.string "Porto Alghepoli, dall'altra parte\l"
	.string "di Hoenn.\p"
	.string "Dicono che la Lega gli abbia chiesto\n"
	.string "di tenere d'occhio i Varchi della zona.$"

PetalburgCity_House2_Text_BattledNormanOnce:
	.string "Una volta ho sfidato Norman, ma…\n"
	.string "uff, era fin troppo forte.\p"
	.string "Come dire?\p"
	.string "Ho avuto la sensazione che vivesse\n"
	.string "solo per i Pokémon.$"

