export const meta = {
  name: 'multiverse-engine-localization',
  description: 'Translate engine/C strings of the ROM hack into official Italian (moves, items, abilities, Pokédex, battle, menus, texts)',
  phases: [{ title: 'Localize', detail: 'one translator per batch, validated with ctextcheck' }],
}
const COMMON = `
You are localizing the ENGINE TEXT of "Pokémon Multiverse" (Italian ROM hack of Pokémon Emerald, pokeemerald-expansion 1.17.1) into ITALIAN, using the official Italian Pokémon terminology. The final game must be entirely in Italian.
Official Italian data extracted from PokeAPI (use it whenever it applies, it is authoritative): /home/user/work/pokeapi_it/ — moves.json, flavor_moves.json, items.json, flavor_items.json, abilities.json, flavor_abilities.json, natures.json, types.json, stats.json, species.json (names/genus), flavor_pokedex.json, egg_groups.json (inspect their structure first; they are keyed by the expansion's constants or English names). The story bible's glossary is in /home/user/Qualsiasi/docs/storia/bibbia.md and nomi.json (if present) — use it for game terms (Allenatore, Capopalestra, Medaglia, Box, Pokémon Market, Centro Pokémon, Poké Ball, Pokédex, Squadra, Borsa, Strumenti, Mosse, Statistiche, Lotta, Fuga, Salva, Opzioni, Esci...). Style: "Pokémon" (never POKéMON), natural modern Italian as in the official games (Gen 8/9 Italian style), Title Case only where the official games use it.
HARD RULES:
1. Change ONLY the contents of string literals inside _("..."), COMPOUND_STRING("..."), ITEM_NAME(...), ITEM_PLURAL_NAME(...) and similar game-string macros. Never change code, identifiers, comments' meaning, array sizes or anything else (exception only if explicitly allowed in your batch instructions).
2. Keep every {PLACEHOLDER}/control code of the original string (e.g. {B_ATK_NAME_WITH_PREFIX}, {B_CURRENT_MOVE}, {STR_VAR_1}, {PLAYER}, {COLOR ...}, {PAUSE ...}, \\n \\l \\p). Do not add new ones.
3. Display width: a translated line must not be wider (in pixels) than the original allows — see the validator. Italian is longer than English: paraphrase, use official abbreviations (e.g. "PS", "Att.", "Dif.", "Att. Sp.", "Dif. Sp.", "Vel.", "MT", "MN") and shorter synonyms. Respect name length limits (moves ≤16 chars, items ≤20, etc.).
4. Characters: apostrophe ' ; quotes “ ” ; accents precomposed; no « » – — ° € # * @.
5. VALIDATE with the C-string validator until 0 errors: python3 -I /home/user/Qualsiasi/tools/loc/ctextcheck.py --single <edit file> <orig file> (read /home/user/Qualsiasi/tools/loc/README.md first). Do NOT run make (the lead builds and will report compile errors back).
5b. WIDTH LIMITS: by default non-battle UI strings may not be wider than the original's widest line. When the REAL window is wider (e.g. a description box or menu window that has spare space), determine the true limit from the code (window templates: width in tiles*8 minus the text x offset, and the font used) and record it in YOUR OWN allowance file /home/user/Qualsiasi/tools/loc/allow/<batch key>.json (keys: file glob, file:SYMBOL or file:line → max px; add a short "_why" note per entry citing the window template), then validate with --allow <that file>. Never set allowances you have not verified in code. Name fields: limits per README (item names ≤19 bytes etc.).
6. Edit ONLY your assigned files (plus your allowance file).
FINAL ANSWER: short report: files, number of strings translated, validator result, any code you had to touch (only if allowed), open issues.
`
const KIND = {
  moves: `BATCH: move names (.name) and descriptions (.description) in src/data/moves_info.h. Use PokeAPI Italian names (MOVE_NAME_LENGTH = 16; if an official name is longer, use the official abbreviated form or the shortest faithful variant) and Italian flavor texts (flavor_moves.json) rewritten to fit the description box: keep the original's number of lines (or fewer) and each line no wider than the original's widest line. Z-Moves/Max Moves/G-Max: official Italian names if known (e.g. "Dynapugno"…), else faithful translation. Moves without Italian data (new or custom): translate yourself in official style.`,
  items: `BATCH: item names (ITEM_NAME, ≤20 chars), plural names (ITEM_PLURAL_NAME, check its limit) and descriptions in src/data/items.h. Use PokeAPI items.json/flavor_items.json; fit descriptions to the original's line count and widths. TMs/HMs are "MT"/"MN" in Italian. Items without Italian data: translate in official style. Keep Poké Ball names official (Poké Ball, Mega Ball, Ultra Ball, Master Ball, Rete Ball, Sub Ball, Nido Ball, Bis Ball, Timer Ball, Lusso Ball, Premier Ball...).`,
  abilities: `BATCH: ability names and descriptions in src/data/abilities.h (PokeAPI abilities.json + flavor_abilities.json; fit descriptions to original widths/lines; check the ability name length limit in include/), and type names in src/data/types_info.h (official: Normale, Fuoco, Acqua, Erba, Elettro, Ghiaccio, Lotta, Veleno, Terra, Volante, Psico, Coleottero, Roccia, Spettro, Drago, Buio, Acciaio, Folletto, Astrale (Stellar), ??? — check the length limits of that array/field).`,
  pokedex: `BATCH: Pokédex texts in the species_info files: for every species/form entry translate .categoryName (Italian genus without the word "Pokémon", e.g. "Seme" — check the length limit of categoryName and how it is displayed) and .description (Pokédex entry) using PokeAPI flavor_pokedex.json / species.json genus (choose the Italian text matching the species/form; for forms without own text, use the base species text or translate the English one). Reflow each description: same number of lines as the original or fewer, each line no wider than the original's widest line (the HGSS-style Pokédex is enabled: check src/pokedex_plus_hgss.c for the description window width and use the stricter of the two). Do NOT change .speciesName or anything else. This is mostly mechanical: write a careful Python script (in /home/user/work/loc/) that uses the textcheck width functions to reflow, apply it, then spot-check 30 random entries by reading them, and run the validator.`,
  battle: `BATCH: battle messages (part of src/battle_message.c). Translate every battle string in the style of the official Italian games ("{B_ATK_NAME_WITH_PREFIX} usa {B_CURRENT_MOVE}!", "È superefficace!", "Non è molto efficace…", "Brutto colpo!", "{B_DEF_NAME_WITH_PREFIX} è esausto!"...). The battle box line limit is 208 px (200 px before \\p or \\l). IMPORTANT Italian grammar issue: English puts "Wild"/"The opposing" BEFORE the Pokémon name via the *_NAME_WITH_PREFIX placeholders; Italian puts "selvatico"/"nemico/avversario" AFTER the name ("Zigzagoon selvatico", "Poochyena nemico"). Find the prefix strings (e.g. sText_WildPkmnPrefix, sText_FoePkmnPrefix… and their lowercase variants) and, if the prefix text strings alone can't produce correct Italian, you are ALLOWED to minimally change the C code that builds these name-with-prefix expansions (in battle_message.c only) so the qualifier is appended after the name — keep it small, report exactly what you changed. Coordinate: the other battle-part translator edits the other half of the file; the prefix logic may be in either part — only change code located in YOUR part, and report if the needed change is in the other part.`,
  ui: `BATCH: menus/UI/system strings. Many strings are drawn in small fixed windows (menus, buttons, headers): never exceed the original width; abbreviate as the official Italian games do. Natures (if in your files, e.g. src/pokemon.c): official Italian names from natures.json (Ardita, Schiva, Audace, Decisa, Birbona, Sicura, Docile, Placida, Scaltra, Fiacca, Timida, Lesta, Seria, Allegra, Ingenua, Modesta, Mite, Quieta, Ritrosa, Ardente, Calma, Gentile, Vivace, Furba, Cauta — verify against the data). Do NOT translate trainer class names in src/battle_main.c gTrainerClasses (the lead handles them from the story bible) nor map/landmark names that are proper nouns handled by the bible (src/landmark.c: translate generic words only if they are not official names; leave names if unsure). Debug-only strings can be skipped.`,
  text: `BATCH: in-game texts stored in C files (match call/PokéNav messages, follower Pokémon messages, Union Room, contest, berries, decorations, trades, credits, ribbons, Battle Frontier texts, etc.). Translate into lively, natural Italian; keep widths within the original's (PokéNav texts: 192 px; others: ≤ original width). Names of the story characters must follow nomi.json if it exists (rival, villains); canonical Hoenn names are official Italian (Petra, Rudi, Walter, Fiammetta, Norman, Alice, Tell e Pat, Rodolfo, Fosco, Ester, Frida, Drake, Adriano, Rocco Petri, Prof. Birch, Wally). Credits (src/data/credits.h): keep original staff names; translate role titles to Italian.`,
  easychat: `BATCH: Easy Chat word lists (src/data/easy_chat/*.h): translate each word/phrase into Italian as in the official Italian Emerald where possible (short words; each word must fit the original's width — the easy chat UI has fixed columns). Avoid duplicates within a group (alphabetical ordering may be assumed by code: check src/easy_chat.c for any sorted-order requirement and respect it, e.g. if words must be alphabetically sorted within a group, re-sorting would require changing order — in that case DO NOT reorder entries; just translate).`,
}
phase('Localize')
const res = await pipeline(args.batches, b => {
  const list = b.files.map(f => {
    if (f.includes('#')) {
      const [file, k] = f.split('#'); const flat = file.split('/').join('__')
      return `- EDIT: /home/user/work/loc/parts/new/${flat}.part${k}\n  ORIG: /home/user/work/loc/parts/orig/${flat}.part${k}  (part ${k} of ${file})`
    }
    return `- EDIT: /home/user/pex/${f}\n  ORIG: /home/user/pex-orig/${f}  (${f})`
  }).join('\n')
  return agent(`${COMMON}\n${KIND[b.kind]}\nYOUR FILES (batch ${b.key}):\n${list}`, { label: `loc:${b.key}`, phase: 'Localize' })
})
return args.batches.map((b, i) => ({ key: b.key, report: res[i] }))
