VerdanturfTown_House_MapScripts::
	.byte 0

VerdanturfTown_House_EventScript_Woman1::
	msgbox VerdanturfTown_House_Text_TrainersGatherAtPokemonLeague, MSGBOX_NPC
	end

VerdanturfTown_House_EventScript_Woman2::
	msgbox VerdanturfTown_House_Text_DefeatEliteFourInARow, MSGBOX_NPC
	end

VerdanturfTown_House_Text_TrainersGatherAtPokemonLeague:
	.string "Lontano lontano, a Iridopoli,\n"
	.string "c'è la Lega Pokémon.\p"
	.string "Gli Allenatori che si radunano lì\n"
	.string "sono tutti di una bravura spaventosa.$"

VerdanturfTown_House_Text_DefeatEliteFourInARow:
	.string "Alla Lega Pokémon, se non sbaglio,\n"
	.string "il regolamento dice che i Superquattro\l"
	.string "vanno sfidati tutti di fila.\p"
	.string "Se perdi contro uno di loro, devi\n"
	.string "ricominciare la sfida da capo,\l"
	.string "partendo dal primo.$"

