SootopolisCity_Gym_B1F_MapScripts::
	.byte 0

SootopolisCity_Gym_B1F_EventScript_Andrea::
	trainerbattle_single TRAINER_ANDREA, SootopolisCity_Gym_B1F_Text_AndreaIntro, SootopolisCity_Gym_B1F_Text_AndreaDefeat
	msgbox SootopolisCity_Gym_B1F_Text_AndreaPostBattle, MSGBOX_AUTOCLOSE
	end

SootopolisCity_Gym_B1F_EventScript_Crissy::
	trainerbattle_single TRAINER_CRISSY, SootopolisCity_Gym_B1F_Text_CrissyIntro, SootopolisCity_Gym_B1F_Text_CrissyDefeat
	msgbox SootopolisCity_Gym_B1F_Text_CrissyPostBattle, MSGBOX_AUTOCLOSE
	end

SootopolisCity_Gym_B1F_EventScript_Brianna::
	trainerbattle_single TRAINER_BRIANNA, SootopolisCity_Gym_B1F_Text_BriannaIntro, SootopolisCity_Gym_B1F_Text_BriannaDefeat
	msgbox SootopolisCity_Gym_B1F_Text_BriannaPostBattle, MSGBOX_AUTOCLOSE
	end

SootopolisCity_Gym_B1F_EventScript_Connie::
	trainerbattle_single TRAINER_CONNIE, SootopolisCity_Gym_B1F_Text_ConnieIntro, SootopolisCity_Gym_B1F_Text_ConnieDefeat
	msgbox SootopolisCity_Gym_B1F_Text_ConniePostBattle, MSGBOX_AUTOCLOSE
	end

SootopolisCity_Gym_B1F_EventScript_Bridget::
	trainerbattle_single TRAINER_BRIDGET, SootopolisCity_Gym_B1F_Text_BridgetIntro, SootopolisCity_Gym_B1F_Text_BridgetDefeat
	msgbox SootopolisCity_Gym_B1F_Text_BridgetPostBattle, MSGBOX_AUTOCLOSE
	end

SootopolisCity_Gym_B1F_EventScript_Olivia::
	trainerbattle_single TRAINER_OLIVIA, SootopolisCity_Gym_B1F_Text_OliviaIntro, SootopolisCity_Gym_B1F_Text_OliviaDefeat
	msgbox SootopolisCity_Gym_B1F_Text_OliviaPostBattle, MSGBOX_AUTOCLOSE
	end

SootopolisCity_Gym_B1F_EventScript_Tiffany::
	trainerbattle_single TRAINER_TIFFANY, SootopolisCity_Gym_B1F_Text_TiffanyIntro, SootopolisCity_Gym_B1F_Text_TiffanyDefeat
	msgbox SootopolisCity_Gym_B1F_Text_TiffanyPostBattle, MSGBOX_AUTOCLOSE
	end

SootopolisCity_Gym_B1F_EventScript_Bethany::
	trainerbattle_single TRAINER_BETHANY, SootopolisCity_Gym_B1F_Text_BethanyIntro, SootopolisCity_Gym_B1F_Text_BethanyDefeat
	msgbox SootopolisCity_Gym_B1F_Text_BethanyPostBattle, MSGBOX_AUTOCLOSE
	end

SootopolisCity_Gym_B1F_EventScript_Annika::
	trainerbattle_single TRAINER_ANNIKA, SootopolisCity_Gym_B1F_Text_AnnikaIntro, SootopolisCity_Gym_B1F_Text_AnnikaDefeat
	msgbox SootopolisCity_Gym_B1F_Text_AnnikaPostBattle, MSGBOX_AUTOCLOSE
	end

SootopolisCity_Gym_B1F_EventScript_Daphne::
	trainerbattle_single TRAINER_DAPHNE, SootopolisCity_Gym_B1F_Text_DaphneIntro, SootopolisCity_Gym_B1F_Text_DaphneDefeat
	msgbox SootopolisCity_Gym_B1F_Text_DaphnePostBattle, MSGBOX_AUTOCLOSE
	end

SootopolisCity_Gym_B1F_Text_AndreaIntro:
	.string "Ti mostrerò le tecniche sublimi che\n"
	.string "mi ha insegnato il maestro Rodolfo!$"

SootopolisCity_Gym_B1F_Text_AndreaDefeat:
	.string "Perdonatemi, maestro Rodolfo…$"

SootopolisCity_Gym_B1F_Text_AndreaPostBattle:
	.string "Guarda cosa succede quando incrini\n"
	.string "tutte le piastrelle del pavimento.$"

SootopolisCity_Gym_B1F_Text_CrissyIntro:
	.string "Sei arrivato fin quaggiù, ma Rodolfo\n"
	.string "non lo vedrai.\p"
	.string "Non se perdi contro di me!$"

SootopolisCity_Gym_B1F_Text_CrissyDefeat:
	.string "Sei forte! Mi sono fatta ingannare\n"
	.string "da quella faccia da bravo ragazzo!$"

SootopolisCity_Gym_B1F_Text_CrissyPostBattle:
	.string "Forse sei abbastanza bravo da non\n"
	.string "farti spazzare via in un colpo solo\l"
	.string "da Rodolfo.$"

SootopolisCity_Gym_B1F_Text_DaphneIntro:
	.string "Vedere Rodolfo dirigere una lotta…\p"
	.string "È stata quella bellezza a spingermi\n"
	.string "a diventare Allenatrice.$"

SootopolisCity_Gym_B1F_Text_DaphneDefeat:
	.string "Hai lottato con più grazia di quanta\n"
	.string "io potessi mai metterne…$"

SootopolisCity_Gym_B1F_Text_DaphnePostBattle:
	.string "La grazia con cui lotti è\n"
	.string "semplicemente favolosa.\p"
	.string "Oh… che fortuna aver incontrato\n"
	.string "i Pokémon.$"

SootopolisCity_Gym_B1F_Text_ConnieIntro:
	.string "Lascia che ti insegni quanto possono\n"
	.string "essere dure le lotte.$"

SootopolisCity_Gym_B1F_Text_ConnieDefeat:
	.string "Oh.\n"
	.string "Sei forte.$"

SootopolisCity_Gym_B1F_Text_ConniePostBattle:
	.string "Ti do un consiglio prezioso.\p"
	.string "Se vuoi arrivare da Rodolfo, devi\n"
	.string "calpestare ogni piastrella una volta.$"

SootopolisCity_Gym_B1F_Text_BridgetIntro:
	.string "La Palestra Pokémon più temibile\n"
	.string "di tutta la regione di Hoenn…\p"
	.string "È la Palestra di Ceneride.$"

SootopolisCity_Gym_B1F_Text_BridgetDefeat:
	.string "Ma che livello altissimo!$"

SootopolisCity_Gym_B1F_Text_BridgetPostBattle:
	.string "Invece di accontentarsi di una Palestra\n"
	.string "forte, credo che allenarsi in giro\l"
	.string "per il mondo renda più forti.\l"
	.string "E poi, diciamolo: è più divertente.$"

SootopolisCity_Gym_B1F_Text_OliviaIntro:
	.string "Alleno i miei Pokémon insieme a\n"
	.string "Rodolfo in persona.\p"
	.string "Non pensare che sia una preda facile.$"

SootopolisCity_Gym_B1F_Text_OliviaDefeat:
	.string "Mi hai battuta…$"

SootopolisCity_Gym_B1F_Text_OliviaPostBattle:
	.string "Secondo me hai del potenziale.\n"
	.string "Perché non resti ad allenarti con noi?$"

SootopolisCity_Gym_B1F_Text_TiffanyIntro:
	.string "Scivolare con grazia sul ghiaccio\n"
	.string "senza mai ripassare sulle proprie orme…\p"
	.string "Un Allenatore capace di tanto sarebbe\n"
	.string "di un'eleganza sublime!$"

SootopolisCity_Gym_B1F_Text_TiffanyDefeat:
	.string "Come, prego?! Ma dico io!$"

SootopolisCity_Gym_B1F_Text_TiffanyPostBattle:
	.string "Sarà ovvio, ma la forza di un\n"
	.string "Allenatore non ha niente a che fare\l"
	.string "con quanti anni ha.$"

SootopolisCity_Gym_B1F_Text_BethanyIntro:
	.string "Quando sto con i miei Pokémon, il tempo\n"
	.string "vola prima che tu possa dire “Ops!”$"

SootopolisCity_Gym_B1F_Text_BethanyDefeat:
	.string "Ops!$"

SootopolisCity_Gym_B1F_Text_BethanyPostBattle:
	.string "Vorrei scordarmi delle sconfitte in\n"
	.string "meno tempo di quanto serve a dire “Ops!”$"

SootopolisCity_Gym_B1F_Text_AnnikaIntro:
	.string "Se ti va, posso lottare con Pokémon\n"
	.string "rarissimi. Alcuni vengono da un Varco!$"

SootopolisCity_Gym_B1F_Text_AnnikaDefeat:
	.string "Oh, ecco qua! Li hai ammirati per\n"
	.string "bene, i miei Pokémon?$"

SootopolisCity_Gym_B1F_Text_AnnikaPostBattle:
	.string "Sono entrata in questa Palestra perché\n"
	.string "Rodolfo ha lodato i miei tesorini.\p"
	.string "Oh, se solo avessi conosciuto Rodolfo\n"
	.string "anni fa, quand'ero più giovane…$"

SootopolisCity_Gym_B1F_Text_BriannaIntro:
	.string "Ihihi…\n"
	.string "Quel tuo sguardo cupo è adorabile.$"

SootopolisCity_Gym_B1F_Text_BriannaDefeat:
	.string "Oh, cielo.\n"
	.string "Sono stata fin troppo gentile.$"

SootopolisCity_Gym_B1F_Text_BriannaPostBattle:
	.string "Rodolfo non riusciresti nemmeno a\n"
	.string "sfiorarlo, ne sono certa. Ihihi…$"

