SootopolisCity_House7_MapScripts::
	.byte 0

SootopolisCity_House7_EventScript_OldMan::
	msgbox SootopolisCity_House7_Text_CityFromEruptedVolcano, MSGBOX_NPC
	end

SootopolisCity_House7_EventScript_PokefanF::
	msgbox SootopolisCity_House7_Text_CaveMadeToKeepSomething, MSGBOX_NPC
	end

SootopolisCity_House7_Text_CityFromEruptedVolcano:
	.string "Un vulcano sottomarino eruttò e si\n"
	.string "fece strada dalle profondità marine.\p"
	.string "Il suo cratere emerse dal mare e si\n"
	.string "riempì di acqua piovana.\p"
	.string "È così che è nata Ceneride.\n"
	.string "Una città nata dal fuoco e dall'acqua.$"

SootopolisCity_House7_Text_CaveMadeToKeepSomething:
	.string "La grotta che collega Ceneride al\n"
	.string "mondo esterno…\p"
	.string "Sembra quasi fatta apposta per\n"
	.string "impedire a qualcosa di uscire.\p"
	.string "O me lo sto solo immaginando?$"

