RustboroCity_House2_MapScripts::
	.byte 0

RustboroCity_House2_EventScript_PokefanF::
	msgbox RustboroCity_House2_Text_TrainerSchoolExcellent, MSGBOX_NPC
	end

RustboroCity_House2_EventScript_LittleGirl::
	msgbox RustboroCity_House2_Text_RoxanneKnowsALot, MSGBOX_NPC
	end

RustboroCity_House2_Text_TrainerSchoolExcellent:
	.string "La Scuola Allenatori è eccellente.\p"
	.string "Studiando lì, potresti perfino\n"
	.string "diventare Capopalestra.$"

RustboroCity_House2_Text_RoxanneKnowsALot:
	.string "Petra, la Capopalestra, sa un sacco\n"
	.string "di cose sui Pokémon.\p"
	.string "Ed è pure fortissima!$"

